### ISSUE TITLE
Qt opacity issues for a few folder icons

### ISSUE THREAD

**Issue by palob** [numixproject/numix-icon-theme#1001]
The following ions appear broken in Qt:
``places``
![1](https://cloud.githubusercontent.com/assets/7050624/12556927/a8d2f27c-c388-11e5-9418-5db470762409.png)
![2](https://cloud.githubusercontent.com/assets/7050624/12556926/a8cd5538-c388-11e5-8a47-855b521683f5.png)
``actions``
![3](https://cloud.githubusercontent.com/assets/7050624/12556935/b27a8880-c388-11e5-977f-7b3848962610.png)

It's an issue with opacities adding up / not being properly applied.
The issue is present for all colours (including ``custom-*) and other styles from numix-folders too.

I can fix this after it's clear how to go about #998 and https://github.com/numixproject/numix-folders/pull/150.

**Comment by wa4557** [comment]
@palob It should be enough to fix only one colour (not the default one, let's say blue). The other colours (and the default icons) can than be created using bash scripts

**Comment by palob** [comment]
Alright, now you say that how to deal with ``custom-folder-move``? I'd turn the transparent black parts into solid grey. The numix-folders script would have to be adapted then, right? The alpha/opacity effect would have to be transfrormed into a L value effect.

**Comment by palob** [comment]
As a matter of fact I don't quite unterstand why those parts aren't transparent outside of Qt.

**Comment by wa4557** [comment]
Yeah that's a strange icon indeed.... I don't think special treatment for the custom icons is necessary. Do you use a new kind of blue (for the blue icon oc) for this icon (you sholdn't)? For the custom icons only the blue parts are then replaced by the custom colours

**Comment by wa4557** [comment]
@palob Can you confirm, that this only happens in style 6?

**Comment by palob** [comment]
Totally forgot about this one.

Installed Dolphin and browsed through the numix-folders repo.
Styles 1 and 2 are fine altogether, style 3 hasn't got the ``xxx-add-folder-to-archive`` issue.
Only styles 5 and 6 have got an arrown on ``xxx-folder-open`` so styles 1-4 aren't subject to that issue.

There might be an additional issue with ``default-folder-copy.svg`` in style 4. While it's rendered properly by Qt I'm not sure it's supposed to look like it does.

**Comment by wa4557** [comment]
Style 3 looks fine for me in dolphin, the others I can confirm (`folder-copy.svg` in style 4 is definitely also broken). Not sure how to fix that though, since the opacity approach seems to be not working...

**Comment by palob** [comment]
Icons still need to be copied over from ``numix-folders``, @wa4557 are you gonna do this?
