### ISSUE TITLE
Repo for EL7 ?

### ISSUE THREAD

**Issue by pgera** [numixproject/numix-icon-theme#1002]
Is there an official repository for RHEL / Centos 7 and other derivatives ? I remember there used to be an rpm repo earlier, but I can't find it.  The fedora instructions on the main page also throw a 404.

**Comment by Foggalong** [comment]
Does this repo work? `sudo dnf copr enable numix/numix`? Someone mentioned a change to it but noone got back to me :(

**Comment by pgera** [comment]
Work! Thanks.

**Comment by Foggalong** [comment]
Huh, seems we did rename the repo then. I wonder when that happened?

**Comment by pgera** [comment]
The repo for EL7 has been down. https://copr-be.cloud.fedoraproject.org/results/numix/numix/epel-7-x86_64/repodata/repomd.xml is not reachable.

**Comment by pgera** [comment]
Maybe it was a temporary issue with fedora's repo hosting ? It looks like it is reachable for me again.

**Comment by palob** [comment]
But the repo is outdated, isn't it?

**Comment by pgera** [comment]
Oh, I didn't check if it is up to date. It was inaccessible earlier today. Here are  my installed version numbers:
numix-icon-theme-shine-999-1453640746.git.el7.centos.noarch
numix-icon-theme-1010-6.git101307f.el7.centos.noarch
numix-icon-theme-circle-1010-6.git101307f.el7.centos.noarch
numix-icon-theme-utouch-999-1453640746.git.el7.centos.noarch
numix-gtk-theme-1010-6.git101307f.el7.centos.noarch

**Comment by palob** [comment]
Could you please get the number of files inside ``/usr/share/icons/Numix-Circle/``?

**Comment by pgera** [comment]
ls -l | wc -l
3879
find -type f | wc -l
2023

**Comment by palob** [comment]
This is outdated big time. The latest [release](https://github.com/numixproject/numix-icon-theme-circle/releases) comes with 4391 files in there.

**Comment by Foggalong** [comment]
Copr is no longer support, we now are in the actual Fedora/RHEL repos :)

**Comment by pgera** [comment]
Nice. Yeah, I just tried, and it shows results from epel. FYI, I had to remove all the old packages and disable the old numix repo because the version numbers aren't aligned. So the epel packages don't show up as updates to the old ones.

**Comment by Foggalong** [comment]
Ah cool, thanks for the heads up! Will bare that in mind when troubleshooting for people :)
