### ISSUE TITLE
Icon for network printers

### ISSUE THREAD

**Issue by zsteinmetz** [numixproject/numix-icon-theme#1007]
At the moment it looks like this in the printer panel

![printers](https://cloud.githubusercontent.com/assets/10266826/12695492/7a87ad38-c750-11e5-8794-fb4db8fdd64b.png)

Icon name is `i-network-printer`

**Comment by palob** [comment]
GNOME needs a symlink
![printer](https://cloud.githubusercontent.com/assets/7050624/13411116/b66fb09a-df3b-11e5-9075-544de3d6074a.png)

**Comment by wa4557** [comment]
What's the other icon (photosmart-b110) I guess this shouldn't be a circle but a `device` icon

**Comment by palob** [comment]
Is ``printer.svg`` supposed to be in ``Circle``? Is it used by some DE's control else or in any other place that justifies an app icon?

**Comment by wa4557** [comment]
It's used as a preference icon showing up in control-center, so yeah I guess it needs to stay :(

**Comment by palob** [comment]
Hmm, the proper ones to use there would be ``preferences-desktop-printer.svg`` or ``system-config-printer.svg``. Which DE do you think uses ``printer.svg``?

**Comment by wa4557** [comment]
Ubuntu 15.10 does use it for sure. Not sure about gnome but `gnome-printer-panel.desktop` and `system-config-printer.desktop` both use `icon=printer`

**Comment by palob** [comment]
Aye, alas it's ``Icon=printer`` in Gnome 3.18 as well.

**Comment by sljunkie** [comment]
@palob yes, on GNOME 3.18 - 3.20 a symlink for printer-network is needed.
