### ISSUE TITLE
Missing cellphone icon from system tray

### ISSUE THREAD

**Issue by astatine** [numixproject/numix-icon-theme#1009]
The cellphone icon in the system tray is missing. I connected an iphone and the generic missing/placeholder icon is shown.

Screenshot:
![missingcellphoneicon](https://cloud.githubusercontent.com/assets/1077402/12939450/c9504e32-cfe5-11e5-80a7-71533292ed70.png)

I have ruled out icon cache issues by using `gtk-update-icon-cache` and `gtk-update-icon-cache-3.0`, which didn't help.

**Comment by Foggalong** [comment]
Any idea what the icon names are?

**Comment by astatine** [comment]
@Foggalong 
I don't know the icon name. How do I find out? Also, why have you marked this bug 'invalid'?

Sorry for the late response; I was traveling.

**Comment by wa4557** [comment]
You could try the `oxygen` icon theme and see what's sshowing up there...

**Comment by Foggalong** [comment]
@astatine requests which don't contain the information required for us to fix it are invalid, but that's okay we can work through to find that information. What program creates the tray icon?
