### ISSUE TITLE
Missing Icon for Cisco AnyConnect VPN Client

### ISSUE THREAD

**Issue by mnapp** [numixproject/numix-icon-theme#1010]
I would very much like to see a Numix version of AnyConnect because it's the only thing in my launcher that isn't styled correctly.

`Icon=/opt/cisco/anyconnect/pixmaps/vpnui48.png`

This is the original icon that comes with the proprietary package:

![vpnui48](https://cloud.githubusercontent.com/assets/4920542/13014943/9602d28e-d1b6-11e5-8b76-347f362a686a.png)

Much appreciated. Thanks

**Comment by Foggalong** [comment]
This is an app icon, not a base icon. Please report it [here](https://github.com/numixproject/numix-icon-theme-circle)
