### ISSUE TITLE
Icon for XCOM 2

### ISSUE THREAD

**Issue by ikaros** [numixproject/numix-icon-theme#1011]
Hi,
could you consider to provide a icon for the XCOM 2 Game on steam?

Icon name is steam_icon_268500

Thank you so much ;-)
/ikaros

**Comment by Foggalong** [comment]
This is an app icon, not a base icon. Please report it [here](https://github.com/numixproject/numix-icon-theme-circle)

**Comment by ikaros** [comment]
OK Thx
