### ISSUE TITLE
Symlink keepassx2 to keepassx

### ISSUE THREAD

**Issue by ammongit** [numixproject/numix-icon-theme#1012]
KeePassX 2's desktop file has the following icon line:
`Icon=keepassx2`

The icon appears to be the same, so a symlink would make sense.

**Comment by Foggalong** [comment]
This is an issue for the [circle theme](https://github.com/numixproject/numix-icon-theme-circle) not here.

**Comment by palob** [comment]
It's already in [Numix Circle](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/keepassx2.svg).

@ammongit You're not using the latest version of the theme.
