### ISSUE TITLE
Trash icon is not changing when trash is not empty

### ISSUE THREAD

**Issue by pwittchen** [numixproject/numix-icon-theme#1014]
In previous versions of Numix Circle Theme trash icon were colored to red, when trash wasn't empty. Right now, it's gray all the time even if something is in the trash. I think that different color (e.g. red) or different icon for non-empty trash is useful for me as a system user. Can you bring previous behavior back or add similar behavior (different color or icon for non-empty trash)?

![screen-01](https://cloud.githubusercontent.com/assets/695319/13197171/f122ffba-d7e5-11e5-8e06-16a1b54f1805.png)
![screen-02](https://cloud.githubusercontent.com/assets/695319/13197172/f14087e2-d7e5-11e5-9cc2-f613b355050f.png)

**Comment by palob** [comment]
In ``Adwaita`` and ``gnome`` there's a ``scalable/status`` icon ``user-trash-full-symbolic``. Do we need that? What's wrong with the lookup here?

**Comment by palob** [comment]
Hmm, copying over the icon to ``status`` doesn't seem to change a thing with Nautilus 3.18.5

**Comment by palob** [comment]
Ah OK, coloured icons aren't supported anymore so we need a distinct design for ``user-trash-full-symbolic``

**Comment by pwittchen** [comment]
It doesn't have to be colored as previously. I think, it's just good to distinguish empty and not empty trash by looking at icon, so two different gray icons for different trash states would be fine.

**Comment by palob** [comment]
I've checked, a lighter-than-normal shade of grey for the empty trash and a darker than normal for the full one works.
But is that discoverable enough?

**Comment by pwittchen** [comment]
I'm not sure if I have the newest icon set, because I have temporary problems with system updates, but in my current version I cannot see the different between empty and not empty icon.

Empty trash:

![empty](https://cloud.githubusercontent.com/assets/695319/13547162/9410f534-e2c6-11e5-9f8d-d020622617cb.png)

Not empty trash:

![not-empty](https://cloud.githubusercontent.com/assets/695319/13547163/a23781a0-e2c6-11e5-829f-a75d36bd79d2.png)

**Comment by palob** [comment]
Yeah, sure I can reproduce that. This is how the two relevant Numix icons in ``scalable/places`` look like:

![trash](https://cloud.githubusercontent.com/assets/7050624/13547175/3e376f98-e2c7-11e5-9b24-5001e9cad06f.png)

Nautilus however renders both with the same colour. You can only achieve different shades of grey tweaking the opacity.

**Comment by pwittchen** [comment]
Can you tell me, how can I do that? Can it be supported with the Numix Project itself?

I remember, I had icons like you posted and they were displaying correctly some time ago.

**Comment by palob** [comment]
Due to the way Nautilus displays those icons we could achieve with one single design is light grey for empty and the standard grey for full. The latter isn't distinguishable as full.

We'll work towards a distinct design for ``user-trash-full-symbolic``.

**Comment by pwittchen** [comment]
Thanks! 

I appreciate your help and effort!

**Comment by wa4557** [comment]
@palob This does also affect all the other "colored" status icons then right? Is this Gtk-{whatever version is the last one right now} or nautilus specific?

**Comment by palob** [comment]
It does affect all symbolic icons in GNOME. You only can achieve shades of grey by means of opacity.
Legacy tray icons can still be coloured though.

**Comment by gregorydk** [comment]
Why not change the shape of the trash icon and make it for example bulging, like the default Adwaita icon theme?

**Comment by palob** [comment]
That's the way to go I think however my first bash at it didn't please me.

**Comment by Sadi58** [comment]
I temporarily use these slightly modified Adwaita icons - I couldn't remove those stripes on the empty one  to create a better empty look:
![user-trash-symbolic](https://cloud.githubusercontent.com/assets/6375934/20561548/c1161ba0-b187-11e6-9ab0-993d490d2dec.png)   ![user-trash-full-symbolic](https://cloud.githubusercontent.com/assets/6375934/20561568/d32e8278-b187-11e6-97a0-d4952b7028e5.png)

**Comment by DarthWound** [comment]
Still have this issue in november 2017.
Different shapes are definitely needed. Is it something that's on the rails?
@Foggalong

**Comment by palob** [comment]
We could simply make the empty one white inside - like the the Adwaita one without stripes - and leave the current one for the full icon.

**Comment by wa4557** [comment]
@palob That's abit subtle isn't it? I still think that the bulging would be the best idea

**Comment by palob** [comment]
Yep, that's better. Does it look fine on 16px?

**Comment by wa4557** [comment]
Like a full trash can. I created a PR
