### ISSUE TITLE
Status icon of indicator-prime

### ISSUE THREAD

**Issue by alim0x** [numixproject/numix-icon-theme#1021]
![image](https://cloud.githubusercontent.com/assets/4954007/13896419/806518a8-edc5-11e5-9605-8a00722e7e9a.png)

![image](https://cloud.githubusercontent.com/assets/4954007/13896417/77494c4e-edc5-11e5-966a-ab78ed4e6421.png)

related repo: [prime-indicator](https://github.com/beidl/prime-indicator)

the intel icon displays normally, but when using nvidia, the icon displayed is not correct nvidia status icon

```
class PRIMEIndicator:
    def __init__(self):
	self.ind = appindicator.Indicator("PRIME Indicator",
                                           "indicator-messages",
                                           appindicator.CATEGORY_APPLICATION_STATUS)
	self.ind.set_status(appindicator.STATUS_ACTIVE)
	self.ind.set_attention_icon("indicator-messages-new")
	self.ind.set_icon_theme_path("/usr/lib/primeindicator/")
	self.isIntegrated = self.checkIntegrated()
	self.ind.set_icon('intel')
	if not self.isIntegrated:
	    self.ind.set_icon('nvidia')
	self.menu_setup()
        self.ind.set_menu(self.menu)
```

**Comment by wa4557** [comment]
I'm afraid this cannot be fixed, since the program is using this very generic name for the tray icon. I solved this issue by changing `nvidia` to `nvidia-panel` and `intel` to `intel-panel` (both icons that already exist in Numix). Maybe we should report that [upstream](https://github.com/beidl/prime-indicator/issues)

**Comment by Foggalong** [comment]
Very much unmaintained.

**Comment by bil-elmoussaoui** [comment]
@Foggalong This can be closed as the icons already exists in Numix theme? @alim0x reported this [here](https://github.com/beidl/prime-indicator/issues/22)
