### ISSUE TITLE
Suspend and hibernate icons missing

### ISSUE THREAD

**Issue by ItTakesTwo** [numixproject/numix-icon-theme#1028]
In the action menu the hibernate and suspend options are missing their specific icons. [https://imgur.com/cStWMo3](https://imgur.com/cStWMo3)
The needed icons seem to be missing in numix-icon-theme but there are already icons for shutdown and reboot.
Could system-hibernate and system-suspend be added?

**Comment by palob** [comment]
Is this Xfce?

**Comment by ItTakesTwo** [comment]
Yes.

**Comment by palob** [comment]
What's the default theme where the icons are included?

**Comment by ItTakesTwo** [comment]
Am 23.03.2016 um 18:50 schrieb palob:
>
> What's the default theme where the icons are included?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/numixproject/numix-icon-theme/issues/1028#issuecomment-200464469>
>
At least on my system they're from hte hicolor-icon-theme. Don't exactly
know if Adwaita brings its own hibernate and suspend icons.

**Comment by wa4557** [comment]
Do you have the icon names, or a screenshot showing these icons when using the `hicolor` icon theme?

**Comment by ItTakesTwo** [comment]
[xfsm-suspend.png](http://i.imgur.com/Dey3tlO.png) and [xfsm-hibernate.png](http://i.imgur.com/Sp9SESj.png)

**Comment by wa4557** [comment]
Oh god, they look awful...

**Comment by ItTakesTwo** [comment]
And now imagine that mixed with the numix icons... Xfce does exactly that in the power-manager window.

**Comment by wa4557** [comment]
We could make something similar to the ubuntu unity icons. They are quite nice
![unbenannt](https://cloud.githubusercontent.com/assets/6475757/14014676/549e7cda-f1b4-11e5-99b8-a4b1356b6c62.png)

**Comment by wa4557** [comment]
Or maybe something like this for hibernate? (still thinking about a metaphor for suspend)
![bildschirmfoto vom 2016-03-24 17-41-13](https://cloud.githubusercontent.com/assets/6475757/14024026/a5e6c65a-f1e7-11e5-979d-905351430974.png)

**Comment by ItTakesTwo** [comment]
The snowflake for hibernate fits well imho.
What about a whistle for suspend? Metaphoric for a suspended player in a sport tournament.

**Comment by wa4557** [comment]
A bit too subtle imo, I guess some kind of clock (like the one from unity) should work just as well

**Comment by ItTakesTwo** [comment]
Well then lets settle on that.

**Comment by Foggalong** [comment]
We do already have icons styles for these I believe (I don't see any missing icons in my XFCE distribution) so either they'll need updating to this style or these icons should mimic their style.

**Comment by wa4557** [comment]
The only one I was able to find is from circle, and it doesn't make a very good base icon imo
![test](https://cloud.githubusercontent.com/assets/6475757/14064520/7d788976-f406-11e5-8111-da4e88a3e48d.png)

**Comment by Foggalong** [comment]
I'm trying to find my hibernate button but Ubuntu at some point disabled it from their options so having a hard time locating it.
