### ISSUE TITLE
Meld diff missing icon

### ISSUE THREAD

**Issue by bilelmoussaoui** [numixproject/numix-icon-theme#1035]
There's a missing action icon in Meld diff 
The icon name : `meld-version-control`
The default icon : 
![meld-version-control](https://cloud.githubusercontent.com/assets/7660997/14068525/1c0f61ca-f486-11e5-8ee5-50657d06a2f1.png)
Screenshot of the icon in the app:
![capture du 2016-03-28 01-41-20](https://cloud.githubusercontent.com/assets/7660997/14068532/3600116a-f486-11e5-911f-79f5c36fbbea.png)

**Comment by palob** [comment]
Upstream's using symbolic icons now.
