### ISSUE TITLE
Missing telegram status icon

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-icon-theme#1036]
There's a missing telegram status icon to complete Hardcode-Tray support!
Telegram uses a different icon for "muted" chats and we don't have one.. 
The icon looks like this
![icomute_22_9](https://cloud.githubusercontent.com/assets/7660997/14068563/96d71e60-f487-11e5-9954-5a6e972b4a0e.png)
The normal status icon is the same with a red background instead of the grey one.
The icon name : `telegram-mute-panel`

**Comment by wa4557** [comment]
@bil-elmoussaoui What do you suggest? Making the `telegram-attention` icon semitransparent?

**Comment by bil-elmoussaoui** [comment]
Great idea :)
