### ISSUE TITLE
HipChat icon in top panel is cut

### ISSUE THREAD

**Issue by pwittchen** [numixproject/numix-icon-theme#1037]
Hello,

I recently installed HipChat client on Ubuntu and noticed that its icon in top panel is a little bit cut as you can see on the screenshot.

![hipchat-icon-cut](https://cloud.githubusercontent.com/assets/695319/14077005/3920cb62-f4e7-11e5-804a-c470688aa79a.png)

I'm using Ubuntu 14.04, Gnome 3 with gnome-session-fallback (Gnome Classic).

Can you fix this or help me to find place, where I can fix this myself if it cannot be done on the Numix Theme level?

I know, it's small issue, but it annoys me a little bit (I already managed to fix bad looking Spotify and Skype icons by myself earlier ;-).

Regards,
Piotr

**Comment by bil-elmoussaoui** [comment]
Hello, 
When you change the icon theme to an other one, the icons is still the same?

**Comment by pwittchen** [comment]
Wow! You're so fast!

I changed icons theme to default and HipChat icon didn't change. I'm attaching screenshot below.

![icons-default](https://cloud.githubusercontent.com/assets/695319/14077126/aabb73f2-f4e8-11e5-9b25-fb2696351dd5.png)

**Comment by bil-elmoussaoui** [comment]
We will need the icon name to fix it. Take a look at  `/usr/share/icons/hicolor`

**Comment by pwittchen** [comment]
I've found the following icons in `/usr/share/icons/hicolor/16x16/apps` directory:

`hipchat4.png` 

icon used for menu - it looks fine in the menu!

![hipchat4](https://cloud.githubusercontent.com/assets/695319/14077341/dcf0125e-f4ea-11e5-866a-c51bffeab6cc.png)

`hipchat4-attention.png` 

this icon is probably used for top panel, because it's white and has transparent background

![hipchat4-attention](https://cloud.githubusercontent.com/assets/695319/14077347/e54e10ea-f4ea-11e5-8e38-967a6d33eaf5.png)

**Comment by bil-elmoussaoui** [comment]
There's two icons in Numix theme `renamed-hipchat` and `hipchat-attention` I think that `renamed-hipchat` can be used as an icon for `hipchat4-attention`. Can you try renaming the icon in 16,22,24 sizes and then update the cache using `sudo gtk-update-icon-cache -f /usr/share/icons/Numix`, close hipchat and reopen it again and screenshot the tray icon? :+1:

**Comment by pwittchen** [comment]
Ok. I've found icons named `renamed-hipchat.svg` for 16px, 22px and 24px, changed their name to `hipchat4-attention.png`. Renamed old icons to `hipchat4-attention-old.png`, pasted new icons to the following directories:
- /usr/share/icons/hicolor/16x16
- /usr/share/icons/hicolor/22x22 (this directory didn't have hipchat icon)
- /usr/share/icons/hicolor/24x24

and typed: `sudo gtk-update-icon-cache -f /usr/share/icons/Numix`
I also tried: `sudo gtk-update-icon-cache -f /usr/share/icons/hicolor`

Nothing was changed and I still see old icon.

**Comment by wa4557** [comment]
You mustn't name it *png if it is a svg file

**Comment by pwittchen** [comment]
For *.svg it behaves the same.

**Comment by bil-elmoussaoui** [comment]
Maybe the icon is hardcoded? :/

**Comment by wa4557** [comment]
Why moving these icons to `hicolor` in the first place? Just rename the icons in Numix and run the `gtk-update-icon-cache` command

**Comment by pwittchen** [comment]
Directory `/usr/share/icons/Numix/16/status` has `renamed-hipchat.svg` icon and `hipchat-attention.svg` attention icon as well. It looks like that:
![hipchat-attention](https://cloud.githubusercontent.com/assets/695319/14089920/b92d6f54-f537-11e5-9f77-5be7c4600b44.png)

so I don't think that renaming `renamed-hipchat.svg` icon to `hipchat-attention.svg` will cause any change, because this directory already has such icon.

**Comment by bil-elmoussaoui** [comment]
you should rename it to `hipchat4-attention` and not `hipchat-attention`

**Comment by pwittchen** [comment]
Ok. Now, I've performed the following steps:

Renamed `renamed-hipchat.svg` icon to `hipchat4-attention.svg` in the following directories
- `/usr/share/icons/Numix/16/status`
- `/usr/share/icons/Numix/22/status`
- `/usr/share/icons/Numix/24/status`

Run: `sudo gtk-update-icon-cache -f /usr/share/icons/Numix`
Run HipChat application.
Bad icon still is visible in the top panel.

**Comment by bil-elmoussaoui** [comment]
I don't think that the icons are hardcoded.. do you know any theme that has this icon? 
@Foggalong @wa4557 @palob do you guys know why we renamed `hipchat` status icon to `renamed-hipchat` ?

**Comment by Foggalong** [comment]
It was renamed to avoid clashes with the app icon of the same name. There's a specific issue explaining the details but I don't have it to hand right now.

**Comment by dirtydancing** [comment]
@bil-elmoussaoui I figure renaming to `renamed-` was done because of https://github.com/numixproject/numix-icon-theme/issues/190 and https://github.com/numixproject/numix-icon-theme/issues/192, unless there is a specific situation for `hipchat`.

**Comment by wa4557** [comment]
we cannot rename the icon to `hipchat` because it would show up in places instead of the circular icon. I'm afraid this cannot be fixed until hipchat changes its name (not ope source, so cannot be fixed with a simple PR)
