### ISSUE TITLE
Expand Inheritance Lines?

### ISSUE THREAD

**Issue by palob** [numixproject/numix-icon-theme#1042]
Now that Plasma 5 and KF5 applications trickle down to the last major distributions I think we should add `breeze` to the inheritance line in order to avoid blank spots.

What was the reason again the line reads just `Inherits=gnome,hicolor` and doesn't include, say `elementary` or `Adwaita`?

**Comment by dirtydancing** [comment]
Ah, the inheritances. I am still not sure what exactly is going on in the background, but as I understand it, the intended way to go is to rather remove the inheritances than to add new ones.

Evidence (at least for GNOME) so far appears to suggest that there are "automatic" inheritances that work regardless of whether they are defined by a selected icon theme, cf. https://github.com/numixproject/numix-icon-theme/issues/485#issuecomment-119170622.

Furthermore, the more inheritances are added, the more problems could be caused once a distribution changes its default inheritances, e.g. Ubuntu from `gnome` to `Adwaita`, cf. https://github.com/numixproject/numix-icon-theme/issues/442#issuecomment-91794720.

**Comment by palob** [comment]
Well, I'd consider blank spots instead of icons quite the issue. But I'll do some tests.

**Comment by Foggalong** [comment]
Yeah, I was under the impression that DEs with a "default" icon theme like elementary, gnome, breeze, automatically add it into the inheritance line? I might be wrong on that though. The reason gnome is in ours is that we still technically ship gnome with Numix so that it picks gnome to fill in the gaps before whatever the "default" theme was.

The reason for choosing gnome is a historical one based on the development of Numix, rather than one based upon the current state of gnome. The aim then now is to remove the inheritance  completely rather than swap gnome for another one or add more.

**Comment by wa4557** [comment]
For me breeze has a very different design than Numix (monochrome action icons etc...). Doesn't it look weird having breeze icons mixed with Numix ones?

**Comment by palob** [comment]
Last time I tested it seemed that Oxygen (that plastic look theme which mixes much worse with Numix and which is a subset of Breeze) is the default fallback icon theme for KDE applications.
(Maybe this is subject to change to Breeze in the course of the ongoing KF5 transition)
@wa4557 As long as moving target #580 isn't entirely fixed we'll have that mix.

Same for elementary OS where as long as #437 isn't fixed users have to manually edit ``index.theme`` in order not to encounter blank spots.

GNOME however seems to get things straight anyway. Briefly checking I couldn't find any glitches after editing the inheritance to ``hicolor`` only.

**Comment by dirtydancing** [comment]
@palob Regarding GNOME: removing `hicolor` as well (or removing the entire inheritance line) should not make any difference either. Evidence suggests that `hicolor` is always "automatically" inherited.

**Comment by palob** [comment]
``hicolor`` anyway but GNOME seems to fetch ``Adwaita``/``gnome`` as fallback on its own.

**Comment by dirtydancing** [comment]
Exactly, confirmed for GNOME, cf. also this older comment https://github.com/numixproject/numix-icon-theme/issues/485#issuecomment-119170622. iirc this is implemented via an "icon theme" named `default` in `/usr/share/icons`, which simply inherits `Adwaita`.

Possibly there is a similar mechanism with KDE? E.g., with Arch/GNOME and some KDE applications, `/usr/share/icons/` contains an "icon theme" with a folder named `default.kde4`, and its `index.theme` contains `Name=Oxygen`. This seems to indicate that indeed currently `Oxygen` is the default KDE fallback icon theme.

All of this is an argument for not including inheritances at all, as the desktop environments apparently include their own specific icon theme inheritance implementations, which are tailored to their specific needs. And as Numix caters to all DE/distributions, it would make sense to leave the inheritances up to those.

**Comment by palob** [comment]
Maybe we should look into how for instance KDE apps behave in GNOME and vice versa.

**Comment by dirtydancing** [comment]
With Arch/GNOME and Numix-Circle icon theme, KDE applications apparently display Oxygen icons. So far, I have not noticed missing icons. `default.kde4` in `/usr/share/icons` is a folder symlink to `oxygen`.

Screenshot with Okular settings (Okular 0.24.2, KDE 4.14.18):

![okular](https://cloud.githubusercontent.com/assets/7164227/14254236/24597316-fa8f-11e5-92f8-24832051f691.png)

**Comment by palob** [comment]
Okular is one of those applications which still is [not ported](http://developer.kde.org/~cfeck/portingstatus.html) to KF5.
Have you got a KF5 app at hand?

**Comment by dirtydancing** [comment]
I checked with Kdenlive 15.12.3, KDE 5.20.0, Qt 5.6.0. The application itself appears to be fine, no missing icons.

Screenshot with Kdenlive settings:

![kdenlive](https://cloud.githubusercontent.com/assets/7164227/14288088/92e34d2c-fb55-11e5-8fa8-2eb4df9be6ac.png)

One problem I noticed with Arch/GNOME is that the app icon is not showing in the Activities dash, although the correct Numix-Circle icon is displayed in the app overview. Screenshot:

![kdenlive_2](https://cloud.githubusercontent.com/assets/7164227/14288136/c1a9909e-fb55-11e5-94a3-f211061e2131.png)

E.g. for Okular (KDE 4, cf. above), the original icon is displayed in the Activities dash, and the correct Numix-Circle icon is displayed in the app overview as well.

**Comment by bil-elmoussaoui** [comment]
It's the same issue as Numix folders if you remember! you need to use https://github.com/bil-elmoussaoui/StartupWMClassFixer. Okular is already supported but not Kdenlive

**Comment by dirtydancing** [comment]
@bil-elmoussaoui Thanks! Confirmed that after adding the line `StartupWMClass=kdenlive` to the .desktop file, all is running fine with the correct Numix-Circle icon in the GNOME Activites dash :+1:

Screenshot:

![kdenlive_3](https://cloud.githubusercontent.com/assets/7164227/14289519/6f9829fe-fb5b-11e5-9b78-07b06fc0a295.png)

**Comment by palob** [comment]
So the good news is that the ``breeze`` icons seem to be fetched without further ado.
However in the worst-case scenario all KDE apps come with that ``StartupWMClass`` issue.

**Comment by Foggalong** [comment]
> @palob: Revisiting Inherits: What is the reason we don't append themes like Adwaita, breeze, elementary (or respective -dark variants) to our inheritance line?

My understanding based on the above conversation is that these days most mainstream distros automatically include "must have" icon themes in the inheritance lines, so they no longer need adding as fallback options by specific themes. The only reason a theme might now want to add additional inheritances is if there's a particular theme which is close design wise and useful to have as a fallback for missing icons, which even though not perfect. would look closer than the default fallbacks.

Mind, I'm very open to being corrected if I've misunderstood that! inheritance has never been my area of expertise and even then it's a couple of years since I properly did any reading on this topic. Might be worth rolling up some VMs and doing some testing to see if the behaviour has changed at all.

**Comment by palob** [comment]
Fixed.
