### ISSUE TITLE
Icons tollbar for Thunderbird

### ISSUE THREAD

**Issue by ElvisPresly** [numixproject/numix-icon-theme#1052]
It is possible to replace not getting icons for tollbar?
![a23b14c4-fd69-11e5-9eff-2203a294676b](https://cloud.githubusercontent.com/assets/18265958/14381993/7a784f2e-fd9b-11e5-9a6a-e978f437c14c.png)

**Comment by bil-elmoussaoui** [comment]
Are you sure that you're using the latest version of both Numix & Numix Circle? some base icons looks blurry! And we also need the icon names so we can fix them :+1:

**Comment by ElvisPresly** [comment]
The latest version from a repository.
Muddy icons because HI-DPI is used. I so think not up to the end there is a support of high permissions.
I unfortunately haven't found the name of icons (

**Comment by dirtydancing** [comment]
Unless things have changed for Thunderbird, these icons are hardcoded and this issue can be closed, cf. https://github.com/numixproject/numix-icon-theme/issues/153. I have the same issue with current Thunderbird on Arch/GNOME.

**Comment by dirtydancing** [comment]
Just a quick info: with the update to Thunderbird 45.0 on Arch/GNOME, the Thunderbird tool bar now features consistently monochrome icons. Screenshot:

![thunderbird_45](https://cloud.githubusercontent.com/assets/7164227/14652091/100db350-0673-11e6-9d0a-404992ef22f0.png)
