### ISSUE TITLE
Ubuntu 16.04: Unable to get Numix Icons working in launcher.

### ISSUE THREAD

**Issue by gillescastel** [numixproject/numix-icon-theme#1063]
* I've installed the icons via the ppa
* I'm using unity tweak tool to update icons

Icons do work in Nautilus, other applications and in the panel:
![image](https://cloud.githubusercontent.com/assets/7069691/14735558/bf3f75ca-0871-11e6-8929-90e2d9b5c48e.png)
![image](https://cloud.githubusercontent.com/assets/7069691/14735581/e3148cc4-0871-11e6-8d1b-6df9c1b87530.png)

Icons don't work in the launcher:
![image](https://cloud.githubusercontent.com/assets/7069691/14735564/cad4c638-0871-11e6-9f5f-b275ca9322fc.png)

When I change the icons to Paper Icons, everything works (of course not as visually appealing as the Numix Icons).

Using:
* Ubuntu 16.04 (fresh install, not updated from 15.10)
* Gtk 3.0

The icons worked fine in Ubuntu 15.10

What could be the cause of this problem?

**Comment by bil-elmoussaoui** [comment]
You need to install Numix Circle too and use it as your default theme(Numix Circle is Numix base + applications icons)

**Comment by gillescastel** [comment]
Thank's a lot for the quick response! I'm sorry for this stupid question.
