### ISSUE TITLE
AppImage mimetype

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-icon-theme#1090]
The only missing mimetype along with #1082 
https://github.com/probonopd/AppImageKit
The mimetype : `application/x-appimage`
The icon name : `application-x-appimage`
There's no default icon so maybe using the same icon as with Snap & FlatPak
The mimetype won't be shown by default as the AppImage mimetype was not submited yet to xdg : https://github.com/probonopd/AppImageKit/issues/144

**Comment by palob** [comment]
Maybe the package icon with **APP** on it?

**Comment by bil-elmoussaoui** [comment]
Looks fine to me :)

**Comment by palob** [comment]
Mimetype has been submitted to xdg as [``https://cgit.freedesktop.org/xdg/shared-mime-info/commit/?id=01fa61fc002afdcf43f61e7df2d6cc6f6968d8d2``](https://cgit.freedesktop.org/xdg/shared-mime-info/commit/?id=01fa61fc002afdcf43f61e7df2d6cc6f6968d8d2).
