### ISSUE TITLE
New keyboard indicators don't look native

### ISSUE THREAD

**Issue by codefuhrer** [numixproject/numix-icon-theme#1091]
I thought something was wrong with keyboard-indicator and fonts :confused: 

| Ubuntu Ambient: | New Numix design: |
| --------------  | ---------------- |
| ![original](https://cloud.githubusercontent.com/assets/2178368/16237580/228d6b5e-37ee-11e6-9b6d-04afd865cd89.png) | ![new](https://cloud.githubusercontent.com/assets/2178368/16237609/3f507ccc-37ee-11e6-84c4-91e30773a0e8.png) |

**Main problem:** the font weight is not the same with other indicators (like calendar/date): 300 against 500.
Moreover, 16x16 icons seem blurred, due to the thin lines:

| indicator-keyboard dropdown: |
| ------------------------  |
| ![small](https://cloud.githubusercontent.com/assets/2178368/16237946/a8ed54e2-37ef-11e6-9e1d-c9093cb4d3bb.png)  |

Problem PR: https://github.com/numixproject/numix-icon-theme/pull/1064

**Comment by Foggalong** [comment]
@wa4557 Any idea using bold font could be automated?

**Comment by wa4557** [comment]
I guess? I'll play around..

**Comment by codefuhrer** [comment]
What's the problem in using masks and `<text>`? I assume these icons are only used in Ubuntu, so the Ubuntu font family will always be present.

**Comment by palob** [comment]
@codefuhrer masks don't work with Qt. The icons are definitely used outside of Ubuntu.

**Comment by codefuhrer** [comment]
Ok, thanks for clarification :+1: 

@wa4557, you may find useful the default icons' coordinates for positioning paths:

```svg
<text
   y="15.5"
   x="3"
   style="font-size:12;font-family:Ubuntu;font-weight:500;fill:black"
   id="text9">Sr</text>
<text
   y="18.5"
   x="14"
   style="font-size:8;font-family:Ubuntu;font-weight:500;fill:black"
   id="text11">5</text>
```

**Comment by wa4557** [comment]
@codefuhrer Happy ?

**Comment by codefuhrer** [comment]
Much better. Thanks, @wa4557!
