### ISSUE TITLE
Monogame Pipeline icon

### ISSUE THREAD

**Issue by Hori873** [numixproject/numix-icon-theme#1095]
Icon for monogame pipeline

Original icon:
<img width="512" alt="monogame" src="https://cloud.githubusercontent.com/assets/10261133/16708082/2a0a6792-45ef-11e6-8a3b-f16f7a1b5292.png">

Desktop file: /usr/share/applications/Monogame\ Pipeline.desktop
Icon line: Icon=monogame

**Comment by Hori873** [comment]
![monogame](https://cloud.githubusercontent.com/assets/10261133/16708099/aea5580e-45ef-11e6-94a0-8d62cf82a777.png)
I've created this one, based on the original svg icon. What do you guys think, is it ok like that or should we make it more fancy? I'm not very sure if I put the objects at the right coordinates tho

**Comment by wa4557** [comment]
This is the wrong repo for app-icons please report that (there)[https://github.com/numixproject/numix-icon-theme-circle]

**Comment by Hori873** [comment]
Oh, I'm so sorry! I didn't realise I was on the base icon pack repository :(
