### ISSUE TITLE
Icons for DOCX, XLSX, PPTX and PPSX files are wrong

### ISSUE THREAD

**Issue by brunces** [numixproject/numix-icon-theme#110]
Hey, guys.

Today I noticed that there are some icons with wrong symlinks (I guess) here.

DOCX is shown as ODT. DOC is OK.
XLSX is shown as ODS. XLS is OK.
PPTX and PPSX are shown as ODP. PPT and PPS are OK.

Actually, PPS is shown as PPT, but I don't think that's a problem, except for perfectionists. (lol)

Thanks for your attention. :)

**Comment by orschiro** [comment]
I retrieved the mimetpye for a `docx` document which is the following: 

```test.docx: application/vnd.openxmlformats-officedocument.wordprocessingml.document
```

**Comment by Foggalong** [comment]
Thanks @orschiro, that was the clue I needed to fix this :)

**Comment by orschiro** [comment]
@Foggalong 

Glad, welcome! :)
