### ISSUE TITLE
PPA broken for numix-icon-theme

### ISSUE THREAD

**Issue by wa4557** [numixproject/numix-icon-theme#1103]
It seems that the daily ppa updates are broken for the base repo as well :(  The last update was June 21, whereas the last commit was 6th of July. 

Did something go wrong with the last commits?

**Comment by palob** [comment]
At least I can't get hold of anything which looks like a git submodule in the latest commits.

**Comment by wa4557** [comment]
After all the remaining PRs are taken care of, we can do another filter-branch where we remove the "bad" commit. 
@TiZ-EX1 I'm afraid we have to remove your commits #1075 because you are a verified user and launchpad can't handle that. But I can add your icons afterwards again.

**Comment by TiZ-EX1** [comment]
No problem. :+1:

**Comment by wa4557** [comment]
@Foggalong: I think I figured out how to solve this problem:

Run (after the two open PRs are taken care of):

`git rebase -i 4c51641cbf7ecb0f6d5873d7ef9d48a24a86a563~1`

A text editor will open: 
Delete those lines, and save:
```
pick a721b4d Ruby logo was sitting a bit too low on 32, bumped it up a px.
pick c612cbd 64 had misaligned logo. 48 and 64 had inconsistent BG colors from other sizes.
pick 8807fc4 Add mimetypes for Crystal. Crystal is heavily inspired by Ruby but is static and compiled so it uses Ruby's logo and C's colors.
pick 2cce72b Add mimetypes for Haxe. Uses a white silhouette of Haxe's logo and the BG is the primary color of said logo.
pick e016ca7 Fixed BG color on Ruby 64. It was just barely off; wouldn't have noticed if not for me checking Crystal icons after batch sed.
pick 07db8a9 Add mimetypes for Nim. Traced logo-crown and used the yellow from that image as the BG color.
pick 20a1fb7 Fix Nim logo size and position.
```
Git will rebase without those commits, and afterwards I can add the files made by @TiZ-EX1 back, and the PPA should start to work again...

**Comment by TiZ-EX1** [comment]
So... wait... did my verified commits really break the PPA? ;_;

**Comment by wa4557** [comment]
Yeah I'm afraid the did. But it is totally and 100% launchpads fault

**Comment by TiZ-EX1** [comment]
Huh. I hope they fix it.

They probably won't.

**Comment by Foggalong** [comment]
I long since stopped hoping for Canonical to fix any problem in anything they make.

**Comment by Foggalong** [comment]
I did those commands and pushed the result to a ppa-fix branch, but it's looking a bit weird to me. Why is it "55 commits ahead, 93 commits behind master" rather than just a different of 8 commits, the number removed?

**Comment by wa4557** [comment]
But that's fine. git goes back in history before those commits and applies all fixes since then. That's why the PR looks so huge. Why it says "55 commits ahead, 93 commits behind master" is because it usually if you merge a PR into master it produces two entries in git log. The second commit messages, that say "Merge PR from ..." are removed (for whatever reason, but that doesn't matter)

**Comment by Foggalong** [comment]
@wa4557 Do we then also need to remove the "merge PR from..." commits too? I remember us trying to do something similar with cirlce

**Comment by wa4557** [comment]
Probably. `4c51641` from June 21 is the relevant PR, but I guess this one gets removed automatically

**Comment by Foggalong** [comment]
I've just looked at this again, and even with an extra commit for every merged signed commit (and including `4c51641` to boot) that brings the total number of commits removed to 18. Since the difference between 93 and 55 is 38, doesn't that mean at least an extra 20 commits have been removed too?

**Comment by wa4557** [comment]
If I look into git log I see exactly 30 of those PRs that get removed.
The first one would be
`4c51641cbf7ecb0f6d5873d7ef9d48a24a86a563 Merge pull request #1075 from TiZ-EX1/mimetypes-prog-langs`
the last one
`a0a7548a67d8b64712c39ea5cb8e2e6c6d46b7f5 Merge pull request #1124 from wa4557/master`

inbetween are 28 of those messages. All fine

**Comment by wa4557** [comment]
Those are the ones that will get removed + the eight problematic commits makes a total of 38
```
a0a7548a67d8b64712c39ea5cb8e2e6c6d46b7f5 Merge pull request #1124 from wa4557/master
b58d5ef7c5f88ea3efb87358c38fbd7a86d40ffd Merge pull request #1133 from wa4557/auda
813d3a2f818e5b5dd68b7258b20402c7e0a68017 Merge pull request #1117 from frisbee00/qtox-tray
3c8b9563fe25e0cb9c3f0137e495481da07d5f58 Merge pull request #1131 from wa4557/inkscape
9ccc1ed3edf082fcf9b88d643e78d833132cda22 Merge pull request #1122 from wa4557/1119
789364a222fc9e5e432dcb6f9c08cd252779e7bf Merge pull request #1130 from wa4557/elem
7d3829d4d7a1c8eef081136c7fa5e08115ad2c4c Merge remote-tracking branch 'upstream/master'
c57927107fd1f8919f5288194eabd4e8c650d7e0 Merge pull request #1129 from wa4557/jockey
85bdc717441b1eb66059282c8b4ef85fc3d72c00 Merge remote-tracking branch 'upstream/master'
2cbb9748ae1fda71fdf84a9d054e2cfaff219750 Merge pull request #1127 from wa4557/xfburn
2d7a070785188dfdcd9e4cb099ba23332da60815 Merge pull request #1126 from wa4557/network-printer
b518058a7efb472bddfb6277a6bf937f3292c6eb Merge pull request #1128 from wa4557/newoffline
ae0f510015481a0f5a4a284c04321e32ffc42457 Merge pull request #1125 from wa4557/9892
c29f221ce65e4c8c766591bde184d34c419f107c Merge pull request #1123 from wa4557/adw
5116147b3ea1175e6d5c3fa98bba16d1aebb3834 Merge pull request #1121 from wa4557/1120
3c9380d5e60754203add0e39bf77285d3f6c5d23 Merge pull request #1116 from wa4557/elementary
d1e9a8d5c7b74be48502d8e9b2440f4b136971b9 Merge pull request #1114 from wa4557/ownmerged
38b25a0f5e67f980682a561c8a312dfba3bec14f Merge pull request #1115 from wa4557/folder
27ddab577356d8bce30f4557d321245161282e30 Merge pull request #1109 from wa4557/nylas
5b64259270ec209d7b221c1f20365e5b55bae33a Merge pull request #1098 from wa4557/printer
cdf8e3a950ab7a06b66bfb23b88298fcc6039c4a Merge pull request #1108 from palob/rar-symlinks
ef3f3e0620bbb0ab6573e245d7b9e10995285be7 Merge pull request #1106 from wa4557/skype
9563b6acbb587a51bf882038af682eeaab4a6219 Merge pull request #1105 from wa4557/inkscape
3aa12852444594165548eb3d753184223d6e07d7 Merge pull request #1104 from palob/geojson-link
0d47b4126726d6237a51339c390d68606ad73548 Merge pull request #1102 from palob/appimage-mimetype
42d58639defb175d39c231b038fbba2f9d928b8e Merge pull request #1101 from wa4557/hibernate
b62eddcf534b5103aee10291de2f8366ddbbe9fe Merge pull request #1097 from wa4557/telegram
8a2f08c7ac9faefb85a0f39ed598d865a89a7080 Merge pull request #1096 from wa4557/junk
72c00cb61622e4a0c00243eda405746866dd82f9 Merge pull request #1092 from wa4557/keyboard
4c51641cbf7ecb0f6d5873d7ef9d48a24a86a563 Merge pull request #1075 from TiZ-EX1/mimetypes-prog-langs
```

**Comment by Foggalong** [comment]
Ahhh, I see what's happening: it's just removing all of the merge message commits and then readding all of those commits under a new pull request! Sorry for being so slow to catch on with that. Will merge the pull request now :+1:

**Comment by wa4557** [comment]
Well, the commits are still there. Maybe you have to do this on master?

**Comment by Foggalong** [comment]
Well damn. I'll try doing it again on the master branch :+1:

**Comment by TiZ-EX1** [comment]
Just checking in because I feel like I should. :3

**Comment by wa4557** [comment]
@Foggalong What we did was kinda stupid. We just reapplied all the same PR again. For the rebase on master you have to not only remove the eight prolematic commits (the same as before) but also the "duplicate" commits starting from `a052f2d` (bold font for indicator-keyboards) till the end `432bcb1` (a few last quirks)

**Comment by Foggalong** [comment]
@wa4557 I get this error when I try to do the rebase. Any ideas?

```bash
josh@brain:~/Code/numix/icons/base$ git rebase -i 4c51641cbf7ecb0f6d5873d7ef9d48a24a86a563~1
error: could not apply 0b209ee... Clean up unnecessary nodes on Nim logo.

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".
Could not apply 0b209eed9b2e5793fe9a76dbc23405943311bb1b... Clean up unnecessary nodes on Nim logo.
```

**Comment by wa4557** [comment]
You have to do what I said in my last commit. All commits introduced by the previous "fix" have to be removed as well, it works then!

**Comment by khurshid-alam** [comment]
Are you guys using "squash & merge" ? It's better. Also if ppa-fix branch was perfect, the we should replace current master branch with ppa-fix (as master).

**Comment by wa4557** [comment]
If we do merge --squash,  are the commits really gone? PPa-fix was perfect, we can also replace current master, same thing actually

**Comment by khurshid-alam** [comment]
Which commits? Commits from that PR? **No**. (In-fact I noticed now that you guys are indeed using squash merge.)

**Comment by Foggalong** [comment]
@khurshid-alam Am I right in thinking you're currently trying rebuilding this based off the ppa-fix branch? If so I won't retry rebasing master until you're done

**Comment by khurshid-alam** [comment]
`ppa-fix` branch works. https://code.launchpad.net/~khurshid-alam/numix-icon-theme/ppa-fix

Now replace the master and this issue is closed.

**Comment by khurshid-alam** [comment]
@Foggalong 

> Am I right in thinking you're currently trying rebuilding this based off the ppa-fix branch?

Yes. Only to check whether it works or not. And it works.

**Comment by Foggalong** [comment]
the previous `master` is now `backup` and what was `ppa-fix` is now `master`

**Comment by TiZ-EX1** [comment]
I'll make sure to turn off commit signing next time I contribute. Sorry for all the trouble guys. <3

**Comment by Foggalong** [comment]
@TiZ-EX1 It's really no problem, we all do stuff like this from time to time by accident :smile:

**Comment by wa4557** [comment]
Fixed:)
