### ISSUE TITLE
Electron apps tray icons

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-icon-theme#1107]
Here's a list of new tray icons that were added to Hardcode-Tray recently and i think that have a lot of users out there :)

Nylas : 
- [x] `nylas-tray-full-newitems`
- [x] `nylas-tray-full`
- [x] `nylas-tray-empty`

Stremio: 
- [x] `stremio-tray`

Twitch Indicator:
- [x] `twitch-indicator`

Anatine: 
- [x] `anatine-indicator`
- [x] `anatine-notification`

![selection_003](https://cloud.githubusercontent.com/assets/7660997/16900999/48ff73e6-4c2e-11e6-919f-5ede53b5352c.png)

Caprine: 
- [x] `messenger-indicator` 
- [x] `messenger-notification`

![selection_002](https://cloud.githubusercontent.com/assets/7660997/16900973/8092f1da-4c2d-11e6-8085-1a82e5a137a2.png)

Slack:
- [x] `slack-indicator-highlight`
- [x] `slack-indicator`
- [x] `slack-indicator-unread`

I'm going to add screenshot of icons later.

**Comment by bil-elmoussaoui** [comment]
@Foggalong @wa4557 I think this one can be closed ? :)

**Comment by wa4557** [comment]
yeah
