### ISSUE TITLE
Icon request: qtox tray icons

### ISSUE THREAD

**Issue by frisbee00** [numixproject/numix-icon-theme#1110]
The tray icon names for qtox as per https://github.com/tux3/qTox/pull/2689.
* [x] **qtox-online**
![qtox-online](https://cloud.githubusercontent.com/assets/6317854/17097735/aebd9a74-527c-11e6-86d2-9604db4b2e88.png)
* [x] **qtox-offline**
_Could not find the right icon._
* [x] **qtox-busy**
![qtox-busy](https://cloud.githubusercontent.com/assets/6317854/17097737/b88bc77e-527c-11e6-927d-7c5fdb36cc71.png)
* [x] **qtox-away**
![qtox-away](https://cloud.githubusercontent.com/assets/6317854/17097743/c1524b8a-527c-11e6-8138-fbb99bee9d4e.png)
* [x] **qtox-invisible**
_Could not find the right icon._
* [x] **qtox-event**
_Could not find the right icon._

**Comment by bil-elmoussaoui** [comment]
The icons can be found here https://github.com/tux3/qTox/tree/master/img/taskbar/

**Comment by frisbee00** [comment]
How about these for starters?
[qtox-panel.zip](https://github.com/numixproject/numix-icon-theme/files/399234/qtox-panel.zip)

**Comment by bil-elmoussaoui** [comment]
You need to provide 16x16, 22x22 and 24x24 sizes also a dark and light variant of colors. Once it's done you can open a PR

**Comment by frisbee00** [comment]
Are those fine? I am not sure about the colours and other specifications for it to fit in the theme.

**Comment by bil-elmoussaoui** [comment]
I can't really give you an opinion about this. @wa4557 is the best one to comment your tray icons design! :+1:

**Comment by Foggalong** [comment]
If these are to go in the tray they need to be monochrome or single colour for notification highlights. They also need aligning to grid considerably more before they can be merged. @frisbee00 if you'd like to work on them with us though open a pull request and we can start on fixing them up :)

**Comment by wa4557** [comment]
Fixed \o/
