### ISSUE TITLE
Numix breaks Virtualbox (Ubuntu 16.04)

### ISSUE THREAD

**Issue by firestar115** [numixproject/numix-icon-theme#1112]
When installing VBox, I get an error about Numix.

All is well, until I try to run `/sbin/vboxconfig` to configure it. It throws a seg fault, which with a little poking around I found it was related to an `icon-theme.cache`. I immediately connected this to Numix, since it threw an error on install.

**Comment by Foggalong** [comment]
@firestar115 What package does the `/sbin/vboxconfig` command come from? I dont' have it after installing the standard `virtualbox` package

**Comment by firestar115** [comment]
The `.deb` from the site

**Comment by Foggalong** [comment]
![screenshot_2016-08-13_19-07-05](https://cloud.githubusercontent.com/assets/5920259/17644804/28507454-6189-11e6-971a-e196a6e8f224.png)

@firestar115 I've just installed the deb and I'm still not getting this command so I'm not sure how else to go about reproducing it on my end. What's the exact error you're getting and are you having this problem with any other icon themes?

**Comment by firestar115** [comment]
It wasn't Numix, it was the drivers I didn't have installed, sorry :P it's just that Numix game an error when Virtual box was installed, and I've fixed both errors.

**Comment by Foggalong** [comment]
Ah, no problem! Thanks for letting us know :smile:
