### ISSUE TITLE
The edit-find-symbolic icon should be a magnifying glass.

### ISSUE THREAD

**Issue by hugomg** [numixproject/numix-icon-theme#1113]
Please change the edit-find-symbolic icon into a magnifying glass instead of the current "targeting crosshairs" image.

For example, the following screenshots show the search feature in the Evince document viewer. The first screenshot shows the part of the toolbar with the search button and the second screenshot shows the search field that appears when you click the button:

![screenshot_2016-07-31_12-55-22](https://cloud.githubusercontent.com/assets/1452192/17278486/f5a10310-5734-11e6-981c-102a67069eaf.png)

![screenshot_2016-07-31_15-54-16](https://cloud.githubusercontent.com/assets/1452192/17278601/2dddf1be-5737-11e6-8f5f-4409c36b004e.png)

Most other icon themes use a magnifying glass for these search icons. For example, here is how Evince looks like under the Adwaita theme:

![screenshot_2016-07-31_12-56-25](https://cloud.githubusercontent.com/assets/1452192/17278504/39dfd51a-5735-11e6-9cf6-4b1b0ece3b9f.png)
![screenshot_2016-07-31_15-54-58](https://cloud.githubusercontent.com/assets/1452192/17278618/8d3f0706-5737-11e6-9f51-9640ec4687e9.png)

When I see the crosshairs icon from the current Numix theme I expect it to be related to be some point-and-click targeting. I think the traditional magnifying glass would be a clearer indicator for text-based search.

The magnifying glass would also be more consistent with other Numix icons. Although `actions/edit-find-symbolic.svg` is a set of crosshairs, both `actions/edit-find-replace-symbolic.svg` and `actions/edit-find.svg` use a magnifying glass.

| Symbol name | Image |
| :-- | :-- |
| edit-find-symbolic | ![edit-find-symbolic](https://cloud.githubusercontent.com/assets/1452192/17278640/fb08fdb4-5737-11e6-879a-fcc9ce8722bb.png) |
| edit-find-replace-symbolic | ![edit-find-replace-symbolic](https://cloud.githubusercontent.com/assets/1452192/17278641/031ecee8-5738-11e6-95f8-64d50aa6fb60.png) |
| edit-find | ![edit-find](https://cloud.githubusercontent.com/assets/1452192/17278667/bff7de24-5738-11e6-9b38-db0615c68485.png) |
| edit-find-replace | ![edit-find-replace](https://cloud.githubusercontent.com/assets/1452192/17278668/c299545a-5738-11e6-8037-944459fed2b9.png) |

**Comment by Foggalong** [comment]
We definitely need to decide on one or the other to standardise from, though I do have a soft sport for the cross-hair iconography.

**Comment by wa4557** [comment]
@Foggalong I do like the crosshair icon, but it is a bit hard to recognize as a cross-hair since it is a very non-standard way to make this icon. Since we do have already the colored icons for the action icons, maybe we should switch the symbolic icon?

**Comment by Foggalong** [comment]
I like the cross-hair icon too :( but yeah, probably switch to the magnifying glass since that's the standard. Maybe keep the crosshair around under another name incase we find use for it elsewhere down the line
