### ISSUE TITLE
Todoist icon is outdated.

### ISSUE THREAD

**Issue by VinnyFonseca** [numixproject/numix-icon-theme#1118]
[This](https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwipjbCV1bTOAhWEuxQKHegtDesQjRwIBw&url=https%3A%2F%2Fblog.todoist.com%2F&psig=AFQjCNHRVBiX1PR7GH5yNxNFSVyTHJm-yA&ust=1470843497539196) is their current icon.
[This](http://orig12.deviantart.net/97c2/f/2014/268/2/3/todoist_by_lopaneyo-d80jgms.png) is Numix Circle's outdated icon.

Could you update it?

**Comment by wa4557** [comment]
Wrong repository. Please report it [here](https://github.com/numixproject/circle-core)

**Comment by VinnyFonseca** [comment]
Reported, thanks.
