### ISSUE TITLE
Numix light messaging indicator in Unity

### ISSUE THREAD

**Issue by boriseto** [numixproject/numix-icon-theme#1119]
Using the Numix light theme, the messaging menu indicator doesn't lit up in a color whenever there is an event. It works for the Numix theme though.

**Comment by wa4557** [comment]
@boriseto Can you elaborate on what happens instead? Simple symlink should be sufficient I guess

**Comment by boriseto** [comment]
@wa4557 nothing, the icon remains black, like there is no notification. The same happens with the light circle theme as well.

**Comment by wa4557** [comment]
@Foggalong I think it would be best to symlink all "coloured" icons from `status` and `panel` to Numix-Light as well. Just to prevent further issues. What do you think?

**Comment by wa4557** [comment]
@boriseto I made a PR that should fix this issue. If you want you can try that out

**Comment by boriseto** [comment]
@wa4557 at work at the moment, can't test. Will go home on Monday. :)

**Comment by Foggalong** [comment]
@wa4557 Agreed, will merge after it's been tested :+1:

**Comment by wa4557** [comment]
@boriseto 
Can you already say if the fix works?

**Comment by boriseto** [comment]
@wa4557 sorry that I was unavailable, just arrived home. Will give it a go now.

**Comment by Foggalong** [comment]
@boriseto I was going to write a whole tutorial explaining how to get them running side by side, but in honesty it's probably easier to uninstall the PPA version and then just [download the git version](https://github.com/numixproject/numix-icon-theme-circle/archive/master.zip) and copy the `Numix` and `Numix-Light` folders to /usr/share/icons/`.

**Comment by wa4557** [comment]
@Foggalong: he has to try out my branch though :)

@boriseto: I'll try it out myself and report back when I'm finished

**Comment by wa4557** [comment]
I can confirm the issue, and that the fix works. From top to bottom (always with an active notification of course)

Numix / Numix Light (without patch) / with patch
![screenshot from 2016-09-07 22-16-30](https://cloud.githubusercontent.com/assets/6475757/18327125/57e58ff0-7549-11e6-8e1a-5d71d575673e.png)

**Comment by Foggalong** [comment]
@wa4557 Ah shoot, forgot about that. Thanks for testing it though! Will merge now :+1:
