### ISSUE TITLE
Broken library-podcast.svg symlinks

### ISSUE THREAD

**Issue by k-kirill** [numixproject/numix-icon-theme#1120]
It seems that the following symlinks are broken:
./Numix/128/places/library-podcast.svg
./Numix/128@2x/places/library-podcast.svg
./Numix/64/places/library-podcast.svg
./Numix/64@2x/places/library-podcast.svg

```
[   26s] ERROR: link target doesn't exist (neither in build root nor in installed system):
[   26s]   /usr/share/icons/Numix/64/places/library-podcast.svg -> /usr/share/icons/Numix/64/devices/network-wireless.svg
```

**Comment by wa4557** [comment]
Pushed a fix. There shouldn't be a `128` folder, though

**Comment by k-kirill** [comment]
> There shouldn't be a 128 folder, though

`128` points to `64`, that's why it was affected by the same broken link.

Thanks for fixing!
