### ISSUE TITLE
Tray icons of audacious.

### ISSUE THREAD

**Issue by darkshram** [numixproject/numix-icon-theme#1132]
Audacious is missing tray icons in MATE desktop. The name of the missing icon is audacious-panel.svg. Humanity icon themes have it in apps/22 and apps/24. Numix-circle has a very nice 48x48 icon named audacious.svg that is perfect fot the tray icon.
![pantallazo-2016-09-08 22-51-31](https://cloud.githubusercontent.com/assets/10327500/18375200/94fc9f48-7619-11e6-95df-a313acb7457d.png)

**Comment by palob** [comment]
We don't think our app icons are suited for the tray, We'll design a new one. Can you find out the name of the tray icon for QOwnnotes shown in the screenshots?

**Comment by darkshram** [comment]
Cool! Thank you! As for QOwnNotes: the icon name is 'QOwnNotes'.

**Comment by wa4557** [comment]
And the one that shows the screen, with the ruler?

**Comment by darkshram** [comment]
That's gnome-display-properties.

**Comment by bil-elmoussaoui** [comment]
Is that the gtk or qt version of audacious?

**Comment by darkshram** [comment]
It's the gtk2 version of audacious.

**Comment by darkshram** [comment]
mate-display-properties (gnome-display-properties) and QOwnNotes use the same icon name for both the desktop and tray. The only way a different icon could show up in the systray from mate-panel is if devs from these projects change the icon name for the tray.
