### ISSUE TITLE
Franz panel icon too small?

### ISSUE THREAD

**Issue by edgard** [numixproject/numix-icon-theme#1136]
Is it just me or does the Franz panel icons seems a little too small? Feels a little wrong for me...

Original:
![image](https://cloud.githubusercontent.com/assets/9547/18599992/8624b05a-7c31-11e6-858f-b1ac52e78e46.png)

With Numix-Icon:
![image](http://oi63.tinypic.com/14ipd7m.jpg)

**Comment by wa4557** [comment]
Is it? What do you propose. I kinda like it

**Comment by Foggalong** [comment]
I think it probably needs to be a px or 2 down becasue atm it's not centred.

**Comment by edgard** [comment]
That might be it, maybe if it's aligned it doesn't feel so small :D

**Comment by wa4557** [comment]
Alright, I'll fix it afrer #1103 has been taken Care of

**Comment by wa4557** [comment]
I cannot reproduce that, for me the panel icons is almost perfectly centered.
![unbenannt](https://cloud.githubusercontent.com/assets/6475757/19051343/ed405bb6-89b2-11e6-8ce5-100112bbc85c.png)

**Comment by edgard** [comment]
Might be something GnomeShell/TopIcons related then. Yours look much better than here.
