### ISSUE TITLE
Add firewall-applet icons?

### ISSUE THREAD

**Issue by darkshram** [numixproject/numix-icon-theme#1138]
Please add firewalld-applet icons. The icon names used are:
- [ ] firewall-applet-error
- [ ] firewall-applet-panic
- [ ] firewall-applet

![firewall-applet](https://cloud.githubusercontent.com/assets/10327500/18821441/c652ba8c-836b-11e6-9786-000e71f615c5.png)
firewall-applet icon

![firewall-applet-error](https://cloud.githubusercontent.com/assets/10327500/18821443/c655ae68-836b-11e6-8b77-e5fce0e196f4.png)
firewall-applet-error icon

![firewall-applet-panic](https://cloud.githubusercontent.com/assets/10327500/18821442/c6557948-836b-11e6-97ab-65569addf059.png)
firewall-applet-panic icon

Looks like this in MATE panel:
![pantallazo-2016-09-25 21-56-31](https://cloud.githubusercontent.com/assets/10327500/18821444/c6579728-836b-11e6-9b06-e8ac8982f172.png)

**Comment by wa4557** [comment]
@darkshram Sure. We have to think for a good design though, since they are not easy to do. Why is there the folder-desktop icon in the right corner. Is this a MATE thing?

@Foggalong Can you run the rebase commands for the PPA? I don't want to open PRs until this is fixed...

**Comment by darkshram** [comment]
@wa4557 That's the MATE applet used to 'show desktop'. I use this panel layout:
![aldos](https://cloud.githubusercontent.com/assets/10327500/18827392/2de030a4-8398-11e6-80b7-0dafdccb6b34.png)
It's a custom Linux distro.

**Comment by Foggalong** [comment]
Edited the original comment to enter list format. I could have sworn we already had some firewall icons for Mint (a shield design iirc) but I'm possibly mistaken

**Comment by wa4557** [comment]
@Foggalong We have those `mintupdate-*` icons that would fit. (Thinking about it, I'm not sure why the `mintupdate` icons do have the firewall symbolism)

**Comment by Foggalong** [comment]
@wa4557 Ah that would be them. I think that's because the original Mint update icons also use shields for updates so using themm for the firewall has the potential to get confusing.

**Comment by wa4557** [comment]
@Foggalong Maybe we should change the update icons then (something similar to the `pamac-` icons for example) and use these icons as firewall icons. Makes more sense imo

**Comment by darkshram** [comment]
@wa4557  it's because yumex uses that kind of icons. That's the reason they look like shields.
/usr/share/pixmaps/yumex/tray-error.png
/usr/share/pixmaps/yumex/tray-info.png
/usr/share/pixmaps/yumex/tray-no-updates.png
/usr/share/pixmaps/yumex/tray-updates.png
/usr/share/pixmaps/yumex/tray-working.png

![tray-error](https://cloud.githubusercontent.com/assets/10327500/18839804/f1cd4180-83d1-11e6-8bef-771a037d653e.png) ![tray-info](https://cloud.githubusercontent.com/assets/10327500/18839805/f1ce96ac-83d1-11e6-8e32-c0169b687859.png) ![tray-no-updates](https://cloud.githubusercontent.com/assets/10327500/18839806/f1cf8486-83d1-11e6-8a16-4614a8dc0fdd.png) ![tray-updates](https://cloud.githubusercontent.com/assets/10327500/18839808/f1d6c75a-83d1-11e6-8ba5-06a4c7262b2a.png) ![tray-working](https://cloud.githubusercontent.com/assets/10327500/18839807/f1d053c0-83d1-11e6-8d0c-3a963708a49b.png)

**Comment by wa4557** [comment]
Yeah, this is stupid though imo. Why using a firewall icon for update status? I guess we should rather change the update icons, than thinking about a new design for firewall icons. No need to stay close to the original here.

**Comment by Foggalong** [comment]
@wa4557 Switching the designs from the original and using them elsewhere is a bad idea because it gets confusing from the users perspective.

**Comment by wa4557** [comment]
@Foggalong Alright, I'll think of a different design for firewall then. You still need to do the rebase commands though, before I can start sending PRs again :)

**Comment by darkshram** [comment]
I had a few free time and did these icons, based on other numix icons. I'm not an artist, so guess they are far from being perfect or even comply to numix standards.

<img width="18" alt="firewall-applet" src="https://user-images.githubusercontent.com/10327500/31156006-d2f39ebe-a877-11e7-998d-d55977f1f75d.png">
<img width="18" alt="firewall-applet-error" src="https://user-images.githubusercontent.com/10327500/31156004-d2eef634-a877-11e7-9a81-df712431f721.png">
<img width="18" alt="firewall-applet-panic" src="https://user-images.githubusercontent.com/10327500/31156007-d2f4fdae-a877-11e7-8a2a-1cea7d870997.png">
<img width="18" alt="firewall-config" src="https://user-images.githubusercontent.com/10327500/31156005-d2f1c99a-a877-11e7-87f8-e88a54845c4c.png">

[firewall-applet-and-config.zip](https://github.com/numixproject/numix-icon-theme/files/1354334/firewall-applet-and-config.zip)

**Comment by darkshram** [comment]
Tested my icons in my desktop. Looks like this:
![pantallazo-2017-10-07 21-29-36](https://user-images.githubusercontent.com/10327500/31313369-e67ee920-aba6-11e7-93a7-e910e75a3d13.png)

**Comment by wa4557** [comment]
No, they are good, I will use them to create a pull request
