### ISSUE TITLE
Missing symlink for Nautilus

### ISSUE THREAD

**Issue by Tadly** [numixproject/numix-icon-theme#1139]
Starting with Gnome 3.22, nautilus uses the icon-name `org.gnome.Nautilus`.

A symlink `org.gnome.Nautilus` -> `file-manager.svg` should be created.

Thanks :)

**Comment by Foggalong** [comment]
This is an issue for [circle-core](https://github.com/numixproject/circle-core) since that's the repo where we deal with app icons.
