### ISSUE TITLE
XFCE Wired Network Pannel Icon

### ISSUE THREAD

**Issue by Foggalong** [numixproject/numix-icon-theme#114]
![screenshot - 270414 - 17 46 40](https://cloud.githubusercontent.com/assets/5920259/2811683/a2bf45c4-ce2b-11e3-8603-2f309f98db68.png)

Existed before 14.04 and now doesn't. I'm trying to find the icons location now but with no success. I'll keep looking. I thought ```nm-device-wired.png``` would be the relevant icon but changing it doesn't seem to do anything.

**Comment by dirtydancing** [comment]
With https://github.com/numixproject/numix-icon-theme/issues/461, this issue can be closed now.

**Comment by wa4557** [comment]
This is fixed now :)

**Comment by Foggalong** [comment]
\O/
