### ISSUE TITLE
Rambox indicator

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-icon-theme#1142]
As requested https://github.com/bil-elmoussaoui/Hardcode-Tray/issues/177
The icon names are 
- [ ] `rambox-indicator`
![icon](https://cloud.githubusercontent.com/assets/7660997/19021560/ddc0435c-88c4-11e6-8a8d-240c461fa9eb.png)
- [ ]  `rambox-notification`
![icontrayunread](https://cloud.githubusercontent.com/assets/7660997/19021559/ddbbf2a2-88c4-11e6-81f0-6ea72eb95f33.png)

**Comment by wa4557** [comment]
With the original icon., is the gorilla recognizable?

**Comment by Foggalong** [comment]
Roughly yeah ![screenshot_2016-10-03_20-56-18](https://cloud.githubusercontent.com/assets/5920259/19051717/db31acec-89ab-11e6-862d-f2754b3a3f88.png)

**Comment by wa4557** [comment]
Meh, this looks no good :(

**Comment by Foggalong** [comment]
It's not an amazing icon, but it doesn't really have anything else to uniquely identify it
