### ISSUE TITLE
Clementine panel icon fix

### ISSUE THREAD

**Issue by sagarpanchal** [numixproject/numix-icon-theme#1149]
You've added too many panel icons for clementine in `status/` directory but It doesn't looks for any icons in `status/` directory.

Clementine's **/src/ui/[qtsystemtrayicon.cpp](https://github.com/clementine-player/Clementine/blob/3fc6208248a211c10b4e171b450c8b3d6b600259/src/ui/qtsystemtrayicon.cpp)** looks for only two icons inside `panel/` directory to generate all system-tray icons.

```
Numix/24/panel/clementine-panel.svg
Numix/24/panel/clementine-panel-grey.svg
```

```
Numix-Light/24/panel/clementine-panel.svg
Numix-Light/24/panel/clementine-panel-grey.svg
```

**Search for "clementine-panel" in `/src/ui/qtsystemtrayicon.cpp`** and you'll understand the issue --> https://github.com/clementine-player/Clementine/blob/3fc6208248a211c10b4e171b450c8b3d6b600259/src/ui/qtsystemtrayicon.cpp

Patch --> [numix-clementine-status-icons-fix.tar.gz](https://github.com/numixproject/numix-icon-theme/files/516723/numix-clementine-status-icons-fix.tar.gz) [Tested with Qt version 4.8.7, Clementine version 1.2.3 on Ubuntu 16.04 (Unity, Gnome and xfce)]

**Comment by Foggalong** [comment]
@sagarpanchal Can you please submit the patch as a pull request, it make review much easier
