### ISSUE TITLE
Slack tray icon shows as question mark in Ubuntu 16.10

### ISSUE THREAD

**Issue by PHLAK** [numixproject/numix-icon-theme#1156]
I'm using the numix-circle theme on Ubutu 16.10 and the Slack icon shows up as the following question mark icon.

![selection_007](https://cloud.githubusercontent.com/assets/53531/19537600/7540aea4-9605-11e6-8d78-d1302e9d49b3.png)

However, when I first launch Slack it shows up properly for several seconds before going back to this.

**Comment by wa4557** [comment]
How does it look like with other themes?

**Comment by PHLAK** [comment]
It doesn't look right for other themes either.  I think this is an issue with the app itself, not numix-icons.  Though it might be nice to add a numix specific tray icon for Slack in the future.

**Comment by bil-elmoussaoui** [comment]
It's already there, just use Hardcode-Tray as mentioned on the README :+1:
