### ISSUE TITLE
NoMachine Indicator

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-icon-theme#1158]
As requested here https://github.com/bil-elmoussaoui/Hardcode-Tray/issues/181
The missing icons are 
- [ ] `nomachine-indicator` ![nomachine-icon](https://cloud.githubusercontent.com/assets/7660997/19851328/a6901f6a-9f5d-11e6-855d-2fe348fbdd6d.png)

- [ ] `nomachine-disabled` ![nomachine-icon](https://cloud.githubusercontent.com/assets/7660997/19851328/a6901f6a-9f5d-11e6-855d-2fe348fbdd6d.png) the default icon is fully transparent (nothing shown at all...) but we can use a the same indicator a little more transparent for a desactive state.

**Comment by varlesh** [comment]
From easy way :) From Papirus with color change to #ececec
[nomachine-hardcode-tray.zip](https://github.com/numixproject/numix-icon-theme/files/561749/nomachine-hardcode-tray.zip)
