### ISSUE TITLE
ibus-mozc icon indicator for numix

### ISSUE THREAD

**Issue by sandycorzeta** [numixproject/numix-icon-theme#116]
Requesting an input method icon indicator for ibus-mozc

the icon file is found on "/usr/share/ibus-mozc/" folder .

there are a lot of icon here but only have 22x22 res and no any high resolution size more than that. So i'll gonna put this in one pack (as mozc package) instead make it one by one.

and here is the icon looks like

filename "tool.png" :
![tool](https://cloud.githubusercontent.com/assets/4186454/2815646/96e93402-cebd-11e3-825a-8bf9a5989e8a.png)

filename "properties.png" :
![properties](https://cloud.githubusercontent.com/assets/4186454/2815647/96fbdddc-cebd-11e3-88ac-c1255d93cccc.png)

filename "product_icon.png" :
![product_icon](https://cloud.githubusercontent.com/assets/4186454/2815648/9708dbc2-cebd-11e3-9b59-46aabf62c2d8.png)

filename "katakana_half.png" :
![katakana_half](https://cloud.githubusercontent.com/assets/4186454/2815649/970c79a8-cebd-11e3-9b41-44b45fb01a21.png)

filename "katakana_full.png" :
![katakana_full](https://cloud.githubusercontent.com/assets/4186454/2815650/97164370-cebd-11e3-841e-7c4eb3109c7d.png)

filename "hiragana.png" :
![hiragana](https://cloud.githubusercontent.com/assets/4186454/2815651/971fffaa-cebd-11e3-806d-1d90a46827f6.png)

filename "direct.png" :
![direct](https://cloud.githubusercontent.com/assets/4186454/2815652/97346e40-cebd-11e3-8cac-82866b9298bb.png)

filename "directory.png" :
![dictionary](https://cloud.githubusercontent.com/assets/4186454/2815653/97442b50-cebd-11e3-896e-ac385b2e8ad5.png)

filename "alpha_half.png" :
![alpha_half](https://cloud.githubusercontent.com/assets/4186454/2815654/97582088-cebd-11e3-93d2-482991a30434.png)

filename "alpha_full.png" :
![alpha_full](https://cloud.githubusercontent.com/assets/4186454/2815655/975d29c0-cebd-11e3-92aa-79c3e9fda9f2.png)

if there is anything missing or something wrong with the bug, please reply so i can provide more help about the original icon and anything more about it

**Comment by bil-elmoussaoui** [comment]
@Foggalong It's now possible to fix those icons using HardcodeTray, if @sandycorzeta still want them, you can open this issue and #115 too
