### ISSUE TITLE
Question regarding hardcoded tray icons

### ISSUE THREAD

**Issue by mikassi** [numixproject/numix-icon-theme#1162]
This repo's README links to a hardcoded tray icons fixer, however the repo for the circle and square icons links to another fixer. If I want to submit a request, which fixer should I use?

Thanks.

**Comment by bil-elmoussaoui** [comment]
Hey,
The fixer on Numix base icons README is for tray icons. The one on Circle and Square repo is for the hardcoded icons (desktop files).

**Comment by mikassi** [comment]
Oh, my bad, I misread. Thanks.
