### ISSUE TITLE
icon for Eric6

### ISSUE THREAD

**Issue by wyattwhat** [numixproject/numix-icon-theme#1163]
please add a numix-circle icon for eric6 python editor 
the icon line says 'eric'
w/ original  icon attached
![screenshot from 2016-11-13 16-21-54](https://cloud.githubusercontent.com/assets/21696869/20249749/5af10ef6-a9bd-11e6-9320-26a70c6d1764.png)

**Comment by palob** [comment]
This is an issue for https://github.com/numixproject/numix-core.

We've already got this icon for quite a time. Supposing you're using Numix-Circle your installation seems to be outdated. How did you install it?

**Comment by wyattwhat** [comment]
i installed via fedy yesterday

**Comment by wyattwhat** [comment]
if i installed mate and switched will it work?

**Comment by wyattwhat** [comment]
here is a picture of my desktop. It shos my themes i installed simple dock for gnome and it does not show up on the dock 
![screenshot from 2016-11-13 17-51-26](https://cloud.githubusercontent.com/assets/21696869/20250262/ed2dee4a-a9c9-11e6-93f5-d5bac1aea18c.png)

**Comment by palob** [comment]
Looks like the Fedy package is outdated. Please report this against Fedy or manually install the latest Numix Circle from https://github.com/numixproject/numix-icon-theme-circle/releases.
