### ISSUE TITLE
Add an icon for Komodo edit

### ISSUE THREAD

**Issue by wyattwhat** [numixproject/numix-icon-theme#1164]
an icon is needed for Komodo edit ext editor.
unfortunately there is no iccon line because there is no file in /usr/share/applications/
here is a photo of the software in fedora
![screenshot from 2016-11-13 16-31-09](https://cloud.githubusercontent.com/assets/21696869/20249818/aba691c6-a9be-11e6-8270-c328cfc7ea08.png)

**Comment by palob** [comment]
Please report missing app icons over here https://github.com/numixproject/numix-core

We've already got an icon icn for Komodo Edit, alas it's *hardcoded*. 

Please cf. the readme of the numix-core repo about how to go on in such cases.

**Comment by wyattwhat** [comment]
i downloaded the hard-code fixing client or whatever its called and i launched it all four ways but none of them fixed this nor eric6

**Comment by palob** [comment]
Is there a file in ``~/.local/share/applications``?
