### ISSUE TITLE
Panel icons for Indicator-kdeconnect

### ISSUE THREAD

**Issue by varlesh** [numixproject/numix-icon-theme#1165]
Released new version Indicator-kdeconnect 0.3 with new icons:
https://github.com/Bajoja/indicator-kdeconnect

Icons for panel (not hardcoded):
`laptop-connected`
![laptop-connected svg](https://cloud.githubusercontent.com/assets/8083855/20355982/489ec206-ac34-11e6-9c9a-2e283e2ffc69.png)

`laptop-disconnected`
![laptop-disconnected svg](https://cloud.githubusercontent.com/assets/8083855/20356011/5d533498-ac34-11e6-94b8-16b668f29362.png)

`laptop-trusted`
![laptop-trusted svg](https://cloud.githubusercontent.com/assets/8083855/20356100/94a54ca6-ac34-11e6-98ba-2d64b1816a44.png)

`smartphone-connected`
![smartphone-connected svg](https://cloud.githubusercontent.com/assets/8083855/20356102/94a700dc-ac34-11e6-8805-91c069290990.png)

`smartphone-disconnected`
![smartphone-disconnected svg](https://cloud.githubusercontent.com/assets/8083855/20356103/94a737aa-ac34-11e6-88cb-dd371797c83b.png)

`smartphone-trusted`
![laptop-trusted svg](https://cloud.githubusercontent.com/assets/8083855/20356100/94a54ca6-ac34-11e6-98ba-2d64b1816a44.png)

`tablet-connected`
![tablet-connected svg](https://cloud.githubusercontent.com/assets/8083855/20356098/94a0be66-ac34-11e6-986a-abeed1c84ea2.png)

`tablet-disconnected`
![tablet-disconnected svg](https://cloud.githubusercontent.com/assets/8083855/20356099/94a20906-ac34-11e6-8dc0-d85ad2ccdb32.png)

`tablet-trusted`
![tablet-trusted svg](https://cloud.githubusercontent.com/assets/8083855/20356104/94c39468-ac34-11e6-8e80-f965768a81cd.png)

app icon not changed:
```
[Desktop Entry]
Name=KDE Connect Indicator
Comment=An awesome system for Desktop-Phone continuity.
Exec=indicator-kdeconnect
Terminal=false
Type=Application
StartupNotify=true
Icon=kdeconnect
Categories=GNOME;GTK;System;
```

**Comment by wa4557** [comment]
Fixed
