### ISSUE TITLE
Four options of Numix icons but only work two

### ISSUE THREAD

**Issue by christianbueno1** [numixproject/numix-icon-theme#1168]
Fedora 25, gnome 3.22.1. 
I installed that by> dnf  copr... etc.
I has changed  "$releasever" for "24" in _copr_numix-numix.repo
I have 4 numix options [image](http://i.imgur.com/dYUgD2o.png) , only work Numix-Cricle and Numix-Circle-Light but Gnome File icon do not change in both. [images2](http://i.imgur.com/UOEhRx2.png)
That's is normal or I must to fix something?

**Comment by bil-elmoussaoui** [comment]
First of all this issue should be reported on Numix-Core repo; and this was already fixed, the copr repo is outdated. We hope that it will be fixed soon :+1:

**Comment by christianbueno1** [comment]
ok. going [here](https://github.com/numixproject/numix-core/issues/3514)
