### ISSUE TITLE
Pixalated icons

### ISSUE THREAD

**Issue by leoheck** [numixproject/numix-icon-theme#1169]
Selected icons are pixelated on Ubuntu System Settings. 
Look the image on issue https://github.com/numixproject/numix-gtk-theme/issues/634#issue-193314406

**Comment by palob** [comment]
I take it it's only when the cursor is on it, right? It looks to be an issue with https://github.com/numixproject/numix-gtk-theme. I can't reproduce it with other GTK themes under GNOME 3.22.

**Comment by leoheck** [comment]
Yeah, right, only on mouse over.
https://github.com/numixproject/numix-gtk-theme/issues/634#issue-193314406

**Comment by leoheck** [comment]
Hey, look https://github.com/numixproject/numix-gtk-theme/issues/634#issuecomment-270927635
@palob you tested it wth Adwaita but @rewqazxv said that there is no hover effect there.
