### ISSUE TITLE
Volume icon not showing up in Banshee

### ISSUE THREAD

**Issue by lnx64** [numixproject/numix-icon-theme#1171]
While in banshee, there should be a volume icon at the top right, but with the Numix theme icon set, it's actually invisible as the color is the same as the application background.  If I use the numix-light icon set, then it becomes visible, however the icons in the Unity system tray become too dark to see.

Screenshots showing it invisible with the Numix icon set, but visible with Ubuntu's own "dark" theme.

![screenshot from 2016-12-19 04-22-31](https://cloud.githubusercontent.com/assets/2136976/21307371/330afee0-c5a3-11e6-9581-630eca8a34e5.png)
![screenshot from 2016-12-19 04-23-02](https://cloud.githubusercontent.com/assets/2136976/21307372/330bd518-c5a3-11e6-9f32-d9864ca02c81.png)

**Comment by palob** [comment]
To make sure it's really just an issue of identical colours: how does it look with another GTK+ theme and Numix?

**Comment by lnx64** [comment]
Yes I can verify and prove it.  The icon is "technically" visible in the screenshot above where it seems invisible.  Numix is using the background color "eeeeee", whereas the icon is using "ececec" which is the same as the icon used in the system tray at the top in Unity (is it maybe sharing the same icon perhaps whereas Ubuntu doesn't do this for this reason?)

When using another theme as shown here, it is visible, once again with the color "ececec", so it is technically there, it just is using clashing colors.

![screenshot from 2016-12-19 13-46-40](https://cloud.githubusercontent.com/assets/2136976/21324991/0f5ac6ac-c5f2-11e6-8b01-d5326ea1f82d.png)

This is actually not the only icon that clashes like this in the toolbar area of some applications, but I can't remember what program I was in last time, I will update here if I find.  (It wasn't the speaker icon).

**Comment by hlechner** [comment]
I agree with you @lnx64 it's really annoying, and it's a very common issue with many different icon sets (not just numix).

The big problem is that some apps like the ones that you have mention do not use their own icons or specific icons for use in this kind of toolbar.

The sound and the keyboard icons are largely used on menu systems like the menu in gnome,xfce or unity that the most of them are black or dark colors.

It's more an app's design problem than a theme issue.

For example, if you start to use the ``Numix Light`` Instead of just ``Numix`` you probably have this issue solved, however the icons of the menu of your system will be dark so you need to use a GTK light theme too.


In my opinion the best approach would be to raise an issue in the application's bug report (if not already raised) so they can analyse the best way to solve it. if was to use a different icons or create their owns.

**Comment by bil-elmoussaoui** [comment]
It's an application issue. I believe they're using the wrong icon name...

**Comment by palob** [comment]
If it is it probably won't be fixed, Banshee is a dead project.

**Comment by hlechner** [comment]
Kind of, not dead yet, but alike, many people dislike this project because it uses mono.

But there is a second app that he mentioned seems to be active: https://github.com/FreeRDP/Remmina

**Comment by bil-elmoussaoui** [comment]
The keyboard issue might be related to a non updated device icons. The icons were monochrome. I'm on mobile so I can't get the issue number

**Comment by lnx64** [comment]
Ok I get that, but how does it work with Ubuntu's own default set of icons?  They aren't using the same icon resource as it's extremely different looking that what's in the menu.  Clearly they are doing something to make it work.  Banshee may be dead, but I just flat out don't like Rythmbox.

**Comment by hlechner** [comment]
@lnx64 thanks for this info!

I can't check the ubuntu default icon set, but looking at the adwaita theme (gnome default) it seems to use symbolic.svg files to the panel, and the icon from Banshee seems to use the normal one.

I think changing to a non-monochromatic design on non-symbolic files could lead to a bugs on different DE like xfce or kde, any clue guys?

**Comment by palob** [comment]
@lnx64 Do you know [Lollypop](http://gnumdk.github.io/lollypop-web/)?

**Comment by lnx64** [comment]
@palob I do not, but thank you for linking me to that, that looks very interesting and may be a perfect candidate for a replacement!  Thanks!

**Comment by lnx64** [comment]
Unfortunetly I already managed to kill Lollypop..  "Internal data flow error".  The main problem with this software and Rythmbox is that they both start scouring my Music folder before I get to tell it NO, and point it to the right folder where I really have music.  It ends up crashing once it hits my .gbs, .vgm, etc stuff, and these software seem incapable of simply having a setup start screen to tell it where to look before it "assumes" where it should go, then it becomes completely useless in the end.  This is why I like banshee, it doesn't start until I tell it where to look, and it's the only software that ever worked on that principle.

**Comment by lnx64** [comment]
I got Lollypop working, but the Play/Pause, Forward, Backwards buttons don't have properly aligned icons in the buttons.  The icons in those buttons are vertically too high and look rather "off".  The program while giving me a rough start, appears to be running ok so far, but this is another GUI issue with this theme, but it's not the icon theme, it's the Numix GTK theme, Ambiance doesn't have this alignment issue, only Numix.

**Comment by bil-elmoussaoui** [comment]
@lnx64 well on this case, open a new issue on Numix-gtk-theme repository
