### ISSUE TITLE
[Suggestion] different icon color for different image file types

### ISSUE THREAD

**Issue by glubsy** [numixproject/numix-icon-theme#1174]
Everytime I install Numix on a machine, I have to manually add new icons for image files and video files to better differentiate them. 

For example: 
**png** red 
**jpg/jpeg** green (current one)
**gif** yellow
**bmp** blue
**psd** purple
**tga** orange
**tiff** light orange
**mp4** purple
**webm** light blue
**avi** blue (current)
**mpeg** brown

My current setup below as an example:
![Screenshot: different color for each mime type](http://i.imgur.com/wc2ZVOQ.png)

The icon files already exists in a way (they are symlinks to the same file: **application-images.svg** and **application-video.svg**"), but it's painful to do it for each size (x16, x22, x24, x32, etc.).
I have to redo each icon in Inkscape and copy them over the symlinks... It would be nice to have those by default in Numix. 

Have you considered it? Why not differentiate between formats? Why keep the same file for all the formats pointing at it?

**Comment by bil-elmoussaoui** [comment]
It's only for the 16 sizes, as it's not possible to provide each mime type with different colors :p and normally if you see those icons on a bigger scale (32, 48...) you will see the mime type of the icon (SVG, PNG or JPG for example)

**Comment by glubsy** [comment]
Yes, I did notice the bigger icons have the file type written on them. 
Why do you say it's not possible? 
I did change the bigger scale versions too, I even symlinked to the 16p versions in some cases and it works just fine.

**Comment by bil-elmoussaoui** [comment]
I didn't say it was not possible, but it's so hard to a find a proper color for each mimetype, that will help you recognize the mimetype by just looking at the color of it.

**Comment by glubsy** [comment]
Isn't it just a matter or picking one and sticking to it? 
IrfanView did that on Windows, it worked well. See below:
![irfanview icons example](http://i.imgur.com/aSTFSIA.png) ![irfanview icons example (small version)](http://i.imgur.com/PBXoJOY.png)
I'd say Numix could gain from doing the same thing. ;)

**Comment by palob** [comment]
I like the grouping of mimetypes the current colouring communicates. With distinct colours for each and every mimetype we'd lose that and things might look annoyingly/confusingly colourful.

Then if we did that for all ``image-...`` mimetypes we'd have to do it for the whole thing. The text labels would be redundand and we'd need a redesign for our entire mimetype icon collection.

Frankly I fail to see which poblem this is supposed to solve. I think Numix already provides a highly diverse mime icon collection and in file managers you can easily activate a column showing the mimetype.

What I'm more open to is maybe different lightness/saturation while retaining the hue for different image types. Or slightly varying symbols for say photos (JPG) on the one hand and graphical assets (PNG, TIFF) on the other hand like you did (did you?). Something along the lines of the discussion in #595.

**Comment by glubsy** [comment]
Thanks, I understand your point. 

Maybe it's just my personal preference then. 
I never use the file type column in file managers as it clutters the view way too much. I need to see quickly which file is of which type and act accordingly in a matter of milliseconds. That's why I always use the colour scheme I posted in the original post. 

I like the idea of neighbouring gradients in case too many colours is not desirable. Perhaps add the first letter of the filetype on the 16p size icons too instead of the small white embedded icon too? I doubt neighbouring gradients would be efficient enough by themselves. 

Anyway, that was just an idea. I'll keep doing this  little enhancement for myself though. ;)

**Comment by hlechner** [comment]
The idea of gradients will keep the design away from the Numix design.

I see your point, you need to differentiate because you probably manipulate a lot of images, however for a general purpose icon theme I do believe it can a lot be more confusing with the many different colors. specially for who do not work with images and videos.

About the first letter on the 16px is something that I believe someone can at least try it, however it will be very painful to add letters on those designs due to very limited space, because we avoid any blurry icons, we develop a pixel-by-pixel icon specific for 16px.

---

I do believe the best approach for you would be to develop a shell script to change the icons, you can also share it as a github project so if someone have the same usage as you we can share your shell script.

Just to remember: I'm not a Numix member, I'm just a community contributor

**Comment by Foggalong** [comment]
Marking this as wontfix - agreed with @palob, if we add icons for every mimetype it'd loose all meaning. However if you're wanting to make this change yourself you'd be much better serviced doing it with a sed command (`sed -i s/#OLDHEX/#NEWHEX/g [someregex]`.
