### ISSUE TITLE
*.stp files display a huge icon in engrampa archive manager.

### ISSUE THREAD

**Issue by darkshram** [numixproject/numix-icon-theme#1175]
Just opened a rpm file with engrampa (MATE archive manager) and a *.stp file showed with a relly huge icon.
![pantallazo-2017-01-10 00-43-02](https://cloud.githubusercontent.com/assets/10327500/21796398/2752c40c-d6ce-11e6-95ca-92a1fe7b4770.png)

**Comment by bil-elmoussaoui** [comment]
We don't provide those icons at all, is this happening with other themes? if not it might be related somehow to #1076

**Comment by darkshram** [comment]
You are right. It's openteacher's fault. It installs a 128x128 icon into hicolor icon theme. Please close this issue.

**Comment by bil-elmoussaoui** [comment]
Can you add the mimetype of the file, so we can add it to theme ? which will fix your issue too

**Comment by palob** [comment]
Yeah, why is that icon shown as mimetype icon? I take it you only use Numix (not Numix + Numix Circle/Square)?

**Comment by hlechner** [comment]
@bil-elmoussaoui it's not related to that issue.

@palob openteacher install the mimetypes only in 128x128 size on hicolor theme, that is why it's so big.


Here a part of python script responsable in openteacher to install the mimetypes in hicolor:
```
		("share/icons/hicolor/128x128/mimetypes", ['linux/application-x-openteachingtopography.png', 'linux/application-x-kvtml.png', 'linux/application-x-ludem.png', 'linux/application-x-wrts.png', 'linux/application-x-anki.png', 'linux/application-x-jmemorizelesson.png', 'linux/application-x-vokabeltrainer.png', 'linux/application-x-oriente-voca.png', 'linux/application-x-granuledeck.png', 'linux/application-x-domingo.png', 'linux/application-x-overhoringsprogrammatalen.png', 'linux/application-x-openteachingwords.png', 'linux/application-x-openteachingmedia.png', 'linux/application-x-pauker.png', 'linux/application-x-cuecard.png', 'linux/application-x-jvlt.png', 'linux/application-x-vocabularium.png', 'linux/application-x-overhoor.png', 'linux/application-x-apkg.png', 'linux/application-x-kgeographymap.png', 'linux/application-x-flashqard.png', 'linux/application-x-anki2.png', 'linux/application-x-backpack.png', 'linux/application-x-teachmaster.png', 'linux/application-x-teach2000.png', 'linux/application-x-openteacher.png']),
		("share/icons/hicolor/128x128/apps", [
			"linux/openteacher.png"
		]),
```

As you can see there are many different mimetypes but many of them are just the same icon.
![image](https://cloud.githubusercontent.com/assets/11244067/21840976/6c39ccba-d7c7-11e6-82dc-571b55695f42.png)

**Comment by palob** [comment]
OK, so it seems there is actually a mimetype assignment bug. It's definitely not our bug. Someone should report to the Openteacher guys. What they do is quite nonsensical.


@darkshram Can you please fire up the file properties and report what's the mime type?

**Comment by hlechner** [comment]
@palob there is no need to the report from @darkshram.

Because the openteacher uses not just one, but many, which is the mimetypes that I've reported above. So, If we gonna do something we should address most of all them (even with symlinks):



The mimetypes and the respective images:
---
![image](https://cloud.githubusercontent.com/assets/11244067/21872737/71abd1ae-d851-11e6-9f7d-9238d769dd44.png)
```
application-x-kvtml
application-x-ludem
application-x-wrts
application-x-anki
application-x-jmemorizelesson
application-x-vokabeltrainer
application-x-oriente-voca
application-x-granuledeck
application-x-domingo
application-x-overhoringsprogrammatalen
application-x-pauker
application-x-cuecard
application-x-jvlt
application-x-vocabularium
application-x-overhoor
application-x-apkg
application-x-kgeographymap
application-x-flashqard
application-x-anki2
application-x-backpack
application-x-teachmaster
application-x-teach2000
application-x-openteacher
```

![image](https://cloud.githubusercontent.com/assets/11244067/21872772/a33df846-d851-11e6-9e21-0ab23411190d.png)
```
application-x-openteachingmedia
```


![image](https://cloud.githubusercontent.com/assets/11244067/21872785/b651a0d6-d851-11e6-916f-6a81c70e6f8c.png)
```
application-x-openteachingtopography
```


![image](https://cloud.githubusercontent.com/assets/11244067/21872799/c7fb3d42-d851-11e6-8879-4d4eeda60711.png)
```
application-x-openteachingwords
```

**Comment by palob** [comment]
For an instant fix we could symlink them all to the default text or document mimetype but again, this is not an issue we are supposed to fix. The OpenTeacher devs bothed big time here.

**Comment by palob** [comment]
@darkshram Does it look the same with other themes?

**Comment by darkshram** [comment]
@palob Yes. It happens to in other themes. To fix the issue in my distro (which will be using Numix as default theme in the next release) I had to repackage openteacher doing a resize of the mimetypes icons. Sorry for the delay of my answer (I had too much work).

**Comment by wa4557** [comment]
@palob Why not just adding the respective openteacher mimetype icons? Providing all the sizes will solve the wrong size issue, I suppose. Since this is a very niche application, I suppose one icon symlinked to all others @hlechner posted should be fine

**Comment by palob** [comment]
So just symlinks to ``text-plain`` or something for now?

Actually, I think the multitude of mimetypes @hlechner reported justify a dedicated "learning" mimetype design. Maybe based on our ``openteacher`` app icon.

**Comment by wa4557** [comment]
Yeah I guess a dedicated icon would be cool

**Comment by palob** [comment]
I couldn't get a graduation cap design working for 16px.
I'm now at a temple thing as metaphor for *education* but does this make any sense?
![education](https://cloud.githubusercontent.com/assets/7050624/26753615/6a19852e-486a-11e7-9b07-16c17c23235b.png)

Any ideas?

**Comment by wa4557** [comment]
I think a temple thing is very fitting, why not? It's also quite discernible

**Comment by palob** [comment]
OK, got the hang of it, big building/temple = culture/civil engineering/science/ingenuity/creativity which education is the foundation of.

I'll go for it.

**Comment by palob** [comment]
Which colour to go with?

**Comment by wa4557** [comment]
Some kind of blue would make sense, considering the original color, but also a darkish red maybe (I don't know why but I connect that to education somehow)

**Comment by palob** [comment]
Because red is what the colour of the teacher's pen used to be? :x:

**Comment by wa4557** [comment]
Yeah now that you say it I prefer a different color ;)

**Comment by palob** [comment]
What do you say?

![overview](https://user-images.githubusercontent.com/7050624/27503404-009e892e-587c-11e7-82e7-25e7e722f445.png)

**Comment by palob** [comment]
A few colour variantions
![overview2](https://user-images.githubusercontent.com/7050624/27506873-4f7f7d4a-58c3-11e7-9d2d-9e8f87c072df.png)
![overview3](https://user-images.githubusercontent.com/7050624/27506874-4f8dc684-58c3-11e7-972b-ff68d6fba0b8.png)
![overview4](https://user-images.githubusercontent.com/7050624/27506872-4f77576e-58c3-11e7-92ea-6cc6538e19e0.png)
![overview5](https://user-images.githubusercontent.com/7050624/27506875-4fa19c72-58c3-11e7-832c-870df0fb03b0.png)
![overview6](https://user-images.githubusercontent.com/7050624/27506876-4fa42334-58c3-11e7-868a-f91f92e3f11d.png)

**Comment by wa4557** [comment]
aren't the colors a bit harsh? But the design is nice :+1:

**Comment by palob** [comment]
They are but for mimetypes most colours are fully saturated (S255).

**Comment by wa4557** [comment]
Yes you're right. In that case I would go with them
