### ISSUE TITLE
System Settings icon

### ISSUE THREAD

**Issue by pgera** [numixproject/numix-icon-theme#1179]
The system settings icon looks too much like an on/off switch. Something with either a gear or a wrench, as it is conventionally represented, would be a lot more intuitive.

**Comment by bil-elmoussaoui** [comment]
This should be reported here instead https://github.com/numixproject/numix-core

**Comment by pgera** [comment]
Done. https://github.com/numixproject/numix-core/issues/3553

**Comment by bil-elmoussaoui** [comment]
Can you close this one? Thanks!

**Comment by pgera** [comment]
Reopening. https://github.com/numixproject/numix-core/issues/3553 for more details.

**Comment by palob** [comment]
Can you please add a screenshot so it's clear which icon this is about?

**Comment by pgera** [comment]
![screenshot from 2017-01-24 23 10 19](https://cloud.githubusercontent.com/assets/5542855/22319742/8f097708-e353-11e6-9769-e5f8234f1c2c.png)

The last icon at the bottom in the launcher

**Comment by khurshid-alam** [comment]
We shouldn't fall back to gnome under with Ubuntu. Unity doesn't even have full gnome icon theme installed by default. On ubuntu  we should fall back like this: `ubuntu-mono, gnome, hicolor.` This will improve visuals for those who wants to use base icon theme.

**Comment by palob** [comment]
Maybe it's time to check a few new inherits (``Adwaita``, ``breeze``,...). So far we haven't implemented distro-specific fallbacks.

Does anybody know how themes are going to be with 17.10 when GNOME will be the standard desktop.

**Comment by khurshid-alam** [comment]
I can patch in Ubuntu(only in for Ubuntu) for fallback inherits. Or we could pull adwaita-icon-theme-full as dependency

>Does anybody know how themes are going to be with 17.10 when GNOME will be the standard desktop.

Everything will be the same. With gnome full gnome icon theme will be installed by default. So we won't be needed distro specific patch. For shell, I plan on porting gnome-shell theme.

**Comment by Foggalong** [comment]
@khurshid-alam I'd sooner not pull a big theme like that as a dependency. As inherits is fine, but I don't think we should force user to fallback to something they don't want to
