### ISSUE TITLE
Icon Request - Layout Editor 3D

### ISSUE THREAD

**Issue by leoheck** [numixproject/numix-icon-theme#1180]
We need a new icon for layout editor. It should be ``layout3d`` the previous was ``layout``

I created a sample here from the icon we already have, you can pick from here:
https://www.dropbox.com/s/2xhr8yhl8cdh8pz/layout3d.svg?dl=0

Original Icon
![screenshot from 2017-01-16 09-50-35](https://cloud.githubusercontent.com/assets/1277920/21981988/4aea2e0c-dbd1-11e6-9e6a-e90ffc29de91.png)

New icon
![layout3d svg](https://cloud.githubusercontent.com/assets/1277920/21981957/1e07cdb8-dbd1-11e6-964e-313ea768bf8b.png)

**Comment by palob** [comment]
Is this discernible at smaller sizes?

**Comment by leoheck** [comment]
Which smaller sizes? The default icon size looks good for me and it is better than the default.

**Comment by palob** [comment]
Scales down. Right now our theme only comes in one size (48px) which needs to look good scales down as well - as far as it is possible.

**Comment by leoheck** [comment]
Ok, but which smaller sizes? I am almost right that none of the icons will be recognizable at 10px. What is the minimum size you are talking about? 16px, 24px? However, the icon I shared is already the best considering that the original does not fit the theme. But, for sure, It can be improved.

**Comment by palob** [comment]
16px, I'll take at a look :)

**Comment by leoheck** [comment]
@palob Can I make a pull request for this icon?

**Comment by palob** [comment]
I've had a look (sorry for not doing it later) and it's not that grat at smaller sizes. Do you have any other idea for a metaphor of "3D"?

By the way, can you please transfer this to https://github.com/numixproject/numix-core lest I forget it again? :)

**Comment by Foggalong** [comment]
Only just realised this was in the wrong repo :P
