### ISSUE TITLE
Icons for webservices

### ISSUE THREAD

**Issue by leoheck** [numixproject/numix-icon-theme#1182]
Anyone know if there are icons for Webservices? I am relating this issue https://github.com/albertlauncher/albert/issues/341

Some initial icons are:
- [ ] Google
- [ ] Youtube
- [ ] Amazon
- [ ] Ebay
- [ ] Github

**Comment by hlechner** [comment]
Yes, Numix does, those icons are provided on **Numix-Circle** and **Numix-Square**.

By aware that Numix-Square at the moment is not complete as Numix-Circle is.

Here examples:
![image](https://cloud.githubusercontent.com/assets/11244067/22252681/26cdf3e4-e236-11e6-869e-406c1f06f5bf.png)
![image](https://cloud.githubusercontent.com/assets/11244067/22252854/ae2b728a-e236-11e6-810a-2adf5c7f1316.png)


- web-google
- web-youtube
- web-amazon
- (I didn't find ebay, maybe there is no icon for this one)
- github

--

about the issue that you mention on albertlauncher maybe a good option is to provide a call for the icons named **web-*nameserver***

**Comment by palob** [comment]
The icons @leoheck is referring to aren't suppose to be app icons. We've got some of them in Numix base.

**Comment by leoheck** [comment]
Ok @palob, can you show me an example which icons we are talking about?

**Comment by palob** [comment]
The icons I've had in mind are inside ``Numix/<size>/apps``.

**Comment by bil-elmoussaoui** [comment]
Google Icon is : web-google?
Youtube Icon is : youtube
Amazon Icon is : amazon-store
Ebay Icon is : chrome-bnadbgmffcofipfljniafanjcafjlbom-Default
Github Icon is : github
Are those icons needed on Numix base or just in Circle/Square,?

**Comment by wa4557** [comment]
we do have a google icon. The others shouldn't be hard to make since most of them exist in circle. @leoheck Can you tell where they are shown?

**Comment by leoheck** [comment]
sure @wa4557, https://github.com/numixproject/numix-icon-theme/issues/1182#issue-202791338. Look the link for albert launcher issue.

**Comment by bil-elmoussaoui** [comment]
This can be closed as upstream didn't fix anything. So they're not needed at least at the moment for the base theme.
