### ISSUE TITLE
Missing system-xxxxxx icons

### ISSUE THREAD

**Issue by luis-pereira** [numixproject/numix-icon-theme#1184]
[LXQt](http://lxqt.org/) users are requesting:

- [ ] system-suspend-hibernate
- [ ] system-suspend

Examlple:
![screen-2017-02-03-16-04-50](https://cloud.githubusercontent.com/assets/62877/22601571/68ddf992-ea37-11e6-83df-ff867545c4a0.png)

Keep up the good work.

**Comment by palob** [comment]
Are you sure the icon names are correct? The icons shown are Numix ones. But that's probably Qt again picking up an icon just named ``system``.

**Comment by luis-pereira** [comment]
@palob That's it. As the icons doesn't exist the icon engine picks `system` as a fallback.

**Comment by luis-pereira** [comment]
@palob Sorry, What's not a good choice ?
I'm not sure I understood your comment.

Numix already has:
- `system-reboot`
- `system-shutdown`
- `system-log-out`
- `system-lock-screen`

**Comment by wa4557** [comment]
@palob Why do yyou think the already existing hibernate and suspend icons are not a good choice? I'd argue they fit pretty well

**Comment by palob** [comment]
I was talking about the Qt fallback mechanism when mentioning bad choice :) Sorry for the confusion.

**Comment by luis-pereira** [comment]
@palob It may be a bad choice. But it's a by the book implementation of the standard.


From the[ icon naming specification standard](https://standards.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html
):

> The dash “-” character is used to separate levels of specificity in icon
>  names, for all contexts other than MimeTypes. For instance, we use
>  "input-mouse” as the generic item for all mouse devices, and we use
>  "input-mouse-usb” for a USB mouse device. However, if the more specific
>  item does not exist in the current theme, and does exist in a parent
>  theme, the generic icon from the current theme is preferred, in order
>  to keep consistent style.

**Comment by palob** [comment]
@luis-pereira Didn't know that. However I cant understand the rationle. The result is an inconsistent style and icons in places they shouldn't be.

**Comment by luis-pereira** [comment]
@palob The standard argue with style consistency.
A point that they don't mention is performance. See this [comparison](https://github.com/lxde/libqtxdg/issues/128).

**Comment by palob** [comment]
Wow, didn't expect that much of a slow-down for such an unspectacular task.

**Comment by palinek** [comment]
Just a note: the requested icons exist in the numix circle (light) theme

**Comment by palob** [comment]
@palinek Oh, they are indeed. Which is a problem. I wonder if they actually belong in there.
