### ISSUE TITLE
deadbeef: noartwork.png icon

### ISSUE THREAD

**Issue by sljunkie** [numixproject/numix-icon-theme#1186]
Deadbeef provides an icon when there's no album art available:

`/usr/share/deadbeef/pixmaps/noartwork.png`

![screenshot from 2017-02-17 17-43-59](https://cloud.githubusercontent.com/assets/7532854/23080916/cd525aa0-f539-11e6-8d44-9983d0e3a6a9.png)

**Comment by palob** [comment]
I think deadbeef provides this icon, it's not from Adwaita.

**Comment by sljunkie** [comment]
@palob you're right

it's `/usr/share/deadbeef/pixmaps/noartwork.png`

I'll change the description

**Comment by palob** [comment]
Thanks. Now the question is whether it is themeable or hardcoded.

**Comment by Foggalong** [comment]
@palob I think hardcoded if it's located in the deadbeef directory :/

**Comment by bil-elmoussaoui** [comment]
@Foggalong yeah it's :) sadly we can't do anything about it
