### ISSUE TITLE
Static Workspace Icon

### ISSUE THREAD

**Issue by platonish** [numixproject/numix-icon-theme#1187]
I have setup 4 workspaces on Ubuntu 16.10. The 'Workspace Switcher' icon in the Launcher doesn't update to show what workspace I'm currently on. The stock Ubuntu icon would show me what workspace I'm currently on. 

Numix icon: 
![screenshot from 2017-02-27 16-35-35](https://cloud.githubusercontent.com/assets/24620401/23359148/e1c34228-fd0a-11e6-9ba7-b43f89bb0693.png)

**Comment by palob** [comment]
Actually it should switch. Can you please reopen this issue here https://github.com/numixproject/numix-core and find out the orinial icons' names?
