### ISSUE TITLE
Files with .md extension have larger icons?

### ISSUE THREAD

**Issue by szekeres2016** [numixproject/numix-icon-theme#1188]
Good day, I just noticed this strange bug, I'm not sure if it's Nemo or the base Numix icon theme the cause of it, but I only just noticed this. So far only files with .mb extension seems to render relatively larger than the other icons.
![kepernyokep 2017-03-01 17-41-02](https://cloud.githubusercontent.com/assets/20751590/23470480/cca5988a-fea6-11e6-8bc5-3f61324a980e.png)

**Comment by bil-elmoussaoui** [comment]
Can you try with Nautilus and see if you can reproduce this ?

**Comment by szekeres2016** [comment]
Nautilus seems to be affected as well:
![kepernyokep 2017-03-01 17-50-28](https://cloud.githubusercontent.com/assets/20751590/23470841/cea53e82-fea7-11e6-84d8-65729355f966.png)

**Comment by palob** [comment]
There is some text-in-icon preview option for Nemo. Is it turned off?

**Comment by szekeres2016** [comment]
I couldn't find anything like that, will check again in dconf editor as well once I get home. I have Ubuntu Unity on my laptop and it seems to be fine there. I also checked other icon themes in mint but they work fine, only Numix Circle/Square and base Icon theme seems to render these icons larger for some reason.

**Comment by palob** [comment]
Can you check what's the actual recognised mimetype of the file?

**Comment by szekeres2016** [comment]
If by that you mean this: "file --mime-type -b README.md" it gives an output of "text/plain"

**Comment by palob** [comment]
You can simply see it in the file properties from the right click context menu as well :)

So it isn't ``text/markdown``? What's your distro and your version of ``shared-mime-info``?

**Comment by szekeres2016** [comment]
Ah okay :) (I was afraid it is something more complicated), right-click properties say that those mb files that look large are indeed "text/markdown" the system default is RStudio to open them. The distro is Linux Mint 18.1 Serena Cinnamon 64-bit and shared-mime-info version is 1.5-2ubuntu0.1

**Comment by palob** [comment]
I don't know where it gets the icon from. For me ``text/markdown`` files look just the same as ``text/plain`` files whereas your screenshots - apart from the bigger size - show a different icon.

What happens when changing the icon size or in list view?

**Comment by szekeres2016** [comment]
If I pick a smaller icon size its still a bit bigger, but if I go larger it seems fine. Also in list view there seems to be no error, while in compressed view it again larger a bit.
![Uploading Képernyőkép – 2017-03-03 07-44-02.png…]()
![kepernyokep 2017-03-03 07-44-10](https://cloud.githubusercontent.com/assets/20751590/23541072/627efbb4-ffe5-11e6-96bc-b1afd9b2ceae.png)

**Comment by palob** [comment]
Well, Nemo somewhere has an option to show preview text inside icons - a feature only a few icon themes support and which is known to cause issues otherwise.

**Comment by palob** [comment]
I can now reproduce this with Nemo. Looks like a Nemo bug.

**Comment by wa4557** [comment]
Problem with the theme somehow, since the problem is not there for other themes. Will investigate that

**Comment by palob** [comment]
Ooh, missing symlinks. Good catch, @wa4557 :)
