### ISSUE TITLE
Big icons type files MHT, MHTML, MD.

### ISSUE THREAD

**Issue by Faust30000** [numixproject/numix-icon-theme#1189]
Numix circle theme. Linux Mint Cinnamon 18.1. 
With the average value of the icon size in the file manager, the icons of the MHT, MHTML, MD files are much larger than the rest.

**Comment by palob** [comment]
Please take a look at #1188.

Looks like this is a Linux Mint issue.
Can you please check whether there's someting like "text preview in icons" activated in Nemo's preferences?

**Comment by Faust30000** [comment]
The option "text preview in icons" is absent in Nemo.

**Comment by palob** [comment]
Can you please change to the Mint-X theme and see if there's text preview for e.g. plain text and PDF files?

**Comment by Faust30000** [comment]
Applied theme Mint Y. In the conventional text and PDF there is no preview.
