### ISSUE TITLE
GZDoom Icon

### ISSUE THREAD

**Issue by Rotzke** [numixproject/numix-icon-theme#1190]
Guys, I am using your finest icons for about two years and would be so damn extremely grateful if you could add a GZDoom icon. It's a DOOM engine emulator, so icon could be same for all similar apps like ZDoom, etc. A Doomguy helmet in a circle within Numix Circle Icons set - a real dream!

**Comment by palob** [comment]
Hi, please reopen your request here https://github.com/numixproject/numix-core and add the information asked for in the readme.
