### ISSUE TITLE
Terminix got a new name: Tilix

### ISSUE THREAD

**Issue by KSXGitHub** [numixproject/numix-icon-theme#1193]
A terminal app named [Terminix](https://github.com/gnunn1/terminix) was renamed to [Tilix](https://github.com/gnunn1/tilix)

Please copy/rename terminix icons

**Comment by bil-elmoussaoui** [comment]
Please check the if the issue was reported before reporting it... https://github.com/numixproject/numix-core/issues/3624
https://github.com/numixproject/numix-core/issues/3620

Already fixed on master
