### ISSUE TITLE
Not working file system icon - Fedora

### ISSUE THREAD

**Issue by I-n-d-e-r** [numixproject/numix-icon-theme#1195]
File system icon not working. Tested on Fedora 25, 26, 27

![zrzut ekranu z 2017-04-02 16-53-02](https://cloud.githubusercontent.com/assets/18102267/24588253/175584c6-17c5-11e7-9ecb-f3b9168399c4.png)
![zrzut ekranu z 2017-04-02 16-49-55](https://cloud.githubusercontent.com/assets/18102267/24588254/175a2a44-17c5-11e7-9532-64ee37c84ab8.png)

**Comment by aengelke** [comment]
Its probably because the Fedora RPMs are outdated...

```
$ rpm -qa numix-icon-theme*
numix-icon-theme-0.1.0-12.git101307f.fc25.noarch
numix-icon-theme-circle-0.1.0-11.gitc3aefdb.fc25.noarch
```

**Comment by palob** [comment]
Duplicate, please cf. https://github.com/numixproject/numix-core/issues/3623 for assistance.
