### ISSUE TITLE
Request: Postman icon

### ISSUE THREAD

**Issue by jonasknobloch** [numixproject/numix-icon-theme#1196]
https://www.getpostman.com/
https://github.com/postmanlabs/

"A powerful GUI platform to make your API development faster & easier, from building API requests through testing, documentation and sharing."

postmanlabs GitHub avatar: https://avatars1.githubusercontent.com/u/10251060

**Comment by palob** [comment]
Hi, can you please reopen the issue here https://github.com/numixproject/numix-core?
