### ISSUE TITLE
Show Applications button on Gnome Dash

### ISSUE THREAD

**Issue by Sadi58** [numixproject/numix-icon-theme#1203]
I've just made an early transition from Unity to **Gnome DE** with the **17.04** upgrade (switching to **Ubuntu Gnome**), and use **Numix Circle Light** icon theme with it.
However the only odd icon on my **Dash** (equivalent of Unity Launcher) is the **Show Applications button**, which is dark (therefore almost invisible).
It seems icons `/user/share/icons/Numix/scalable/actions/view-grid-symbolic.svg` and `/user/share/icons/Numix-Light/scalable/actions/view-grid-symbolic.svg` should swap places.

**Comment by palob** [comment]
What's your Shell theme?

**Comment by bil-elmoussaoui** [comment]
As @palob mentioned, the shell theme can overwrite the Show applications button symbolic icon. So, if you use another theme, that does not provide one by default; The Numix one will be used instead

**Comment by Sadi58** [comment]
I didn't select any specific Shell theme, in fact I've even disabled "User Themes" via the extension, so I guess this means the default theme is used for Shell, which I like most.

In fact, after reporting this I've realized that there are a couple of other icon files related:
**view-app-grid-symbolic.svg
view-compact-symbolic.svg**
And it was actually one of these (copied from Numix to Numix-Light) that made it possible for me to see a light icon there.

My conclusion is that some other icon theme that does not have those files keeps the default one, but Numix changes it because it thas these files, but **the other way round** - as far as I can see...

**Comment by palob** [comment]
Closing because this isn't themed by the icon theme anymore. (Feel free to reopen if it persist with modern GNOME Shell).
