### ISSUE TITLE
Issues with system-xxxx icons

### ISSUE THREAD

**Issue by frisbee00** [numixproject/numix-icon-theme#1205]
The following icons are in **Numix-Circle** too.

- `system-hibernate`
- `system-lock-screen`
- `system-restart`
- `system-search`
- `system-suspend`

while in **Numix** :
- `system-reboot` and `system-lock-screen` doesn't fit in with the rest (those in **Numix-Circle** would fit in). Shouldn't `system-reboot` be sym-linked to `system-restart`?
- The sym-link `xfsm-hibernate` (from #1199) doesn't seem to be added since there is an icon file of the same name in all the folders (again is an icon that doesn't fit in).

The result is a mixed bag of icons in XFCE log out screen.

![screenshot_2017-04-25_01-29-18](https://cloud.githubusercontent.com/assets/6317854/25358951/ed33dc9e-2960-11e7-85ea-5e88fde56c29.png)

The top row icons are from **Numix** while two in the bottom row are from **Numix-Circle**

**Comment by bil-elmoussaoui** [comment]
This issue is due to this one https://github.com/numixproject/numix-core/issues/3681. Can you please close both of the issues you've reported recently?

**Comment by frisbee00** [comment]
There are some icons mentioned above which are missing there; just in case that went unnoticed.
Closing the issue.

**Comment by palob** [comment]
I think the two Circle icons (lower 2) are out of place. Other than that there's a design inconsistency which sets apart the 3 Numix base icons.
