### ISSUE TITLE
ZDoom and GZDoom

### ISSUE THREAD

**Issue by sljunkie** [numixproject/numix-icon-theme#1208]
Popular Doom source code ports.

https://zdoom.org

`Icon=zdoom`

https://gzdoom.drdteam.org/index.php

`Icon=gzdoom`

A symlink to doomseeker.svg would suffice.

**Comment by wa4557** [comment]
Wrong repo. This repo is for non app icons. Please report that [here](https://github.com/numixproject/numix-core)
