### ISSUE TITLE
Haguichi indication icon request

### ISSUE THREAD

**Issue by leoheck** [numixproject/numix-icon-theme#1211]
Also commented some time ago, here https://github.com/numixproject/numix-icon-theme/issues/8#issuecomment-28295273 and here https://github.com/numixproject/numix-core/issues/41#issuecomment-31522164

**Comment by bil-elmoussaoui** [comment]
What's the indicator icon name?

**Comment by leoheck** [comment]
I don't know and don't know how to find it. But googleing it I found this repository:
https://github.com/mank319/elementaryPlus/tree/master/elementaryPlus/status/24

[haguichi-connected.svg](https://github.com/mank319/elementaryPlus/blob/master/elementaryPlus/status/24/haguichi-connected.svg)
[haguichi-connecting-1.svg](https://github.com/mank319/elementaryPlus/blob/master/elementaryPlus/status/24/haguichi-connecting-1.svg)
[haguichi-connecting-2.svg](https://github.com/mank319/elementaryPlus/blob/master/elementaryPlus/status/24/haguichi-connecting-2.svg)
[haguichi-connecting-3.svg](https://github.com/mank319/elementaryPlus/blob/master/elementaryPlus/status/24/haguichi-connecting-3.svg)
[haguichi-disconnected.svg](https://github.com/mank319/elementaryPlus/blob/master/elementaryPlus/status/24/haguichi-disconnected.svg)

And they look like to the new hamachi icon:
![icon-history](https://cloud.githubusercontent.com/assets/1277920/25602059/1403efa6-2ec7-11e7-8241-29acf952d3cf.png)

**Comment by leoheck** [comment]
Confirmed, it worked inside 22 folder.

**Comment by leoheck** [comment]
PR #1213

**Comment by bil-elmoussaoui** [comment]
@Foggalong This was fixed in https://github.com/numixproject/numix-icon-theme/pull/1213
