### ISSUE TITLE
Failed to synchronize cache for repo 'numix-numix', disabling

### ISSUE THREAD

**Issue by fmenaa** [numixproject/numix-icon-theme#1214]
After enable the repository with the comand "sudo dnf copr enable numix/numix" in fedora when update the system you obtain the message Failed to synchronize cache for repo 'numix-numix', disabling.

**Comment by rgagne** [comment]
also seeing this - Fedora 25

**Comment by phongca22** [comment]
Me too - Fedora 25

**Comment by Foggalong** [comment]
I'll need someone who's on top of the packaging situation to confirm, but I believe we've dropped the copr now because we're in the official Fedora reops

**Comment by bil-elmoussaoui** [comment]
@Foggalong  Yep, can be found here https://admin.fedoraproject.org/pkgdb/package/rpms/numix-icon-theme/

**Comment by Foggalong** [comment]
Yeah, as mentioned above the Copr repo is no longer officially supported and we now just have the official Fedora package
