### ISSUE TITLE
Panel icons for Exaile Music Player

### ISSUE THREAD

**Issue by malysps** [numixproject/numix-icon-theme#1222]
| Application name | Icon name | Original icon |
| --- | :-- | :-- |
| Exaile| `exaile-play` | ![exaile-play](https://cloud.githubusercontent.com/assets/16068365/26477142/c918f9f4-41c3-11e7-8300-c9821ea6686a.png) |
| Exaile| `exaile-pause` | ![exaile-pause](https://cloud.githubusercontent.com/assets/16068365/26477169/0b40eb98-41c4-11e7-9f00-113c0ae1f139.png) |

Hello. I'm using Exaile 3.4.0 and Xfce 4.10. These icons are visible on my panel in the Notification Area when music is playing or is paused. I know that these icons are changing properly in Faenza set for example. I think they should be located in 'status' folder (16, 22, 24, 32 and maybe more?). I suggest that icons to be monochromatic to match current Numix panel icons style.

Thanks!

Website: http://www.exaile.org

**Comment by Foggalong** [comment]
See the readme for more information on where you should be reporting app icons.

**Comment by wa4557** [comment]
@Foggalong why closing this? This are not app icons

**Comment by Foggalong** [comment]
I'm an idiot. Sorry @malysps

**Comment by malysps** [comment]
No problem :) For a moment I thought that there's something wrong with me, because I did open an issue there before (https://github.com/numixproject/numix-core/issues/3731) by my mistake and I was directed here.
