### ISSUE TITLE
"Clipman.svg" can be confused for a battery-status indicator

### ISSUE THREAD

**Issue by O-Gopal** [numixproject/numix-icon-theme#1225]
Suggestion: Tilting the clipboard icon by, say, 10% might help.

**Comment by palob** [comment]
I don't think it looks too much like a battery but I see what you mean. We'll need a different approach to a redesign than tilting because this causes a blaurry icon.

On another note: all ``clipman.svg`` files need a redesign anyway. All are blurry.
