### ISSUE TITLE
Old Numix Icon Pack (year 2014)

### ISSUE THREAD

**Issue by azispratama92** [numixproject/numix-icon-theme#1226]
Where do i find old Numix Icon Pack, like this one ? i want to compile it for and under Ubuntu Mate DE: 

![numix-icons-1](https://user-images.githubusercontent.com/17444955/26908702-93d9d8a4-4c26-11e7-91b0-f625fe172690.jpg)

Many thanks for the developer ^ ^

**Comment by palob** [comment]
There is no need to use an outdated version. You can change the folder style by means of https://github.com/numixproject/numix-folders.

**Comment by azispratama92** [comment]
Awesome =) , thanks a lot!!
