### ISSUE TITLE
Tray icon request: Ring

### ISSUE THREAD

**Issue by matteosecli** [numixproject/numix-icon-theme#1227]
Hello, could you please add a monochrome icon for [Ring](https://ring.cx/)? I see it's already supported by Numix Circle, but the same icon also shows up in the tray and doesn't fit all the others:
![schermata del 2017-06-11 14-29-46](https://user-images.githubusercontent.com/4618521/27011044-4af3f7c0-4eb3-11e7-9746-32437178fa6e.png)
I've also opened an issue at https://github.com/bil-elmoussaoui/Hardcode-Tray/issues/376
Thank you! :smile:

**Comment by palob** [comment]
If it uses the app icon in the tray you should report it upstream and ask for a dedicated tray icon (name).

**Comment by matteosecli** [comment]
Thank you, I will report to them and post here any updates! :smile:

**Comment by matteosecli** [comment]
You can follow the upstream bug here: https://tuleap.ring.cx/plugins/tracker/?aid=1631.

**Comment by bil-elmoussaoui** [comment]
This can be closed as an upstream issue.

**Comment by Foggalong** [comment]
@bil-elmoussaoui No chance of it being fixed by hardcode-tray?

**Comment by bil-elmoussaoui** [comment]
The tray icon is hardcoded on a qrc file see my comment here https://github.com/bil-elmoussaoui/Hardcode-Tray/issues/376#issuecomment-307626953

Which means it's on the binary. And there's no easy way to do that without breaking the app :( As it's open source, we might get a patch for it someday :)

**Comment by Foggalong** [comment]
Ah, fair enough :(
