### ISSUE TITLE
Linux Mint + Caja: Triple click bug

### ISSUE THREAD

**Issue by ArtemBernatskyy** [numixproject/numix-icon-theme#1229]
Hello, i am on Linux Mint Mate 18 x64. (file manager is Caja)
I've just installed numix icons and i need to triple click on folder to open it. It just eats first click.

**Comment by palob** [comment]
Are you sure that's the icon theme's fault?

**Comment by ArtemBernatskyy** [comment]
@palob yep, i've changed back and it disappeared. It is very annoying bug (

**Comment by ArtemBernatskyy** [comment]
@palob i've installed via `sudo apt-get install numix-gtk-theme numix-icon-theme-circle`

**Comment by palob** [comment]
Any Linux Mint users out there?

**Comment by ArtemBernatskyy** [comment]
@palob yep, with caja

**Comment by ocuadrosl** [comment]
Hello, just confirming the bug. I have installed Faenza icon theme and I need three clicks to open folders.

Oscar

**Comment by bil-elmoussaoui** [comment]
The Gtk icon themes doesn't have any possible way to modify anything about any widgets or any configurations. This must be either a gtk theme issue or a caja one.

**Comment by Hacksaurus** [comment]
Hey, I just noticed this issue too on Thunar, but it only applies to my touchpad.
But I don't think this is caused by Numix... I think it would be nice if you could upstream this to Caja or Thunar

**Comment by Foggalong** [comment]
Yeah, this definitely odesn't sound like an icon theme problem. If it persists I'd suggest reporting it to GTK themes or upstream to Caja
