### ISSUE TITLE
update kdenlive icon!

### ISSUE THREAD

**Issue by ramzydoni** [numixproject/numix-icon-theme#1232]
The program icon has been changed for a long time and has been changed in the official website i hope to update in "numix icon" !

https://kdenlive.org/wp-content/uploads/2016/06/kdenlive-logo-hori.png

http://i.imgur.com/G9nrddT.png

thank's

**Comment by Foggalong** [comment]
Please relate issues relating to app icons [here](https://github.com/numixproject/numix-core)

**Comment by bil-elmoussaoui** [comment]
+ It was already reported https://github.com/numixproject/numix-core/issues/3415
