### ISSUE TITLE
microphone mute/un-mute icons

### ISSUE THREAD

**Issue by pgera** [numixproject/numix-icon-theme#1233]
The mic mute and un-mute icons show some sort of a bell in numix. Default icons get it right, and show the actual mic.

Numix:
![screenshot from 2017-07-26 11-45-59](https://user-images.githubusercontent.com/5542855/28630441-43c503aa-71f8-11e7-967f-3c3cf55903ab.png)

Ubuntu mono dark:
![screenshot from 2017-07-26 11-46-42](https://user-images.githubusercontent.com/5542855/28630457-49ca6d9e-71f8-11e7-9a08-0b82a6f54825.png)

**Comment by Foggalong** [comment]
My guess is that's us not covering a mute specific notification icon, but if that's not available it has a fallback to a generic notification icons which we do provide. Do you know what the icon names are?

**Comment by pgera** [comment]
I think it's the microphone-sensitivity-* family of icons.

**Comment by bil-elmoussaoui** [comment]
@pgera I don't think so, the icon must be `notification-*`

**Comment by pgera** [comment]
I see the notification-microphone-sensitivity-* icons in the 48/notifications Numix folder. It looks like those are the correct icons, but they aren't used.

**Comment by Foggalong** [comment]
@palob I think `notifications/` is a 48px specific context

**Comment by bil-elmoussaoui** [comment]
@Foggalong @palob There isn't any notifications context on FreeDesktop standards https://standards.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html
It must be something invented by the Unity guys :p as I couldn't find anything about that on Adwaita icon theme

**Comment by Foggalong** [comment]
@bil-elmoussaoui Yeah it's probably linked to whatever Unity 7 uses for notifications. It's still supported by Canonical until April 2021 though so we should probably still try to fix it, even if GNOME is where they're going from now

**Comment by wa4557** [comment]
@pgera I can't check because I have no microphone at hand I can mute / unmute. But it has to be some icon from here `/usr/share/notify-osd/icons/Humanity/scalable/status` can you check which one?

**Comment by pgera** [comment]
@wa4557, the icons are notification-microphone-sensitivity-* in that directory. There's mute and unmute, but there are also a couple of others for high and low sensitivity. I don't know how to trigger the high and low ones with the keyboard.

**Comment by wa4557** [comment]
Can you try renaming that icons and  see if it changes something?

**Comment by pgera** [comment]
yes, changing them changes the icon. If I rename them in humanity, it uses the gnome ones.

**Comment by wa4557** [comment]
Hmm, weird since we do have this icon in Numix. Can you try `notify-send test -i "notification-microphone-sensitivity-muted"` in a terminal, and see what icon is shown?

**Comment by pgera** [comment]
That command shows the correct icon. The microphone button doesn't trigger that though.

**Comment by wa4557** [comment]
Even weirder. I will have to look into the source code of the microphone thing. They might use hardcoded paths...

**Comment by wa4557** [comment]
@pgera Can you try removing (or renaming) all the icons `notification*` icons in `Numix/scalable/status/`? It can't be hardcoded because it shows a Numix icon in your first screenshot. 

I can't test it, because I have no microphone on/off button....

**Comment by bil-elmoussaoui** [comment]
@Foggalong This  can be closed

**Comment by pgera** [comment]
Thanks everyone. Confirmed that it's fixed.
