### ISSUE TITLE
Battery icon bug in GNOME/Xfce4

### ISSUE THREAD

**Issue by llorephie** [numixproject/numix-icon-theme#1234]
Battery icon displays not an actual charge state, only 100, 65, 15, 5% (as it looks).

**Comment by Foggalong** [comment]
Huh, I didn't realise it was possible to have it more dynamic than that? Have GNOME recently updated their battery indicator to include a lot more icons?

**Comment by bil-elmoussaoui** [comment]
@Foggalong Nop, it was and still the same thing :( we can't really do anything about it...

**Comment by Foggalong** [comment]
@llorephie Could you elaborate further on what you're talking about?

**Comment by Foggalong** [comment]
Closing this due to lack of information from OP. If anyone has that information feel free to post it and we'll reopen
