### ISSUE TITLE
Bluetooth icon is misaligned and missized

### ISSUE THREAD

**Issue by Hacksaurus** [numixproject/numix-icon-theme#1235]
Hello!
I noticed that whenever I have blueman-applet on, the system tray icon is a bit off shown here:
![screenshot_2017-08-15_08-14-31](https://user-images.githubusercontent.com/24832107/29392672-33af9440-82b4-11e7-89b3-ffa3c7917ab5.png)
![screenshot_2017-08-15_08-14-00](https://user-images.githubusercontent.com/24832107/29392671-33af7230-82b4-11e7-97ba-9ffe77e46c5c.png)

I was wondering if there is any way that I can get them fixed?
(BTW I have already posted an issue for blueman and they said to come here!)

**Comment by palob** [comment]
What do you mean by "off"? The changed horizontal position? We have no leverage on that.

What's your DE? Do you use non-integer scaling? Some of your icons look blurry.

**Comment by Hacksaurus** [comment]
I am currently using i3, and what I mean by "off" is that you can kinda see on the right side of the bluetooth icon, you can see that there is a gap. I hope this clears some questions. And I feel like this is caused by maybe the size of the icon or whatever...

**Comment by palob** [comment]
What would bother me more is the blurry icons. Given that those aren't blurry in the oiginal files we might be talking about a i3 issue here. The bluetooth icon doesn't look to be off-centre in the original file (``panel/bluetooth-active`` and ``panel/bluetooth-disabled``).

![bluetooth](https://user-images.githubusercontent.com/7050624/29447064-396fad06-83f0-11e7-91b4-46da3455011d.png)

There is however an issue with pixel grid alignment and canvas size.

**Comment by cschramm** [comment]
I've noticed that all(?) except the bluetooth icons in https://github.com/numixproject/numix-icon-theme/tree/master/Numix/22/panel are rectangular. Looks to me like the panel just shows them left-aligned in a rectangular box if they are not.

**Comment by Hacksaurus** [comment]
At the current state of this issue... I'm not sure entirely on what the problem is... Is it i3? or the icon? I have talked to the i3 devs, and they redirected me here... So could someone please explain the current situation of this bug?
Thank you.

**Comment by palob** [comment]
There is something wrong with the icons for sure. However nobody has reported what you see before.

**Comment by Hacksaurus** [comment]
So is the misalignment of the icon to pixels is causing the issue?

**Comment by palob** [comment]
I don't know exactly, need to do some testing. I don't use blueman nor i3 but the icons needs fixing anyway.

**Comment by palob** [comment]
@Foggalong @wa4557 @dirtydancing Is there any particular reason this icon is (nearly) 13px wide?

**Comment by Foggalong** [comment]
@palob Not a clue unfortunately. Might be a case of changing it to a square icons and then waiting to see if anything goes wrong :confused:

**Comment by Hacksaurus** [comment]
Its been a long time since this issue has been touched...
I don't know if I can really help, but do you think by changing the icon to square would help?

**Comment by wa4557** [comment]
@palob No reason, historic probably. I'm going to change them now

**Comment by Hacksaurus** [comment]
Thank you @wa4557 ! We can finally have nice bluetooth icons!

**Comment by palob** [comment]
@wa4557 Thanks for giving this a shot. I've done a few drafts but got distracted.
I found that ``bluetooth-paired`` is in dire need of a redesign and came up with this (inspired from how it looks on Android). 
![bluetooth-test](https://user-images.githubusercontent.com/7050624/32198863-5438ee7c-bdca-11e7-98bc-b98d0692dc0b.png)

Basically everything you find when searching for *bluetooth* in the Numix root isn't 100% up to scratch.

**Comment by Hacksaurus** [comment]
@palob I think this is a nice solution in making the icon square! And also there needs to be an icon to where bluetooth will be signaled "off"

**Comment by wa4557** [comment]
@palob I like the paired design. Will use that :+1:

**Comment by Hacksaurus** [comment]
I know you guys have fixed the issue from this merge request https://github.com/numixproject/numix-icon-theme/pull/1251 But I still have not seen any changes, I am using Arch Linux and I have installed the `numix-circle-icon-theme-git` package from AUR, if there is a better package to install from please tell me.

**Comment by Hacksaurus** [comment]
@wa4557 @palob Ping?

**Comment by palob** [comment]
I think so. Can you try reinstalling? How do you update your AUR packages?

**Comment by Hacksaurus** [comment]
I update simply by doing 'pacaur -Syu', but I'll try reinstalling...

**Comment by Hacksaurus** [comment]
Ok reviewing the files I realised that blueman has no distinction from paired and active, so the actual new paired icon that I was expecting will not be there...
