### ISSUE TITLE
Questionable design for indicator-stickynotes-mono

### ISSUE THREAD

**Issue by palob** [numixproject/numix-icon-theme#1237]
Looks like this.

![stickynotes](https://user-images.githubusercontent.com/7050624/29447818-e9e717b6-83f3-11e7-9204-f544b2e5b312.png)

I suppose it is intentional but I think we should streamline it.

**Comment by Foggalong** [comment]
Not entirely sure what the little wings are for so they can probably be lost yeah :+1:
