### ISSUE TITLE
Icon=org.gnome.Nautilus

### ISSUE THREAD

**Issue by Koogoo** [numixproject/numix-icon-theme#1241]
Gnome does not have a default icon

Icon=org.gnome.Nautilus

**Comment by Foggalong** [comment]
This is an app icon which aren't covered by Numix, you need to report it in the [Core](https://github.com/numixproject/numix-core) repo so it can be covered by Circle and Square.

**Comment by palob** [comment]
@Koogoo We've already got this in core. You might be using an outdated version.

**Comment by Koogoo** [comment]
@palob 
sudo dnf copr enable numix/numix
sudo dnf install numix-icon-theme

Fedora26 actually also expired in the source?

**Comment by Koogoo** [comment]
@Foggalong 
sorry

**Comment by Foggalong** [comment]
@Koogoo Yeah, you don't need to use the copr anymore. As the message suggests it's been deprecated since the Numix themes are now available in the official Fedora repos :)
