### ISSUE TITLE
Icon for Spotify is wrong color in numix-icon-theme-square

### ISSUE THREAD

**Issue by tangram** [numixproject/numix-icon-theme#1242]
Spotify's brand color ("Spotify Green") is #1ED760.

https://developer.spotify.com/design-resources/spotify-logo-color-guidelines.pdf

**Comment by Foggalong** [comment]
Please report any design changes to [Numix Core](https://github.com/numixproject/numix-core) where the app icons are actually kept

**Comment by tangram** [comment]
Sorry.
