### ISSUE TITLE
Laptop icon and extended KDE Connect status icons

### ISSUE THREAD

**Issue by andyholmes** [numixproject/numix-icon-theme#1247]
Could you please include a color "laptop" icon, to match "phone/smartphone", "tablet" and "computer"? 

Additionally, KDE Connect reports (uncommonly) a "desktop" device with `-connected`/`-disconnected`/`-trusted` variants. Is it possible to symlink `computer-symbolic` to `desktop-symbolic` and make variants for `desktop-connected`/`-disconnected`/`-trusted` that match those for tablet, smartphone and laptop? If this conflicts with current `desktop-*` icons, variants based on `computer-*` would be okay as they could be remapped in programs if necessary.

**Comment by wa4557** [comment]
@andyholmes I want to fix this issue, but I'm lost a bit. Which icons do you need?

**Comment by andyholmes** [comment]
@wa4557  Sorry, it's a bit confusing :) There's sort of two request here, but one is a question I guess.

1. For each icon of computer-symbolic, tablet-symbolic, smartphone-symbolic there is a matching full-color icon (not symbolic). For laptop-symbolic there is no full-color icon, though.
2. Related to those symbolic icons, there are variants specifically for KDE Connect such as smartphone-connected, smartphone-disconnected, smartphone-trusted.
    * It's possible to connect PC-to-PC with KDE Connect and KDE Connect calls these "desktop" (desktop-connected, desktop-disconnected, desktop-trusted).
    * There are no desktop-* icons for KDE Connect (in any theme) and they conflict with what "desktop" icons represent currently so I don't have a good suggestion for how to resolve that, but it would be nice :)

**Comment by wa4557** [comment]
@andyholmes Got it. Will fix it today or tomorrow :)

**Comment by andyholmes** [comment]
Cool, thank you :)
