### ISSUE TITLE
Gnome-Shell notification indicator icons looks ugly

### ISSUE THREAD

**Issue by brittyazel** [numixproject/numix-icon-theme#1248]
It used to be that the Gnome-Shell notification indicator was a monochrome solid white circle, indicating a notification. However, something changed recently and now the notification indicator is a full color icon that doesn't fit at all. Going back to Adwaita icon theme, the solid white circle comes back, so it makes me think that for a while numix was defaulting to the adwaita icon or something.

Is there a way to go back to default to adwaita, or perhaps coming up with a better, more monochrome, notification icon?

**Comment by palob** [comment]
Can you please show a screenshot of the icon in question?

**Comment by palob** [comment]
Now that I'm on 3.26 I might have reproduced it. It's the mail mimetype icon which is really weird and doesn't seem easy to fix.

**Comment by brittyazel** [comment]
Hey sorry I just saw this, I'm glad you were able to see the one I'm talking about. It definitely looks strange, and I don't remember it looking like this before.

**Comment by palob** [comment]
Numix:
![bildschirmfoto vom 2017-10-12 09-09-39](https://userimages.githubusercontent.com/7050624/31499648-af7e6ca8-af65-11e7-802c-7e6eb58c1694.png)
Adwaita:
![adwaita](https://user-images.githubusercontent.com/7050624/31499653-b248a084-af65-11e7-8f43-89037b9cc77c.png)

**Comment by palob** [comment]
This is the [relevant GNOME Shell commit](https://git.gnome.org/browse/gnome-shell/commit/?h=gnome-3-26&id=bddc2c0016878c8eb629d6d4b7c0f2f38353377a).

We haven't got ``message-indicator-symbolic.svg`` but an icon just called ``message.svg`` in ``mimetypes`` which seems to get picked up.

I think we can delete that anyway it doesn't sound like a proper mimetype.

**Comment by palob** [comment]
We could provide this icon as just this circle thing or say a bell icon. But this would take the theming option from the Shell theme.

**Comment by palob** [comment]
Removing ``message.svg`` from ``<size>/mimetypes`` reverts the icon to how it was before GNOME 3.26.
@bil-elmoussaoui @Foggalong @wa4557 @dirtydancing Do you think it's safe to go ahead with this?

**Comment by dirtydancing** [comment]
Regarding Ubuntu (I am currently running 16.04 LTS), it should be safe to remove `message.svg`.

Just to make sure: would providing this icon definitely take the theming option from the Shell theme, or is the Shell theme looked up before the icon theme, if both provide `message-indicator-symbolic.svg`?

**Comment by Foggalong** [comment]
The original PR when you added it was for #756 as part of a KDE fix for #580. Idk what the original icon looks like in Oxygen so it might be worth checking there also
