### ISSUE TITLE
Icon for XnView

### ISSUE THREAD

**Issue by AdLef2595** [numixproject/numix-icon-theme#1266]
A Numix-circle/Square icon for XnView is missing.
The icon line says"/opt/XnView/xnview.png" and the original icon is attached.
![xnview_icon](https://user-images.githubusercontent.com/33607200/32703327-9a052414-c7f4-11e7-9dec-e6688cc98f3b.jpg)

**Comment by bil-elmoussaoui** [comment]
Can you please follow the issue template?

**Comment by bil-elmoussaoui** [comment]
Plus it's an application icon so it should be reported here https://github.com/numixproject/numix-core instead

**Comment by palob** [comment]
We've already got an icon. Your installation hardcodes the icon path. Please read the relevant README section and feel free to come back if you've got questions.
