### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by jbicha** [numixproject/numix-icon-theme#1268]
It's been 6 months since your last release/tag. Maybe it's time to do another release then?

**Comment by Foggalong** [comment]
Aye, will do when #1265 is merged :+1:

**Comment by Foggalong** [comment]
[Done!](https://github.com/numixproject/numix-icon-theme/releases/tag/17-11-18)

**Comment by jbicha** [comment]
@Foggalong, Thanks.

I want to let you know that the release number I used for the Debian/Ubuntu package doesn't match your tagging scheme. First, a hyphen (-) is a special character in Debian pacakge numbers (it separates the upstream version from the Debian packaging version) so I had to replace or remove the hyphens. Then I used the 4-digit year instead of the 2-digit since it's a bit more clear and it matched the old version number I used before we convinced you to make releases.

So your tag was 17-11-18 but the Debian [version](https://tracker.debian.org/pkg/numix-icon-theme) is 0~20171118-1 (with the final -1 being the Debian revision and the initial 0~ being used to help avoid epochs until you decide on a reliable version numbering system.)

I suggests you consider switching to either a number like 17.11.18 or 20171118 next time.

**Comment by Foggalong** [comment]
@jbicha I wish someone had said this sooner. I've been using that format [for circle](https://github.com/numixproject/numix-icon-theme-circle/releases) for over a year now and no one has ever brought up that it caused packaging problems :confused:
