### ISSUE TITLE
Disconnection icon needed for gnome network manager on LAN disconnect

### ISSUE THREAD

**Issue by nathaneltitane** [numixproject/numix-icon-theme#127]
![screenshot from 2014-05-26 15 08 05](https://cloud.githubusercontent.com/assets/5674757/3095666/8b250604-e5ca-11e3-96e7-b7ce771997ad.png)

That ^, is what I sumbled on yesterday when making a shared wired connection to my other machine... it happened when disconnected :|

**Comment by wa4557** [comment]
This can be closed now :)

**Comment by Foggalong** [comment]
\O/
