### ISSUE TITLE
Zotero icon request

### ISSUE THREAD

**Issue by UbuntuRules** [numixproject/numix-icon-theme#1275]
Hello,

Please add the Zotero reference manager icon to the Numix Circle icon theme. Thank you.

Kind regards

**Comment by bil-elmoussaoui** [comment]
Already exists. Please use hardcode-fixer or replace the icon name to zotero.

**Comment by UbuntuRules** [comment]
I just ran the script and it's still the same. Also, I really don't know how to replace the icon name to Zotero.

**Comment by UbuntuRules** [comment]
I figured it out. For anyone who needs the solution, this is what I did...

Open terminal and enter: gedit admin:///usr/share/applications/zotero.desktop

Then comment out this line... 
# Icon=/opt/zotero/chrome/icons/default/default48.png

And below add this line...
Icon=/usr/share/icons/Numix-Circle/48/apps/zotero.svg

So the entire document should look like this when you're done...
[Desktop Entry]
Name=Zotero
Comment=Open-source reference manager (standalone version)
Exec=/opt/zotero/zotero
# Icon=/opt/zotero/chrome/icons/default/default48.png
Icon=/usr/share/icons/Numix-Circle/48/apps/zotero.svg
Type=Application
StartupNotify=true

**Comment by frisbee00** [comment]
As far as I know, just changing it to `zotero` should work, in which case you need not change the path again when you switch to a different icon theme. This worked before; not sure what is the case now.
```
[Desktop Entry]
Name=Zotero
Comment=Open-source reference manager (standalone version)
Exec=/opt/zotero/zotero
#Icon=/opt/zotero/chrome/icons/default/default48.png
Icon=zotero
Type=Application
StartupNotify=true
```

**Comment by UbuntuRules** [comment]
Thank you. That does, indeed, work. However, changing the icon theme to anything other than a Numix-related one causes the loss of that icon. No worries though.
