### ISSUE TITLE
Kdenlive Icon is Different in Gnome Launcher

### ISSUE THREAD

**Issue by UbuntuRules** [numixproject/numix-icon-theme#1276]
The Kdenlive app opens with the default Kdenlive icon in the Gnome launcher instead of the Numix Circle icon for Kdenlive that is actually shown in the applications overview.

**Comment by Foggalong** [comment]
This sounds like a problem with the app theme rather than the base theme, and potentially isn't a Numix issue but an issue with kdenlive. @bil-elmoussaoui?

**Comment by bil-elmoussaoui** [comment]
@Foggalong @UbuntuRules It must be a missing StartupWMClass in your desktop file. Can you please try to execute `xprop WM_CLASS` and click on a Kdenlive window. Paste the content here and also the content of the desktop file

**Comment by UbuntuRules** [comment]
I just did as you mentioned for the first part and this is the result:

WM_CLASS(STRING) = "kdenlive", "kdenlive"

How would I obtain the contents of the desktop file?

**Comment by bil-elmoussaoui** [comment]
It must be in /usr/share/applications open the kdenlive file with a text editor

**Comment by UbuntuRules** [comment]
Perfect. Here you go:

# KDE Config File
[Desktop Entry]
Name=Kdenlive
Name[bs]=Kdenlive
Name[ca]=Kdenlive
Name[ca@valencia]=Kdenlive
Name[cs]=Kdenlive
Name[da]=Kdenlive
Name[de]=Kdenlive
Name[el]=Kdenlive
Name[en_GB]=Kdenlive
Name[es]=Kdenlive
Name[et]=Kdenlive
Name[fi]=Kdenlive
Name[fr]=Kdenlive
Name[ga]=Kdenlive
Name[gl]=Kdenlive
Name[hu]=Kdenlive
Name[it]=Kdenlive
Name[ja]=Kdenlive
Name[km]=Kdenlive
Name[lt]=Kdenlive
Name[lv]=Kdenlive
Name[mr]=के-डि-एनलाइव्ह
Name[nb]=Kdenlive
Name[nds]=Kdenlive
Name[nl]=Kdenlive
Name[nn]=Kdenlive
Name[pl]=Kdenlive
Name[pt]=Kdenlive
Name[pt_BR]=Kdenlive
Name[ro]=Kdenlive
Name[ru]=Kdenlive
Name[sk]=Kdenlive
Name[sl]=Kdenlive
Name[sv]=Kdenlive
Name[tr]=Kdenlive
Name[ug]=Kdenlive
Name[uk]=Kdenlive
Name[x-test]=xxKdenlivexx
Name[zh_CN]=Kdenlive
Name[zh_TW]=Kdenlive
GenericName=Video Editor
GenericName[ar]=محرّر فيديوهات
GenericName[bs]=Video uređivač
GenericName[ca]=Editor de vídeo
GenericName[ca@valencia]=Editor de vídeo
GenericName[cs]=Editor videa
GenericName[da]=Videoredigering
GenericName[de]=Video-Editor
GenericName[el]=Επεξεργαστής βίντεο
GenericName[en_GB]=Video Editor
GenericName[es]=Editor de video
GenericName[et]=Videoredaktor
GenericName[fi]=Videomuokkain
GenericName[fr]=Éditeur vidéo
GenericName[ga]=Eagarthóir Físe
GenericName[gl]=Editor de vídeo
GenericName[hu]=Videoszerkesztő
GenericName[it]=Editor video
GenericName[ja]=ビデオエディタ
GenericName[km]=កម្មវិធី​កែសម្រួល​វីដេអូ
GenericName[lt]=Video redaktorius
GenericName[lv]=Video redaktors
GenericName[mr]=व्हिडीओ संपादक
GenericName[nb]=Videoredigeringsprogram
GenericName[nl]=Video-bewerker
GenericName[nn]=Videoredigering
GenericName[pl]=Edytor wideo
GenericName[pt]=Editor de Vídeo
GenericName[pt_BR]=Editor de Vídeo
GenericName[ro]=Redactor de imagini
GenericName[ru]=Видеоредактор
GenericName[sk]=Editor videa
GenericName[sl]=Urejevalnik videa
GenericName[sv]=Videoeditor
GenericName[tr]=Video Düzenleyici
GenericName[uk]=Відеоредактор
GenericName[x-test]=xxVideo Editorxx
GenericName[zh_CN]=视频编辑器
GenericName[zh_TW]=影像編輯器
Comment=Nonlinear video editor by KDE
Comment[ca]=Editor de vídeo no lineal, creat per la comunitat KDE
Comment[ca@valencia]=Editor de vídeo no lineal, creat per la comunitat KDE
Comment[cs]=Nelineární editor videa od KDE
Comment[de]=Nichtlinearer Video-Editor von KDE
Comment[en_GB]=Non-linear video editor by KDE
Comment[es]=Editor no lineal de video de KDE
Comment[fr]=Éditeur vidéo non linéaire par KDE
Comment[it]=Editor di video non lineare di KDE
Comment[nl]=Niet-lineaire video-bewerker door KDE
Comment[nn]=Program for ikkje-lineær videoredigering
Comment[pl]=Nieliniowy edytor wideo w ramach KDE
Comment[pt]=Editor de vídeo não-linear do KDE
Comment[sk]=Nelineárny editor videa pre KDE
Comment[sl]=Ne-linearni urejevalnik videa s strani KDE
Comment[sv]=Icke-linjär videoeditor av KDE
Comment[tr]=KDE için doğrusal olmayan video düzenleyici
Comment[uk]=Нелінійний редактор відео від KDE
Comment[x-test]=xxNonlinear video editor by KDExx
Comment[zh_CN]=KDE 推出的非线性视频编辑器
Type=Application
Exec=kdenlive %U
Icon=kdenlive
X-DocPath=kdenlive/index.html
X-DocPath[cs]=http://cs.wikibooks.org/wiki/Kdenlive
Terminal=false
MimeType=application/x-kdenlive;
Categories=Qt;KDE;AudioVideo;AudioVideoEditing;
Keywords=video;audio;firewire;video4linux;suite;editing;kde;mlt;
Keywords[ca]=edició;vídeo;àudio;mlt;kde;
Keywords[ca@valencia]=edició;vídeo;àudio;mlt;kde;
Keywords[cs]=úprava;video;zvuk;mlt;kde;
Keywords[da]=redigering;video;lyd;mlt;kde;
Keywords[de]=Editing;Bearbeitung;Schnitt;Videoschnitt;Video;Audio;MLT;
Keywords[en_GB]=editing;video;audio;mlt;kde;
Keywords[es]=edición;video;audio;mlt;kde;
Keywords[et]=redigeerimine;muutmine;video;audio;heli;mlt;kde;
Keywords[fi]=editing;video;audio;mlt;kde;editointi;ääni;
Keywords[fr]=montage;vidéo;audio;mlt;kde;
Keywords[gl]=editing;edición;video;vídeo;audio;son;mlt;kde;
Keywords[it]=editing;video;audio;mlt;kde;
Keywords[nl]=bewerken;video;audio;mlt;kde;
Keywords[nn]=redigering;video;lyd;mlt;kde;
Keywords[pl]=edytowanie;video;wideo;filmy;audio;dźwięk;mlt;kde;
Keywords[pt]=edição;vídeo;áudio;MLT;kde;
Keywords[pt_BR]=edição;vídeo;áudio;mlt;kde;
Keywords[sk]=editovanie;video;audio;mlt;kde;
Keywords[sl]=urejanje;video;zvok;mlt;kde;
Keywords[sv]=redigering;video;ljud;mlt;kde;
Keywords[tr]=editing;video;audio;mlt;kde;
Keywords[uk]=editing;video;audio;mlt;kde;редагування;відео;звук;аудіо;млт;кдє;
Keywords[x-test]=xxeditingxx;xxvideoxx;xxaudioxx;xxmltxx;xxkdexx;
Keywords[zh_CN]=editing;video;audio;mlt;kde;编辑;视频;音频;
Keywords[zh_TW]=editing;video;audio;mlt;kde;
X-DBUS-ServiceName=org.kde.kdenlive

**Comment by bil-elmoussaoui** [comment]
Can you tell me also the desktop file name?

**Comment by UbuntuRules** [comment]
Kdenlive

**Comment by bil-elmoussaoui** [comment]
Well, just use https://github.com/bil-elmoussaoui/StartupWMClassFixer it will fix it for you ;)

**Comment by UbuntuRules** [comment]
Wow, amazing! That worked! :)
