### ISSUE TITLE
Icon for USB Image Writer missing

### ISSUE THREAD

**Issue by orschiro** [numixproject/numix-icon-theme#1283]
Just noticed that there is no icon for the USB Image Writer. 

Can anyone confirm this?

With Numix:

![image](https://user-images.githubusercontent.com/170947/34510486-82cb257c-f054-11e7-856d-14a1d5ce7d12.png)

With the default Mint-X icon theme on Linux Mint 18.3:

![image](https://user-images.githubusercontent.com/170947/34510475-7af56d26-f054-11e7-8df7-8b4d11444499.png)

**Comment by bil-elmoussaoui** [comment]
The Numix theme is supposed to be used with the square or the circle icon theme for the applications icons.

**Comment by orschiro** [comment]
Thanks @bil-elmoussaoui.

It does show with the circle theme:

![image](https://user-images.githubusercontent.com/170947/34518092-0182e69c-f07e-11e7-924b-2bd16c976e75.png)

And now it seems to be working with the square one, too (assuming that the normal one is the square one):

![image](https://user-images.githubusercontent.com/170947/34518132-4acf9b2e-f07e-11e7-8d66-1a1b97ee0b82.png)

![image](https://user-images.githubusercontent.com/170947/34518141-5215ce62-f07e-11e7-95ca-1a7a018ae98f.png)

I guess I am going to close this as invalid. Sorry for the noise...
