### ISSUE TITLE
Missing Volume 0 Percent / Volume Off Icons in Xfce4-Volumed-Pulse

### ISSUE THREAD

**Issue by ragazenta** [numixproject/numix-icon-theme#1285]
After migrating from **xfce4-volumed** to **xfce4-volumed-pulse**, volume 0 percent (volume off) icons are missing.

**Xfce4-volumed-pulse** is a fork of unmaintained **xfce4-volumed** with some [improvements](https://simon.shimmerproject.org/2016/10/01/improved-media-key-handling-with-xfce4-volumed-pulse-0-2-2/):
- Support PulseAudio
- Support Microphone Mute key
- Support Symbolic Icons

After digging their source code, I found it needs `audio-volume-off` and/or `audio-volume-off-symbolic` icons. See [this](https://github.com/xfce-mirror/xfce4-volumed-pulse/blob/faec2e8a55f2f1191e0015e699aacffd27759b6c/src/xvd_notify.c#L80) and [this](https://github.com/xfce-mirror/xfce4-volumed-pulse/blob/faec2e8a55f2f1191e0015e699aacffd27759b6c/src/xvd_data_types.h#L51) and [this](https://github.com/xfce-mirror/xfce4-volumed-pulse/blob/faec2e8a55f2f1191e0015e699aacffd27759b6c/src/xvd_notify.c#L49).

User can choose icon style in `xfce4-settings-editor`, see [README](https://github.com/xfce-mirror/xfce4-volumed-pulse/blob/master/README):

> == Xfconf properties
> In the channel xfce4-volumed-pulse you can set the following properties:
>  * icon-style (int): 0: normal icon style (default), 1: symbolic icon style
> 

I've created these files as workaround:

| Directory | Name | Description |
| --- | --- | --- |
| `24/status` | `audio-volume-off.svg` | symbolic link to `audio-volume-low-zero.svg` |
| `scalable/status` | `audio-volume-off-symbolic.svg` | copy of `audio-volume-low-symbolic.svg` modified using Inkscape |

Screenshots (GIFs):

| Icon Style | Before | After |
| --- | --- | --- |
| normal |  ![use-default-icon-before](https://user-images.githubusercontent.com/3535194/35919924-fc06ca08-0c48-11e8-957a-742875cc2dff.gif)  |  ![use-default-icon-after](https://user-images.githubusercontent.com/3535194/35919980-1e33057e-0c49-11e8-89fc-fd33144936b3.gif)  |
| symbolic |  ![use-symbolic-icon-before](https://user-images.githubusercontent.com/3535194/35920031-4215ba0e-0c49-11e8-9ca5-ea388d001a25.gif)  |  ![use-symbolic-icon-after](https://user-images.githubusercontent.com/3535194/35920066-69d13046-0c49-11e8-9636-1bf5a5aa92b7.gif)  |

Versions

|   | Version |
| --- | --- |
| `xfce4-volumed-pulse` | 0.2.2 |
| `numix-icon-theme` | github clone master |

**Comment by wa4557** [comment]
Argh these notification icons are a pain. I will have a look
