### ISSUE TITLE
Missing Icon for Tutanota

### ISSUE THREAD

**Issue by DarkZeta** [numixproject/numix-icon-theme#1287]
There is no icon for Tutanota. 
The desktop entry is as follows...

`[Desktop Entry]
Type=Application
Version=1.0
Name=Tutanota
Comment=A truly secure email client
Path=/opt/tutanota-electron-git/
Exec=/usr/bin/tutanota
Icon=/opt/tutanota-electron-git/tutanota-linux-x64/resources/app/images/app.png
Terminal=false
Categories=Internet;Office;`

I've added one of the original icons as well. 
![icon-48-mdpi](https://user-images.githubusercontent.com/13984382/36071239-b95ab87e-0ed0-11e8-85ac-1fdf93b9c1ee.png)

**Comment by Foggalong** [comment]
Read the readme

**Comment by DarkZeta** [comment]
My bad. Wrong location. Thank you.
