### ISSUE TITLE
update QGIS icon

### ISSUE THREAD

**Issue by msevilla00** [numixproject/numix-icon-theme#1291]
### Update to new QGIS icon

- QGIS
- A Free and Open Source Geographic Information System 
- `qgis` and `qgis-icon`

**Original logo for reference:** [QGIS Visual Style Guide](https://qgis.org/en/site/getinvolved/styleguide.html)
![QGIS png](https://qgis.org/en/_downloads/qgis-icon128.png)

*Proposed idea for new QGIS icon*:
![QGIS icon - Numix-square style](https://i.imgur.com/tvikCB5.png)

**Comment by palob** [comment]
Hi, please reopen this in our repo for app icons https://github.com/numixproject/numix-core and feel free to open a pull request for the icon.
