### ISSUE TITLE
TeamViewer icon replace in tray on app icon.

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-icon-theme#1294]
The problem with the icon of the program is TeamViewer. A standard icon (not a Numix) of the program is displayed in the system tray. And in the list of installed icons for the tray.
Linux Mint Cinnamon 18.3
![2018-03-17 15-22-41](https://user-images.githubusercontent.com/26191203/37555514-41c293ba-29f9-11e8-9087-0ebf4eedfcdc.png)

**Comment by palob** [comment]
What you describe as "system tray" is just the standard app icon.
Can you please find out the ``icon=`` line from the respective ``.desktop`` launcher following the guide of our app icon repo https://github.com/numixproject/numix-core?

What you call standard icon is in fact a tray icon.

**Comment by Faust30000** [comment]
I use the icon for the tray to mark the icons in the folders status and the panel. Each DE has a system tray, and active program icons for it are taken from these folders. And there is a list of applications and desktop icons, they are taken icons from the apps  folder.
![2018-03-18 07-59-25](https://user-images.githubusercontent.com/26191203/37562905-83dde76e-2a84-11e8-9d36-1a850ffc6ebc.png)
![2018-03-18 08-00-49](https://user-images.githubusercontent.com/26191203/37562906-8416fb4e-2a84-11e8-8612-de18ba315134.png)

**Comment by palob** [comment]
Looks like it is ``Icon=TeamViewer``. Please check if that is the case like I asked you above.
In this case we need a symlink in *numix-core*.

**Comment by palob** [comment]
Labelled this as *bug* since I don't think an icon ``TeamViewer`` should be in our base theme.

**Comment by palob** [comment]
Just saw that there already is a ``TeamViever`` symlink in our app icon themes. Why doesn't it override the base icon here?

@Faust30000 How did you install the theme?

**Comment by Faust30000** [comment]
The theme of the icons was installed from the official repository: ppa:numix/ppa.

**Comment by palob** [comment]
Closing, probably outdated, hardcoded and issue opener isn't on GitHub anymore.
