### ISSUE TITLE
Tray Icon hiri

### ISSUE THREAD

**Issue by Chinney** [numixproject/numix-icon-theme#1295]
Related to this Icon request:
https://github.com/numixproject/numix-core/issues/4300#issuecomment-375383771

| Application name | Icon name | Desktop file name | Original icon |
| --- | :-- | :-- | :-- |
| `Hiri`| `/snap/hiri/hiri.png` | `hiri.desktop` | ![icon](https://user-images.githubusercontent.com/5702231/37763117-7c0d1694-2dbe-11e8-902c-b12c67fc2143.png) |

![image](https://user-images.githubusercontent.com/5702231/37816582-e6c7a1f6-2e73-11e8-86cb-6fc721883a86.png)

It's basically the same Icon as the launcher icon. I could not manage to replace it. I Tried everything and even contacted hiri about it. It seems like the tray icon is somehow part of the binary. Anyways good luck and Thanks in advance!

**Comment by palob** [comment]
Alas, we can not make a dedicated tray icon if it's the same name as the app icon.

**Comment by Chinney** [comment]
Well the launch icon should be placed in the `.../Numix{-Circle/Square/Whatever}/48/apps` folder. Hiri offers the possibility to create a `.desktop` file yourself where the icon can be chosen:

![image](https://user-images.githubusercontent.com/5702231/37825407-fea51ee0-2e8f-11e8-9919-5c01de12beb1.png)

It would be nice if there was also an indicator icon placed somewhere in the `.../Numix/{16/22/24}/status` folders. The icon under the path I posted above can't be substituted anyways since it's a snap package and therefor a read only filesystem. Hiri probably won't use the icon right now but I already sent hiri a feature request so maybe one day we will be able to chose one of your great icons.

**Comment by palob** [comment]
@Chinney Any news from upstream?
The state from 2018 means the icon is hardcoded (not themable without further ado).

**Comment by Chinney** [comment]
Dear @palob, as hiri is deprecated and turned in to a scam company (still charging my credit card without providing any possibility to cancel the subscription) I am no longer using this program. Working on this issue from your side might also be a waste of time. Thank you anyways!
