### ISSUE TITLE
install problem: Cannot add PPA

### ISSUE THREAD

**Issue by themesfa** [numixproject/numix-icon-theme#1306]
I enter the following command in terminal: 
`sudo add-apt-repository  ppa:numix/ppa`
 and get this error:
**`Cannot add PPA: '"Error reading https://launchpad.net/api/1.0/~numix/+archive/ppa: (35, 'gnutls_handshake() failed: Error in the pull function.')"'.`**
how i can fix this ?

**Comment by Foggalong** [comment]
Closed due to lack of information
