### ISSUE TITLE
Missing KDE icons

### ISSUE THREAD

**Issue by danielbucher** [numixproject/numix-icon-theme#1307]
Hi, I just installed the installed the numix-icon-theme using the PPA, but when I try using Numix icon theme I get no icon for some applications (e.g. Konsole).

I'm running a fresh install of Kubuntu 18.04.

Here's the output for `apt show numix-icon-theme`:

```
Package: numix-icon-theme
Version: 0.3+931~201804050035~ubuntu18.04.1
Priority: extra
Section: gnome
Maintainer: Satyajit Sahoo <satyajit.happy@gmail.com>
Installed-Size: 49,6 MB
Download-Size: 2.026 kB
APT-Manual-Installed: yes
APT-Sources: http://ppa.launchpad.net/numix/ppa/ubuntu bionic/main amd64 Packages
Description: Numix icon theme
 Designed to look fresh, swishy and modern using white symbols on vividly
 coloured background for applications and simplistic devices, toolbars
 and status icons.
```

What am I missing?

**Comment by Foggalong** [comment]
If you want themed application icons you also need to install and apply numix-icon-theme-circle or numix-icon-theme-square, one of our app themes :)

**Comment by danielbucher** [comment]
@Foggalong thanks, I already had the circle theme but didn't know there was a square one (the one I'm actually interested in).
