### ISSUE TITLE
Battery indicator shows incorrectly.

### ISSUE THREAD

**Issue by sxnaprkhr** [numixproject/numix-icon-theme#1314]
Battery indicator in GNOME is shown incorrectly considering the percentage of battery left in the laptop.

![screenshot from 2018-09-25 19-14-24](https://user-images.githubusercontent.com/29610365/46018477-912e8400-c0f7-11e8-9238-10914a12c021.png)

**Comment by Foggalong** [comment]
That's odd, I think all our percents are lined up correctly. I don't have a laptop to try and replicate this unfortunately so will have to wait until another dev comes along who does

**Comment by palob** [comment]
I use a laptop with GNOME, will have a look. So far I only had my eyes on the numeric percentage.

**Comment by sxnaprkhr** [comment]
Possible duplicate of #966.
Not a problem with Numix but this is how GNOME works. Closing this issue for now.

**Comment by palob** [comment]
Yeah, right now I've got a fully white battery at 67% charge.

**Comment by palob** [comment]
For the record, gnome-shell has a merge request open for more fine-grained steps.
https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/561

**Comment by sxnaprkhr** [comment]
Yeah, it's a bug that gnome-shell devs refuse to acknowledge.
https://gitlab.gnome.org/GNOME/gnome-shell/issues/492

**Comment by Foggalong** [comment]
@sxnaprkhr That doesn't look like them refusing to acknowledge the issue, rather a report made in the wrong place; there's an [open issue](https://gitlab.freedesktop.org/upower/upower/issues/49) in the power manager which looks to be where the issue is.

**Comment by palob** [comment]
The GNOME Shell battery icon currently isn't themed at all but it now supports finer steps. Cf. this papirus issue https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/1908

**Comment by Foggalong** [comment]
Oh wow those steps are much finer. Guess it's time to bust out the old battery icon flowcharts. Where's @dirtydancing when you need 'em? :wink:
