### ISSUE TITLE
Pamac issue

### ISSUE THREAD

**Issue by palob** [numixproject/numix-icon-theme#1323]
Since a recent update it looks like this:

![pamac](https://user-images.githubusercontent.com/7050624/52118359-62309d80-2616-11e9-845c-0912b0b58f1d.png)

The icons show up in places where previously non-Numix checkboxes were shown.

Haven't checked if it is upstream using wrong icons or us shipping bad designs.

Might be the icons in #184

Seems a to be a similar issue to #562

**Comment by palob** [comment]
This is how the competition does it.

*Adwaita*
![icons-adwaita](https://user-images.githubusercontent.com/7050624/60958601-ec3c0b00-a306-11e9-94a1-97dd8b6d74de.png)

*Breeze*
![icons-breeze](https://user-images.githubusercontent.com/7050624/60958635-f65e0980-a306-11e9-8e85-1efaaeeb8b06.png)

*Papirus*
![icons-papirus](https://user-images.githubusercontent.com/7050624/60958663-00800800-a307-11e9-80ac-41354f0f4656.png)

I'd say we definitely should get of the package metaphor and only keep arrows/checks/crosses etc.
Currently we've got this double package symbol and 16px are to small to support both package+action symbol anyway.

**Comment by palob** [comment]
The ``pamac-*`` icons in ``status`` on the other hand aren't used anywhere.

**Comment by palob** [comment]
Turns out the ones I attributed to Adwaita above are actually to be found in ``hicolor/16x16/status``. ``pacman -Qo`` tells they are installed along with pamac.
![pamac-icons](https://user-images.githubusercontent.com/7050624/61038613-9a11ed00-a3cd-11e9-98b7-ea660272a322.png)

**Comment by Foggalong** [comment]
That's frustrating that people seem to be adjusting the icons to fix the issue, but doesn't look like we have much choice here.

**Comment by palob** [comment]
This is my take
![pamac-new](https://user-images.githubusercontent.com/7050624/61737799-3f8f6e00-ad89-11e9-9069-646ee22cce3a.png)

**Comment by Foggalong** [comment]
Yellow background for outdated, and something else for package reinstall. The cut-in-two background feels really off.

**Comment by palob** [comment]
This for reinstall?
![reinstall](https://user-images.githubusercontent.com/7050624/62417356-9cbed580-b64d-11e9-847e-a9daac726666.png)

**Comment by Foggalong** [comment]
This is perfect, great job!
