### ISSUE TITLE
GNOME 3.32 decided to rename most of its icon paths into a tld.domain.separator.Scheme

### ISSUE THREAD

**Issue by cookiengineer** [numixproject/numix-icon-theme#1324]
With the GNOME 3.32 update, many icons break and there are weird behaviours all over the place when an icon is provided (or not?) by a theme. For example, the "app icon is missing from the dock panel" bug is related to it.

I managed to track down the issue. The GNOME maintainers decided to switch to a domain namespace separated pathing for icons since 3.32.

So all applications that have this path will not be themed by Numix anymore. I don't know how many applications are yet to be ported to it; because there are _lots_ of other gnome applications that still use the old paths in their `desktop` files.

However, this might give a hint on what is broken right now. For example, the old icon name was `utilities-terminal`, and now it's `org.gnome.Terminal`:

```bash
/usr/share/applications $
grep -R "Icon=org.gnome." ./
./org.gnome.Calculator.desktop:Icon=org.gnome.Calculator
./org.gnome.Logs.desktop:Icon=org.gnome.Logs
./org.gnome.Music.desktop:Icon=org.gnome.Music
./org.gnome.Evince.desktop:Icon=org.gnome.Evince
./org.gnome.FileRoller.desktop:Icon=org.gnome.ArchiveManager
./org.gnome.Terminal.desktop:Icon=org.gnome.Terminal
./gnome-system-monitor.desktop:Icon=org.gnome.SystemMonitor
./org.gnome.Cheese.desktop:Icon=org.gnome.Cheese
./org.gnome.seahorse.Application.desktop:Icon=org.gnome.seahorse.Application
./org.gnome.Nautilus.desktop:Icon=org.gnome.Nautilus
./org.gnome.font-viewer.desktop:Icon=org.gnome.font-viewer
./org.gnome.Totem.desktop:Icon=org.gnome.Totem
./org.gnome.Screenshot.desktop:Icon=org.gnome.Screenshot
./org.gnome.gedit.desktop:Icon=org.gnome.gedit
./gnome-control-center.desktop:Icon=org.gnome.Settings
./org.gnome.Epiphany.desktop:Icon=org.gnome.Epiphany
./eog.desktop:Icon=org.gnome.eog
./org.gnome.tweaks.desktop:Icon=org.gnome.tweaks
./org.gnome.DiskUtility.desktop:Icon=org.gnome.DiskUtility
./org.gnome.Contacts.desktop:Icon=org.gnome.Contacts
./org.gnome.baobab.desktop:Icon=org.gnome.baobab
```

I'm not sure how to process here as I'm a first-time issue submitter to this project. Please let me know how I can help making this awesome theme work on GNOME again!

I would imagine that it's just a symbolic link that is generated somewhere, so I would be grateful to receive instructions on how I can fix this myself.

**Comment by palob** [comment]
Thanks for the report. The repo for app icons is https://github.com/numixproject/numix-core. There you can apply symlinks in the ``data.json`` file. Apart from Seahorse which the next releases of Circle/Square will have fixes for we've got those icons names for longer. It appears we need to improve on how we get our latest releases out to people.

**Comment by cookiengineer** [comment]
I wanted to confirm that the current HEAD on master is working. After rebuilding the core and square icons, everything works like a charm!

Sorry for the inconvenience, next time I try building from head before raising an issue.

**Comment by palob** [comment]
We don't expect you to build from core master :), the latest releases https://github.com/numixproject/numix-icon-theme-circle https://github.com/numixproject/numix-icon-theme-square should suffice.

Out of interest, what's your distro and how did you install the theme?

**Comment by cookiengineer** [comment]
I use Arch and the community package for the square variant in `AUR`, the `-git` variants were up to date, so it was quite easy to build and integrate the package.

Package on AUR: https://aur.archlinux.org/packages/numix-icon-theme-git

**Comment by palob** [comment]
Good to hear it is up to date!
