### ISSUE TITLE
Wrong icon for Nextcloud in GOA

### ISSUE THREAD

**Issue by gregorydk** [numixproject/numix-icon-theme#1329]
I know the icon has owncloud in the name but it should be for Nextcloud. GNOME changed from ownCloud to Nextcloud in GOA but didn't change the icon name. So `goa-account-owncloud` should use the Nextcloud logo.

**Comment by gregorydk** [comment]
@palob Not fixed, yet. GOA Nextcloud still has the ownCloud icon with Numix.

**Comment by palob** [comment]
I think I'll "fix" this by removing all of our ``goa-*`` icons altogether. Some have alignment issues and there's nothing distinctly "Numixy" about them. The ones we'd inherit without own icons blend in just as well.

I'm looking for ways to improve Numix's maintainability now the bus factor has amounts to 1. This looks to be a good place to make cuts.
