### ISSUE TITLE
Several missing icons in Xfce

### ISSUE THREAD

**Issue by o-alquimista** [numixproject/numix-icon-theme#1330]
- Xfce Terminal
- Task Manager
- and several other icons (see screenshot below) from the Xfce Settings grid

They are missing. They show up blank when using Numix.

I'm using the [package from AUR](https://aur.archlinux.org/packages/numix-icon-theme-git/) on Arch Linux. It builds from this Git repository.

Currently installed version: `numix-icon-theme-git 0.r1981.896d9100e-1`

I've tested Adwaita icons and Elementary Xfce Icons. Both properly display the icons that are missing in Numix.

This seems to be a regression. It worked with previous versions. I don't know exactly the version when it started.

**Settings:**
![Captura de tela_2019-06-21_18-23-34](https://user-images.githubusercontent.com/25424263/59952230-cf23c300-9451-11e9-8bf7-467d27163cf5.png)
**Launcher:**
![Captura de tela_2019-06-21_18-24-04](https://user-images.githubusercontent.com/25424263/59952232-cf23c300-9451-11e9-8468-30eed3807597.png)
_Observation: Xfce Terminal icon shows up just fine on Whisker Menu. Anywhere else it's blank._

**Comment by o-alquimista** [comment]
Only the Task Manager icon is missing now.

**Comment by palob** [comment]
Hello, what do you mean by "now". Are you using a newer version?

**Comment by o-alquimista** [comment]
Sorry. By now I mean the AUR package currently builds from this commit: https://github.com/numixproject/numix-icon-theme/tree/ea068b43aba040ece617eb9dcc7ca16bfbabf816 and this is the version I have installed.

Yes, it's just plain Numix, without any of the app icon themes. I was instructed by the AUR package maintainer to open an issue here about these missing icons.

**Comment by palob** [comment]
Well, the missing icons are app icons, so it's a matter of course those aren't shown without an app icon theme installed.
We've got the app icons seperate so users can choose between Numix Circle and Numix Square.

Could you please try with one of our app icon themes installed.
If there's still an icon missing please report here https://github.com/numixproject/numix-core
We'll need the icon name from the respective ``.desktop`` launcher file in order to fix it.

**Comment by o-alquimista** [comment]
Oh, I didn't know that. I thought the base icon theme was meant for users who preferred to change only "system" icons, but not app icons, you know what I mean? I'll try one of these, then. Thanks.

Enviado via ProtonMail móvel

-------- Mensagem Original --------
Ativo 26 de jul de 2020 20:26, Vincent Bermel escreveu:

**Comment by palob** [comment]
Maybe we need to make this clearer, glad I could help.

**Comment by palob** [comment]
It is not possible to change only "system icons" de facto. There are overlaps which will lead to broken spots.

**Comment by palob** [comment]
@o-alquimista Still icons missing?

**Comment by o-alquimista** [comment]
Xfce has added many new system icons, so I believe this issue can be closed. I have been using an app icon theme like you suggested.
