### ISSUE TITLE
MIME types for TypeScript

### ISSUE THREAD

**Issue by ziyaddin** [numixproject/numix-icon-theme#1338]
Hello, Numix needs MIME types for TypeScript programming language (`*.ts` files).

**Comment by palob** [comment]
Can you please tell what the actual Mime type is like? Should be shown in the file properties dialog.

**Comment by ziyaddin** [comment]
Numix uses "JavaScript program (application/javascript)" for `*.js` files. Based on that, "TypeScript program (application/typescript)" or "TypeScript file (application/typescript)" can be used for `*.ts` files.

**Comment by ziyaddin** [comment]
If an icon picture needed, you may refer to this [logo](https://raw.githubusercontent.com/remojansen/logo.ts/master/ts.png).

**Comment by Foggalong** [comment]
@ziyaddin That's not necessarily how it work, not every mimetype follows the same format. Please lookup the actual icon name either using the properties dialogue or using `file -b --mime-type something.ts`

**Comment by ziyaddin** [comment]
`file -b --mime-type something.ts` retrieves `text/x-java` and I think it is erroneous.

**Comment by palob** [comment]
That means currently there is no mimetype implemented for TypeScript. 
I couldn't find it here either: https://cgit.freedesktop.org/xdg/shared-mime-info/tree/

**Comment by Foggalong** [comment]
@ziyaddin Yeah, in short that means we can't make an icon for it because the system won't pick up that a given file is TypeScript. If the situation changes and a mimetype gets implemented we could, but I'm not really sure how one even goes about requesting a new mimetype.

**Comment by bilelmoussaoui** [comment]
You can either open an issue here https://gitlab.freedesktop.org/xdg/shared-mime-info/ or update this file https://gitlab.freedesktop.org/xdg/shared-mime-info/blob/master/freedesktop.org.xml.in and send a MR that adds typescript support. Once a new release is out, the new mimetype will be recognized and Numix could add an icon for TypeScript

**Comment by ziyaddin** [comment]
I see. Thanks for providing a possible solution.

**Comment by ziyaddin** [comment]
I put it here as a follow-up to this issue:

https://gitlab.freedesktop.org/xdg/shared-mime-info/issues/117
