### ISSUE TITLE
Ubuntu eoan repo not updated

### ISSUE THREAD

**Issue by JamesCHLim** [numixproject/numix-icon-theme#1350]
Hi everyone, absolutely loving this fantastic icon pack. My only issue is that using POP!_OS, a derivative of ubuntu, the battery icon is not working as it should.

![image](https://user-images.githubusercontent.com/58202195/76594615-bb733c00-654d-11ea-9bf5-ac104b43c6d7.png)

Now i've seen that in a recent commit 3 months ago, support for proper battery level and charging icons has been added for gnome. I want to grab it, but neither the normal ppa or nightly ppa are updated (for eoan). I followed the readme instructions, and added the ppa, and updated and attempted to install.

![image](https://user-images.githubusercontent.com/58202195/76594790-26247780-654e-11ea-9cdd-b2208d60a20e.png)

but the latest versions are very far behind

![image](https://user-images.githubusercontent.com/58202195/76594846-418f8280-654e-11ea-9718-c3929945d348.png)

I would love to install the latest updates manually as a temporary fix, but I have no idea as how to do so.

I am relatively new to Linux, so I don't know too much about these PPA's, other than Ubuntu's seems to be generally outdated. Is it possible that someone is able to update them?

Thanks!

P.S It seems the eoan repo is outdated, switched the eoan to bionic and was able to get a recent update, as the battery fix has not been released yet, my problem still remains. Though I am happy to wait. But please update eoan! :)

![image](https://user-images.githubusercontent.com/58202195/76596304-e495cb80-6551-11ea-8689-57fae4244b30.png)

**Comment by Foggalong** [comment]
I'm gonna tag new releases for Ubuntu and the PPA today so these should role out - I think the issue with batter is that there hasn't been a tagged release since the fix landed. Let me know if this doesn't trickle down into the repos!

**Comment by Foggalong** [comment]
[Done](https://github.com/numixproject/numix-icon-theme/releases/tag/20.03.20)!
