### ISSUE TITLE
Ubuntu 20.04 16px status icon too much padding

### ISSUE THREAD

**Issue by andia89** [numixproject/numix-icon-theme#1355]
Ubuntu 20.04 will use 16px icons instead of 22px icons in the top bar. Since all (most?) 16px status icons have way too much padding that looks as if these icons were way too small. I think a proper solution would be to go through the 16px icons and remove the padding

See here for reference: https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/211

I have some free time the next few days, I could go through them and change it?!

**Comment by palob** [comment]
Is this different from GNOME upstream? Thought those had been 16 px forever.

**Comment by andia89** [comment]
That is the reason they changed it in Ubuntu now. To be the same as upstream

**Comment by palob** [comment]
But I don't seem to have any problems with GNOME on Arch. That is without any tray icons (only Shell extension indicators) actually.
That Shell extension is for legacy tray icons, right?

**Comment by palob** [comment]
So what for did we use that much padding?

**Comment by andia89** [comment]
I think these icons were never really used, that's why we didn't really care. 

Here you can see what I mean

![image](https://user-images.githubusercontent.com/6475757/78458606-fed74b00-76b2-11ea-9891-a9ef3c655659.png)
The dropbox icon as well as variety (the sqaure with the mountain in it) look way too small

**Comment by palob** [comment]
Is this screenshot rescaled? Because the icons don't look just too small but also blurry which would mean there is some rescaling (as a result of the wrong size being picked?) going on.

**Comment by andia89** [comment]
Well, from what I saw quite a few of those 16px icons are also not properly aligned to grid. So yes they are on top of that blurry. As I said I think these icons were never really used, so we didn't care
