### ISSUE TITLE
Missing calendar icon in datetime-indicator Ubuntu 14.04 

### ISSUE THREAD

**Issue by garchomps** [numixproject/numix-icon-theme#136]
![datetime](https://cloud.githubusercontent.com/assets/6912559/3324855/0ea1667c-f786-11e3-8c88-2e80327e3fcb.jpg)
Normally where the blank icon is is a smaller version of the calendar icon. I have noticed this using every custom icon theme in Ubuntu, even with following the install instructions properly. It would be nice if my favorite icon theme would be the first to get it right :)

**Comment by wa4557** [comment]
Is there a reason why the corresponding icon `calendar.svg` is present in numix-circle and not numix-base? Works for me fine if I copy it from circle to base.
![calendar](https://cloud.githubusercontent.com/assets/6475757/7101228/a4ab9604-e04e-11e4-8200-1847b38eafed.png)

**Comment by Foggalong** [comment]
Probably so it doesn't interfere with `calendar.svg` as an app icon

**Comment by wa4557** [comment]
I think you misunderstand. There is no `calendar.svg` in circle except this one. So definitely no interference...

![unbenannt](https://cloud.githubusercontent.com/assets/6475757/7101280/bd904892-e051-11e4-97c1-4356cd063bb1.png)

**Comment by wa4557** [comment]
@Foggalong This can be closed now

**Comment by Foggalong** [comment]
\o/
