### ISSUE TITLE
Numix PPA does not support Ubuntu 20.04

### ISSUE THREAD

**Issue by polmes** [numixproject/numix-icon-theme#1361]
Not sure if this should be submitted here or upstream in numix-core, but as far as I can tell, the existing Numix PPA does not support Ubuntu 20.04 (after checking [here](https://launchpad.net/~numix/+archive/ubuntu/ppa), there don't seem to be any packages built for the latest version of Ubuntu), and in fact when you try to add the PPA, apt gives you the following error:
> The repository 'http://ppa.launchpad.net/numix/ppa/ubuntu focal Release' does not have a Release file.

I know 20.04 was just released a few days ago, but I would love to see support for it!

**Comment by morariu27** [comment]
I think this is the place to submit this issue. Ubuntu 20.04 without Numix theme is not good.

**Comment by polmes** [comment]
Seems to be fixed now. Thanks!
