### ISSUE TITLE
Missing icons in GNOME's On-Screen Keyboard

### ISSUE THREAD

**Issue by palob** [numixproject/numix-icon-theme#1366]
Stumbled upon this Papirus issue https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/2318

It looks the same with Numix.
![keyboard](https://user-images.githubusercontent.com/7050624/87130065-993ac200-c292-11ea-9c3f-8e41a2777c8d.png)

As a fallback for the missing icons a generic keyboard icon is shown.

**Comment by palob** [comment]
Icon names are
``keyboard-caps-lock-filled-symbolic``
``keyboard-enter-symbolic``
``keyboard-hide-symbolic``
``keyboard-layout-filled-symbolic``
``keyboard-shift-filled-symbolic``

**Comment by palob** [comment]
I'm wondering why that keyboard icon is shown. Even adding ``Adwaita`` to the ``Inherits`` line (and running ``gtk-update-icon-cache`` as well as removing the cache file) doesn't bring up the Adwaita icons.

**Comment by Foggalong** [comment]
@palob Some applications check the applied theme for fallback icons before checking inherited themes for the actual icons; it's not an area I've done much research in from what I've seen it varies somewhat between applications and environments.

**Comment by palob** [comment]
Turns out the icons are not part of neither ``Adwaita`` nor ``gnome``.
