### ISSUE TITLE
Go-Bottom Icon cut off

### ISSUE THREAD

**Issue by Justinzobel** [numixproject/numix-icon-theme#1385]
Is the bottom supposed to be cut off or is it an export failure?

https://github.com/numixproject/numix-icon-theme/blob/master/Numix/16/actions/go-bottom.svg

**Comment by palob** [comment]
The ``go-...`` icons are designed to look like this but this might be a design to be revised at some point.

**Comment by Justinzobel** [comment]
Ah OK. It was reported as an issue on the KDE Bugzilla as it didn't look right to a user.
