### ISSUE TITLE
Icons for gammastep

### ISSUE THREAD

**Issue by Stunkymonkey** [numixproject/numix-icon-theme#1390]
For sway (wayland) `redshift` does not work out of the box. There is a fork which fixes many bugs called [`gammastep`](
https://gitlab.com/chinstrap/gammastep).

when looking at distros it is widely adopted.
[![Packaging status](https://repology.org/badge/vertical-allrepos/gammastep.svg)](https://repology.org/project/gammastep/versions)

For me personally it would be fine to have a symlink between `redshift` and `gammastep`.

gammastep-indicator-icon and tray-icons are missing

**Comment by palob** [comment]
Are those indicator/tray unchanged redshift ones or do they ship new ones?

Could you please provide a screenshot of the original icons?

**Comment by Stunkymonkey** [comment]
they look identically

app icon: 
![Screenshot-2020-12-04_145133](https://user-images.githubusercontent.com/1315818/101171783-8f9a6800-3640-11eb-9871-c603a92cc39b.png)

tray icon: 
![Screenshot-2020-12-04_145139](https://user-images.githubusercontent.com/1315818/101171801-95904900-3640-11eb-98ea-73210dc87505.png)

if i use redshift the icons from numix are used. So i guess they ship new ones.

**Comment by Stunkymonkey** [comment]
this PR is to be merged first: https://github.com/numixproject/numix-core/pull/5696

**Comment by Stunkymonkey** [comment]
I can confirm, that the icon for `gammastep` application works, but the tray-icon still uses the original one.

I am unable to find the correct repo where to report the issue/PR. Could you tell me where to start?

**Comment by palob** [comment]
Isn't this very one the exact issue?
Or are there hardcoded tray icons which still are unthemed even with the links in your PR?

**Comment by palob** [comment]
So your PR fixes the issue completely?
