### ISSUE TITLE
Broken tray-icon for remmina

### ISSUE THREAD

**Issue by zensubz** [numixproject/numix-icon-theme#1392]
The newer versions of remmina (v1.4.13) use a different name for panel-icon, it used to be remmina-panel.svg, but now it uses org.remmina.Remmina-symbolic.svg, which is not available in Numix/Numix-Circle.

It would be great if Numix/Numix-Circle makes the necessary panel-icon for this (symlinking to remmina-panel.svg might work). Thanks.

**Comment by palob** [comment]
How does the original icon look like? If it is a symbolic icon like the name suggest there is not much wiggle room for a distinct "Numixy" design.

**Comment by zensubz** [comment]
The symbolic icon is placed at /usr/share/icons/hicolor/apps/org.remmina.Remmina-symbolic.svg (compressed file attached here).


[org.remmina.Remmina-symbolic.svg.gz](https://github.com/numixproject/numix-icon-theme/files/6251775/org.remmina.Remmina-symbolic.svg.gz)

**Comment by palob** [comment]
Ah, I see. That isn't really a symbolic icon and hence it stands out.

**Comment by zensubz** [comment]
Looks like the latest version (1.4.17) of remmina has this issue fixed. More info here:

[https://gitlab.com/Remmina/Remmina/-/merge_requests/2261](url)

**Comment by palob** [comment]
Closing because fixed upstream.
