### ISSUE TITLE
Problem with librsvg-2.52.0

### ISSUE THREAD

**Issue by pillmuncher** [numixproject/numix-icon-theme#1405]
After the weekly update of Solus Linux yesterday the User Indicator icon (Numix/scalable/actions/system-shutdown-symbolic.svg) had disappeared both from the Budgie Panel, as well as the LightDM login screen, yet not from the file system. It has since been determined that a downgrade from librsvg-2.52.0 to librsvg-2.50.7 fixes the problem. Thought y'all oughta know.

See also:
https://discuss.getsol.us/d/7442-user-indicator-icon-missing/7
https://dev.getsol.us/T9920

**Comment by palob** [comment]
I can confirm this. I don't see a shutdown icon in GNOME on Arch but I didn't notice so far, maybe I took it as a design choice.

**Comment by Foggalong** [comment]
That's really weird, especially that the presence of the `numix-icon-theme` package is causing issues for _other_ themes

**Comment by algent-al** [comment]
> That's really weird, especially that the presence of the `numix-icon-theme` package is causing issues for _other_ themes

I think the reason for that is because the affected icon themes are inhering icons from Numix.
For example you can see Surfn `index.theme`:
https://github.com/erikdubois/Surfn/blob/master/surfn-icons/Surfn/index.theme#L4

**Comment by Foggalong** [comment]
That's useful intel, thanks Algent!

**Comment by Noobsai** [comment]
I defined the width property in the svg file and problem is gone
`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16.0243" width="16" height="16.02">`

**Comment by Foggalong** [comment]
In which case this is a bug with `librsvg` 2.52, not `numix-icon-theme`; the `height` and `width` attributes are [optimal](https://www.w3.org/TR/SVG11/struct.html#SVGElementWidthAttribute) in the SVG spec (default 100%, with us controlling size via `viewbox`).

**Comment by pillmuncher** [comment]
I opened an issue at GNOME's gitlab: https://gitlab.gnome.org/GNOME/librsvg/-/issues/797

**Comment by Foggalong** [comment]
Thanks @pillmuncher, will tack this issue there for now!

**Comment by Foggalong** [comment]
Upstream bug has now been [fixed](https://gitlab.gnome.org/federico/librsvg/-/commit/c6f1cbef1b234abe541df32b4f1c61085a368630), pegged for release in 2.52.1 pending a fix for another unrelated bug.
