### ISSUE TITLE
Possible typo in model-x.stl-binary.svg 

### ISSUE THREAD

**Issue by spezialspezial** [numixproject/numix-icon-theme#1407]
numix-icon-theme/Numix/48/mimetypes/model-x.stl-binary.svg 

Should this be model-x-stl-binary.svg (- for .)?

**Comment by spezialspezial** [comment]
seems to exist in model like that, what gives

**Comment by Foggalong** [comment]
Yeah some mimetypes have weird names 🤷‍♀️

**Comment by spezialspezial** [comment]
Mimetypes are a mess. Registry says model/stl but the other definition in my mime cache splits it in model/x.stl-ascii and model/x.stl-binary. 

https://www.iana.org/assignments/media-types/media-types.xhtml#model
