### ISSUE TITLE
Element tray-icon (formerly riot)

### ISSUE THREAD

**Issue by Stunkymonkey** [numixproject/numix-icon-theme#1408]
element is currently not using a numix-tray-icon, because there is none.

I highly believe, that it is supported by [`Hardcode-Tray`](https://github.com/bilelmoussaoui/Hardcode-Tray/blob/master/data/database/element.electron.json).
An inspiration can be seen at [papirus-icon-theme](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/master/Papirus/24x24/panel/element-desktop-tray.svg). is it possible to use the same files? or how are the files generally created?

only two file need to be created:
```
Numix/24/panel/element-desktop-tray.svg
Numix-Light/24/panel/element-desktop-tray.svg
```

**Comment by palob** [comment]
Well it's a symbolic-type icon so there is not much room for a distinct Numix design. Colour, size  and positioning might need adjustment.

**Comment by Stunkymonkey** [comment]
because I have no experience in designing such icons, I opened this issue. So if anyone wants to help everyone is welcome.

**Comment by palob** [comment]
I've never contributed tray icons either and my knowledge is limited.

**Comment by palob** [comment]
So without applying Hardcode-Tray the (green-white) app icon is shown?

**Comment by Stunkymonkey** [comment]
exactly
