### ISSUE TITLE
Problem with librsvg 2.54.0

### ISSUE THREAD

**Issue by napcok** [numixproject/numix-icon-theme#1414]
After update librsvg to 2.54.0 numix icons looks like: 
![numix-icons](https://user-images.githubusercontent.com/3028270/163578632-189b445c-8f35-4f33-9b63-3f9790224f48.png)

The same issue like after updating librsvg to 2.52.0 if I remember correctly.
So maybe it is a good idea to add width attribute to icons? To not face this problem every few months.

**Comment by palob** [comment]
Did you try if adding width/height helps?

**Comment by napcok** [comment]
Yes, adding width and height helps.

**Comment by palob** [comment]
Is it still present with 2.54.1?

**Comment by napcok** [comment]
It is fixed with 2.54.1 :+1:  Thanks.
