### ISSUE TITLE
New icon for clash (a net-proxy app)(from China)(48*48)

### ISSUE THREAD

**Issue by RosenYin** [numixproject/numix-icon-theme#1416]
I draw a icon for clash 
![clash](https://user-images.githubusercontent.com/63038691/164909875-81ebc9b2-6346-4a3a-bcd5-ef99d1f09773.svg)

**Comment by palob** [comment]
Hi, can you please open a pull request to review this here https://github.com/numixproject/numix-core?
Do you know how to do this?

You can find some basic design guidelines here: https://github.com/numixproject/numix-core/wiki/Guidelines
In the numix core repo are template baseplates where you can place your symbol on.
