### ISSUE TITLE
[Request] WiFi status icon for GNOME 42

### ISSUE THREAD

**Issue by onlymash** [numixproject/numix-icon-theme#1417]
Numix-Circle:
![Screenshot from 2022-06-15 11-06-32](https://user-images.githubusercontent.com/5838634/173728354-e3b039e0-e961-4812-8878-a25f79a2c692.png)

Adwaita(default):
![Screenshot from 2022-06-15 11-06-54](https://user-images.githubusercontent.com/5838634/173728412-00c90600-3df8-4c24-bb5f-27c41f6f3c46.png)

**Comment by Foggalong** [comment]
@onlymash Do you have the name of the icon needed?

**Comment by palob** [comment]
commit 7d382d38b33e395a13f081e48c48c9acb4136f06 should have fixed the broken fallback resulting in no proper icon showing up.

**Comment by onlymash** [comment]
@palob thx
