### ISSUE TITLE
Evolution 3.44.3 icons

### ISSUE THREAD

**Issue by ckotte** [numixproject/numix-icon-theme#1418]
Evolution 3.44.3 introduced some changes to the icons:

https://gitlab.gnome.org/GNOME/evolution/-/commit/698ae96b7409215cca7a3c620862360c324653a8

```
Evolution 3.44.3 2022-07-01
---------------------------
Bug Fixes:
	I#1848 - icons: Add symbolic variants for toolbar/folder tree icons (Jakub Steiner)
	I#1918 - Composer: Skip STYLE and other tags in convert to Plain Text
	I#1919 - Drag&Drop creates many identical temporary files
	I#1930 - Update Task preview, when Task is updated
	I#1941 - ESourceSelectorDialog: Close on double-click on source only
	I#1944 - Crash when printing task list to pdf
	I#1946 - Logic of "Do not sign meeting requests" is inverted
	M!109 - EShell: Use symbolic icons on GNOME (Cédric Bellegarde)
```

**Evolution 3.44.3**

A few icons are replaced by Numix with symbolic icons, but not all of them:

Numix
![Evolution_3 44 3_numix](https://user-images.githubusercontent.com/8488565/177036737-271583a5-738e-4b4f-a7a7-4bf95ac941c0.png)

Adwaita
![Evolution_3 44 3_adwaita](https://user-images.githubusercontent.com/8488565/177036735-9312d6ac-d31e-45c2-a999-8f213011ab47.png)

How can I change it back to the old behavior without downgrading. Can the Numix icon theme be updated to use the colored icons or how can I get rid of the ugly symbolic icons in the new version?

**Evolution 3.44.2**

Numix
![Evolution_3 44 2_numix](https://user-images.githubusercontent.com/8488565/177036714-a94e43a7-8139-4ac4-a6a8-f29ef4066bdc.png)

Adwaita
![Evolution_3 44 2_adwaita](https://user-images.githubusercontent.com/8488565/177036716-30dcf7be-58ff-412b-83a7-e43edac7c42c.png)

**Comment by palob** [comment]
As far as I can see we can't fix this unless we were to push multicoloured icons in place of symbolic icons. This wouldn't work however, the icons wouldn't be displayed correctly.
Evolution will probably soon receive a CSD header bar GUI (cf. the open - at time of writing - MR). The symbolic icons won't be oversized and won't look out of place then I think.

**Comment by ckotte** [comment]
> CSD header bar GUI (cf. the open - at time of writing - MR)

I don't understand the abbreviations. cf? MR?

I guess the symbolic icons in the left pane can't be changed then too? 

![image](https://user-images.githubusercontent.com/8488565/177037604-eb63dcae-fcaa-4f7f-98d7-28aabd9d4897.png)

However, the mails have a blue icon:
![image](https://user-images.githubusercontent.com/8488565/177037693-a8f5b0d7-e05c-4c0c-9f27-f0f96af2445f.png)

Some of the symbolic icons are not changed by Numix and look out of place. For example, the New icon and the icons in the right corner at the bottom.

**Comment by palob** [comment]
Sorry, MR means merge request. I'm referring to this one https://gitlab.gnome.org/GNOME/evolution/-/merge_requests/108

Take a look at the folder icons in the left pane. Those are actually non-symbolic Numix icons. This is somewhat how non-symbolic icons will look in place of symbolic icons which only support a dark shade + a bright shade + an accent colour.

**Comment by palob** [comment]
@ckotte Do you have access to the latest Evolution release with CSD header bar and would you mind checking how it looks now?

**Comment by ckotte** [comment]
Now it looks right. I'm using evolution 3.46.1 on Arch Linux. Thanks for fixing.

![Screenshot from 2022-11-18 00-35-56](https://user-images.githubusercontent.com/8488565/202518131-43f31fcc-8d7e-46c8-8975-4e04714f78e0.png)

**Comment by palob** [comment]
Thanks but we didn't do anything. This might change again in future as per GNOME HIG (human interface guidelines) symbolic icons are to be used in a headerbar.
