### ISSUE TITLE
Please add text-speak to your theme

### ISSUE THREAD

**Issue by Master811129** [numixproject/numix-icon-theme#1419]
`text-speak` is usually used in text to speech applications such as [voicegen](https://gitlab.com/PersianGolf/voicegen) or [Kmouth](https://apps.kde.org/kmouth/). adding it would be great:
Numix:
![Screenshot_2022-07-15_03-22-13](https://user-images.githubusercontent.com/37829730/179213685-4807604c-9e1f-4c3a-91b5-320e6688bccd.png)

Papirus:
![Screenshot_2022-07-15_03-23-48](https://user-images.githubusercontent.com/37829730/179213725-1b865de2-f059-454e-9f58-fbcbb1c40604.png)

**Comment by palob** [comment]
What is this icon used for? Can we be more specific than using a generic speaker icon?

**Comment by Master811129** [comment]
I'm sorry i meant `text-speak`
> What is this icon used for?
when you want a button that plays a computer voice you use this icon. 
this is Kmouth (a kde app) it converts text to speech. speak button uses `text-speak`:
![Screenshot_20220716_101754](https://user-images.githubusercontent.com/37829730/179341849-790b8b40-84e5-4ef7-96c7-bf8d1f5e209c.png)

here is `text-speak` in cuttlefish icon browser:
![Screenshot_20220716_102228](https://user-images.githubusercontent.com/37829730/179341963-26a52d77-bc87-4dac-b20e-01e6e946e4d6.png)

**Comment by Master811129** [comment]
Thanks.
