### ISSUE TITLE
Same Symbol for "Icon View" and "Compact View" in Nemo File Manager

### ISSUE THREAD

**Issue by stabilergriller** [numixproject/numix-icon-theme#1427]
Good day,

On a fresh install of Arch + Budgie 10.6.4 + Nemo 5.4.3, it seems like the icon for the Icon View is wrongly using the same icon as Compact View.

![Selection_001](https://user-images.githubusercontent.com/115423284/200137362-72a18fe0-c897-4471-a372-a5448b9b45e9.png)

For reference, I installed Numix Square with the [AUR](https://aur.archlinux.org/packages/numix-square-icon-theme) (but the problem also happens with Numix Circle), therefore I put this issue in the General bugtracker.

I believe this behaviour is a bug, since it doesn't happen on every other icon theme I tried. Here is how it looks like on Papirus:

![image](https://user-images.githubusercontent.com/115423284/200137523-870f4d19-2fd7-49bc-af7d-5f8fd02731ad.png)

On Nordzy:

![image](https://user-images.githubusercontent.com/115423284/200137551-a5466177-d7e8-43b9-995c-45fd8a1c9b57.png)

On Mint Y:

![image](https://user-images.githubusercontent.com/115423284/200137611-263ae34e-bc8f-4291-b085-5588ebe60a90.png)

**Comment by palob** [comment]
Hi, thanks for reporting. Can you please verify with other themes if the names of the icons in question are (from left to right)
``view-grid(-symbolic)``, ``view-list(-symbolic)``, ``view-compact(-symbolic)``?

**Comment by palob** [comment]
Pushed a design looking like the ``hicolor`` icon which I think is the best representation of how the compact view actually looks in Nemo.
