### ISSUE TITLE
Distribute folder icons in other colors.

### ISSUE THREAD

**Issue by Initu-Castilhos** [numixproject/numix-icon-theme#1439]
Distribute for download the folder icons with full colors in Gnome Look as the Papirus developer did.  I have to have scrypt that changes folder colors and styles, but for lay users it's better to have it available for download.

**Comment by palob** [comment]
Do you know https://github.com/numixproject/numix-folders?

It has got a GTK3 GUI which however is broken in so much as it doesn't work under wayland and can't apply the icons locally (only system-wide).
You can apply numix-folders (also sytem-wide only) using the script which ships with it. You have to reapply it every time you update the numix base theme though, this is a bit cumbersome.

Right now I'm the sole maintainer and contributer to Numix. I definitely won't make packages for each folder colours. I lack the time and I don't think it is a very worthwhile effort.

**Comment by Initu-Castilhos** [comment]
> Você conhece https://github.com/numixproject/numix-folders ?
> 
> Ele tem uma GUI GTK3 que, no entanto, está quebrada, tanto que não funciona em wayland e não pode aplicar os ícones localmente (apenas em todo o sistema). Você pode aplicar pastas numix (também em todo o sistema) usando o script que vem com ele. Você deve reaplicá-lo toda vez que atualizar o tema base numix, porém, isso é um pouco complicado.
> 
> No momento, sou o único mantenedor e colaborador do Numix. Definitivamente não farei pacotes para cada cor de pasta. Falta-me tempo e não acho que seja um esforço que valha a pena.
> 
> É claro que estou aberto a qualquer pessoa comprometida há muito tempo entrando e fazendo o trabalho.
I can post the icons on Gnome Look, I just need your approval.  I can post the link to your Github page.
