### ISSUE TITLE
Breeze action icons don't follow the light/dark theme in KDE Plasma.

### ISSUE THREAD

**Issue by api33tiramisu** [numixproject/numix-icon-theme#1440]
**Linux Distribution:** Debian 12
**Desktop environment:** KDE Plasma 5.27.5

I have ran into this issue where the non-themed action icons use the light variant of Breeze which makes icons hard to see with a dark theme. Tested with both the version Debian provided and the latest Git version.

![Application Launcher Places icon](https://github.com/numixproject/numix-icon-theme/assets/107980627/d57672b4-c532-490a-8609-571369708828)

![Action icons](https://github.com/numixproject/numix-icon-theme/assets/107980627/3b7cb549-6849-48ba-bfb1-451c45592f82)

**Comment by palob** [comment]
Does this occur with *Numix* or *Numix Light*?

**Comment by palob** [comment]
So the very same icons look like they should with ``Breeze`` applied but ``Numix (Light)`` messes up the colours?

Might be something wrong in the ``index.theme`` file.

**Comment by palob** [comment]
Couldn't find any obvious cause so far. @api33tiramisu Does this occur with both the light and dark Plasma UI theme options?

**Comment by palob** [comment]
So with light Plasma theme Numix doesn't break the unthemed Breeze icons?

**Comment by palob** [comment]
One more question: How does it look with ``breeze-dark`` Numix inheritance when using a light Plasma theme? No unexpected behaviour (e.g. light icons on light background)?

**Comment by palob** [comment]
Well, let's see how other icon themes handle this. It's *light* icons (to be used with a *dark* UI theme).
And I need to give KDE another spin (maybe when Plasma 6 is out). With GNOME ``Numix-Light`` isn't needed at all.

**Comment by palob** [comment]
Change to ``breeze-dark`` released.

**Comment by palob** [comment]
Ah so I should rather revert since AFAIK light UI schemes are default for Plasma.

**Comment by palob** [comment]
You can reproduce the issue using the MoreWaita icon theme it appears. https://github.com/somepaulo/MoreWaita/issues/124

**Comment by palob** [comment]
Thank you! So the inheritance ought to be ``Inherits=Adwaita,~breeze-dark~,gnome,hicolor`` and ``FollowsColorScheme=true`` has got to be added to *Numix*, *Numix-Light*?

To the app icon themes as well?

**Comment by palob** [comment]
Now, does it work with both ``Inherits=breeze,...`` and ``FollowsColorScheme=true`` in the index.theme?

I'm not sure the breeze inheritance can be safely removed.
