### ISSUE TITLE
KDE Plasma 6 panel bluetooth wrong icon

### ISSUE THREAD

**Issue by oldherl** [numixproject/numix-icon-theme#1443]
The bluetooth icon on the panel on KDE Plasma 6 is wrong.
Numix Light - using Numix/48/places/default-network.svg icon instead of a bluetooth icon
![bluetooth-wrong](https://github.com/numixproject/numix-icon-theme/assets/172495/35c8cf1c-5ffd-45a2-a3f1-19d7fe3de751)
Breeze - correct bluetooth icon
![bluetooth-breeze](https://github.com/numixproject/numix-icon-theme/assets/172495/322ba31b-a5b5-46b0-ac4f-6d175e56c005)

Arch Linux, plasma-desktop 6.0.1-1, numix-icon-theme-git 23.12.02.r0.g00f14ad4e-1

**Comment by palob** [comment]
Hi, can you zero in on what's the icon name of the correct Breeze icon (it might not be ``default-network`` but something else we have implemented as symlink to ``default-network``)?
Now if it really is ``default-network`` this seems an odd choice for a bluetooth icon.

**Comment by oldherl** [comment]
Here's the code for bluetooth plasmoid:
https://invent.kde.org/plasma/bluedevil/-/blob/master/src/applet/package/contents/ui/main.qml?ref_type=heads
From there I compared with the breeze icons:
![breeze-icons](https://github.com/numixproject/numix-icon-theme/assets/172495/6956dfee-42c5-486c-9bd3-2a4a58b6e611)
It should be fixed with those three symbolic links:
```
ln -s bluetooth-active.svg network-bluetooth-symbolic.svg
ln -s bluetooth-disabled.svg network-bluetooth-inactive-symbolic.svg
ln -s bluetooth-paired.svg network-bluetooth-activated-symbolic.svg
```

**Comment by palob** [comment]
Can you show a screenshot of how this looks like without Numix Circle applied and can you confirm the "bank vault" icon name is ``plasmavault`` or ``org.kde.plasmavault``?

**Comment by palob** [comment]
The paperclip icon name is ``klipper`` I suppose and it should be removed from our app icons themes.

**Comment by oldherl** [comment]
> Oh no, that's a huge mess with app icons (Numix Circle) in the mix. Might not be possible to fix due to conflicting icon names.

I'm not sure why you say there's a conflict. If you mean it's hard to make the tray icon monochrome, then it's a plus for me. I prefer colourful icons in the tray than the monochrome ones.

**Comment by palob** [comment]
@oldherl There is the issue of KDE picking up icons with incomplete file names. It picks up the wrong icon ``network-wireless`` (the radio tower icon) instead of ``network-wireless-signal-[ok/weak/none/good/excellent]``.
Maybe just removing ``network-wireless`` from Numix base will fix this possibly at the cost of other DEs.

**Comment by palob** [comment]
Well, those circle icons aren't supposed to pop up in such places because of wrong sizing which leads to blurry results.

**Comment by palob** [comment]
In the end the problem is us using distinctly different design languages for app icons and everything else.

**Comment by oldherl** [comment]
> @oldherl There is the issue of KDE picking up icons with incomplete file names. It picks up the wrong icon `network-wireless` (the radio tower icon) instead of `network-wireless-signal-[ok/weak/none/good/excellent]`. Maybe just removing `network-wireless` from Numix base will fix this possibly at the cost of other DEs.

I created this issue just for the bluetooth icon. I don't care about whether showing the wifi signal strength or not.

**Comment by oldherl** [comment]
And since the current "wrong" icon is more colourful (with the blue signal graphics) than the monochrome icon with strength, I actually prefer the current one.

**Comment by palob** [comment]
I see. It is wrong though because it can't show the signal strength and is misplaced relative to the other icons shown.

**Comment by palob** [comment]
I'll tag new releases soon. Please check if the issue persists.
