### ISSUE TITLE
Inherit AdwaitaLegacy icons.

### ISSUE THREAD

**Issue by Initu-Castilhos** [numixproject/numix-icon-theme#1446]
Starting with Gnome 42, the legacy icons were removed, leaving some colored icons missing. So this theme package was created to add the colored icons back.
https://gitlab.gnome.org/GNOME/adwaita-icon-theme-legacy

**Comment by Initu-Castilhos** [comment]
It would be this sequence: 
Inherit=AdwaitaLegacy, Adwaita, breeze, gnome, hicolor.

**Comment by palob** [comment]
Thanks, I think ``gnome`` can be dropped now.

**Comment by palob** [comment]
Fixed in https://github.com/numixproject/numix-icon-theme/commit/02e5e3b2c85d82703b6887e8af7e8f1c57545cc6

**Comment by Initu-Castilhos** [comment]
> Corrigido em [02e5e3b](https://github.com/numixproject/numix-icon-theme/commit/02e5e3b2c85d82703b6887e8af7e8f1c57545cc6)

Thanks!
