### ISSUE TITLE
Thunderbird 31 missing icons

### ISSUE THREAD

**Issue by clauded** [numixproject/numix-icon-theme#153]
Seems like upgrading to Thunderbird 31 (under Ubuntu 14.04) breaks numix circle icons in the toolbar (was fine with version 24).

![capture du 2014-07-22 23 05 00](https://cloud.githubusercontent.com/assets/4673125/3668209/66fac3ae-1216-11e4-80e7-fd436c92bae9.png)

**Comment by dirtydancing** [comment]
This looks like the same problem as with "Saved Search", cf. https://github.com/numixproject/numix-icon-theme/issues/428, so I think this issue can also be switched to hardcoded and can also be closed.

**Comment by dirtydancing** [comment]
Unless of course the icon names would be known, so that this could be checked to make sure.

@clauded Do you know what the relevant icon names are? Are these icons getting themed with different icon themes?

**Comment by wa4557** [comment]
No. Those are standard icons that can be themed. This are just leftover png icons in Numix
![unbenannt](https://cloud.githubusercontent.com/assets/6475757/7444470/cc6d325a-f184-11e4-8fa6-98314d62909e.png)

**Comment by dirtydancing** [comment]
I would disagree :). These were different icons the last time I checked. Are you sure that these are the same icons that Thunderbird is using?

**Comment by wa4557** [comment]
I don't use thunderbird, but look at `mail-inbox` those are the same icons :)

**Comment by dirtydancing** [comment]
Well, if you look very closely, they are not the same icons. E.g. for `mail-inbox` in Thunderbird the green arrow is slightly thinner and longer (surely they look almost identical). And e.g. `mail-sent` is different, too. I just checked again with `mail-inbox`, and this one is not picked up by Thunderbird.

**Comment by wa4557** [comment]
Right. Well it seems they are not themable. Really stupid, why are there some icons that can be themed and some cannot?

**Comment by dirtydancing** [comment]
Good question :). I have been wondering about that as well.

**Comment by dirtydancing** [comment]
I still believe that just as https://github.com/numixproject/numix-icon-theme/issues/428, this issue can be closed as `hardcoded` :)
