### ISSUE TITLE
Missing additional drivers icon

### ISSUE THREAD

**Issue by pgera** [numixproject/numix-icon-theme#160]
There's no icon for additional drivers (jockey) on Trusty for numix and numix circle. Numix-shine and Numix-utouch have icons though.

Numix:
![screenshot from 2014-08-05 21 51 55](https://cloud.githubusercontent.com/assets/5542855/3821418/cee6f11c-1d0c-11e4-8031-2e85c780c9b8.png)

Default:
![screenshot from 2014-08-05 21 52 33](https://cloud.githubusercontent.com/assets/5542855/3821419/d89442e6-1d0c-11e4-8b34-b79ac57012c5.png)

**Comment by bil-elmoussaoui** [comment]
This is working on Ubuntu 14.04.2 (unity too) also in eOS 0.3 Beta 2 both are based on ubuntu trusy.

**Comment by dirtydancing** [comment]
Ubuntu 14.10 here: using the current PPA versions of Numix and Numix-Circle, I can confirm that no icon is shown with Numix base as in the first screenshot above (in contrast, Numix-Circle has an icon).

The .desktop file for Additional Drivers contains the icon line `Icon=jockey` (as mentioned above, but not explicitly as the icon line).

![additional-drivers_desktop](https://cloud.githubusercontent.com/assets/7164227/7097345/092d0510-dfd5-11e4-8dd9-788182c03934.png)

Numix-Circle icon: 

![jockey](https://cloud.githubusercontent.com/assets/7164227/7097348/0b08340e-dfd5-11e4-947d-89ea79c94a8b.png)

I checked, and after adding a `jockey.svg` to Numix base, that icon was shown with Numix base.

Icon in Humanity (as displayed in the second screenshot above):

![jockey_humanity](https://cloud.githubusercontent.com/assets/7164227/7097421/c7b2a760-dfd5-11e4-92cc-ff34538eb77f.png)

In Numix base, I checked with size 48x48, not sure though which folder this would belong to (e.g. in Humanity, `jockey.svg` is located in `apps`).

**Comment by wa4557** [comment]
The problem is, that there is no fallback icon for `jockey.svg` in `gnome` or `hicolor` only in Humanity. So without adding `Humanity` to the inheritence line there is nothing `Numix` can do about that, except copying the icon from `Humanity` to base ?!

**Comment by dirtydancing** [comment]
Or alternatively add a Numix `jockey.svg` icon to base (in different sizes). Possibly even e.g. a symlink with the target (closer to the icon in Humanity) `categories/applications-electronics.svg` or (closer to the icon in Numix-Circle) `categories/applications-development.svg` might be suitable?

Except, it appears that the decision has been made to include `jockey.svg` in Numix-Circle, so I am not sure if this icon is supposed to be in Numix base as well (?).
