### ISSUE TITLE
Linux Mint Software Manager (mintinstall﻿) icons missing

### ISSUE THREAD

**Issue by jpmacedosilva** [numixproject/numix-icon-theme#166]
Hello,

I'm using Numix Icon Theme in Linux Mint 17 Xfce and the in Software Manager (mintinstall﻿) are missing category icons and applications icons.
I'm attaching screenshots with pictures demonstrating this issue.
![lm sm3](https://cloud.githubusercontent.com/assets/5247071/3943287/d076f7fc-2595-11e4-97f0-34a7bbe8ab4f.png)
![lm sm 2](https://cloud.githubusercontent.com/assets/5247071/3943289/d08bc11e-2595-11e4-8e7c-b7f32df266a7.png)
![lm software manager](https://cloud.githubusercontent.com/assets/5247071/3943288/d07c0bde-2595-11e4-8d49-096034772aaa.png)

**Comment by gilbertohasnofb** [comment]
I have the same problem, tested with two different notebooks running Linux Mint 17.1.

**Comment by bil-elmoussaoui** [comment]
@Foggalong  this is same issue as in Numix Circle [Mintinstall #1930](https://github.com/numixproject/numix-icon-theme-circle/issues/1930) 
@gilbertohasnofb can you proive a screenshot using an other icon theme? (not the default one)

**Comment by Foggalong** [comment]
@bil-elmoussaoui this issue is slightly different from what iI can see because it also shows that the app icons are broken.

**Comment by wa4557** [comment]
I think this is a duplicate too, because here all the `applications-*` from circle aren't shown. The icons where these icons are only in base are ok. That's the same thing as in #1930

**Comment by bil-elmoussaoui** [comment]
We can't definitely do nothing about this. The Linux mint software manager is quite bad at dealing with freedesktop standards. 
If an application icon is not shown while the others are working correctly it's an upstream issue for me.

The categories icons, are already on Numix Circle/Square.

**Comment by Foggalong** [comment]
Do we know if this is even still an issue? I've not used Mint in years and don't currently have hardware beefy enough to set up a VM

**Comment by Foggalong** [comment]
Just checked and this issue is now fixed in even the oldest supported version of Mint (and mintinstall). Fixing bugs: sometimes you just have to wait :joy:
