### ISSUE TITLE
Pamac icons needed

### ISSUE THREAD

**Issue by sergioad** [numixproject/numix-icon-theme#184]
Numix icons are needed for Pamac's package icons. These are listed, with their relevant icon, below:

* [x] ![package-available](https://cloud.githubusercontent.com/assets/5375145/4365837/1f5e9f38-42b4-11e4-810e-14f062fe71d4.png) package-avaliable
* [x] ![package-available-locked](https://cloud.githubusercontent.com/assets/5375145/4365838/1f69c8b8-42b4-11e4-972f-307887f70bee.png) package-avaliable-locked
* [x] ![package-available-new](https://cloud.githubusercontent.com/assets/5375145/4365846/1f8aada8-42b4-11e4-9b3d-b752625544fc.png) package-available-new (symlink to package-new)
* [x] ![package-broken](https://cloud.githubusercontent.com/assets/5375145/4365839/1f6cce96-42b4-11e4-9d67-0f92b5a2de28.png) package-broken
* [x] ![package-downgrade](https://cloud.githubusercontent.com/assets/5375145/4365840/1f71c61c-42b4-11e4-86dd-0a4e50badd56.png) package-downgrade
* [x] ![package-install](https://cloud.githubusercontent.com/assets/5375145/4365841/1f7416a6-42b4-11e4-98f4-4d9bc8b45be9.png) package-install
* [x] ![package-installed-locked](https://cloud.githubusercontent.com/assets/5375145/4365842/1f77d5ca-42b4-11e4-9b86-3f37e7e59df5.png) package-installed-locked
* [x] ![package-installed-outdated](https://cloud.githubusercontent.com/assets/5375145/4365844/1f81a92e-42b4-11e4-88f2-ab51daa636db.png) package-installed-outdated
* [x] ![package-installed-updated](https://cloud.githubusercontent.com/assets/5375145/4365843/1f7f1dc6-42b4-11e4-9b05-dc1fd34e6a81.png) package-installed-updated
* [x] ![package-new](https://cloud.githubusercontent.com/assets/5375145/4365846/1f8aada8-42b4-11e4-9b3d-b752625544fc.png) package-new
* [x] ![package-purge](https://cloud.githubusercontent.com/assets/5375145/4365845/1f88ab66-42b4-11e4-8664-936f55cc993c.png) package-purge
* [x] ![package-reinstall](https://cloud.githubusercontent.com/assets/5375145/4365847/1f8cc11a-42b4-11e4-88ec-34977f23d04e.png) package-reinstall
* [x] ![package-remove](https://cloud.githubusercontent.com/assets/5375145/4365848/1f92a846-42b4-11e4-9e95-8c82bf097e0f.png) package-remove
* [ ] ![package-supported](https://cloud.githubusercontent.com/assets/5375145/4365849/1f92c024-42b4-11e4-8f7a-65e4c0373cab.png) package-supported
* [x] ![package-upgrade](https://cloud.githubusercontent.com/assets/5375145/4365850/1fa8f286-42b4-11e4-8584-c5b5ef4a0241.png) package-upgrade
* [x] ![pamac-add](https://cloud.githubusercontent.com/assets/5375145/4365853/3b45df4a-42b4-11e4-9eef-0e5f0678ba17.png) pamac-add
* [x] ![pamac-cleanup](https://cloud.githubusercontent.com/assets/5375145/4365854/3b4c3336-42b4-11e4-8256-beca0020bb72.png) pamac-cleanup
* [x] ![pamac-delete](https://cloud.githubusercontent.com/assets/5375145/4365855/3b4f828e-42b4-11e4-894e-3e4a01922155.png) pamac-delete
* [x] ![pamac-download](https://cloud.githubusercontent.com/assets/5375145/4365856/3b4f70f0-42b4-11e4-9c77-5daf0ad0b253.png) pamac-download
* [x] ![pamac-refresh](https://cloud.githubusercontent.com/assets/5375145/4365858/3b5805da-42b4-11e4-80df-fa3c35d77c33.png) pamac-refresh
* [x] ![pamac-search](https://cloud.githubusercontent.com/assets/5375145/4365859/3b58bc32-42b4-11e4-847b-0fbeb4439183.png) pamac-search
* [x] ![pamac-setup](https://cloud.githubusercontent.com/assets/5375145/4365857/3b56edbc-42b4-11e4-931d-0661a24e1448.png) pamac-setup
* [x] ![pamac-update](https://cloud.githubusercontent.com/assets/5375145/4365860/3b5c96cc-42b4-11e4-9f23-46fa747a4b60.png) pamac-update
* [x] ![pamac-wait](https://cloud.githubusercontent.com/assets/5375145/4365861/3b6760b6-42b4-11e4-859d-3b12824e12bd.png) pamac-wait

**Comment by bil-elmoussaoui** [comment]
Some of the icons do exists, they're in ```/actions``` folder 
```
package-downgrade.svg
package-install.svg
package-purge.svg
package-reinstall.svg
package-remove.svg
package-upgrade.svg
```

**Comment by Foggalong** [comment]
I need to turn this question into a checkbox list like the others.

**Comment by sergioad** [comment]
How can be done the change?

**Comment by bil-elmoussaoui** [comment]
Add this at the beginning of each line ``` - [ ] ```

**Comment by Foggalong** [comment]
@sergioad @bil-elmoussaoui I've cleaned up the original issues formatting and removed all the off-topic stuff about `application-menu.svg` - that needs to be addressed in another issue report.

**Comment by sergioad** [comment]
Ok

**Comment by wa4557** [comment]
@sergioad Would it be ok to symlink the second part of those icons to the first part? Are they used in different places or alongside the others? At least for me they seem to serve the same purpose

**Comment by sergioad** [comment]
@wa4557 the second part starting with pamac-add are used on the package transaction dialogs, for example when a package is being downloaded removed configured or updated, even when the transaction is  waiting to another pacman transaction so should be diferent being status icons basically

**Comment by wa4557** [comment]
I see, so they are used in cases like this, aren't they?
![unbenannt](https://cloud.githubusercontent.com/assets/6475757/8039882/e1779dbc-0e0c-11e5-8640-f81f21ca119e.png)

**Comment by sergioad** [comment]
Yes

**Comment by wa4557** [comment]
@Foggalong Please reopen, I'm not finished yet :) (Bad idea to put the issue number in commit name...)

**Comment by Foggalong** [comment]
It wasn't the commit name, it was that the body of the pull request contained "fix #546" - silly GitHub autodetection :)

**Comment by bil-elmoussaoui** [comment]
@Foggalong can you add ```package-available-new.svg``` it's used in elementary os :P

**Comment by Foggalong** [comment]
Do you have the default icon, preferably the same resolution as the others in the list so I can include it :)

**Comment by Foggalong** [comment]
Or is it just the same as `package-new`?

**Comment by bil-elmoussaoui** [comment]
Yeah it's the same as package-new, it's looks like that, so can be symlinked to ```package-new```
![capture du 2015-06-09 23 13 19](https://cloud.githubusercontent.com/assets/7660997/8069774/1f268e2a-0efd-11e5-8b0b-bece80f18e31.png)

**Comment by Foggalong** [comment]
Awesome :+1:

**Comment by khurshid-alam** [comment]
Which commit exactly fixed this? It seems synaptic still uses old-icons.

**Comment by Foggalong** [comment]
It should be in 26ada7c?

**Comment by khurshid-alam** [comment]
That was only for `package_supported.svg`

**Comment by Foggalong** [comment]
That's super weird. @wa4557 any idea what's happened here?
