### ISSUE TITLE
Icons missed on network settings

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-icon-theme#189]
Hello, i've got a problem on the ubuntu 14.04 using the numix theme and the numix cercle as an icon theme

the issue : 

![selection_001](https://cloud.githubusercontent.com/assets/7660997/4546941/54be78a2-4e48-11e4-81e0-6bd7edd69cf5.png)

some icons are not themed, or i dont know.. 
Thanks

**Comment by bil-elmoussaoui** [comment]
The missing icon is related to #127 
This icon must be in status : 16x16,22x22,24x24,32x32,48x48,256x256

**Comment by wa4557** [comment]
@bil-elmoussaoui I'm not sure about the status thing. I think this icon should be in devices. Not in status
