### ISSUE TITLE
Light, Lighter, Dark, Darker symbols themes

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-icon-theme#201]
The last numix theme with numix circle icon(not the light one). i'm using nautilus as a file manager, when i activate the location bar as you see in the picture below , two icons are gray? they must be black or something darker ?

![capture du 2014-10-15 23 32 04](https://cloud.githubusercontent.com/assets/7660997/4654080/83cc7434-54b3-11e4-9266-874e9c308656.png)
 
Thank you

**Comment by bil-elmoussaoui** [comment]
I guess this was a Nautilus issue, as i'm not having this anymore on Ubuntu Gnome 15.04 with gnome 3.16 and Nautilus 3.16.1 with the ppa version of Numix GTK and numix base. Can you confirm this @dirtydancing ?
![screenshot from 2015-05-23 01-19-52](https://cloud.githubusercontent.com/assets/7660997/7781176/f25d18ee-00e9-11e5-96d6-3e6485410976.png)

**Comment by dirtydancing** [comment]
Yes, I can confirm that the icons in question are now visible. Might still be somewhat light-coloured, but definitely well visible. This might as well not be an issue of Nautilus, but rather of GTK (?). Anyways, here is a screenshot, Arch with Nautilus 3.16.2, Numix GTK and Numix base with latest version from GitHub:

![nautilus_3-16-2](https://cloud.githubusercontent.com/assets/7164227/7788948/907b692a-024f-11e5-98a1-1c2b49b78134.png)

**Comment by bil-elmoussaoui** [comment]
I guess those icons are in the scalable folder, and this is fixed since the release of GTK 3.16! So those icons are still missed in the numix base

**Comment by dirtydancing** [comment]
Well, since they are showing up (and better visible with GTK 3.16), why are they missing in numix base?

**Comment by dirtydancing** [comment]
These two icons look like `folder-symbolic.svg` from `scalable/places` and `edit-clear-symbolic.svg` from ` scalable/actions`. As I figure that these icons can be colour-themed by the GTK theme, I still think this is a GTK theme issue after all.

**Comment by bil-elmoussaoui** [comment]
Ah, i had no idea that is possible to theme those icons using gtk theme. If so, we can close this?

**Comment by dirtydancing** [comment]
As far as I can tell, these icons are colour-themeable by the GTK theme because they are "symbolic"-named. And yes, I believe this issue can be closed in Numix base.

**Comment by bil-elmoussaoui** [comment]
Well, i'm closing this then. i will wait until the new release of Numix gtk theme and see if this will be fixed or not
