### ISSUE TITLE
Folders for "Folder-Color"

### ISSUE THREAD

**Issue by Foggalong** [numixproject/numix-icon-theme#204]
See [#5](https://github.com/numixproject/numix-folders/issues/5) for more info :)

**Comment by bil-elmoussaoui** [comment]
You can close this one ;)

**Comment by Foggalong** [comment]
The symlinks for Folder-Color aren't in yet, just the coloured folders themselves.

**Comment by costales** [comment]
>
> The symlinks for Folder-Color aren't in yet, just the coloured folders
> themselves.


Thanks a lot Joshua!!
Please, remember that Folder Color needs them in the scalable folder
(symlinks or icons). Until that, Folder Color will not recognized the theme
;)
Cheers!

**Comment by Foggalong** [comment]
Um, they can't go in /scalable because they're not scalable icons. Each one is made for a specific size. The Folder Color documentation says to put it in the specific sizes too :/

**Comment by costales** [comment]
Costales

On 02/03/15 19:31, Joshua Fogg wrote:
> they can't go in /scalable because they're not scalable icons

You're right, but could you create a syslink from scalable to 48x48? :)


> The Folder Color documentation says to put it in the specific sizes too :/

"too" as extended theme :) I'll try the branch just now and I'll tell 
you something :)

**Comment by costales** [comment]
Damn it! The README file was obsolete :( I forget to remove one line in 
my last edition:
     http://bazaar.launchpad.net/~costales/folder-color/trunk/revision/169

I confirm that Folder Color needs a syslink in the "scalable" folder. 
Could be possible to create them?

I'm so sorry Joshua! :$
Costales

**Comment by Foggalong** [comment]
But why is it looking in scalable at all? Every file manager I've encountered uses the fixed sizes directory for the main folder icons. The only ones that go in scalable are the ones are the monochrome 16px sidebar icons!

**Comment by costales** [comment]
You're right :$ I don't know why I set "scalable" as base (maybe I saw 
something a few months ago).
Please, don't change anything, give me a few days, I'll think on it. I'm 
so sorry :(
Costales

**Comment by Foggalong** [comment]
It's alright, just adding coloured folders support has been ~2 weeks of work so it's a lot of stuff to undo. Thinking about it would be appreciated

**Comment by costales** [comment]
After the help from Joshua by PM, I'll adapt Folder Color as it has to 
be :) I'll tell you the release here.

Thanks a lot Joshua |o/

Costales

**Comment by costales** [comment]
Hi! I'll release Folder Color tomorrow with support to Numix :)

I was looking into the [Numix PPA](https://launchpad.net/~numix/+archive/ubuntu/ppa/+packages?field.name_filter=icon-theme&field.status_filter=published&field.series_filter=trusty) and the new icons aren't in there yet: 

FYI I updated the [README](http://bazaar.launchpad.net/~costales/folder-color/trunk/view/head:/README) file. The custom icons will have another name (you're not using it in your branch, then don't worry).

Cheers!

**Comment by costales** [comment]
Released now! :D Cheers!

**Comment by bil-elmoussaoui** [comment]
@costales its still not working; i'm using the last version of Numix Base theme, and the last version of Folder color too.
![selection_001](https://cloud.githubusercontent.com/assets/7660997/6546018/5c0d2eba-c5a2-11e4-82fe-54d071de2f9d.png)

**Comment by costales** [comment]
Let's take a look :)
Could you give me the URL where you download Numix?
Is folder color the 0.0.50? apt
Which file browser are you using?
Thanks in advance!

**Comment by bil-elmoussaoui** [comment]
I'm using the 0.0.51; and i installed the Numix base 0.3+249~201503012031~ubuntu14.04.1 from the ppa :) For the file browser i'm using Nautilus

**Comment by costales** [comment]
Yes, the Numix icons aren't in the PPA yet. From the package:
https://launchpad.net/~numix/+archive/ubuntu/ppa/+files/numix-icon-theme_0.3%2B249%7E201503012031%7Eubuntu14.04.1.tar.gz

costales@netbook:~/Desktop/numix-icon-theme-0.3+249~201503012031~ubuntu14.04.1$
find . -name "folder_color*.svg"
costales@netbook:~/Desktop/numix-icon-theme-0.3+249~201503012031~ubuntu14.04.1$



@Joshua: Could you confirm us when the icons will arrive to the PPA? :)

Cheers!

**Comment by Foggalong** [comment]
"@Joshua" isn't me :P

But no, the icons should have landed in the PPA by now so this isn't a problem on our end

**Comment by costales** [comment]
@bil-elmoussaoui You have to see this when the PPA will be updated:
https://www.youtube.com/watch?v=BAwEpRgI4YE
Tell me if not ;) Cheers!

**Comment by bil-elmoussaoui** [comment]
@costales the last version of Numix theme or Folder color ? Thanks!

**Comment by costales** [comment]
@bil-elmoussaoui The last versions of both of them :)
Folder Color 0.0.51 is in the PPA now. Numix will be ASAP (I think) :) Cheers!

**Comment by dirtydancing** [comment]
Please cf. this issue thread: https://github.com/numixproject/numix-folders/issues/30 and specifically my comment at https://github.com/numixproject/numix-folders/issues/30#issuecomment-78165982
