### ISSUE TITLE
Battery icon: remove battery-good-charging.svg from devices directories

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-icon-theme#206]
Hi, question: is there a reason why currently there is a symlink/icon (depending on size) named `battery-good-charging.svg` in all of the fixed size `devices` directories? There is an icon named `battery.svg` in devices which belongs there.

Screenshot from `48x48/devices`:

![batter-good-charging](https://cloud.githubusercontent.com/assets/7164227/4689078/a1147d5e-56a5-11e4-8db3-99332aff8acf.png)

`battery-good-charging.svg` is not a device icon, but, if at all (that would be a different issue) a status icon. Moreover, the design is that of a "neutral" battery and does not indicate a charging status (flash symbol, battery filled to a certain height).

So, unless there is a specific reason for this icon in `devices`, I would suggest to remove it.

Additional information: In Ubuntu 14.04 LTS, these icons are used e.g. for the "Energy Statistics" window which is not in the panel, but can be accessed when clicking on the battery symbol in the panel power dropdown window. Here are two screenshots, the first one showing the (incorrect) Numix `battery-good-charging.svg`, the second one showing the GNOME fallback icon for `battery-full-charging.svg`.

![energy_1](https://cloud.githubusercontent.com/assets/7164227/4689117/4e10b486-56a7-11e4-969b-e64a7118e56e.png)

![energy_2](https://cloud.githubusercontent.com/assets/7164227/4689120/51c6142c-56a7-11e4-85f3-447f21c0e540.png)

This observation actually goes back to an observation in this former comment https://github.com/numixproject/numix-icon-theme/issues/107#issuecomment-52829244

**Comment by Foggalong** [comment]
What different icon names to this have? Because of where it's displayed in the menus it falls within our "devices category" but if it is supposed to take on multiple appearances based on the status of the battery we should do them too :)

**Comment by dirtydancing** [comment]
I see. I will have to look into this, to see if this might bring up any conflicts with the other battery status icons. Basically, these icons should be named just like the "symbolic"-named icons, just without the "symbolic"-part. I will get back to you on this (might be a while, though, just let me know when this should be becoming more urgent).

**Comment by dirtydancing** [comment]
Update: I have created this branch to check this: https://github.com/dirtydancing/numix-icon-theme/tree/battery-device-status

@wa4557 In case you are interested to check this branch against your Ubuntu installation: this is about the battery icons showing in "Energy Statistics" in Ubuntu (you get there by e.g. by clicking the battery icon in the dropdown menu of the panel). This is somewhat unusual, because with the approach presented below, there are symlinks in Numix with targets in Numix-Light. This actually means "dark icons in a light icons theme", and so far in this special battery icon case it works just fine :-)

These are "device status" icons picked up by "Energy Statistics" in Ubuntu, and in gnome icon theme they are placed in the `status` directory:

![gnome-icon-theme](https://cloud.githubusercontent.com/assets/7164227/7101527/ca18f5c6-e05d-11e4-8a26-d9f966ff9716.png)

The most elegant approach to this that I have come across so far is to create symlinks to the already existing battery status icons in Numix-Light (dark icons).

This would mean going from this current battery status icon overview:

![battery-status-icons_20150327](https://cloud.githubusercontent.com/assets/7164227/7101529/fff7d5a4-e05d-11e4-8518-52a5f577e4b7.png)

to this draft one:

![battery-status-icons_20150411](https://cloud.githubusercontent.com/assets/7164227/7101530/05b43af0-e05e-11e4-98af-152449184314.png)

First, I removed `battery-good-charging.svg` from the devices directories, cf. this issue.

Second, I removed the current symlinks `battery-caution.svg` and `battery-low.svg` from the status directories, cf. https://github.com/numixproject/numix-icon-theme/issues/236.

Third, I added the new symlinks in the right column of the draft overview. This was only needed in Numix, as my preliminary testing showed that Numix-Light picks these icons up as well, because Numix-Light inherits from Numix.

E.g., in current daily Ubuntu 15.04, this means going from here (gnome fallback battery icon):

![ubuntu1504_numix-circle_ppa](https://cloud.githubusercontent.com/assets/7164227/7101553/d20a4072-e05e-11e4-80fc-2c4d8ec2843d.png)

to here (Numix "device status" battery icon):

![ubuntu1504_numix-circle_numix-battery-device-status](https://cloud.githubusercontent.com/assets/7164227/7101554/df284ee8-e05e-11e4-9918-be99d3c0e151.png)

In addition, adding a symlink `ac-adapter.svg` with the target `ac-adapter-symbolic.svg` in Numix-Light will theme the AC icon in this overview correspondingly (this would be a separate follow-up issue, so I have not included this in the battery-device-status branch):

![ubuntu1504_ac](https://cloud.githubusercontent.com/assets/7164227/7101585/deeffb46-e05f-11e4-9987-9254e5184d81.png)

I am not sure why in daily Ubuntu 15.04, the ac-adapter icon is not centered (it was centered in Ubuntu 14.10). This might be because the icon size of that icon is not 24x24, but rather 15x24. This might be a part of that follow-up issue then. For now, I figure you get the idea :-)

@Foggalong What do you make of this approach?

**Comment by wa4557** [comment]
@dirtydancing Sure thing. At a first glance I'd say however that I like the fallback icon better :P

**Comment by dirtydancing** [comment]
Haha, the fallback is completely inconsistent with the other Numix icons, though :-) Of course, another possibility would be to create a separate set of "battery device status" icons just for this purpose. The default size that gets picked up here is 32x32, so with the current approach of using existing 24x24 (dark) battery status icons, they get scaled somewhat. Anyways, once we know that these icons do not cause conflicts somewhere else, the icon design itself could be fine tuned (per default, these are not monochrome icons).

**Comment by dirtydancing** [comment]
And btw, currently these icons are displayed very inconsistently: mostly the gnome fallback icons are shown, but e.g. for `battery-good-charging.svg` it is the blue icon from above that has not really got much to do with "charging", but rather is plain battery icon, and for `battery-caution.svg` and `battery-low.svg` the light status icons from Numix are shown, which are hardly visible on the light background.

**Comment by wa4557** [comment]
@dirtydancing Agreed, they have to be redesigned for sure. But I think they do belong to `32x32/devices` and I don't think they will interfere with the status icons because of their different size. I'll try something...

**Comment by dirtydancing** [comment]
@wa4557 Great! Looking forward to what you will come up with...

I would not be so sure that the size alone will prevent conflicts (esp. if such icons should be located in the `scalable` directory), I think it is rather the different naming. But I have not seen those gnome fallback icons being displayed in any panel either, so that should be fine.

btw, the three blue-coloured icon names in the right column of the draft overview do not exist in the gnome fallback icons, I am not sure why, so in order to not forget that, I chose a different colour for those.

`battery-empty.svg` and `battery-empty-charging.svg` are handled differently here from the fixed size directory status icons in the panel: apparently they only show up at 0%, so they will hardly ever be seen. That is a matter of the percentage thresholds, and those might change at some point, so for completeness it makes sense to include them.

All this being said, these "device status" icons would fit into either the `status` or the `devices` directories, so `32x32/devices` should be just fine.

And as a side note for the completeness of the three icons being displayed: `ac-adapter.svg` would surely belong into `devices`.

**Comment by wa4557** [comment]
Ok I have made the icons for the battery icons They are definitely better than the monochrome ones :)

https://github.com/wa4557/numix-icon-theme/tree/batterydevice
![bildschirmfoto 2015-04-11 19 47 15](https://cloud.githubusercontent.com/assets/6475757/7102568/329ca07c-e084-11e4-9ad8-7f8cceb84d71.png)
I have to come up with something for `ac-adapter.svg` though

I think it's just fine to have them in `devices`. On my Ubuntu machine this works, and status icons and the se new icons are shown alongside the other ones.

**Comment by dirtydancing** [comment]
Sweet! Nice enhancement.

`battery-caution.svg` and `battery-caution-charging.svg` are missing, though. So maybe somewhat smaller steps inbetween full-good-low-caution-empty?

And for the toned down blue colour icons, these seem to have a slight shift to the bottom, exposing a little more of the battery head, cf. screenshot:

![battery-empty](https://cloud.githubusercontent.com/assets/7164227/7102643/be36c674-e086-11e4-93d3-a9092de31818.png)

And I guess it is fine to have a `battery-missing.svg` here in addition to the already existing `battery-missing.svg` in the fixed size status directories 16x16, 22x22, 24x24. I have not seen this icon in action so far, and if a problem should come up, that will be easy to address.

**Comment by wa4557** [comment]
Ok I'll to this tomorrow or later this evening :)

**Comment by dirtydancing** [comment]
One more thing: `battery-full-charged.svg` should not be a symlink to `battery-full-charging.svg` because that would be an inconsistency with the battery panel status icons. They have a check mark design for `battery-full-charged.svg`. Maybe it is possible to implement s.th. similar with these icons?

**Comment by dirtydancing** [comment]
Updated battery icon draft overview:

![battery-status-icons_20150411_2](https://cloud.githubusercontent.com/assets/7164227/7102719/dc1da2cc-e089-11e4-8370-988087ad3877.png)

**Comment by dirtydancing** [comment]
Confirmed on Ubuntu 14.10 that the proposed battery device status icons in `32x32/devices` are picked up for the "Energy Statistics" and are not interfering with the panel status icons. Looking very good! :-)

**Comment by Foggalong** [comment]
The AC icon not being centered is usually caused by the canvas not being square

**Comment by dirtydancing** [comment]
@Foggalong Ah, suspected so, thanks for confirming :)

@wa4557 When you have another look at the proposed set of battery status device icons, here is some more visual feedback: the height of the bar in the battery is a little hard to make out in practice on my machine, esp. for the charging icons with the flash. Possibly there is a way to add some more contrast?

**Comment by wa4557** [comment]
Done. The checkmark looks not good however, so I'll keep it as it is now. The charging symbol also makes sense because it shows that it is still plugged in + these icons are somehow independent from the ones in 16, 22 and 24 so a little bit of inconsistency is not too bad imo :)
I'll think about something for `ac-adapter.svg` and then I'll create a pull request

**Comment by dirtydancing** [comment]
Cool! Much better now :) And agreed that the checkmark would not look good, and that it is just fine to keep the charging symbol for `battery-full-charged.svg`.

So once again, here is an updated battery icon draft overview, including also the notification icons:

![battery-status-icons_20150411_3](https://cloud.githubusercontent.com/assets/7164227/7103338/54ab2530-e0a2-11e4-86fa-cfeb3051dc85.png)
