### ISSUE TITLE
Battery icon 10: in fixed size directories 16, 22 and 24, delete the 2 symlinks "battery-caution.svg" and "battery-low.svg"

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-icon-theme#236]
In continuation of https://github.com/numixproject/numix-icon-theme/issues/226 and https://github.com/numixproject/numix-icon-theme/issues/107, step 10:

In fixed size directories 16, 22 and 24, delete the 2 symlinks `battery-caution.svg` and `battery-low.svg`.

These 2 symlinks are not needed for the panel, and in this context they only cause confusion.

![battery-status-icons_20141028_carried-over_10](https://cloud.githubusercontent.com/assets/7164227/4858786/fcdf1a76-60e2-11e4-806a-caf9943920cb.png)

Now, these are not outdated icon names. They are just used for a different purpose, at least in Ubuntu 14.04 LTS/Unity: They are NOT used for the panel (monochrome), but rather e.g. for the gnome-power-statistics window of the gnome-power-manager (Ubuntu). Ubuntu default (just as Numix base) currently is using the GNOME fallback icon theme here.

Screenshot for "full-charging" status, with current Numix-Circle, please note that although this is a device information list, for Ac adapter, a static device icon is used, whereas for Laptop battery, dynamic status icons are used:

![statistics_full-charging](https://cloud.githubusercontent.com/assets/7164227/4858889/2a8f72b2-60e4-11e4-8924-4f5090462091.png)

With this, it becomes apparent that the current symlinks `battery-caution.svg` and `battery-low.svg` actually are visually unfitting for this purpose. Screenshot with current Numix-Circle for "battery-low" status (icon is hardly visible):

![statistics_low](https://cloud.githubusercontent.com/assets/7164227/4858901/48781252-60e4-11e4-8a59-abc527df4788.png)

If this series of battery icons (NOT "percentage"-named, NOT "symbolic"-named) is used, then there would have to be a consistent and encompassing set (empty to full-charged), not only the "stand-alone" icons `battery-caution.svg` and `battery-low.svg`. Again, that would be a different issue, so I am leaving it at that for this issue.

Side note: At the same time, this also shows that https://github.com/numixproject/numix-icon-theme/issues/206 is still valid and that `battery-good-charging.svg` should be removed from the `devices` directories (not a panel issue, though).

This step 10 concludes the mini-series of step-by-step issues. With steps 1-10, present Numix base is modified to arrive at the current battery status icons diagram:

![battery-status-icons_20141028_end](https://cloud.githubusercontent.com/assets/7164227/4858807/397f9ee2-60e3-11e4-98cd-22af16ff6f20.png)

**Comment by ragazenta** [comment]
Now in xfce-power-manager 1.5.x, non -symbolic suffix filename is used. So these files are needed again:

    battery-caution-charging.svg
    battery-caution.svg
    battery-empty-charging.svg
    battery-empty.svg
    battery-full-charged.svg
    battery-full-charging.svg
    battery-full.svg
    battery-good-charging.svg
    battery-good.svg
    battery-low-charging.svg
    battery-low.svg

**Comment by Foggalong** [comment]
@ragazenta If those are icons that are needed, please file a [new request](https://github.com/numixproject/numix-icon-theme/issues/new)
