### ISSUE TITLE
Calibre icon-theme?

### ISSUE THREAD

**Issue by andia89** [numixproject/numix-icon-theme#239]
Just a short question: Is anyone interested in an icon theme for calibre? I did not create any icon by myself, I just scanned the available icons and used the most appropriate ones and converted them to png. I'm afraid a few icons are still missing since there is no corresponding icon in the theme, but the majority is there.
Looks pretty cool imo. If anyone is interested let me know!

Ciao

**Comment by ChuckDaniels87** [comment]
I've found this:
http://www.mobileread.com/forums/showthread.php?t=151397

And this:
http://manual.calibre-ebook.com/customize.html#overriding-icons-templates-et-cetera

Maybe could be useful.

**Comment by ChuckDaniels87** [comment]
Just ignore my last message. :-1:

**Comment by leoheck** [comment]
Hi,  calibre uses icons from its own folders.. ``/opt/calibre/resources/images``

I found this:
http://numixcalibre.deviantart.com/art/Numix-theme-for-calibre-1-01-502183176

I wondering we have all calibre icons in Numix, I could create a script like ``hardcode-fixer`` for calibre, to simlink all Calibre icons to the Numix replacement. This could be a workaround until Calibre developer accepts the linux standards.

What do you think? I will love to have icon with numix icons.

Calibre resourses:
![screenshot from 2016-08-14 10-21-27](https://cloud.githubusercontent.com/assets/1277920/17649324/ee210ad4-6208-11e6-80ba-450eff9eb933.png)

**Comment by bil-elmoussaoui** [comment]
We tried to do something like this a year ago. But it's hard to choose
which icon size to use.. the best thing is to have a repo with calibre
theme that can be installed as other calibre icon themes. If calibre ever
respects freedesktop standards we can just copy those icons back to Numix
base(the same as with LibreOffice and other applications)

**Comment by ChuckDaniels87** [comment]
> ...the best thing is to have a repo with calibre theme that can be installed as other calibre icon themes.
It would be really nice to have it. :+1:

> If calibre ever respects freedesktop standards [...]
I really doubt that they will change this any time soon, you can check [their answer](https://bugs.launchpad.net/calibre/+bug/1390949/comments/1).

**Comment by leoheck** [comment]
Ok totally agree with you @bil-elmoussaoui, I can create a repo called something like numix-calibre, but I think you can create in numixproject to keep things related. So we can try to start something there. We can start with the stuff already present in the deviantart. What do you think?

**Comment by wa4557** [comment]
There are still a lot of Icons missing that needs to be designed (the Calibre icon theme you linked really uses a lot of inappropriate Icons). 

Another Problem is that Calibre needs png Icons and cannot use svg Icons. 

If you open a Repo and put together a list of missing Icons we can work on making this happen though :)

**Comment by leoheck** [comment]
@wa4557, I agree, this themes should not be circle. 
Calibre icons: https://github.com/kovidgoyal/calibre/tree/master/imgsrc

**Comment by leoheck** [comment]
I made this, using some numix-icons to test. I just picked up some icons that match with the menus. Take a look:

https://github.com/leoheck/numix-calibre

 We can fork calibre to improve the support. Its guis are some python files and can be easly changed.
