### ISSUE TITLE
user-trash-full-symbolic.svg not showing in Ubuntu 14.10 with default Ambiance GTK theme

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-icon-theme#240]
I have encountered a rather strange phenomenon in default Nautilus File Manager (3.10.1-0ubuntu15) in Ubuntu 14.10 with default Ambiance GTK theme (same for Radiance GTK theme): when the rubbish bin is full, the symbolic red Numix icon is very hard to see, as a light grey colour is displayed on a light grey background. This does not happen with the Numix GTK theme, though.

Screenshot with Numix GTK theme:

![trash1](https://cloud.githubusercontent.com/assets/7164227/5007772/a573aef6-6a55-11e4-8344-24d1dcafc688.png)

Screenshot with Ambiance GTK theme (rubbish bin marked so this can be seen at all):

![trash2](https://cloud.githubusercontent.com/assets/7164227/5007776/acc1060e-6a55-11e4-8af0-f7bba649f170.png)

On the other hand, with Ambiance GTK theme, the user-trash-full-symbolic.svg is showing correctly for other icon themes, such as for the default Ubuntu icon theme and for Moka/Faba icon theme.

So this might not be a bug anywhere, as the respective "defaults" are working with each other. Still, this is the first time that I am noticing that the Numix icon theme is not playing well with the Ubuntu default Ambiance GTK theme, so I am filing this issue here.

Possibly there is an "easy" way that this can be addressed from Numix's side?

I have found a "workaround" by modifying the icon in question: e.g., if it looks like this, it is displayed with Ambiance GTK theme as well. So apparently there can be colours in the icons, and this seems to relate to the specific red colour that the Numix icon is currently using (?):

![trash3b](https://cloud.githubusercontent.com/assets/7164227/5007806/eedb4ee6-6a55-11e4-9807-058335cccee0.png)

![trash3a](https://cloud.githubusercontent.com/assets/7164227/5007800/ea24af64-6a55-11e4-968a-d41084c70ade.png)

**Comment by dirtydancing** [comment]
Bug report filed against Ambiance GTK theme (ubuntu-themes): https://bugs.launchpad.net/ubuntu/+source/ubuntu-themes/+bug/1426774

**Comment by dirtydancing** [comment]
Quick update: by now, this problem has been qualified as a papercut bug in Ubuntu, cf. https://bugs.launchpad.net/ubuntu/+source/ubuntu-themes/+bug/1426774

I would suggest to still keep this bug open in Numix base for the time being.

@satya164 Do you happen to have an idea what is going on here with Ambiance GTK theme? Possibly this is s.th. to also watch out for in Numix GTK theme (?).

As far as I can tell, this is the only instance of the combination of Numix(-Circle) icon theme and Ubuntu default Ambiance GTK theme not properly working together in Ubuntu.

![1_ambiance-gtk](https://cloud.githubusercontent.com/assets/7164227/6448122/06ef43e8-c118-11e4-89bd-0201742ef55b.png)

**Comment by Foggalong** [comment]
See the pull request for more info on why this is a wontfix
