### ISSUE TITLE
WICD Panel Icons

### ISSUE THREAD

**Issue by sonal-keshav** [numixproject/numix-icon-theme#246]
The default panel icons for WICD are pretty ugly. They are .pngs. located in usr/share/pixmaps/wicd
Is it possible to have them replaced with at least the default network manager icons? 
![e33e19fa-730c-11e4-9344-a75a5ed9a7b9](https://cloud.githubusercontent.com/assets/2701579/5207890/c2cadcae-757c-11e4-9302-d82603961678.png)

**Comment by Foggalong** [comment]
+1

**Comment by wa4557** [comment]
I'll do that
