### ISSUE TITLE
Ubuntu notification icons - volume

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-icon-theme#248]
Currently, there are no Numix Base icons for the notifictions in Ubuntu (NotifyOSD), cf. overview at https://wiki.ubuntu.com/NotifyOSD#Icon. I would like to suggest to add these.

These icons per default are of size 48. In Ubuntu (14.10), they are located per default in `usr/share/notify-osd/icons/gnome/scalable/status`. So I would suggest to create a new folder in Numix Base (and correspondingly in index.theme) named `48x48/notifications`.

A good place to start this would be the volume notification icons. I have tested this with the current Numix Base 22x22 .svg volume icons (renamed and added to an extra folder `22x22/notifications` for testing purposes), and this has worked just fine.

The relevant icons here are
`notification-audio-volume-high.svg`
`notification-audio-volume-low.svg`
`notification-audio-volume-medium.svg`
`notification-audio-volume-muted.svg`
`notification-audio-volume-off.svg`

Volume icon overview screenshot:
![notification-icons_volume](https://cloud.githubusercontent.com/assets/7164227/5299056/307d2710-7bc3-11e4-849f-6b52798656dd.png)

Comparative screenshots of the Ubuntu default and the Numix notification when changing the volume:

Ubuntu default as of present:
![notification_default](https://cloud.githubusercontent.com/assets/7164227/5298996/bc731fa0-7bc2-11e4-9159-7940f95c69e5.png)

With Numix volume notification icon:
![notification_numix](https://cloud.githubusercontent.com/assets/7164227/5299005/c10634a8-7bc2-11e4-83b7-b02c29a64dcf.png)

**Comment by dirtydancing** [comment]
Mobile broadband added: https://github.com/numixproject/numix-icon-theme/issues/287

**Comment by wa4557** [comment]
Aaand fixed :)
