### ISSUE TITLE
Symlink Google docs;sheet,form extensions

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-icon-theme#249]
Hello everyone,
i would like to ask you to symlink those extensions with the available ones 
gddoc : google docs
gdsheet : google sheets
gdform : google form

i'm asking for that; cause i'm using insync to sync my google drive storage, and i've those ugly icons instead of your beautiful ones :D
Hope to see this on the next updates 
Thanks

**Comment by Foggalong** [comment]
Gonna do these soon :)
