### ISSUE TITLE
insync support 

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-icon-theme#250]
Hello, 
i would like to ask you to support insync (googel drive)
there's alot of icons; but some could be symlinked to others (i dont have any idea)
those icons are in hicolor/48X48/status
insync-error.png
![insync-error](https://cloud.githubusercontent.com/assets/7660997/5320576/a7ce01d6-7cb3-11e4-8cf4-48e6e3e6ec05.png)
insync-normal.png
![insync-normal](https://cloud.githubusercontent.com/assets/7660997/5320579/ad1fbeb8-7cb3-11e4-9953-3fbd3b119303.png)
insync-offline.png
![insync-offline](https://cloud.githubusercontent.com/assets/7660997/5320587/b270cd1c-7cb3-11e4-80f0-8c5a177846e9.png)
insync-partial-error.png
![insync-partial-error](https://cloud.githubusercontent.com/assets/7660997/5320589/b6327eaa-7cb3-11e4-824c-de8f24338b2d.png)
insync-pause.png
![insync-pause](https://cloud.githubusercontent.com/assets/7660997/5320591/bcf68f4c-7cb3-11e4-80b2-2e85ff9eee77.png)
isnync-synced.png
![insync-synced](https://cloud.githubusercontent.com/assets/7660997/5320596/c509b470-7cb3-11e4-83d9-5e7f1de51a7b.png)
insync-share.png
![insync-share](https://cloud.githubusercontent.com/assets/7660997/5320598/cbe897d4-7cb3-11e4-8969-81e5743fb34c.png)
isync-syncing-1.png
![insync-syncing-1](https://cloud.githubusercontent.com/assets/7660997/5320600/d192f242-7cb3-11e4-9ae0-067045bc318f.png)
isync-syncing-2.png
![insync-syncing-2](https://cloud.githubusercontent.com/assets/7660997/5320601/d1ad039e-7cb3-11e4-8890-3d20c4e35f33.png)
isync-syncing-3.png
![insync-syncing-3](https://cloud.githubusercontent.com/assets/7660997/5320603/d1b31914-7cb3-11e4-8c7d-72ef3cdd1a01.png)
isync-syncing-4.png
![insync-syncing-4](https://cloud.githubusercontent.com/assets/7660997/5320602/d1b29160-7cb3-11e4-8825-e93d95b8b927.png)

those one are in hicolor/64x64/emblems/
emblem-insync-des-error.png
![emblem-insync-des-error](https://cloud.githubusercontent.com/assets/7660997/5320640/1264668e-7cb4-11e4-921c-b625e7a2ddf8.png)
emblem-insync-des-error-shared.png
![emblem-insync-des-error-shared](https://cloud.githubusercontent.com/assets/7660997/5320641/1266136c-7cb4-11e4-82cc-cd7c276e9c68.png)
emblem-insync-error.png
![emblem-insync-error](https://cloud.githubusercontent.com/assets/7660997/5320642/126a89c4-7cb4-11e4-902d-8b3d3dc6b26e.png)
emblem-insync-error-shared.png
![emblem-insync-error-shared](https://cloud.githubusercontent.com/assets/7660997/5320643/126ab7e6-7cb4-11e4-964f-7d297bec1d01.png)
emblem-insync-synced.png
![emblem-insync-synced](https://cloud.githubusercontent.com/assets/7660997/5320644/126b1c68-7cb4-11e4-86e1-122e4b95d669.png)
emblem-insync-synced-callbacks.png
![emblem-insync-synced-callbacks](https://cloud.githubusercontent.com/assets/7660997/5320645/126e90fa-7cb4-11e4-95e6-43b6b4262006.png)
emblem-insync-synced-callbacks-active.png
![emblem-insync-synced-callbacks-active](https://cloud.githubusercontent.com/assets/7660997/5320649/127c4308-7cb4-11e4-9ddd-f3e9f61d96bc.png)
emblem-insync-synced-shared.png
![emblem-insync-synced-shared](https://cloud.githubusercontent.com/assets/7660997/5320646/127afb42-7cb4-11e4-87d4-697c2c39a421.png)
emblem-insync-syncing.png
![emblem-insync-syncing](https://cloud.githubusercontent.com/assets/7660997/5320648/127c0884-7cb4-11e4-9b1d-075412019d07.png)
emblem-insync-syncing-shared.png
![emblem-insync-syncing-shared](https://cloud.githubusercontent.com/assets/7660997/5320647/127b8738-7cb4-11e4-8f3d-1264bed90bea.png)

Thank you so much

**Comment by edgard** [comment]
:+1:

**Comment by bil-elmoussaoui** [comment]
@Foggalong insync status icons uses the icon from Numix Circle, should i open a new issue for that? or just open a pull request to fix it (by creating a symlink from Base to circle as we did for other status icons)

**Comment by wa4557** [comment]
You just have to move them from `status` to `panel` no need for new symlinks...

**Comment by bil-elmoussaoui** [comment]
Thanks! i will open a new pull request for that!

**Comment by bil-elmoussaoui** [comment]
@wa4557 they're already in `panel`..

**Comment by wa4557** [comment]
Then they are also in circle...

**Comment by bil-elmoussaoui** [comment]
I don't know why this is happening, the normal status icon is working fine but when i change from normal to pause the indicator icon uses the circle one (in elementary)! and in Ubuntu Gnome the status icon does not uses Numix one at all (the same in Fedora 23)

**Comment by wa4557** [comment]
I don't have insync (and not going to buy it) so I don't know, sorry...

**Comment by bil-elmoussaoui** [comment]
@wa4557 There's a free trial version (if you wanna try), @edgard As you wanted those icons too, can you confirm that they're looking fine (or not) in your distro?

**Comment by edgard** [comment]
Not sure what I'm suppose to look at. :D

I use icon-circle and with the last available numix packages from ppa, it seems it's not changing at all. Actually it changes from a brief moment when loading and then it goes back to the regular Insync icons.

```
[edgard@lynxarc ~]$ dpkg -l | grep numix-icon
ii  numix-icon-theme                            0.3+655~201511080816~ubuntu15.10.1       all          Numix icon theme
ii  numix-icon-theme-circle                     1.0.2+5~201510162111~ubuntu15.10.1       all          Numix Circle icons
```

**Comment by MirkoCe** [comment]
Same here, paused icon and syncing icons are just the circular ones. The regular icons works though....Is there any workaround?
