### ISSUE TITLE
Ubuntu notification icons - brightness

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-icon-theme#251]
In continuation of https://github.com/numixproject/numix-icon-theme/issues/248, here are the relevant icons for display brightness (in alphabetical order):

`notification-display-brightness-full.svg`
`notification-display-brightness-high.svg`
`notification-display-brightness-low.svg`
`notification-display-brightness-medium.svg`
`notification-display-brightness-off.svg`

Screenshot of the default brightness notification icons:
![notifications-icons_brightness](https://cloud.githubusercontent.com/assets/7164227/5326777/70ae7e74-7d2b-11e4-8690-a5955d32de23.png)

With these icons, apparently the transparency of the rays is changing, creating a smooth transition for different levels of brightness. I have checked: all 5 icons are used.

In contrast to the volume icons, these brightness icons are not present (in another icon size) in Numix Base yet. The only brightness icon in Numix Base currently is `display-brightness-symbolic.svg` in `scalable/status`.

Screenshot:
![brightness](https://cloud.githubusercontent.com/assets/7164227/5326800/92054912-7d2c-11e4-9646-42ea8812060f.png)

**Comment by wa4557** [comment]
Should be fixed
