### ISSUE TITLE
Ubuntu notification icons - wireless

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-icon-theme#252]
In continuation of https://github.com/numixproject/numix-icon-theme/issues/248 and https://github.com/numixproject/numix-icon-theme/issues/251, now on to the notification icons for wireless:

The two relevant notification icon names here are:

`notification-network-wireless-disconnected.svg`
`nm-device-wireless.svg`

Screenshot comparison for wireless disconnected in current default and with Numix notification icon:

Notification wireless disconnected current:
![notification_wireless_disconnected_current](https://cloud.githubusercontent.com/assets/7164227/5327690/a1fcb2d6-7d5b-11e4-81e0-7a8ceec81f74.png)

Notification wireless disconnected with Numix Base notification icon:
![notification_wireless_disconnected_numix_base](https://cloud.githubusercontent.com/assets/7164227/5327693/c213be20-7d5b-11e4-8b27-12b25636fb6d.png)

The "notification" icon for wireless connected actually is `nm-device-wireless`. This would be a regular Numix Base status icon e.g. in `22x22/status`.

This is a longstanding limitation (feature?) of NotifyOSD/Upstream (no actual signal strength displayed in the Ubuntu notification bubble), as can be seen in these two bug reports:

https://bugs.launchpad.net/hundredpapercuts/+bug/387626
https://bugzilla.gnome.org/show_bug.cgi?id=686357

Still, in my view, this would not be a case of Numix catering to a bug in another project. Rather, currently `nm-device-wireless.svg` actually is an icon also in Numix-Circle, although this icon belongs to Numix Base, cf. https://github.com/numixproject/numix-icon-theme-circle/issues/1361 over at Numix-Circle. So having this icon only in Numix Base, just like e.g. `nm-device-wired.svg`, would automatically lead to it being displayed correctly in the Ubuntu notification bubble.

Screenshot comparison for wireless connected currently and with `nm-device-wireless.svg` status icon (for testing purposes, I renamed an existing 22x22 Numix icon accordingly in a somewhat different icon theme structure, so this is only for illustrating):

Notification wireless connected current:
![notification_wireless_connected_current](https://cloud.githubusercontent.com/assets/7164227/5327702/431cf072-7d5c-11e4-8760-a153c367f4f6.png)

Notification wireless connected with Numix Base `nm-device-wireless.svg` icon:
![notification_wireless_connected_numix_base](https://cloud.githubusercontent.com/assets/7164227/5327705/60acf182-7d5c-11e4-95f0-37889cbb2788.png)

**Comment by bil-elmoussaoui** [comment]
I hope this got fixed ; this symlink is not the best idea so far : 
![capture du 2015-02-19 23 00 33](https://cloud.githubusercontent.com/assets/7660997/6276996/248940ba-b88b-11e4-97c0-2c8809fa6f09.png)
as you can see in this picture; i'm using elementary os with only the numix circle icons ;)

**Comment by dirtydancing** [comment]
Same currently in Ubuntu 14.10:
![ubuntu1410](https://cloud.githubusercontent.com/assets/7164227/6277235/42668730-b88d-11e4-922f-ffc65afd90be.png)

@bil-elmoussaoui Can you confirm that this is indeed `nm-device-wireless.svg`? I did not check that for this icon, and I am not sure that this is the one here (actually I suspect it is not).

**Comment by bil-elmoussaoui** [comment]
@dirtydancing There's an icon with this name in :/usr/share/icons/Numix/48x48/devices/nm-device-wireless.svg 
and /usr/share/icons/Numix/48x48/apps/nm-device-wireless.svg
the icon is looking like this 
![capture du 2015-02-19 23 24 42](https://cloud.githubusercontent.com/assets/7660997/6277402/8aa0c136-b88e-11e4-8fe2-e2b739de57ab.png)

**Comment by dirtydancing** [comment]
@bil-elmoussaoui Sorry for being unclear, I was referring to the icon name of the marked icon in our screenshots. There are several different symlinks in Numix-Circle that have the same icon as `nm-device-wireless.svg`, which is a bit tricky. I quickly checked, and when I changed `nm-device-wireless.svg` in Numix-Circle, the icon did not change. But when I changed `preferences-system-network.svg`, the icon changed:

![system-preferences-network](https://cloud.githubusercontent.com/assets/7164227/6277848/767edf86-b892-11e4-8002-d899928ae7a1.png)

![ubuntu1410_2](https://cloud.githubusercontent.com/assets/7164227/6277849/78c8d59e-b892-11e4-9f01-3a371a47907e.png)

This means that the icon in question here appears to be `preferences-system-network.svg`. Can you confirm this? If this indeed is so, the icon issue that you are pointing to would require a separate bug report, and it would have to be checked if this specific icon is employed elsewhere and therefore should not be modified.

**Comment by bil-elmoussaoui** [comment]
I found a symlink on Numix-Circle/Scalable/nm-device-wireless.svg; after removing this icon the notifications are getting their default icon ;) i will take a look later for the network manager icon

**Comment by bil-elmoussaoui** [comment]
@dirtydancing  The same thing here! when i changed the preferences-system-network.svg the icon changed! so i believe we have to report this?

**Comment by dirtydancing** [comment]
@bil-elmoussaoui Good, so `preferences-system-network.svg` is confirmed. Where does this take us? Definitely out of this present bug report which (i.a.) deals with `nm-device-wireless.svg` :-)

I would guess that `preferences-system-network.svg` is used somewhere else as well, but I have not checked. This might also be an issue with the network settings in Ubuntu (and not a Numix issue at all), but then again I do not know right now what the proper icon name should be from Ubuntu's side.

Could you possibly open a new isse on this with Numix Icon Theme and refer to the relevant lower section of this present issue, and then the Numix team will be able to respond properly. Otherwise I am afraid that this is getting too confusing.

**Comment by wa4557** [comment]
@dirtydancing does removing nm-device-wireless in Numix-Circle break anything? I don't think it is used at all (in Ubuntu at least, haven't tested other distros yet)

**Comment by dirtydancing** [comment]
No, removing `nm-device-wireless.svg` in Numix-**Circle** does not break anything, and it has already been removed, cf. https://github.com/numixproject/numix-icon-theme-circle/pull/1690.

Of course, when I say, it does not break anything, I am referring to what I am aware of. Back in the day, this has been requested in Numix-**Circle** for Lubuntu, but when I reported my test results with Lubuntu, this was not used anymore, so no breakage, cf. https://github.com/numixproject/numix-icon-theme-circle/issues/154.

Even if this was still used a distribution as an icon name that would require a Numix-**Circle** icon, this would rather be a naming bug in that distribution than a missing icon in Numix, cf. my argument over at https://github.com/numixproject/numix-icon-theme-circle/issues/1361.

**Comment by wa4557** [comment]
Ok, if I put an appropriate icon in 48x48/notifications would this be picked? Doesn't seem to work for me... I'm asking because the nm-device-wireless.svg in Numix-base has imo the wrong colour

**Comment by wa4557** [comment]
Even better: Iis the nm-device-wireless.svg used somewhere else? Can we change it's colour to #dcdcdc? By doing this we wouldn't need an additional notification-icon in 48x48/notifications...

**Comment by dirtydancing** [comment]
Yeah, this is part of the complexity involved here. I have not tested an 'nm-device-wireless.svg` in Numix base in 48x48/notifications yet. The icons in the Ubuntu notification bubble for the network connections are not really playing by the book: they use "notification"-named icons for disconnected, but "device"-named icons for connected.

The next question then is the order of which directories are looked at for finding this "device"-named icon to be put into the notification bubble. It might well be that if there is such an icon in Numix base as e.g. `nm-device-wireless.svg` in 48x48/devices (it is), than that one will get picked. This is up to testing.

And the next question would then be whether it would make sense to just place the directory 48x48/notifications into Numix-**Circle**, because in the icon theme inheritance line this comes before Numix base, and thus e.g. `nm-device-wired.svg` might then get picked up from 48x48/notifications in Numix-**Circle**. But this is a kind of last resort (and would require much more testing to make sure that it doe not break anything anywhere else), so at this point this would just be a possible option to be aware of.

As to the icon itself: I am not sure if this is the wrong colour in Numix base. iirc, `nm-device-wireless.svg` in Numix base is not placed in the 16,22 and 24 status directories, in contrast to wired and wwan (?), but I would need to check myself in more detail, and as to what is the reason for that.

**Comment by dirtydancing** [comment]
Just seeing your last comment: I do not know the answer to that (whether `nm-device-wireless.svg` in Numix **base** is used anywhere else).

**Comment by wa4557** [comment]
No 48x48/notifications is not picked, but `48x48/devices` (and changing colours of nm-device-wireless in /devices is probably a bad idea). The only way to have this sorted:

adding a notification-network-wireless-disconnected.svg in `48x48/notifications` that uses the same colour-scheme as `nm-device-wireless` in `devices`  although I kin of dislike its grey...

**Comment by dirtydancing** [comment]
Ok, I just checked this scenario (only as a background check): When `nm-device-wireless.svg` is placed in the (new) directory 48x48/notifications in Numix-**Circle**, then that icon gets picked up in the notification bubble when connecting. 

And, more relevant right now, I can NOT confirm that when looking exclusively at Numix **base**, the notification icon for wireless is taken from `48x48/devices` when there is also such icon in `48x48/notifications`. Actually, this works on my machine, and the icon from `48x48/notifications` is picked up. Are you sure that on your machine, the icon from `48x48/notifications` is not picked up? I will re-test here.

**Comment by bil-elmoussaoui** [comment]
@dirtydancing i tried it and got the same thing on ubuntu 14.04.2 , maybe its a cache problem @wa4557 ?

**Comment by dirtydancing** [comment]
@bil-elmoussaoui Hi there :-) What do you mean with "the same thing"?

**Comment by dirtydancing** [comment]
And yeah, always a good idea to update the icon cache, just in case. I re-tested and it worked again, I will provide screenshots right away.

**Comment by wa4557** [comment]
@dirtydancing @bil-elmoussaoui Yeah silly me, I forgot to update the cache. 

Fine, then placing a proper `nm-device-wireless.svg` in ǹotifications` should be the way to do this, cool!

**Comment by dirtydancing** [comment]
Ah, ok, so we are all on the same page, no screenshots needed :-). Cool!

**Comment by wa4557** [comment]
Should be fixed now with #283

**Comment by dirtydancing** [comment]
@wa4557 Should I comment over at https://github.com/numixproject/numix-icon-theme/pull/283? Anyways: I checked, and wireless is working now - almost :-). Icon colour: I still got the darker grey for wireless connected.

This time, this is apparently caused by `index.theme`, which has already shown in the past that it requires absolute precision: the directory `48x48/notifications` was listed in the 22x22 directories, so I moved it into the 48x48 order (above and below), and just for consistency below started "Notifications" in the "Context=" line with a capital "N" (also worked with a small "n", which is used everywhere else):

[48x48/notifications]
Size=48
Context=**N**otifications
Type=Fixed

Now it is working correctly! To visualise, here come two screenshots, the first one with your latest commit, the second one with the corrected `index.theme`. Can you confirm this?

Current (darker grey):
![current](https://cloud.githubusercontent.com/assets/7164227/6656394/d9d2362e-cb29-11e4-93ab-02425884b46d.png)

Corrected `index.theme` (correct grey):
![corrected](https://cloud.githubusercontent.com/assets/7164227/6656396/f25d809a-cb29-11e4-86b5-470e0365e5ae.png)

**Comment by wa4557** [comment]
@dirtydancing Argh, ok this is fixed now as well. I also fixed #253 the same way. Unfortunately I cannot test it since I have no wired connection right now...

**Comment by dirtydancing** [comment]
I can test the wired a little later and will report back.

**Comment by dirtydancing** [comment]
Just checked, and wired is working great! I will continue over at https://github.com/numixproject/numix-icon-theme/pull/283

**Comment by wa4557** [comment]
Fixed :)
