### ISSUE TITLE
Ubuntu notification icons - wired

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-icon-theme#253]
In continuation esp. of https://github.com/numixproject/numix-icon-theme/issues/252 for wireless, here are the corresponding notification icons for wired:

The two relevant notification icon names for wired are:

`notification-network-ethernet-disconnected.svg`
`nm-device-wired.svg`

Screenshot comparison for wired disconnected in current default and with Numix notification icon: Suggested here is the same icon for the notification that is also showing in the panel. Alternatively, to make this icon more distinct, a "wired" icon with a red or white cross (for disconnected) in it could be created, similar to the current default icon approach.

Notification wired disconnected current:
![notification-wired-disconnected_current](https://cloud.githubusercontent.com/assets/7164227/5328642/b17f478c-7d88-11e4-9a61-44b21258c2f6.png)

Notification wired disconnected with Numix Base notification icon:
![notification-wired-disconnected_numix](https://cloud.githubusercontent.com/assets/7164227/5328643/b84f0d54-7d88-11e4-9f62-63e2628faac8.png)

The "notification" icon for wired connected, in practice, actually is `nm-device-wired`.

Now, currently in Numix Base, there are two kinds of `nm-device-wired` icons:

First, in `status` with the two arrows:
![nm-device-wired_status](https://cloud.githubusercontent.com/assets/7164227/5328649/d7a3459e-7d88-11e4-940a-28deb530f5b4.png)

and second, in `devices`, looking like this:
![nm-device-wired_devices](https://cloud.githubusercontent.com/assets/7164227/5328652/e960e1ce-7d88-11e4-9d41-7bda10445c8a.png)

Overview screenshot of `nm-device-wired.svg` in current Numix Base:
![nm-device-wired_overview](https://cloud.githubusercontent.com/assets/7164227/5328656/0500e2e4-7d89-11e4-91ba-0ad3520a53d6.png)

This might be a good opportunity to make these icons consistent, and I would suggest to adopt the design with the two arrows also for the `devices` icons. That is unless there is a reason for the quite divergent icon designs inbetween `status` and `devices`, of course.

Screenshot comparison for wired connected currently (icon apparently picked from a Numix Base `devices` folder) and for testing purposes with `nm-device-wired.svg` `status` icon:

Notification wired connected current:
![notification_wired-connected_current](https://cloud.githubusercontent.com/assets/7164227/5328660/3a33eeac-7d89-11e4-9a6b-f375eeefdf3e.png)

Notification wired connected with Numix Base `nm-device-wired.svg` `status` icon:
![notification-wired-connected_numix-status](https://cloud.githubusercontent.com/assets/7164227/5328661/3fd93510-7d89-11e4-96c5-55c2590d48b7.png)

**Comment by Veske** [comment]
I would also add that when using Numix light theme,   the icon on the top bar for wired connection is not fit for light theme: 
![bad-wired-icon](https://cloud.githubusercontent.com/assets/5602603/5617873/f474e4e8-951b-11e4-89a0-8a0d8638577a.png)

**Comment by dirtydancing** [comment]
@Veske Thanks for pointing this out. The issue you are raising is already being addressed in https://github.com/numixproject/numix-icon-theme/issues/209.

**Comment by wa4557** [comment]
Can be closed
