### ISSUE TITLE
Missing "battery-full-charged-symbolic.svg" file

### ISSUE THREAD

**Issue by tuliomarchetto** [numixproject/numix-icon-theme#254]
On **GNOME Shell 3.14.1** and **Numix 0.3+241** wasn't showing the full charge battery on the top right bar and after click it show a huge icon. I managed to fix it coping the original Adwaita:

```
sudo cp /usr/share/icons/Adwaita/scalable/status/battery-full-charged-symbolic.svg /usr/share/icons/Numix/16x16/status
```

Before:

![screenshot from 2014-12-08 02 25 56](https://cloud.githubusercontent.com/assets/9877039/5334800/f013d676-7e81-11e4-807a-f1c44cf5429e.png)

After:

![screenshot from 2014-12-08 02 20 51](https://cloud.githubusercontent.com/assets/9877039/5334799/f009ba7e-7e81-11e4-9e00-5dad8e274faa.png)

Maybe you guys should make link for this missing file.

**Comment by dirtydancing** [comment]
I believe this issue can be closed. This does not look like a Numix bug to me. The relevant Numix battery status icon `battery-full-charged-symbolic.svg` is in place in `scalable/status` and should be picked up in GNOME Shell. As far as I am aware, this is the only case in which this kind of issue has come up.
