### ISSUE TITLE
Ubuntu notification icons - battery alerts

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-icon-theme#255]
In continuation of https://github.com/numixproject/numix-icon-theme/issues/248, https://github.com/numixproject/numix-icon-theme/issues/251, https://github.com/numixproject/numix-icon-theme/issues/252 and https://github.com/numixproject/numix-icon-theme/issues/253, this issue concludes the mini-series of Ubuntu notification icons (NotifyOSD) for the time being.

This has been tested in current Ubuntu 14.10/Unity with the default settings. In practice, the battery alerts turned out to be apparently a mixture of time and percentage alerts, 5 alerts altogether, although the value "use-time-for-policy" in "org.gnome.settings-daemon.plugins.power" was default on, and only a trilogy of (1) low, (2) critical and (3) action was to be expected.

The present issue is a tricky one. But looking back at all the previous Numix Base battery icon issues, I figure it would not really be the battery icon if this was a trivial and straightforward process :-).

The relevant icon names for the battery notifications are:
`notification-battery-020.svg`
`notification-battery-low.svg` (symlink with target notification-battery-020.svg)
`notification-battery-000.svg`
`notification-battery-empty.svg` (symlink with target notification-battery-000.svg)
`battery-caution-symbolic.svg` (symlink with target notification-battery-000.svg)

Screenshot with an overview of the relevant icons:
![notifications-battery-alerts_overview](https://cloud.githubusercontent.com/assets/7164227/5337264/dc95a3aa-7ec6-11e4-801f-cf78f86a579a.png)

1st alert: battery low (time 20 min): `notification-battery-low.svg`

Comparative screenshots:

Current
![1a_notification-battery-low-time_current](https://cloud.githubusercontent.com/assets/7164227/5337280/f0157ac2-7ec6-11e4-9360-d89ced231216.png)

With Numix Base `notification-battery-low.svg`
![1b_notification-battery-low-time_numix](https://cloud.githubusercontent.com/assets/7164227/5337288/fc7a6656-7ec6-11e4-98d1-0a3f5ad0c009.png)

2nd alert: battery low (percentage 10%): `notification-battery-020.svg`

Comparative screenshots:

Current
![2a_notification-battery-low-percentage_current](https://cloud.githubusercontent.com/assets/7164227/5337294/103c2a80-7ec7-11e4-8c58-ed5f5058cac8.png)

With Numix Base `notification-battery-020.svg`
![2b_notification-battery-low-percentage_numix](https://cloud.githubusercontent.com/assets/7164227/5337298/13f89a3c-7ec7-11e4-9e5b-8266c75daab7.png)

3rd alert: battery critical (percentage 5%, or possibly time 5 min): `notification-battery-000.svg`

Comparative screenshots:

Current
![3a_notification-battery-critical-percentage_current](https://cloud.githubusercontent.com/assets/7164227/5337304/20a23edc-7ec7-11e4-8761-0d755a7e45b9.png)

With Numix Base `notification-battery-000.svg`
![3b_notification-battery-critical-percentage_numix](https://cloud.githubusercontent.com/assets/7164227/5337312/36e152be-7ec7-11e4-9ee8-f702625cd8d3.png)

At the same time, for completeness, I would recommend to have `notification-battery-empty.svg` as a symlink with the target `notification-battery-000.svg`.

On an additional note: currently the icon `battery-000.svg` in the fixed size directories 16, 22 and 24 is not bright enough, in contrast to `battery-empty-symbolic.svg` in the scalable directory. I will open a separate bug report for that.

4th alert: battery action (about to suspend, time ca. 2 min): `battery-caution-symbolic.svg`

I am not sure why this is `battery-caution-symbolic.svg`, as this is an anomaly in this context. This is an interesting one, after the extensive battery status icon coverage in https://github.com/numixproject/numix-icon-theme/issues/107. In a (new) directory `48x48/notifications` as a size 48 icon, it should not interfere with the `battery-caution-symbolic.svg` icons in the fixed size directories 16, 22, 24 and esp. not with the scalable directory (GNOME shell). Alternatively, this icon could simply not be added, to avoid interference, but then in the Ubuntu notification bubble, it would be the "wrong" icon (caution instead of "empty") and moreover it would be too big.

On the other hand, this could be one of the cases in which the scalable directory is looked into first, so an additional icon in `48x48/notifications` would not be "seen" without manual intervention.

This specific icon would remain to be seen along the way, and I figure it would be advisable to NOT include it right away.

Comparative screenshots:

Current (picking up `battery-caution-symbolic.svg` from `scalable/status`)
![4a_notification-battery-action_current](https://cloud.githubusercontent.com/assets/7164227/5337374/e3cae170-7ec7-11e4-9c95-9a9a870339e4.png)

With Numix Base "notification" (testing with renamed 22x22 icon) `battery-caution-symbolic.svg`
![4b_notification-battery-action_numix](https://cloud.githubusercontent.com/assets/7164227/5337376/ee0b9a6c-7ec7-11e4-8637-6a0a636a7d6c.png)

5th and final alert: battery action (imminent, with additional info): `battery-caution-symbolic.svg` (same as for 4th alert)

Comparative screenshots (cf. also 4th alert):

Current
![5a_notification-battery-action-imminent_current](https://cloud.githubusercontent.com/assets/7164227/5337381/00c72400-7ec8-11e4-936c-1a3e2d4e8c79.png)

With Numix Base "notification" icon
![5b_notification-battery-action-imminent_numix](https://cloud.githubusercontent.com/assets/7164227/5337384/05f2107a-7ec8-11e4-92f1-9692ecb23497.png)

**Comment by wa4557** [comment]
@dirtydancing fixed this as well now. In my setup it works as expected. I also changed the brightness of the battery-empty icon, as suggested in your pull request

**Comment by wa4557** [comment]
Should be fixed
