### ISSUE TITLE
Battery icon: "battery-000.svg" in the fixed size directories 16, 22 and 24 is not bright enough

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-icon-theme#256]
As indicated in https://github.com/numixproject/numix-icon-theme/issues/255, `battery-000.svg` in the fixed size directories 16, 22 and 24, in contrast to `battery-empty-symbolic.svg` in the scalable directory is not bright enought.

Comparative icon screenhots:

22x22
![fixed-size](https://cloud.githubusercontent.com/assets/7164227/5337628/03494566-7ecb-11e4-89d4-795a41331f0c.png)

scalable
![scalable](https://cloud.githubusercontent.com/assets/7164227/5337633/0a2f2468-7ecb-11e4-9959-55d4ab40ece7.png)

This is not alerting enough e.g. in Ubuntu, and esp. also in regard to the (reported) notification icons (NotifyOSD).

Screenshot of Ubuntu 14.10/Unity (default Ubuntu wallpaper):
![notification-battery-critical-percentage_numix](https://cloud.githubusercontent.com/assets/7164227/5337658/4eee41ce-7ecb-11e4-8d4d-d4aad5bf7e67.png)

This has already been mentioned in https://github.com/numixproject/numix-icon-theme/issues/107#issuecomment-52675136. But I figure that this detail got lost along the way, so I am reporting it here on its own.

**Comment by Foggalong** [comment]
This is actually an intentional thing. As the battery level goes down the not full part becomes transparent until you get to the 0% one when it's all transparent red because it's empty :)

**Comment by dirtydancing** [comment]
@Foggalong Ah, ok. Well then, let me present you with an argument to have this icon with 100% opacity instead of 40% opacity, for your consideration to revise this design decision, if convinced:

1) Having a transparent red defies the purpose of the warning. This is a "red alert". With transparency, the icon is not very well visible. This might become an even bigger problem with transparent panels.

2) With transparent red, the battery staus icon(s) with "orange warning" before the final full-size "red warning" become more visible than the "red warning". This is a functional inconsistency.

3) The transparent red is only present for the fixed size directories, the corresponding `battery-empty-symbolic.svg` in the scalable directory this icon has 100% opacity red. This is one more inconsistency.

4) The equivalent icon for `battery-000-charging.svg` has no transparent red either, although also here the battery is just starting to charge and thus still almost empty. Another inconsistency.

5) The newly added Ubuntu notification icon `notification-battery-000.svg` displays a full non-transparent red. With the default wallpaper in 14.04 TLS/14.10, the transparent red is hardly visible.

6) This is the only "red alert" icon in Numix base that has a transparent red at all, as far as I am aware, which is an additional more general inconsistency.

I have always considered this to be unintentional. Which is why I am presenting these arguments.

Convinced? :-)

@wa4557 Bringing you in here for your information because this might relate to our notification icons conversation over at https://github.com/numixproject/numix-icon-theme/pull/283

**Comment by wa4557** [comment]
@dirtydancing Actually I agree with Foggalong here, I think the transparent red is a reasonable choice. I think however that a 100% opacity for the notification icon is also reasonable. Why not keep it as it is now? Transparent status icon but non-transparent notification icon, this way you have your warning red that warns you that sth is going on and the transparent red (because empty battery) in the tray?

**Comment by dirtydancing** [comment]
I see your point: but what about a distribution (or a setting in Ubuntu) that does not have notification icons? And why have this very icon transparent in fixed size and non-transparent in scalable? Maybe this is because the scalable directory for the battery icons is mainly used by GNOME Shell, which iirc does not make use of these notification icons (?). My point is: the `battery-000.svg` icon should fulfill its warning purpose regardless of any notification icons.

**Comment by wa4557** [comment]
If you look for example at `ubuntu-mono-dark` you'll see that there as well the icon is completely empty as well. I don't think that the tray status should warn the user that the battery is empty, but rather inform the user about the state of the battery, and hence a full battery icon doesn't make a lot sense, imo. 

That said, I have no problem if the team decides that a full icon is better and changes it :)

**Comment by dirtydancing** [comment]
Definitely no problem on my side either, this can go either way and probably be just fine. I just wanted to let you know my arguments.

Back to you point: `ubuntu-mono-dark` has a different design and thus in not necessarily comparable: it uses a border line around the battery throughout, which Numix does not. (also no orange for the battery icons in `ubuntu-mono-dark`). The empty battery in `ubuntu-mono-dark` is still very visible and thus functional, because the red is non-transparent :-)

**Comment by Foggalong** [comment]
@dirtydancing I think you've convinced me

**Comment by dirtydancing** [comment]
Sure, will do so :-)
