### ISSUE TITLE
Synapse indicator icon

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-icon-theme#258]
Hello,
a synapse indicator icon is missed, i found an icon on /usr/share/icons/Numix/16x16/status/synapse.svg
but its not looking the same on my appindicator 
![selection_001](https://cloud.githubusercontent.com/assets/7660997/5435164/11cabd26-8458-11e4-8982-5fa90fb48c75.png)
i really dont think its hardcoded ;
![menu_003](https://cloud.githubusercontent.com/assets/7660997/5435190/62491f7c-8458-11e4-84e2-f61398a04f78.png)
this picture is from synapse indicator too and it's using the themed icon... maybe you should add an other size? like 24x24? 
thanks

**Comment by wa4557** [comment]
I don't think this is fixable, since it's an icon from scalable. So it has automatically a different design and color. This is a synapse bug imo...

**Comment by bil-elmoussaoui** [comment]
I don't think so, i'm using elementary OS now with the elementary base theme and the icon is picked from actions/24x24

**Comment by wa4557** [comment]
@bil-elmoussaoui Yeah but it doesn't make sense to add an *symbolic icon to a non scalable folder. So if synapse is using `edit-find-symbolic.svg` that is and should be an icon from `scalable` and consequentely has a different design

**Comment by bil-elmoussaoui** [comment]
Well, we might add the same icon from scalable into the 24x24 size and give it a try? I've read somewhere in the elementary community (Google+) that this icon must be a 16x16 icon in a 22x22 shape or something like that; because the icon looks big in elementary too.
 If someone want to report this to the developer of synaptic indicator it will be very helpful.
