### ISSUE TITLE
New bin icon

### ISSUE THREAD

**Issue by scottwillmoore** [numixproject/numix-icon-theme#259]
The current bin icon: `user-trash.svg` and `user-trash-full.svg`, looks squashed and out of place, especially combined with numix-circle-icons or numix-square-icons.

I have created a simple, mockup of a new bin (feel free to modify or make a completely new one), based around the numix-circle-icons, but I guess it could also be modified to fit the numix-square-icons.

![user-trash](https://cloud.githubusercontent.com/assets/9512557/5468215/ddc562f0-861f-11e4-8176-e24163cf457d.png) vs ![trash](https://cloud.githubusercontent.com/assets/9512557/5468192/852fa1aa-861f-11e4-8a10-aa5bca697d5c.png)

I just feel the current bin icon looks odd. and ugly?

EDIT: Also how do you update each individual icon for each size? Do you have a script or do you manually update each size, because there are 8 different sizes for each icon!

**Comment by dirtydancing** [comment]
I believe that this issue can be closed now that new rubbish bin icons have been released with the folder redesign, cf. https://plus.google.com/+NumixProjectOrg/posts/QrAZwebVUrk

![rubbish_bin_new](https://cloud.githubusercontent.com/assets/7164227/6146299/8da71d2a-b1eb-11e4-97b0-27ebcd9b218f.png)

**Comment by Foggalong** [comment]
Aye, this design is now the standard we'll be sticking to
