### ISSUE TITLE
Empathy status icons symlink

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-icon-theme#262]
Hello;
i guess theres a symlink to make there!

![screenshot from 2015-01-06 14 03 59](https://cloud.githubusercontent.com/assets/7660997/5628866/139f4700-95ad-11e4-99c8-5837527f00a5.png)
as you can see, the status icons are all white (cant see them until you hover the status) 
Hope you can fix that !
Thanks

**Comment by Foggalong** [comment]
Do younknow any of the icon names, well need them to make the symlinks

**Comment by bil-elmoussaoui** [comment]
i ve been looking for a few minutes; and i found out that theres no other icons(no symlinks needed) 
but i guess theres some sizes that you dont support for the moment ? 
you support only 16x16 ; while on the gnome icon theme theres those sizes too : 
16x16; 22x22 ;24x24; 32x32;48x48; 256x256

**Comment by wa4557** [comment]
Should be fixed I suppose, since there are now symlinks also in 16x16 and 24x24 and 32x32 etc. are most probably not needed for status icons

**Comment by bil-elmoussaoui** [comment]
@wa4557 is your PR has been merged? as i did not found the icons in the latest github version

**Comment by wa4557** [comment]
@bil-elmoussaoui I see
```
empathy-available.svg
empathy-extended-away.svg
empathy-away.svg
empathy-offline.svg
empathy-busy.svg 
```
 in numix base

**Comment by bil-elmoussaoui** [comment]
@wa4557 The icons did exists in status/24x24 but not in 48x48 and other sizes

**Comment by wa4557** [comment]
Ok. But those are icons are probably not needed in those bigger sizes. As In your screenshot the icons are definitely smaller than 32px

**Comment by bil-elmoussaoui** [comment]
Well, the reason i posted this is the bigger sizes were missing. I don't really know why but the icons are not working (the same result as in the screenshot above)

**Comment by wa4557** [comment]
Maybe they are just invisible because they have the same colour as the background?

**Comment by bil-elmoussaoui** [comment]
Not really, the available icon is green; and the busy icon is red .  I tried different themes but i didn't try a darker theme.

**Comment by wa4557** [comment]
weird, I cannot reproduce your bug report (see screenshot; everything seems to work for me). Can you try again?
![unbenannt](https://cloud.githubusercontent.com/assets/6475757/7671742/2912bec4-fcdb-11e4-8034-4efb27e152ed.png)

**Comment by bil-elmoussaoui** [comment]
I have to reinstall Empathy to try this again

**Comment by bil-elmoussaoui** [comment]
i just tested this on Ubuntu Gnome 15.04 and empathy 3.8.6 and everything working fine. Thanks @wa4557
