### ISSUE TITLE
C and C++ header file (.h and .hpp) icon request

### ISSUE THREAD

**Issue by Archielles** [numixproject/numix-icon-theme#263]
Hello, I would like to request an icon for both C and C++ header file (.h and .hpp).
Thank you for your attention.

Edit: Also can I request a Makefile icon?

**Comment by Foggalong** [comment]
We have icons for all 3 of those file types, they must just not be linked up properly. I don't suppose you have the icon name?

**Comment by Archielles** [comment]
I see, the mimetypes for those files are the following:
![screenshot from 2015-01-26 16 16 37](https://cloud.githubusercontent.com/assets/7337960/5897447/af3a1bd0-a576-11e4-89a6-feae994105cd.png)
In the source the Makefile's mimetype is set to `gnome-mime-text-x-makefile` and not `text-x-makefile`.
`text-x-c++hdr` (for .hpp) doesn't exist, but `text-x-chdr` (for .h) exist.

**Comment by Foggalong** [comment]
I tried doing a reverse readlink to find which make file mime you're talking about, but the only ones I could find were `gnome-mime-text-x-makefile.svg` & `text-x-makefile.svg`. As for the others, is it okay if they link to the C/C++ file types or do they need H/H++ ones doing?

**Comment by Archielles** [comment]
My apologies for the Makefile, I didn't have the latest version, as it's working now.
I think the .hpp and .cpp icons should be distinct like .h and .c icons. As it can be confusing if someone have both of these file in a same directory.

**Comment by ChuckDaniels87** [comment]
I usually code in C++ and  I agree with @Archielles, they should be different.

**Comment by Foggalong** [comment]
Alright, different they shall be! :)

**Comment by ChuckDaniels87** [comment]
:+1:

**Comment by Archielles** [comment]
Thanks! :) :+1:

**Comment by hlechner** [comment]
What you think @Foggalong ?
![image](https://cloud.githubusercontent.com/assets/11244067/6812507/1f8278ac-d24e-11e4-8225-d4b5b8a0eb19.png)

I can make in all sizes. I used the same colors as C/C++ style.

**Comment by palob** [comment]
Maybe better without the dot?
There isn't a dot on any other mimetype icon after all.

**Comment by Foggalong** [comment]
@hlechner if you remove the dot then that's fine for a pull request :)

**Comment by Foggalong** [comment]
@hlechner Do you have this icon?

**Comment by hlechner** [comment]
Oops, sorry, maybe there was a lot of topics that people ask me and I didn't see it.

I had it before, I'm not sure If I deleted, I will check it here

**Comment by Foggalong** [comment]
Thanks! :)

**Comment by hlechner** [comment]
It seems that I've deleted it, I can create it again actually, but I just want to put here my idea of design.

The dot really doesn't fit in Numix style, but it seems that just a **h** or **hpp** or even **o** will look like new languages with the respective names. Due to the already created Black/White style mime-type for **C**, **C++**, **C#**, **F** (Fortress) and **D** languages.

Any ideas on this or should I create with just **h**?

**Comment by Foggalong** [comment]
Just the h is fine :)

**Comment by palob** [comment]
I think the **h** symbol could be used for both C and C++ header files.
@hlechner If that's accepted you could do ``text-x-c++hdr`` as symlinks.

**Comment by wa4557** [comment]
@palob The header files for c++ do have a `.hpp` or `.hh` file extension, don't they? This should then be different from a plain **h** but rather something like **h++**?

**Comment by palob** [comment]
Yeah but just the *h* as representation for "header file". I mean there are more mimetypes which share the same icon and *hpp* or *h++* would look a bit squeezed.
But if someone's up to make it why not :)

**Comment by hlechner** [comment]
Sorry guys, I'm too busy this time that I haven't did it.

Thanks @wa4557 for making the icons!
