### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by kuboosoft** [numixproject/numix-icon-theme#264]
Hi, please includes a changelog or text about the current version. Thanks.

**Comment by Foggalong** [comment]
What would you want from a changelog above what is in the [commit history](https://github.com/numixproject/numix-icon-theme/commits/master)?

**Comment by Foggalong** [comment]
I don't think we'll be adding a change log in addition the the commit history shown above anytime soon. If you do want to keep up with the latest Numix new though we post a lot on our [Google+](https://plus.google.com/+NumixProjectOrg/posts) page :)

**Comment by kuboosoft** [comment]
forget el changelog, A best choice is add a tag, maybe 1.0...  is dificult put a release number when you make a rpm or try make a package for other distributions Linux.

**Comment by Foggalong** [comment]
[See here](https://github.com/numixproject/numix-icon-theme-circle/issues/1789) for the reasoning why we won't do that.
