### ISSUE TITLE
Unity: Gedit and Terminal show as question mark icon

### ISSUE THREAD

**Issue by loxK** [numixproject/numix-icon-theme#266]
In Unity (Ubuntu 14.04) Gedit and Terminal show as question mark icon instead of their proper icon.

**Comment by Foggalong** [comment]
That's because this is just the base theme, you need to install an app theme like Numix Circle to get the app icons too.

**Comment by loxK** [comment]
Those icons show properly in Ubuntu Gnome ...

I really don't get you answer, if I wanted circled icons I would have installed them ...

**Comment by loxK** [comment]
And what if I want the base theme but stock apps icons ? Why only Gedit and Terminal do appear as a question mark icon ?

**Comment by Erdbeergeist** [comment]
Same problem although the terminal icon is not always a question mark.
