### ISSUE TITLE
folder-symbolic.svg is not yet adapted to the new folder design

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-icon-theme#268]
Apparently, `folder-symbolic.svg` in `/usr/share/icons/Numix/scalable/places` has not yet been adapted to the new folder design.

![folder-symbolic](https://cloud.githubusercontent.com/assets/7164227/5987615/526b1130-a935-11e4-843c-f7c189809eb3.png)

After updating via the Numix PPA, the folder design has changed, but `folder-symbolic.svg` is still in the old folder shape.

Comparative screenshots from Nautilus/Files in Ubuntu 14.10:

Before the latest PPA update:

![folders_old](https://cloud.githubusercontent.com/assets/7164227/5987618/916425d4-a935-11e4-8842-a8e18151a5d7.png)

After the latest PPA update:

![folders_new](https://cloud.githubusercontent.com/assets/7164227/5987620/98f13b16-a935-11e4-9970-e42dfe767fd4.png)

**Comment by me4oslav** [comment]
Oooops, sorry. Just fixed it.

**Comment by me4oslav** [comment]
Screenshot of the fix.
![screenshot from 2015-01-31 13 33 45](https://cloud.githubusercontent.com/assets/1658870/5987900/ebc514bc-a94d-11e4-9109-d58cd2e284f1.png)

**Comment by me4oslav** [comment]
Ignore the fact that the sidebar icons are Ozon ones, I used a rather mish-mashy icon theme for thes screenshot for testing purposes.

**Comment by dirtydancing** [comment]
Brilliant, thanks!

**Comment by me4oslav** [comment]
Just took the regular 16px folder icon and made it a symbolic ones. But thanks. :P
