### ISSUE TITLE
Dropbox folder in elementary os (Ferya)

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-icon-theme#269]
Hello, i upgraded to the last version to test the new folders ! (they loook awesome btw)

but the dropbox folder look like this ??
![capture du 2015-01-31 23 42 28](https://cloud.githubusercontent.com/assets/7660997/5990121/dbe25ba4-a9a2-11e4-90f0-54ae4494cb5c.png)
i dont know if i have to give you more informations about this ?
And i'm using panatheon files manager 

Thank you!!

**Comment by Foggalong** [comment]
@me4oslav ?

**Comment by bil-elmoussaoui** [comment]
I believe its a pantheon file manger bug as its working fine on Nautilus & Nemo ;)

**Comment by Foggalong** [comment]
Ah, thanks for checking :)
