### ISSUE TITLE
Clementine actions icons

### ISSUE THREAD

**Issue by varlesh** [numixproject/numix-icon-theme#273]
![2015-02-05 14 01 38](https://cloud.githubusercontent.com/assets/8083855/6059337/656ad36e-ad41-11e4-973d-feb60d865717.png)
left to right:

* [x] folder-sound
* [ ] view-media-playlist
* [x] multimedia-player-ipod-mini-blue
* [ ] view-media-lyrics
* [ ] x-clementine-artist
* [ ] edit-clear-locationbar-ltr
* [ ] edit-clear-list

**Comment by bil-elmoussaoui** [comment]
I can symlink folder-sound to folder-music , @Foggalong should i add a pull request here or in Numix Folders?

**Comment by Foggalong** [comment]
@bil-elmoussaoui Folder symlinks go in base, only source icon files in Numix Folders :)

**Comment by palob** [comment]
I suppose the last two of the list above are reversed as to "from left to right".
``edit-clear-list.svg`` as symlink to ``process-stop.svg``?
``edit-clear-locationbar-ltr.svg`` as symlink to ``edit-clear.svg``?

**Comment by Foggalong** [comment]
Fixed in 6dd800c01db639f8b737fdb3588a735fdab9c2fe
