### ISSUE TITLE
Icon for CherryTree

### ISSUE THREAD

**Issue by June27** [numixproject/numix-icon-theme#274]
A numix-circle icon for CherryTree is missing.
The icon line says "cherrytree" and the original icon is attached.
![screenshot-1](https://cloud.githubusercontent.com/assets/10868358/6063603/38b64394-ad37-11e4-9269-cc0942ff1909.png)

**Comment by ChuckDaniels87** [comment]
For a numix circle icon you must open the issue in its own repo: https://github.com/numixproject/numix-icon-theme-circlehttps://github.com/numixproject/numix-icon-theme-circle

And well, that icon was recently added: https://github.com/numixproject/numix-icon-theme-circle/pull/1544
