### ISSUE TITLE
Repositories for Fedora20 as well Fedy is not working

### ISSUE THREAD

**Issue by gauravdighe** [numixproject/numix-icon-theme#275]
Hello,
I have a fresh Fedora20 installed. Fedy is not getting downloaded nor does the opensuse repos for Fedora20 for Numix, etc are working.

Please check and assist.

**Comment by Foggalong** [comment]
@satya164 @PaoloRotolo

**Comment by Foggalong** [comment]
Fedy is being updated and reworked so this issue should be fixed soon in the latest version :)
