### ISSUE TITLE
Avahi Tools Icon Request with Example

### ISSUE THREAD

**Issue by bkk2912** [numixproject/numix-icon-theme#276]
Hey, thank you guys for the great work! :)
The icons for Avahi tools (Avahi Zeroconf Browser, Avahi VNC Server Browser, Avahi SSH Server Browser) really look bad in my opinion expecially in Gnome 3 Apps Overview:

http://img4web.com/view/R2D2ME

All three use Icon=network-wired
in the /usr/share/applications/avahi-discover.desktop
./bssh.desktop
./bvnc.desktop

**Comment by Foggalong** [comment]
Yeah, that's not something we can fix. `network-wired.svg` should be reserved for the status icon, so it's an issue that Avahi have used it. Please report the issue to them!
