### ISSUE TITLE
Improvements for ElementaryOS 0.3

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-icon-theme#277]
Hello, i would like to ask you to fix some Symlinks problems with the Elementary Os Ferya (0.3)
Those from geary
![capture du 2015-02-19 22 37 42](https://cloud.githubusercontent.com/assets/7660997/6276552/f58e6694-b887-11e4-8f25-2ef326e72724.png)
![capture du 2015-02-19 22 38 18](https://cloud.githubusercontent.com/assets/7660997/6276557/0361c144-b888-11e4-8d94-f5b1d186055c.png)
Bad symlink on settings 
![capture du 2015-02-19 22 39 15](https://cloud.githubusercontent.com/assets/7660997/6276580/2acb3df0-b888-11e4-9c0b-d4edab07daca.png)
And so more.. 
if i can do anything about it, please say it on the comments ;) 
thanks

**Comment by Foggalong** [comment]
We'll need the icon names to fix this, which is always a bit tricky when it's not an app icon

**Comment by bil-elmoussaoui** [comment]
i will try to get the icon names this weekend ;)

**Comment by bil-elmoussaoui** [comment]
I will close this at the moment. i will open a new one when i will have more informations about the missing icons.
