### ISSUE TITLE
.pyc/.pyo icons should be distinct from .py icons.

### ISSUE THREAD

**Issue by RossBrunton** [numixproject/numix-icon-theme#281]
.pyc and .pyo files contain compiled bytecode for .py Python files. It would be useful for me and I'd imagine other people if the icons for these files were different in some way (like different colours) so we can see at a glance which files are which.

**Comment by Foggalong** [comment]
Do you know what the icon names are for the two mimetypes?

**Comment by RossBrunton** [comment]
gnome-mime-text-x-python and text-x-python for the py files and gnome-mime-application-x-python-bytecode and application-x-python-bytecode for the .pyc/.pyo files.

**Comment by palob** [comment]
Came up with this:
![pyc-test](https://cloud.githubusercontent.com/assets/7050624/6771067/100e2a04-d0d4-11e4-889d-f43f1b7a3050.png)
![pyc-test-b](https://cloud.githubusercontent.com/assets/7050624/6771068/100e8756-d0d4-11e4-909e-06728b73f091.png)
Any better suggestions?

**Comment by RossBrunton** [comment]
That seems okay to me.
