### ISSUE TITLE
Geany actions icons [$12]

### ISSUE THREAD

**Issue by hlechner** [numixproject/numix-icon-theme#284]
Inside Geany program as example:
![image](https://cloud.githubusercontent.com/assets/11244067/6555054/cf16f55a-c640-11e4-92c7-6bc2003310f7.png)

**Save All**
- [ ] Icon=geany-save-all
![image](https://cloud.githubusercontent.com/assets/11244067/6555075/0672e964-c641-11e4-83da-33144f3e0e3c.png)

**Close All**
- [ ] Icon=geany-close-all
![image](https://cloud.githubusercontent.com/assets/11244067/6555099/602a7e18-c641-11e4-85be-b79bf0de29f0.png)

**Build**
- [ ] Icon=geany-build
![image](https://cloud.githubusercontent.com/assets/11244067/6555120/b1759f82-c641-11e4-9ffe-9288d2c0bdcd.png)

These 3 icons above are added to "hicolor" theme (at the Geany's installation), having in the following sizes: 16x16, 24x24, 32x32, 48x48, scalable

And also not Geany exclusive icons:
![image](https://cloud.githubusercontent.com/assets/11244067/6556284/3d9fe6e4-c64b-11e4-9884-a84b53594f9d.png)

**Color chooser**
- [ ] Icon=gtk-select-color
![image](https://cloud.githubusercontent.com/assets/11244067/6556370/c631c0d6-c64b-11e4-9395-e047c2bdba21.png)

**Compile**
- [ ] Icon=gtk-convert
![image](https://cloud.githubusercontent.com/assets/11244067/6556536/f5e76e60-c64c-11e4-9da6-5dd2cde6a8ad.png)

**Comment by hlechner** [comment]
It seems that the numix-icon-theme doesn't have the **bounty** label.

It was added $7 of bounty on this issue:
https://www.bountysource.com/issues/9356958-geany-actions-icons

So I'll manually edit it with "[$7]" in the title. Feel free to edit it if needed.

**Comment by hlechner** [comment]
@Foggalong Should the Bouncy only be used on numix-icon-theme-circle project ?

**Comment by Foggalong** [comment]
Nono, it should work here too. I'll look into why it hasn't

**Comment by hlechner** [comment]
The 2 gtk-icons of this issue I've reported here:
#315
