### ISSUE TITLE
dialog-password Icon

### ISSUE THREAD

**Issue by hlechner** [numixproject/numix-icon-theme#285]
Request for dialog-password icon.

Used by some programs like Gparted:
![image](https://cloud.githubusercontent.com/assets/11244067/6557317/def351be-c652-11e4-8066-8ddd04221c80.png)

Gparted uses the 22x22 size. (22x22/status)

Icon=dialog-password

16x16:
![image](https://cloud.githubusercontent.com/assets/11244067/6557348/166381e6-c653-11e4-8cc9-c07125fb7efd.png)
24x24:
![image](https://cloud.githubusercontent.com/assets/11244067/6557357/1fbca4de-c653-11e4-9965-ba1a554f9fee.png)
256x256:
![image](https://cloud.githubusercontent.com/assets/11244067/6557371/3dda1bfe-c653-11e4-9533-fe9e79cde2e0.png)

It's possible also to create a symlink for this icon with name "gtk-dialog-authentication"

**Comment by hlechner** [comment]
Maybe can be based on this icon:

Numix/22x22/status/
![image](https://cloud.githubusercontent.com/assets/11244067/6885248/567a9658-d5ed-11e4-89ab-6a4d5bef74a0.png)

**Comment by bil-elmoussaoui** [comment]
The sizes are : 16x16,22x22,24x24,32x32,48x48,256x256 (the one exists in the gnome theme)
