### ISSUE TITLE
Ubuntu notification icons - mobile broadband

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-icon-theme#287]
In continuation of the Ubuntu notification mini series starting at https://github.com/numixproject/numix-icon-theme/issues/248 and esp. relating to https://github.com/numixproject/numix-icon-theme/issues/252 (wireless) and to https://github.com/numixproject/numix-icon-theme/issues/253 (wired), here is an addition for mobile broadband:

The two relevant icon names are:

`notification-gsm-disconnected.svg`
`nm-device-wwan.svg`

Currently displayed icons:

notification-gsm-disconnected (from notify-osd/icons/gnome/scalable/status)
![notification-gsm-disconnected](https://cloud.githubusercontent.com/assets/7164227/6574794/a4de5f06-c728-11e4-821f-445536223997.png)

nm-device-wwan (from Numix/24x24/status)
![nm-device-wwan](https://cloud.githubusercontent.com/assets/7164227/6574823/ea863416-c728-11e4-9fce-da8cb80817f0.png)

**Comment by wa4557** [comment]
Can be closed
