### ISSUE TITLE
Icon for new-messages.svg and symlink new-messages-red.svg not yet adapted to the current design in sizes 16x16 and 24x24

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-icon-theme#288]
The icon for `new-messages.svg` and the correpsonding symlink `new-messages-red.svg` has not yet been adapted to the current design (bell symbol) in Numix/16x16/status and in Numix/24x24/status.

Those sizes 16x16 and 24x24 are still showing the letter symbol (in contrast, `indicator-messages.svg` and `indicator-messages-new.svg` are both showing the bell symbol):

![16x16](https://cloud.githubusercontent.com/assets/7164227/6575025/25c8dc84-c72b-11e4-8f13-1b0b3bf292e5.png)

![24x24](https://cloud.githubusercontent.com/assets/7164227/6575028/2abc3ca4-c72b-11e4-893d-4ab047e46d05.png)

In contrast, in size 22x22, the current bell symbol is consistently displayed also for these two icons:

![22x22](https://cloud.githubusercontent.com/assets/7164227/6575029/2f1b3b7e-c72b-11e4-8598-dade0ff6e9c6.png)

**Comment by Foggalong** [comment]
Did this in the status redesign :)
