### ISSUE TITLE
books folder

### ISSUE THREAD

**Issue by l0okme** [numixproject/numix-icon-theme#289]
How about an eBook folder icon, for example for the folder Calibre creates?

**Comment by Foggalong** [comment]
Where were you when we made the call out for folder suggestions? :( that would have been a brilliant one to have, and if we'd had it then it would have meant only making 24 icons. Because we have it now after we've done all the colours and scaling it would mean making 540 new icons.

We don't have the resources to fix this unless a) a bounty is placed on it or b) a user contributes it. Sorry :(

**Comment by l0okme** [comment]
Okay, I will have time in a few weeks, I'll contribute then. Hope you'll like it ;)

**Comment by l0okme** [comment]
Here's a quick prototype based on an idea from Googles Material Design icons.
![default-folder-books](https://cloud.githubusercontent.com/assets/6469566/6600030/5eee3c1a-c80d-11e4-9565-f14afb883478.png)

**Comment by Foggalong** [comment]
If it was to be done it'd have to be using one of our existing book symbols, seen in `calibre.svg`, `Amazon Cloud Reader-read.amazon.com.svg`, `artha.svg`, or `almanah.svg`

**Comment by l0okme** [comment]
There's no need to apologize. If that's ok, I think I'll choose the one from ´calibre-gui.svg´ since it seems to scale best. Here again some prototypes:
![16-default-folder-books-4](https://cloud.githubusercontent.com/assets/6469566/6629050/50a3f420-c90b-11e4-8b0e-7d7a7e2ba1fe.png)
![48-default-folder-books-4](https://cloud.githubusercontent.com/assets/6469566/6629052/50a536dc-c90b-11e4-8637-1515a03930ec.png)
![256-default-folder-books](https://cloud.githubusercontent.com/assets/6469566/6629051/50a493ee-c90b-11e4-882c-5e17a055b1e4.png)

Feel free to add your thoughts.

**Comment by Foggalong** [comment]
You're right, that does scale pretty well! Well if you're up for the job, [this repo](https://github.com/numixproject/numix-folders) will be the place to do it. We merge in any changes made there into the main repo :)

**Comment by wa4557** [comment]
@l0okme You still working on this? 
If yes fine. 
If not: do you mind if I tackle this bug? I'm also very interested in such a folder, and I have a few bash scripts that allows me to generate a lot of the folders automatically

**Comment by l0okme** [comment]
I have not started yet but if you want to, I can give you the icons above, I already optimized the book for the 16px view.

**Comment by bil-elmoussaoui** [comment]
@Foggalong  i guess this must be in Numix-folders ?

**Comment by Foggalong** [comment]
Aye :)
