### ISSUE TITLE
BTSync GUI status icons

### ISSUE THREAD

**Issue by Foggalong** [numixproject/numix-icon-theme#292]
Moved from [#850](https://github.com/numixproject/numix-icon-theme-circle/issues/850) in Circle, these are the status icons needed for BTSync GUI:

128x128/apps/btsync-gui.png
16x16/apps/btsync-gui.png
16x16/status/btsync-gui-cloud.png
16x16/status/btsync-gui-direct.png
22x22/status/btsync-gui-0.png
22x22/status/btsync-gui-1.png
22x22/status/btsync-gui-10.png
22x22/status/btsync-gui-11.png
22x22/status/btsync-gui-2.png
22x22/status/btsync-gui-3.png
22x22/status/btsync-gui-4.png
22x22/status/btsync-gui-5.png
22x22/status/btsync-gui-6.png
22x22/status/btsync-gui-7.png
22x22/status/btsync-gui-8.png
22x22/status/btsync-gui-9.png
22x22/status/btsync-gui-connecting.png
22x22/status/btsync-gui-disconnected.png
22x22/status/btsync-gui-paused.png
256x256/apps/btsync-gui.png
32x32/apps/btsync-gui.png
44x44/status/btsync-gui-0.png
44x44/status/btsync-gui-1.png
44x44/status/btsync-gui-10.png
44x44/status/btsync-gui-11.png
44x44/status/btsync-gui-2.png
44x44/status/btsync-gui-3.png
44x44/status/btsync-gui-4.png
44x44/status/btsync-gui-5.png
44x44/status/btsync-gui-6.png
44x44/status/btsync-gui-7.png
44x44/status/btsync-gui-8.png
44x44/status/btsync-gui-9.png
44x44/status/btsync-gui-connecting.png
44x44/status/btsync-gui-disconnected.png
44x44/status/btsync-gui-paused.png
48x48/apps/btsync-gui.png
64x64/apps/btsync-gui.png

[Handy link](https://mega.co.nz/#!f4IlELhQ!vP1nI-yiz4Xd6gjmsEa0G_rJWBnYiIgRIHMvLAHoo5M) which has the existing icons

**Comment by wa4557** [comment]
@Foggalong I have the icons ready (made them for myself some time ago), but only for the 22x22/status directory. I suppose the other ones are not really necessary? Worked fine for me all the time with just the 22x22/status icons on Ubuntu 14.10
