### ISSUE TITLE
C object file (.o) icon request

### ISSUE THREAD

**Issue by RossBrunton** [numixproject/numix-icon-theme#293]
Mime type: application/x-object

When working with C programs, you compile c files down to .o object files, which are then linked into the actual executable. The current icon is for shell scripts, which I don't feel is appropriate. I think something like the one for application-x-desktop should suffice.

**Comment by palob** [comment]
How about a symlink to ``application-octet-stream.svg``?

**Comment by RossBrunton** [comment]
That's okay with me.
