### ISSUE TITLE
TEX mimetype doesn't show up

### ISSUE THREAD

**Issue by palob** [numixproject/numix-icon-theme#302]
However in comparison with other themes where the mimetype is shown correctly there are no files missing or misnamed.

**Comment by Foggalong** [comment]
What's the file manager, working fine in Thunar?

![screenshot - 210315 - 17 57 13](https://cloud.githubusercontent.com/assets/5920259/6766186/b700f648-cff3-11e4-855e-806d3974c191.png)

**Comment by palob** [comment]
Nemo. 
Works fine in Nautilus as well.

**Comment by wa4557** [comment]
Works for me fine in nemo 2.2.0

**Comment by Foggalong** [comment]
@palob what distro are you using it on?

**Comment by hlechner** [comment]
I've tried here in Arch Linux, and I could confirm this bug:
![image](https://cloud.githubusercontent.com/assets/11244067/6880463/12ffde24-d511-11e4-880e-da7b8c6f68c1.png)

Nemo 2.4.5

However, I'm not sure how nemo works with this kind of file. In nautilus some files are just recognized by file content others by file extension.

After taken the image above, I've added some TEX content into the file and try it using command line:
```
$ file test.TEX 
test.TEX: ASCII text
```

As you can see for *file* its just a normal text file

**Comment by wa4557** [comment]
For me this seems to be than an Arch bug rather than a Numix bug, as it works perfectly for me in Ubuntu 14.10 and Nemo 2.4.5

**Comment by cldx** [comment]
Has anybody tried if it makes a difference with lowercase and uppercase naming? A la .tex and .TEX ?

**Comment by wa4557** [comment]
@cldx Yes; both works

**Comment by hlechner** [comment]
Probably not arch bug, this kind of behavior normally is a upstream bug (nemo bug) that for some reason not affect all others distros. it should be reported into upstream bug report

**Comment by hlechner** [comment]
@cldx 
![image](https://cloud.githubusercontent.com/assets/11244067/6880498/7643b9ea-d513-11e4-8f19-ab6b0c267dc3.png)

**Comment by palob** [comment]
I'm on Arch as well.

**Comment by hlechner** [comment]
@palob Looking for Nemo bug report, it's in github too, so, it should be easier to report:
- https://github.com/linuxmint/nemo

Could you please raise an issue there? I can raise but due to I've never used this software before I think you can detail it better than me.

**Comment by palob** [comment]
I'll further dissect the issue before reporting it as a Nemo bug. Then again I'm going to abandon Cinnamon soon

**Comment by palob** [comment]
I don't encounter the bug with other icon themes (for instance Oxygen) which have got a TEX mimetype icon.

**Comment by Foggalong** [comment]
@palob Is it possible that they have a TEX symlink that we're missing?

**Comment by palob** [comment]
No. In fact, Numix has got an additional symlink *application-x-tex*.

**Comment by Foggalong** [comment]
@palob possibly one of the Numix symlinks pointing to the wrong location?

**Comment by palob** [comment]
No broken links.

**Comment by Foggalong** [comment]
@palob any of the ones related to tex not pointing where they should though?

**Comment by palob** [comment]
Everything correct, as far as I can see.

**Comment by Foggalong** [comment]
@palob Well balls. Could it be related to [this issue](https://github.com/numixproject/numix-icon-theme/issues/142)?

**Comment by palob** [comment]
That's it! Thanks muchly. No need to turn off image preview however.
It's the *text in symbols* option (not supported by the Numix theme anyway) which triggers the issue.

**Comment by palob** [comment]
@hlechner Can you confirm the fix?

**Comment by Foggalong** [comment]
Not a problem! What's the text in symbols option, is that something we should be supporting?

**Comment by hlechner** [comment]
@palob yes! working without preview

@Foggalong It's the text preview inside the icon. Here an example:
![image](https://cloud.githubusercontent.com/assets/11244067/6884625/9acb4fa2-d5d2-11e4-8c9e-10ae7b6f2b89.png)
note: this image it's not mine, I just took it from internet


Maybe what happened is because nemo uses nautilus preview, so chances are that this function is deprected in the latested nautilus preview (I'm just assuming...)

**Comment by hlechner** [comment]
BTW: this text preview in icons are always terrible looking.

**Comment by palob** [comment]
@Foggalong IIRC the Linux MInt icon set (Faience?) does this, showing the first view lines on the icon.

Issue resolved for now.
