### ISSUE TITLE
How can I change the default color of the orange one to the blue one.

### ISSUE THREAD

**Issue by xploshioOn** [numixproject/numix-icon-theme#304]
I want to use numix-circle but with folder icons default to blue, i tried with Folder color, but didn't work... but I see that in the numix folder there are blue-folder...

How can i accomplish this? blue by default in all my folders?

thanks, this is a really good work.!

**Comment by Foggalong** [comment]
Were yet to implement the feature but it'll be there soon :)

**Comment by xploshioOn** [comment]
Even if I change the defaul folder svg icons, it wouldn't use it? for example, delete the default and rename blue to default?

well, ill wait for that, keep doing that, this is nice.

**Comment by dirtydancing** [comment]
@xploshioOn Just to let you know: with the latest Numix base PPA update that landed today, the folder icon names corresponding to those that Folder Color picks up are included.

This means that, according to my current testing, Folder Color is working without limitations for individual folder colors. The "Global Color" feature of Folder Color is generally working as well now, although I have across some current limitations. You can always go back to `Default`, though, and no harm is done.

The Folder Color dev, @costales, is aware of this (I have been in contact with him i.a. for the Folder Color German translations, which in the screenshots below are more current than in the official release).

To be more specific (just pointing out what I am currently noticing):

1) "Global Color" does not change folder icons that you have manually selected. As you see in the two screenshots below, the folders POL, Projects and VM did not change the color (Numix folder style 5).

![global-color_default](https://cloud.githubusercontent.com/assets/7164227/6766478/6502864e-d008-11e4-80ac-c29b921a14ef.png)

![global-color_blue](https://cloud.githubusercontent.com/assets/7164227/6766481/71cfb040-d008-11e4-9be2-919070edc19f.png)

2) Folder Color is presently using the folder icon size 48x48 for the "Global Color" feature. This means that e.g. for folder size 16x16, not the specific size 16x16 folder icons will be displayed (cf. global default colour below), but rather a scaled version of the 48x48 folder icons (cf. global colour blue below).

![size_16x16_default](https://cloud.githubusercontent.com/assets/7164227/6766485/7c717268-d008-11e4-8801-246f46c27ade.png)

![size_16x16_blue](https://cloud.githubusercontent.com/assets/7164227/6766486/7c83a1b8-d008-11e4-9b7b-52caa3fa380b.png)

**Comment by xploshioOn** [comment]
For some reason that just don't work, I don't know what i am doing wrong... 

I have linux mint 17.1 cinnamon with numix theme and numix icons... updating the package don't show me the options to change the color, I even remove it and reinstalled again but have the same issue. 

reinstalled and updated cache and is the same, for some reason the options to change color show up when i am in root mode in nemo
![captura de pantalla de 2015-03-21 19 40 20](https://cloud.githubusercontent.com/assets/1786726/6767443/2da9d0ae-d002-11e4-9909-bd4d224d3ddc.png)
but even when they show up, the color don't change...

for some reason if it's not root, the options don't show up...

maybe i am missing something. can you just tell what are all the instructions install the icon theme and i have to install folder-color too?
maybe some instructions for people that just don't work... 

I added the ppa for numix-icons, installed... don't work, tried with folder-color, download the zip from github, fired the .sh but don't work neither.

thanks for yout time and the nice explanation, but that just don't work for me

**Comment by dirtydancing** [comment]
Hmm, with all being said here, please keep in mind that Numix has not even officially announced the feature of colour/global colour change for the Numix folders yet :-)

I am using Folder Color (on the right-click menu showing as "Ordnerfarbe" in German) as normal user, not as root. On my machine running Ubuntu 14.10 with default Nautilus/Files 3.10.1, this is working.

Now on to your question: OK, this is Mint. I am not a Mint user but I am aware that Mint has implemented its own take on changing the "folder color".

I am using Folder Color from http://foldercolor.tuxfamily.org/ (via PPA). Is this what you are using as well? I am asking because your screenshot above apparently shows the Mint folder color change option. This is not the menu of Folder Color from my screenshots above. Maybe that is already the solution?

I do not know if Mint's folder color change feature is themeable, i.e. if if works with other icon themes. Anyways, the colours in your selection menu above are not the colours for the Numix folders. In the screenshot below, I have temporarily overridden Ubuntu's design decision not to display icons in the context menu, and you can see the folder icons in front of each colour choice. These are different colours from the ones showing in your screenshot:

![colours](https://cloud.githubusercontent.com/assets/7164227/6768816/63543a68-d080-11e4-9d55-f99621b37d3e.png)

**Comment by dirtydancing** [comment]
@xploshioOn Just s.th. to consider: as there is a folder color switcher in Linux Mint, and there is Folder Color that I have referred to above, the issue of a possible conflict between these two tools comes up. I had in mind that there is no conflict in Linux Mint, and I just checked back and wanted to point you to this comment by Linux Mint's Clem: https://github.com/numixproject/numix-folders/issues/4#issuecomment-60982130 (no conflict).

@clefebvre Just to keep you informed about this current issue concerning the folder color in Linux Mint.

**Comment by xploshioOn** [comment]
well, now that you send me this url "http://foldercolor.tuxfamily.org/ " I was using that, but just installed folder-color but reading a little more, that say that in mint, that uses nemo as explorer for files, you have to install it with folder-color-nemo. and now all works as espectly, all my folders are now blue.! that's really nice. really good work here, thanks for your help and time.

![captura de pantalla de 2015-03-22 08 09 42](https://cloud.githubusercontent.com/assets/1786726/6769388/4c8e99fa-d06b-11e4-9ca9-504306cba0d7.png)

And yes, mint support change for folders color natively, but I think just in mint default theme, you even have mint-x-aqua, min-x-blue themes...

**Comment by dirtydancing** [comment]
Great! We posted at the same time :-) Good to see that this is working for you now!

The subject of "folder color" can be a little confusing I guess, with the different aspects of individual folder(s) colour vs global folder colour, with Folder Color as an app, with e.g. Linux Mint having its own folder color support (at least for Mint's default icon theme), and with e.g. Numix icon theme going the super-extra mile of not only supporting different folder colours, but even (currently 6) completely different folder styles, and each folder style in the same different non-default folder colours :-)

**Comment by xploshioOn** [comment]
yeah, thanks for your help guys.

yeah, there are some thins that you need to have in mind, but is really easy and nice that you can customize all the appareance of your desktop. I tried deepin distro and really liked the appareance, but in performance isn't so good and is like for windows user, even the terminal is so simple, i can't even run a shorcut with a sudo command... xD

But with other options like this theme and icons you can have a really nice appareance without change your distro, so many thanks for you. is not to have some nice performance, you sometimes need a good view if you work all the day in the computer.

**Comment by xploshioOn** [comment]
Hi guys, i am opening this again. I installed linux mint 17.1 in my portatil, installed numix icon theme, everything ok, but now when I install folder color, it just change the colors for individual folders, the global option is not there, is something in numix? or a problem with folder color, everything is ok, but not the global option. looking in google but nothing there, the symlinks for 32 bits, i do it, installed python nemo... and still can't see the global option.
![captura de pantalla de 2015-05-04 03 30 52](https://cloud.githubusercontent.com/assets/1786726/7450385/079b67e6-f20e-11e4-9756-f19119a00818.png)
any idea? thanks.

**Comment by dirtydancing** [comment]
This actually is on purpose. The global/default colour change is taken care of by the Numix script, cf. https://github.com/numixproject/numix-folders/issues/51.

**Comment by xploshioOn** [comment]
So now i can uninstall folder color? is that package not necessary now?

**Comment by dirtydancing** [comment]
While the Numix script handles the global/default colour change better for Numix icon theme, Folder Color still remains the tool to go to for individual folder colour changes. So it depends on what you want to change, global folder colour or/and individual folder colour :)

**Comment by dirtydancing** [comment]
And yes, if you only want to change the global/default folder colour, Folder Color is not necessary.

**Comment by xploshioOn** [comment]
nice, I used the script and work very nice, simple. thanks.! ill close it again hehe then ill let both to use them as i want later, thanks.

**Comment by Zujiry** [comment]
Sorry to reopen this, but I can not find the script. Is there still the possibility to recolor items with a script or is it in work?

**Comment by bil-elmoussaoui** [comment]
@Zujiry https://github.com/numixproject/numix-folders

**Comment by Zujiry** [comment]
Thank you very much sir!

**Comment by bil-elmoussaoui** [comment]
@Zujiry You're welcome! :+1:
