### ISSUE TITLE
gtk-icons missing

### ISSUE THREAD

**Issue by hlechner** [numixproject/numix-icon-theme#315]
![image](https://cloud.githubusercontent.com/assets/11244067/6769951/2f3c1dea-d08f-11e4-8c8d-06f878a715e5.png)
Left to Right:

**1º line**:
- [x] gtk-color-picker
- [x] gtk-connect
- [x] gtk-convert #284 #300 
- [x] gtk-dialog-authentication #285 
- [x] gtk-disconnect
- [ ] gtk-dnd
- [ ] gtk-dnd-multiple

**2º line**:
- [x] gtk-edit [#1309](https://github.com/numixproject/numix-icon-theme-circle/issues/1309)
- [x] gtk-select-color #284
- [x] gtk-select-font
- [x] gtk-index
- [x] gtk-undelete
- [x] gtk-orientation-landscape
- [x] gtk-orientation-portrait

**3º line**:
- [x] gtk-orientation-reverse-landscape
- [x] gtk-orientation-reverse-portrait
- [x] gtk-page-setup
- [x] gtk-print-error
- [x] gtk-print-paused
- [x] gtk-print-report
- [x] gtk-print-warning

Second gtk-dialog:
![image](https://cloud.githubusercontent.com/assets/11244067/6882493/7e685142-d565-11e4-8436-fffe9565f42c.png)
The second one is missing, that's why only the first appears.

- [x] gtk-caps-lock-warning
- [x] gtk-network

**Comment by hlechner** [comment]
Its possible also to run the script that I ran on screenshot, you just need the gtk-dialog:

```
#! /bin/sh

pmap(){
echo '<pixmap icon_size="6" tooltip-text="'$1'"><input file stock="'$1'"></input></pixmap>'
}
export MAIN_DIALOG='
<vbox><hbox>
'"$(pmap gtk-color-picker)"'
'"$(pmap gtk-connect)"'
'"$(pmap gtk-convert)"'
'"$(pmap gtk-dialog-authentication)"'
'"$(pmap gtk-disconnect)"'
'"$(pmap gtk-dnd)"'
'"$(pmap gtk-dnd-multiple)"'
</hbox><hbox>
'"$(pmap gtk-edit)"'
'"$(pmap gtk-select-color)"'
'"$(pmap gtk-select-font)"'
'"$(pmap gtk-index)"'
'"$(pmap gtk-undelete)"'
'"$(pmap gtk-orientation-landscape)"'
'"$(pmap gtk-orientation-portrait)"'
</hbox><hbox>
'"$(pmap gtk-orientation-reverse-landscape)"'
'"$(pmap gtk-orientation-reverse-portrait)"'
'"$(pmap gtk-page-setup)"'
'"$(pmap gtk-print-error)"'
'"$(pmap gtk-print-paused)"'
'"$(pmap gtk-print-report)"'
'"$(pmap gtk-print-warning)"'
</hbox>
<button cancel></button>
</vbox>
'

gtkdialog --program=MAIN_DIALOG
```

**Comment by ChuckDaniels87** [comment]
Great!

**Comment by ChuckDaniels87** [comment]
Maybe [this](https://git.gnome.org/browse/gtk+/tree/gtk/icons) could be useful.

**Comment by hlechner** [comment]
I found this documentation: https://developer.gnome.org/gtk2/stable/gtk2-Stock-Items.html

I based on this one and added two gtk-icons missing

**Comment by ChuckDaniels87** [comment]
@hlechner That link looks really nice! It seems all default gtk icons are there.

**Comment by wa4557** [comment]
gtk-network is actually not missing but already present in `places`

**Comment by Foggalong** [comment]
Anyone know what `gtk-dnd` is actually used for? The default icon isn't very descriptive

**Comment by bil-elmoussaoui** [comment]
i guess that this icon is used for drag and drop

**Comment by hlechner** [comment]
Hello Guys,

A long time I don't come here, Excellent job your doing BTW!

Screenshot of actual state of gtk-icons:
![image](https://cloud.githubusercontent.com/assets/11244067/8023866/8c50acf2-0cf4-11e5-989e-1af1839aa4b0.png)

As you can see the print-* are not being displayed, and I discover that these icons are not the same name of gtk names. for example I found on Faenza the ``gtk-print-error`` as ``print-error.svg`` and this one work there. Maybe the gtk-print-* needs a symlink  without ``gtk-``, but I haven't tested it yet.

And the gtk-network still without being displayed:
![image](https://cloud.githubusercontent.com/assets/11244067/8023890/83f9bc00-0cf5-11e5-8fa3-71af174d079c.png)

About the DND icons, Bil-elmoussaoui is correct:

GTK_STOCK_DND
```#define GTK_STOCK_DND              "gtk-dnd"```
The "Drag-And-Drop" icon.

GTK_STOCK_DND_MULTIPLE
```#define GTK_STOCK_DND_MULTIPLE     "gtk-dnd-multiple"```
The "Drag-And-Drop multiple" icon.

**Comment by hlechner** [comment]
Oh, Just now I recognized...

The Icon itself is displayed, but the icon color is so bright (for the dark panels) that is hard to notice that there is a icon there.

**Comment by wa4557** [comment]
Cool, looks good so far, a few of the icons are actually pretty good (a few aren't that great but I guess that's ok). Nevertheless I'm a little bit out of ideas concerning the `*-dnd` icons. I really can't derive anything from the original icons :( All I can think of is some kind of deviation from `gtk-copy` but no specific idea

**Comment by hlechner** [comment]
@wa4557 I'm using evopop-gtk-theme:
https://github.com/solus-project/evopop-gtk-theme

**Comment by hlechner** [comment]
This symlink works for the gtk-print-error:
``lrwxrwxrwx  1 root root   19 Jun  7 10:40 printer-error.svg -> gtk-print-error.svg``

The others 3 seems that do not follow the same order, if I find it I will share here

**Comment by wa4557** [comment]
I figured it out. The missing symlinks are `printer-error` `printer-paused` `printer-warning` and `printer-info`
![unbenannt](https://cloud.githubusercontent.com/assets/6475757/8024249/9cec703a-0d2d-11e5-9874-7171c516679e.png)

**Comment by hlechner** [comment]
Thanks @wa4557

**Comment by hlechner** [comment]
``gtk-network`` also doesn't call the ``gtk-network.svg`` icon.

it calls ``status/wired.svg`` or other file name with the same icon design.

**Comment by wa4557** [comment]
Yeah but that's good enough imo. I wouldn't fiddle with the icons from `status`

**Comment by palob** [comment]
If I recall correctly there are some more ``gtk-...`` action icons in the Mint-X theme.

**Comment by hlechner** [comment]
@palob yes, there are some icons named ``gtk-`` used by some applications, but I avoided add here because it seems that it's just a normal application's icon started with "gtk-" in name.

The real/official gtk icons seems to be documented on the following page:
- https://developer.gnome.org/gtk2/stable/gtk2-Stock-Items.html

But, anyway, that is why I didn't added other icons here, its possible to reopen this one and add here other icons or just create a new topic.

**Comment by palob** [comment]
Found even more in the gnome theme.
