### ISSUE TITLE
Mimetype: application/x-gramps-package

### ISSUE THREAD

**Issue by hlechner** [numixproject/numix-icon-theme#319]
Name: **Gramps package**
Mimetype: **application/x-gramps-package**
Possible extensions: **.gpkg**

Description: **Export of family tree of [GRAMPS](https://gramps-project.org/) software**

![image](https://cloud.githubusercontent.com/assets/11244067/6782555/9d882586-d153-11e4-93b7-18d44112c788.png)

Target file name: application-x-gramps-package.svg

**Comment by Foggalong** [comment]
I'm un-self-assigning this since it turns out I didn't have the time to do it I thought I would. If someone does do it though, make sure to relate it to the [Circle icon](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/gramps.svg).

**Comment by hlechner** [comment]
First drafts:
![image](https://cloud.githubusercontent.com/assets/11244067/11716731/13bd1650-9f33-11e5-84aa-07832e7abf66.png)![image](https://cloud.githubusercontent.com/assets/11244067/11716738/2116ff1e-9f33-11e5-9947-f2c1dac30c8d.png)

**Comment by bil-elmoussaoui** [comment]
The second one looks fine !

**Comment by Foggalong** [comment]
Second one :+1:

**Comment by hlechner** [comment]
![image](https://cloud.githubusercontent.com/assets/11244067/11721094/4348e640-9f49-11e5-9cd8-6d9169efe427.png)![image](https://cloud.githubusercontent.com/assets/11244067/11721102/4fb8ce18-9f49-11e5-80c8-bd81d06f1b12.png)![image](https://cloud.githubusercontent.com/assets/11244067/11721108/55c29b4a-9f49-11e5-9e47-2100346f666a.png)![image](https://cloud.githubusercontent.com/assets/11244067/11721114/5b175c34-9f49-11e5-956c-137a8547077c.png)![image](https://cloud.githubusercontent.com/assets/11244067/11721120/622f0be8-9f49-11e5-9b8f-230acab0ddf8.png)

**Alternatives:**
48:
![image](https://cloud.githubusercontent.com/assets/11244067/11721171/ab440536-9f49-11e5-8e26-886474f0ef59.png)
24:
![image](https://cloud.githubusercontent.com/assets/11244067/11721187/bfa31882-9f49-11e5-9b30-0962ec184e0b.png)![image](https://cloud.githubusercontent.com/assets/11244067/11721192/c4ec67c6-9f49-11e5-8f1d-055166d5fcfe.png)
16:
![image](https://cloud.githubusercontent.com/assets/11244067/11721195/ce1eedd2-9f49-11e5-87a0-4c5775372be5.png)

**Comment by wa4557** [comment]
I think it's good as is :+1:
