### ISSUE TITLE
Mimetype: text/x-iptables

### ISSUE THREAD

**Issue by hlechner** [numixproject/numix-icon-theme#320]
Name: **iptables configuration file**
Mimetype: **text/x-iptables**
Possible extensions: **.rules**

Description: **File that contains iptable rules.**
![image](https://cloud.githubusercontent.com/assets/11244067/6783869/fbb3249c-d15a-11e4-87d7-35aee0200f55.png)

Target file name: text-x-iptables.svg

**Comment by Foggalong** [comment]
I've been trying to work out what this icon should look like and just have nothing. Open to the floor

**Comment by palob** [comment]
A flame?
![test-iptab](https://cloud.githubusercontent.com/assets/7050624/8035758/7b6d8ed2-0df3-11e5-9734-e8b9ee3ae44d.png)
Needs to be a simpler design though. This one isn't recognisable at small sizes.

**Comment by hlechner** [comment]
Nice idea!
I like the flame symbol

**Comment by Foggalong** [comment]
Ooo, nice idea! Go with the second definitely

**Comment by palob** [comment]
So which one's the best flame design?
![flames_all](https://cloud.githubusercontent.com/assets/7050624/8066654/1d591a4a-0ee9-11e5-87b5-bfa5338ca1d7.png)

**Comment by Foggalong** [comment]
Preference would be 1. with the orange colour. I really love the style of 2 too, but for Numix consistency prefer the first
