### ISSUE TITLE
Bug: text-x-vcard.svg crashing nautilus

### ISSUE THREAD

**Issue by hlechner** [numixproject/numix-icon-theme#323]
Issue raised here just for collect needed information for raise a bug report into gnome bug tracker.

The file: **Numix/**size**/mimetypes/text-x-vcard.svg** is crashing nautilus when open a directory with this file on it. returning: segmentation fault

What is causing it is the nautilus preview having problem to render the symbol "@" in svg file so crash. if edit the line 77 and change "@" for something else it will work.

Could someone of you guys let me know if you face it too? Just try to access in nautilus the directory: **Numix/48x48/mimetypes/**

If it crash or not let me know with the following details:
- What is your linux distribuition?
- What is your gnome version?
- What is your nautilus version?

Better report it now, otherwise you guys can have this issue in the future.
Thanks!

**Comment by palob** [comment]
I had a crash in the past with symlinks pointing to each other after I had botched something.

Other than that possibly the issue could be about the **@** not converted to path in the svg.

**Comment by hlechner** [comment]
Thanks for your feedback.

When I locate the file I just copy it to another directory, keeping the file alone on it.

Actually I'm a complete ignorant in svg file, i just open with a text editor and make some tests.

Here it's the part of code that is getting the problem:
```
  <text
     x="11.231547"
     y="34.912415"
     style="font-size:25.28473091px;line-height:125%;letter-spacing:0;word-spacing:0;fill:#888888;font-family:Ubuntu Mono"
     xml:space="preserve"
     transform="scale(1.0078875,0.99217427)"
     id="text10"
     sodipodi:linespacing="125%"><tspan
       x="11.231547"
       y="34.912415"
       style="font-weight:bold;font-family:Open Sans"
       id="tspan12">@</tspan></text>
```

In this case the **@** is just a visual symbol for this icon:
![image](https://cloud.githubusercontent.com/assets/11244067/6814003/5e385f02-d259-11e4-86a9-ba35f3f0f765.png)

I think you're in right direction, maybe it's converter by some path. Do you know if I can "escape" this symbol? I tried but without success

**Comment by palob** [comment]
Yep, so the **@** is a font letter here, not converted to path. That's not optimal but I don't know why that's a problem however. You most probably have *Open Sans* installed and otherwise there should be a fallback font in place.

**Comment by ChuckDaniels87** [comment]
Maybe a missing font, yep. Letters and symbols must be converted to path to avoid this kind of problems and others.

**Comment by hlechner** [comment]
@palob good point of view! The font is actually is a problem for distros like Arch Linux. That doesn't come with this font and also there isn't it inside the Arch repository. So the most of users will not search for it unless explicit needed, in this case its possible to get this font from AUR package.

Maybe a good way to show to Arch Linux's users that this theme needs this font is ask to the [numix-icon-theme-git](https://aur.archlinux.org/packages/numix-icon-theme-git/) AUR mainteiner include this font as **Optional Dependence**, so this svg file for example will be displayed correct for who install the option dependence. What you think @Foggalong ?

Maybe it's a good idea to "catalog" the needed fonts, Arch Linux users like myself will thank so much! Because when I installed the font **Open Sans** it get it so better looking!!!

@ChuckDaniels87 I've installed the new font here in my system to test it, but it still getting crash :(

Do you know what I need to edit to test if is something related to path? Sorry, I'm stupid with svg technology

**Comment by ChuckDaniels87** [comment]
Icon must be fixed from Letter/Symbol to Path inside a SVG editor (Inkscape for example). It is an easy fix.

_This **Path** is not related with system paths, it is referred to vectorial representation. Check [this](http://graphicssoft.about.com/od/inkscape/ss/Cutting-Machine-Tips_2.htm) if you want more info._

**Comment by hlechner** [comment]
You guys rock! It solve the problem!

I just open with inkscape, click on symbol, Path > Object to Path, so, no problem with this one.

should I be aware of any other change needed? Otherwise I'll send a pull request of this change

**Comment by ChuckDaniels87** [comment]
You must have installed the original font before converting it to __Path__ or it will not display the original symbol.

**Comment by palob** [comment]
@hlechner Arch Linux "doesn't come" with OpenSans because it provides you with basically nothing at all preinstalled. :smirk:
I'd say it's the most generic free as in freedom font out there.

**Comment by hlechner** [comment]
@palob  You're totally right, sorry I've expressed myself very badly on this explanation. (BTW, My English skill doesn't help me some much, There is a lot to improve on it)

Basically, On arch Linux, the system will install a little few fonts just for the system basic usage, and after it when installing an application/program some fonts will be install as dependence. For example, when installing Gnome, will be there some fonts required by gnome and their dependencies.

After it, Arch Linux's users will use the Arch Wiki as reference (In my opinion one of the best wiki ever of Linux distros), and for Fonts they will access the following page:
- https://wiki.archlinux.org/index.php/fonts

It will guide users like me in some suggestions, to simplify: There is some "package groups" that install some kind of fonts and there is some individuals fonts suggested on there too.

However the Open Sans it's not mention there, so users like me, will install this font only if some program depend on it, otherwise most of us will not even know about this font.

That's why its a good idea to suggest as optional dependence a font on the package.

If it's the only icon that needs this font to render a symbol it should be ok now, after apply the fix suggested by you guys.

**Comment by palob** [comment]
If you need some more fonts you could install the *google-fonts* package from the AUR.
It's a bit big though, since it will install all fonts from here:
https://www.google.com/fonts
(collection of freely licensed fonts)
