### ISSUE TITLE
Additional percentage level battery status icons in fixed size directories 16, 22 and 24

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-icon-theme#331]
Following-up on my comment over at https://github.com/numixproject/numix-icon-theme/issues/107#issuecomment-76519738, I have done some testing with the additional percentage battery status icons introduced for Ubuntu 15.04 for 10%, 30%, 50%, 70%, 90%:

These (tested with testing battery icons size 22x22) are already working in current daily Ubuntu 15.04, and at the same time they do not cause any breakage in Ubuntu 14.10, which simply does not pick up these additional battery status icons. Also tested against elementary OS Freya Beta 2, based on Ubuntu 14.04 LTS: just like in Ubuntu 14.10, the additional battery status icons simply do not get picked up.

These additional icons are useful because they provide a finer granulation, and because they address the issue of a too early warning status with the present icons, cf. bug report at https://bugs.launchpad.net/ubuntu-ux/+bug/1388235.

Screenshots when tested simultaneously against Ubuntu 14.10 (above) and Ubuntu 15.04 (VM, below):

![battery_28](https://cloud.githubusercontent.com/assets/7164227/6851092/37191382-d3dd-11e4-98f3-2156d509ca24.png)

![battery_20](https://cloud.githubusercontent.com/assets/7164227/6851094/3bd24c18-d3dd-11e4-91c0-97b51a00b9e2.png)

![battery_14](https://cloud.githubusercontent.com/assets/7164227/6851096/3f4578b6-d3dd-11e4-856a-284631adc656.png)

![battery_9](https://cloud.githubusercontent.com/assets/7164227/6851099/43f77ef4-d3dd-11e4-8b68-95ba842d121d.png)

![battery_4](https://cloud.githubusercontent.com/assets/7164227/6851103/47a83944-d3dd-11e4-8d41-ef2822290fde.png)

![battery_charging-2](https://cloud.githubusercontent.com/assets/7164227/6851108/4d2b1b70-d3dd-11e4-9adf-21803e509489.png)

![battery_charging-5](https://cloud.githubusercontent.com/assets/7164227/6851111/515b7d5c-d3dd-11e4-83fd-1c0c0b2a736f.png)

![battery_charging-21](https://cloud.githubusercontent.com/assets/7164227/6851121/56fa46f8-d3dd-11e4-865c-8a5690da64cd.png)

![battery_charging-35](https://cloud.githubusercontent.com/assets/7164227/6851127/5b12693c-d3dd-11e4-9047-48b63c2e26e3.png)

![battery_charging-90](https://cloud.githubusercontent.com/assets/7164227/6851165/991aaeec-d3dd-11e4-82bb-212282f0efbf.png)

This is how these additional battery status icons (10%, 30%, 50%, 70%, 90%) could be fit into the present ones, which in this overview have been left untouched (additionally all selected for visual contrast).

![battery-new-levels](https://cloud.githubusercontent.com/assets/7164227/6851207/e0fb4032-d3dd-11e4-8844-f871553d6d07.png)

![battery-new-levels2](https://cloud.githubusercontent.com/assets/7164227/6851216/f1a88174-d3dd-11e4-8fdc-df15eb38cf7a.png)

I would create a pull request for these myself, but I am not yet very familiar with Inkscape (for the icon overview above I just scaled the already existing bars, which of course does not work for the charging status battery icons).

@wa4557 Are you interested in contributing these? For bar height in the screenshots above, I used px (new sizes bold) **2,5** orange - 4 orange - **5,5** - 7 - **8,5** - 10 - **11,5** - 13 - **14**. In addition, the battery icons seem to use #dedede instead of #dcdcdc, so this might be an opportunity to make these consistent as well. From my perspective, adding these battery status icons makes sense even if there is a status icons redesign in the future, because this establishes a baseline on which such redesign could build upon.

The additional battery status icons in question here are marked yellow in this overview:

![ca8cdf3c-bf37-11e4-8d9b-a2d16276d471](https://cloud.githubusercontent.com/assets/7164227/6851918/18c38d2c-d3e2-11e4-8b3a-00b8c5b82f49.png)

**Comment by wa4557** [comment]
Sure I'm happy to do that :)

**Comment by dirtydancing** [comment]
Fantastic! :-)

**Comment by wa4557** [comment]
@dirtydancing Can you push the icons you did (without the charger) push to a branch of your numix-fork? There's no point in doing them twice...

**Comment by dirtydancing** [comment]
@wa4557 Pushed the icons from the overview above to the folder `testing-battery-22x22` in the branch `testing-battery` https://github.com/dirtydancing/numix-icon-theme/tree/testing-battery

**Comment by wa4557** [comment]
Fantastic thanks, since the new status icons arrived, there won't be any double work neither
