### ISSUE TITLE
Keyboard Indicators Not Updated

### ISSUE THREAD

**Issue by Foggalong** [numixproject/numix-icon-theme#332]
The keyboard language indicators have not been updated to the new design because they're being redesigned by @me4oslav

**Comment by Lumpenhund** [comment]
Imho the current keyboard icon is a bit too big therefore i would prefer one which fits better with the other Numix icons.

**Comment by Foggalong** [comment]
Yeah, @me4oslav is redesigning them while he updates them to the new style so hopefully they'll gel with the rest of them a bit better :)

**Comment by dirtydancing** [comment]
![panel_ubuntu1410](https://cloud.githubusercontent.com/assets/7164227/7107578/3d8cab04-e169-11e4-800d-88293eec39bc.png)

This is current Numix base via PPA in Ubuntu 14.10, and indeed the icon is somewhat large. But also, and possibly more irritating, it is noticeably darker than all the other panel icons with the new `#ececec`.

@wa4557 Btw, did you manage to get hold of your script? :) Might be of use for the redesign as well.

**Comment by wa4557** [comment]
@Foggalong Would you consider using community contributions as well? (Maybe even until better icons are designed by some professional - designers; my tray looks not good with this heavy and wrongly coloured icon). I would suggest something as in #622

**Comment by Foggalong** [comment]
@cldx is in the process of scripting these icons so you'd be better asking him :)

**Comment by bil-elmoussaoui** [comment]
Fixing this will fix a lot of missing icon in Elementary #437!  I really wish this can be fixed asap

**Comment by wa4557** [comment]
@Foggalong can be closed I guess
