### ISSUE TITLE
symbolic links referencing one another

### ISSUE THREAD

**Issue by wa4557** [numixproject/numix-icon-theme#334]
You have a somehow serious symlink problem that needs to be sorted out:

deluge.svg points to deluge-panel.svg in 22x22/status and
deluge-panel.svg points to deluge.svg

one of them mustn't be a symlink, and this error causes nemo to break with a Segmentation fault

**Comment by palob** [comment]
Is it just for 22x22?

**Comment by wa4557** [comment]
Yeah, those icons are missing in 24x24/status and 16x16/status and in Numix-Light all the symlinks are gone so no problem there as well

**Comment by dirtydancing** [comment]
Yep, just to confirm with the current PPA version with status from yesterday: when trying to open the directory `22x22/status`, also Nautilus/Files crashes in Ubuntu 14.10.

Great to see that this has already been located and fixed!
