### ISSUE TITLE
Request: Mimetype: application/json

### ISSUE THREAD

**Issue by hlechner** [numixproject/numix-icon-theme#336]
Name: **JSON document**
Mimetype: **application/json**
Possible extensions: **.json**

![image](https://cloud.githubusercontent.com/assets/11244067/6866393/793243a0-d456-11e4-95ee-15e3ec369ba4.png)
Target file name: application-json.svg

**Comment by hlechner** [comment]
Some tries:
![image](https://cloud.githubusercontent.com/assets/11244067/6866440/0015778e-d457-11e4-93df-984f8261ef67.png)
![image](https://cloud.githubusercontent.com/assets/11244067/6866444/0945b8f0-d457-11e4-8c6b-46a60487e7b0.png)

**Comment by palob** [comment]
Or just a symlink to the JS mime?

**Comment by hlechner** [comment]
Ooops, I didn't realize that there is a JS mime. I'll look into it

**Comment by hlechner** [comment]
The idea of use it's very good due to this format is based on JavaScript programming language.

But in other hand it's independent from programming language, used by many as substitute of XML for save data in file.

Or maybe a JS mime in blue color? What you think?

**Comment by palob** [comment]
There is nothing blue about JSON, or is it?
So I'd rather say a plain symlink or something with a simplified (monochrome) JSON logo.

I can giving it a shot when I have time next week, or will you be working on it?

**Comment by hlechner** [comment]
Apparently not, the blue seems to be used by many just for designer preferences, the icon itself is monochromatic.

If you can take a look will be nice! I've just tried something but I'm not a good designer.

But don't worry, take look when you have a time. Thanks!

**Comment by Foggalong** [comment]
![json](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/JSON_vector_logo.svg/160px-JSON_vector_logo.svg.png) that's the json logo, so maybe try and work that into it

**Comment by palob** [comment]
I'm working on this at the moment:
![application-json0](https://cloud.githubusercontent.com/assets/7050624/6886743/d4b1f9c0-d648-11e4-9ad9-cdcaa836f599.png)
![application-json0b](https://cloud.githubusercontent.com/assets/7050624/6886744/d93a6158-d648-11e4-9abb-e6922be23125.png)

Doesn't scale too well however:
![application-json-16](https://cloud.githubusercontent.com/assets/7050624/6886748/e90a387e-d648-11e4-9e3d-d737ab8b8979.png)

**Comment by palob** [comment]
It does when using two colours for the swirl but that would be a depart from the existing designs:
![application-json-16-2](https://cloud.githubusercontent.com/assets/7050624/6886772/5e089f94-d649-11e4-87c7-581a6eeb8b82.png)

**Comment by Foggalong** [comment]
Yeah, two colours doesn't seem to work so well. Might have to bight the bullet and go with the single colour variant

**Comment by palob** [comment]
Made a few tweaks and now it scales a bit better. PR ready in a moment.

**Comment by hlechner** [comment]
nice job!
