### ISSUE TITLE
Duplicated Light Icons

### ISSUE THREAD

**Issue by wa4557** [numixproject/numix-icon-theme#337]
Due to the redesign all the symlinks in Numix-Light disappeared and turned into regular files (I think that happens when using `sed` because it turns symlinks into regular files, and can be circumvented by using

`find $PATH -type f -name "*" ! -type l -exec sed -i 's/ececec/353535/' {} \;`

instead of regular sed).

I suppose that's not what you want, and you should change that

**Comment by Foggalong** [comment]
Ooo, I didn't realise we'd done this. Thanks for the correction, I'll bare that in mind for future :)

**Comment by wa4557** [comment]
Couldn't we just copy the whole folder 22x22/status (and 16x16/status and 24x24/status) from the normal theme to the light theme and afterwards run the fommand from above? This would ensure that both themes are exactly the same (except the color of course:)

**Comment by Foggalong** [comment]
That's a good idea :D you fancy doing it?

**Comment by wa4557** [comment]
Sure, but this might be a big pull request

**Comment by Foggalong** [comment]
Good point, I'll do it :)

**Comment by wa4557** [comment]
Q: All the icons that are in 22x22/status should also be in 16x16/status, shouldn't they? (Most of the time just scaled down accordingly, but sometimes different, just like the audio icons)

+They should be in 24x24/status with the same icon (size), but a 2px bigger canvas. Am I right? If yes there are quite a few icons missing in the 16x16 and 24x24 directories

**Comment by Foggalong** [comment]
Yeah, the whole status icon system is really messed up for Numix. The person who rolled out the last redesign and maintained them before I took them on only did this for 22px and didn't bother with 16px and 24px. Basically, we've been playing catch up ever since. Because of this they're inconsistent in design and coverage across both sizes even dark/light version colours. I really need to sit down one day and sort it all out :(

**Comment by wa4557** [comment]
Looking into that further, I recognized that my previous assumption was wrong. The symlinks are not turned into regular files, but those files are missing altogether. This means: all the files that are regular files in base are present in numix-light (except the ones with a color different from #ececec, but that's intentional), all the files that are symlinks in numix base are completely missing in numix-light (except the ones I added yesterday through my pull-requests) 
This might be a more serious bug, since Numix-Light inherits Numix (-base) and results in light-grey icons in Numix-light

**Comment by dirtydancing** [comment]
iirc, these symlinks have been missing in Numix-Light all along. That would mean that there is possibly no bug present here at all.

In the past, there has been some confusion about the symlinks in Numix-Light, please cf. e.g. https://github.com/numixproject/numix-icon-theme/issues/209#issuecomment-60239144. Also, Numix-Light has been created more recently than Numix base, so this might just be a case of catching up with Numix-Light (?).

However this may be, right now would be a good opportunity to streamline the symlinks in Numix and those in Numix-Light.

**Comment by wa4557** [comment]
Seeing the comment in #209 this seems to be indeed no bug at all

**Comment by dirtydancing** [comment]
Just to try and keep any confusion to a minimum: for the discussion relating to the symlinks in Numix-Light please cf. https://github.com/numixproject/numix-icon-theme/issues/360#issuecomment-87226611

**Comment by wa4557** [comment]
I created a pull-request for that, with which the status icons (except of the infamous circle base discussion, of course) should be finished. If this commit is merged I think we can close here...

**Comment by wa4557** [comment]
I'm closing this, because we have symlinks now :)
