### ISSUE TITLE
Notification icons symlinks wrongly turned into icon files

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-icon-theme#360]
This might be related to https://github.com/numixproject/numix-icon-theme/issues/337: all the icons in the new directory **`48x48/notifications`** are icon files now, although originally there were a couple of symlinks, cf. the screenshots over at this comment https://github.com/numixproject/numix-icon-theme/pull/283#issuecomment-81641127. These symlinks should return.

This goes for:

`battery-caution-symbolic.svg`
`notification-battery-empty.svg`
`notification-battery-low.svg`

@wa4557?

**Comment by wa4557** [comment]
@dirtydancing Dang, I think you're right. I changed the color using `sed` and this turned the symlinks into files. I'll change that

**Comment by hlechner** [comment]
@wa4557 when using sed, maybe its a good idea for using **--follow-symlinks** argument:
```
sed -i 's/old/net/g' symlink.txt --follow-symlinks
```

other way is to use find to locate only the files itself then exec the sed :)

**Comment by wa4557** [comment]
@hlechner Thanks; actually I usually do that, never do bugixing in a hurry :)
@Foggalong Should I delete all the symlinks in numix-light then and create a pull request, since they are unnecessary?

**Comment by dirtydancing** [comment]
@wa4557 Why are the symlinks in Numix-Light unnecessary? I would argue that they are all needed, because otherwise, the symlink from Numix base is picked up (as Numix-Light inherits Numix base), and the symlink in Numix base points to an icon file in Numix base, and thus the wrong light grey icon will be displayed in Numix-Light. Or is your question only relating to the notification icons, or to https://github.com/numixproject/numix-icon-theme/issues/337?

**Comment by wa4557** [comment]
Nope, I really think they are unnecessary because Numix-Light inherits Numix and uses the symlinks from Numix-light. But the symlinks are relative and are therefore pointing to the correct (the "dark") icons and not the light-grey ones

**Comment by wa4557** [comment]
Sorry posted at the wrong bug report :) Those symlinks are of course necessary

**Comment by dirtydancing** [comment]
Haha, by now I am really getting confused :-) So from your perspective, in Numix-Light, which symlinks are unnecessary and which symlinks are necessary?

**Comment by wa4557** [comment]
All symlinks (without exception) in Numix-Light are unnecessary (but not harmful). The symlinks in 48x48/notification are of course necessary :)

**Comment by dirtydancing** [comment]
Agreed that the symlinks in 48x48/notifications are necessary.

Not agreed (as of now) that all the symlinks in Numix-Light are unnecessary. Do you mean that they are unnecessary because in Numix-Light all icon names are covered by actual icon files (which is currently not the case). Or do you mean that all the symlinks in Numix base will also cover Numix-Light and thus Numix-Light does not need those? This is not the case. You write: "Numix-Light inherits Numix and uses the symlinks from Numix-Light". Which symlinks from Numix-Light, if there are no symlinks in Numix-Light? You further write: "the symlinks are relative..." Exactly: they are relative (and rightly so), and thus a symlink in Numix base is pointing to an icon file in Numix base, not in Numix-Light. Correct? So a light grey icon will be displayed. As an example, that is exactly the situation that occured in https://github.com/numixproject/numix-icon-theme/issues/209 with the fix of adding a symlink in Numix-Light, cf. https://github.com/numixproject/numix-icon-theme/pull/278.

**Comment by wa4557** [comment]
Uses the symlinks from Numix of course (edited my previous post). 
A symlink in numix base is pointing to an icon in numix-base, I think we can agree on that :)

numix-light inherits the numix-base symlinks but since they are relative, they are no longer pointing to a numix-base icon but rather to a numix-light icon when using the numix-light theme. This means that even if numix-light uses symlinks from numix-base they are pointing to dark icons. This is how I understand it at least :)

**Comment by dirtydancing** [comment]
Agreed that a symlink in Numix base is pointing to an icon in Numix base :-)

Not agreed that a symlink in Numix base is pointing to an icon in Numix-Light only because Numix-Light comes before Numix base in the inheritance line. The symlink in Numix base will then not kind of "jump back in the inheritance line" to Numix-Light. This did not happen for the symlink `nm-device-wired.svg`, and I do not see why this should be happening for any other symlink :-)

The good news from all of this is that Numix-Light simply needs to have all the (relative) symlinks that Numix base has, they can just be copied over (as they are relative), and all wil be set.

**Comment by wa4557** [comment]
Ok, you are maybe right, I never tested it myself; this is just what I got from the comment from Foggalong. Well ok if this is the case, this should be an easy fix

**Comment by dirtydancing** [comment]
Yeah, once more the inheritance lines playing one of their dirty tricks, confusion guaranteed :-)
