### ISSUE TITLE
Request: Mimetype: application/x-subrip

### ISSUE THREAD

**Issue by hlechner** [numixproject/numix-icon-theme#362]
Name: **SubRip subtitles**
Mimetype: **application/x-subrip**
Possible extensions: **.srt**

Description: **File responsible for provide subtitles for movies/videos** (very common for non-English speakers)
![image](https://cloud.githubusercontent.com/assets/11244067/6881082/2154f20c-d52f-11e4-8fcc-82d60bf85435.png)
Target File name: application-x-subrip.svg

**Comment by hlechner** [comment]
Could be something based on Numix-Circle/48x48/apps/gnome-subtitles.svg

Just as idea:
![image](https://cloud.githubusercontent.com/assets/11244067/6881160/3db7203e-d532-11e4-9eb0-0a9b3ec186db.png)

**Comment by palob** [comment]
Get rid of the shadow, make the symbol white+align it to the grid for all sizes and I think this could be merged.
