### ISSUE TITLE
Missing icons in 16x16/status and 24x24/status

### ISSUE THREAD

**Issue by wa4557** [numixproject/numix-icon-theme#368]
Since the overhaul of the status icons is now complete, I thought about ironing out the last inconsistencies. One thing is, that there are currently a lot of icons missing in 16x16/status and 24x24/status (numix-base and numix-light). 
1) Icons in 16x16/status are used in dropdown menus of appindicator-icons in Ubuntu for example (keyboard-indicator-icons is a good example for that; or the icons in the soundmenu)
2) Icons in 22x22/status are usually the icons Ubuntu uses for the status appindicator icons and 
3) Icons in 24x24/status are used by xfce distributions (Kubuntu for example or elementary) as their status icons (cf. #258 or #1601 in numix-circle-repo)

as for the design: the icons in 16x16/status are usually just scaled down versions of the ones in 22x22/status (although there are some unique designs as well)

the icons in 24x24/status should be designed in such a way that the icon itself stays the same (same size and position, as in 22x22/status), but the canvas size changes from 22x22 to 24x24

I'll make a task list, which shows all icons that are present in 22x22/status but not in the other sizes

- [x] brasero.svg
- [x] btsync-gui-*
- [x] disper-panel.svg
- [x] fluxgui.svg
- [x] gnome-mplayer.svg
- [x] google-chrome-beta.svg
- [x] google-chrome.svg
- [x] google-chrome-unstable.svg
- [x] hb-icon.svg
- [x] indicator-sound-switcher-panel.svg
- [x] indicator-weather.svg
- [x] nitroshare.svg
- [x] nvidia.svg
- [x] owncloud-client.svg
- [x] evernote.svg
- [x] everpad.svg
- [x] everpad-mono.svg
- [x] pamac-tray-no-update.svg
- [x] pamac-tray-update.svg
- [x] pidgin.svg
- [x] psensor_hot.svg
- [x] psensor_normal.svg
- [x] psensor.svg
- [x] qbittorrent.svg
- [x] redshift-status-off.svg
- [x] redshift-status-on.svg
- [x] spotify-client.svg
- [x] state-error.svg
- [x] state-information.svg
- [x] state-offline.svg
- [x] state-ok.svg
- [x] state-pause.svg
- [x] state-sync.svg
- [x] syspeek-0.svg
- [x] syspeek-100.svg
- [x] syspeek-10.svg
- [x] syspeek-20.svg
- [x] syspeek-30.svg
- [x] syspeek-40.svg
- [x] syspeek-50.svg
- [x] syspeek-60.svg
- [x] syspeek-70.svg
- [x] syspeek-80.svg
- [x] syspeek-90.svg
- [x] touchpad-indicator-light-disabled.svg
- [x] touchpad-indicator-light-enabled.svg
- [x] touchpad-indicator-light.svg
- [x] vlc.svg
- [x] xfce4-notes-plugin.svg
- [x] xnoise.svg
- [x] y-ppa-indicator.svg

If everyone is ok with that, I'll go through this list and contribute the corresponding icons

**Comment by bil-elmoussaoui** [comment]
If you can add #296 , #295 , #312 , #257  , #265 , #250 , #151 if you want to of course :smiley: 
those are all the status icons (panel ones too)

**Comment by wa4557** [comment]
Ohne thing after the another :-) for these icons there aren't even icons in 22x22/status

**Comment by dirtydancing** [comment]
@wa4557 Just wondering: I noticed that in **Numix-Light**, currently `redshift-status-off.svg` is missing, cf. also https://github.com/numixproject/numix-icon-theme-circle/issues/1286. Did you already add that one? Please also cf. https://github.com/numixproject/numix-icon-theme/issues/382 (relating to the Redshift status icons in Numix base) for design consistency (no "glow" in the light bulb).

**Comment by wa4557** [comment]
@dirtydancing Nooo, I thought I covered all of them :) Ok I have to wait till all my pull requests are merged, I think I can remember that I added a redshift icon in one of them. If it doesn't come up, well than I'll propose a final pull request

**Comment by wa4557** [comment]
Closing this because all the status icons are now covered in all sizes 
@bil-elmoussaoui Why not open a new issue with a similar task list that covers your suggestions? I'm interested in doing a few of them (I'm not a great designer though :-)
