### ISSUE TITLE
New Dropbox icons?

### ISSUE THREAD

**Issue by Foggalong** [numixproject/numix-icon-theme#369]
I'll have to check we haven't already got them, but these are transfered from [this issue](https://github.com/numixproject/numix-icon-theme-circle/issues/1389) in Circle.

    dropbox /opt/dropbox/images/emblems/emblem-dropbox-selsync.png
    dropbox /opt/dropbox/images/emblems/emblem-dropbox-syncing.png
    dropbox /opt/dropbox/images/emblems/emblem-dropbox-unsyncable.png
    dropbox /opt/dropbox/images/emblems/emblem-dropbox-uptodate.png
    dropbox /opt/dropbox/images/hicolor/16x16/status/dropboxstatus-blank.png
    dropbox /opt/dropbox/images/hicolor/16x16/status/dropboxstatus-busy.png
    dropbox /opt/dropbox/images/hicolor/16x16/status/dropboxstatus-busy2.png
    dropbox /opt/dropbox/images/hicolor/16x16/status/dropboxstatus-idle.png
    dropbox /opt/dropbox/images/hicolor/16x16/status/dropboxstatus-logo.png
    dropbox /opt/dropbox/images/hicolor/16x16/status/dropboxstatus-x.png
    dropbox /usr/share/pixmaps/dropbox.png

**Comment by wa4557** [comment]
There seems to be everytging in place. The only one that's missing is dropboxstatus-blank.svg but that's just an completely empty svg, so not needed. Everything else is there. I suppose this can be closed

**Comment by bil-elmoussaoui** [comment]
@wa4557 this is not the case in ubuntu gnome :/ the icons are not detected at all 
![screenshot from 2015-05-27 22-19-55](https://cloud.githubusercontent.com/assets/7660997/7846551/85699ce8-04be-11e5-8cb8-9396375f9a07.png)

**Comment by bil-elmoussaoui** [comment]
Ok, i've the solution :smile: 
the dropbox installer uses the icons that are in 
```
/home/bilal/.dropbox-dist/dropbox-lnx.x86_64-3.6.4/images/hicolor/16x16
```
instead of  ``` usr/share/icons/hicolor/``` so yeah, dropbox is hardcoded now :s i can add this to the Hardcode-Tray Fixer

**Comment by wa4557** [comment]
In ubuntu unity it looks fine :)

**Comment by bil-elmoussaoui** [comment]
In all the cases there's no need for new dropbox icons

**Comment by wa4557** [comment]
agreed

**Comment by Foggalong** [comment]
Silly Dropbox. Someone should drop them a message to let them know

**Comment by bil-elmoussaoui** [comment]
This has been fixed now using Hardcode Tray fixer :P if someone do, please share the link 
![screenshot from 2015-05-28 00-44-40](https://cloud.githubusercontent.com/assets/7660997/7849160/ca64eb9a-04d2-11e5-9fae-5da52a24c0a1.png)
