### ISSUE TITLE
Mimetype: application/vnd.tcpdump.pcap

### ISSUE THREAD

**Issue by hlechner** [numixproject/numix-icon-theme#379]
Name: **Network Packet Capture**
Mimetype: **application/vnd.tcpdump.pcap**
Possible extensions: **.cap** **.pcap**

Description: **Packet capture from network, produced by softwares like tcpdump**
![image](https://cloud.githubusercontent.com/assets/11244067/6882939/88d8b264-d576-11e4-97ab-f1bd5d53b5dc.png)

**Comment by hlechner** [comment]
Just some ideas, maybe not good enough but just to try something:
- A matrix-style (movie) letters/symbols
- Eye symbol (nmap style)

**Comment by hlechner** [comment]
I couldn't dedicate time on it, but just to demonstrate a different idea:
![image](https://github-cloud.s3.amazonaws.com/assets/11244067/10566333/34d0bc78-75c3-11e5-9865-7060313ab0e8.png)
based on: ``devices/nm-device-wired.svg`` and ``mimetypes/application-octet-stream.svg``

I know that this icon doesn't fit on Numix style, and maybe could be a little hard to implement on very low sizes, but, anyway, its just a idea that could be developed from it

**Comment by hlechner** [comment]
First drafts:
![image](https://cloud.githubusercontent.com/assets/11244067/11729156/e8aab0c0-9f74-11e5-9c86-d046413a26f0.png)![image](https://cloud.githubusercontent.com/assets/11244067/11729162/f2cbc54e-9f74-11e5-90cf-6c63ecc14b0f.png)

Does someone have any better idea for this mime?

**Comment by Foggalong** [comment]
Nice idea, but circle alignment will have to be on point

**Comment by hlechner** [comment]
![image](https://cloud.githubusercontent.com/assets/11244067/11735231/18388f3e-9fa6-11e5-9db6-058afbd802ec.png)![image](https://cloud.githubusercontent.com/assets/11244067/11735236/2123e1fc-9fa6-11e5-84c0-ff01d7a4844e.png)![image](https://cloud.githubusercontent.com/assets/11244067/11735237/28d94edc-9fa6-11e5-8685-de0b1c26158f.png)![image](https://cloud.githubusercontent.com/assets/11244067/11735242/2fe28716-9fa6-11e5-8456-899cd5aef79d.png)![image](https://cloud.githubusercontent.com/assets/11244067/11735244/3590a562-9fa6-11e5-970e-a0aa02e52e7d.png)

I'm having kind of trouble to perfectly align the circles because of stroke, but maybe you guys can give a hand or some tips.

**Comment by Foggalong** [comment]
Don't use stoke in icons, always just paths. It makes alignment harder and causes problems with librsvg

**Comment by hlechner** [comment]
I didn't know about strokes, if i understood i can convert the stroke to path and it will be ok to use, right?

**Comment by Foggalong** [comment]
Yeah, stoke to path works fine as long as then it's aligned properly :)

**Comment by hlechner** [comment]
![image](https://cloud.githubusercontent.com/assets/11244067/11748485/b2b31804-a00f-11e5-83e7-622e281c3578.png)

What you think?

Here the result:
![image](https://cloud.githubusercontent.com/assets/11244067/11748630/4bd8cdd0-a010-11e5-9c1d-329a11cf9702.png)

**Comment by wa4557** [comment]
I think it's a bit hard to recognize. Maybe make the magnifiyng glass a bit thinner? (3px instead of 4px for largest size, less for smaller sizes of course) but keep the inner 01 pattern as is...

**Comment by hlechner** [comment]
![image](https://cloud.githubusercontent.com/assets/11244067/11749025/7c1a840a-a012-11e5-90e3-4a814108248a.png)

Good suggestion @wa4557

**Comment by hlechner** [comment]
![image](https://cloud.githubusercontent.com/assets/11244067/11753102/84b800d4-a02a-11e5-9e33-6954a8a9545e.png)![image](https://cloud.githubusercontent.com/assets/11244067/11753078/6de69c30-a02a-11e5-96a6-c4436a499516.png)![image](https://cloud.githubusercontent.com/assets/11244067/11753083/75444b4e-a02a-11e5-813e-49a16b00544d.png)![image](https://cloud.githubusercontent.com/assets/11244067/11753122/94d5aeda-a02a-11e5-8143-8b7394d8761d.png)![image](https://cloud.githubusercontent.com/assets/11244067/11753132/9ddb9ee0-a02a-11e5-93f3-7cef3b5fd67e.png)

**Comment by Foggalong** [comment]
Looking good!

(CC: @Albyxyz)
