### ISSUE TITLE
Wrong Transmisson style

### ISSUE THREAD

**Issue by Foggalong** [numixproject/numix-icon-theme#405]
@wa4557 when I told you which style to update the transmission icons to you did the wrong one :P This is the style that's wanted, the 16px version was just like it was because the arrow didn't scale very well. Sorry for the confusion!
![screenshot - 300315 - 12 13 10](https://cloud.githubusercontent.com/assets/5920259/6895272/65a389ca-d6d6-11e4-87d2-7a25a001c075.png)

**Comment by wa4557** [comment]
Ah ok, I'll change that asap. I agree this one looks better :)

**Comment by wa4557** [comment]
But to be fair you told me to do the other one #356 :P

**Comment by Foggalong** [comment]
Yeah, it was just the confusion with the 16px one being different to what it was in 22px and 24px because of scaling. If you can make this one work in 16px though feel free to use that one. It'll match the app icon too :)
