### ISSUE TITLE
Icons for the MAME emulation collection.

### ISSUE THREAD

**Issue by kmdude344** [numixproject/numix-icon-theme#420]
I noticed that if you download the packages MAME, MESS, and the shared fronted for both of them, the numix circle icon pack does not automatically give them icons. There also is no icon for the Gnome video arcade. Hope you fix this soon!
![screenshot from 2015-04-01 13 12 13](https://cloud.githubusercontent.com/assets/7883767/6949511/0f7f406e-d872-11e4-9911-a08ff0202272.png)

**Comment by Foggalong** [comment]
Please post seperate requests for each icon, and follow the procedure set out in the readme. Makes it a bit easier for us :)
