### ISSUE TITLE
Chrome icon became monochrome

### ISSUE THREAD

**Issue by pgera** [numixproject/numix-icon-theme#422]
Sometime last week, after an update from the ppa, the chrome icon turned white. This sounds similar to https://bugs.launchpad.net/numix-icon-theme-circle/+bug/1328307, although I'm not using circle. For me, the base theme is affected. Circle seems all right.

**Comment by Foggalong** [comment]
You're right in that they're similar issues. This is a duplicated of #192 though, so see there for more info :)
