### ISSUE TITLE
Update Other Battery Icons

### ISSUE THREAD

**Issue by Foggalong** [numixproject/numix-icon-theme#432]
We've focused a lot on getting the main battery icons sorted but at the same time the other battery icons have fell behind. It'd be nice if the others were updated to the new style too:

* [x] Mouse (think we're going with [this](http://stayl.deviantart.com/art/Mouse-battery-level-Numix-status-icons-501288081))
* [x] Keyboard
* [x] Phone

**Comment by wa4557** [comment]
@Foggalong I can do that if you want :)

**Comment by Foggalong** [comment]
@wa4557 We'll probably have an internal talk first about what direction we want to go in with the Keyboard and Phones ones, either keeping a battery alongside or switching to the same style as the Mouse

**Comment by wa4557** [comment]
Sure thing, was more thinking about the mouse ones.

**Comment by Foggalong** [comment]
Oh right! In which case feel free to do it :D

**Comment by wa4557** [comment]
Mockup for keyboard:
![keyboard](https://cloud.githubusercontent.com/assets/6475757/7570826/7442328e-f813-11e4-9cea-b9f73b73c1d9.png)

**Comment by Foggalong** [comment]
Really like the idea of the phone one, though it wouldn't really work for battery levels that were white :/

**Comment by Foggalong** [comment]
@wa4557 feel free to go ahead with the keyboard one though :)

**Comment by wa4557** [comment]
@Foggalong What do you think about this one?
![bildschirmfoto vom 2015-09-13 15 28 21](https://cloud.githubusercontent.com/assets/6475757/9836898/2cb006fa-5a2c-11e5-85f4-f2cd7a4fdb8e.png)

**Comment by Foggalong** [comment]
Love it :D

**Comment by wa4557** [comment]
Cool I'll prepare a push :)

Joshua Fogg <notifications@github.com> schrieb am So., 13.09.2015, 15:50:

**Comment by Foggalong** [comment]
:+1:

**Comment by bil-elmoussaoui** [comment]
I don't know where those icons are used ? :)

**Comment by Foggalong** [comment]
It's as a replacement for [this series](https://github.com/numixproject/numix-icon-theme/blob/master/Numix-Light/24x24/status/gpm-phone-020.svg) of icons
