### ISSUE TITLE
Remove blueman-tray.svg from fixed size directories 16x16, 22x22 and 24x24

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-icon-theme#439]
Numix base contains `blueman-tray.svg` which is a symlink pointing to the target `bluetooth-active.svg`. After https://github.com/numixproject/numix-icon-theme/issues/312 it appears that the only blueman icons needed here are `blueman-active.svg` and `blueman-disabled.svg`. This would also simplify things, because then there would be a consistent icon naming with `bluetooth*` and `blueman*`.

In conclusion, unless there is a specific reason to keep it, I would suggest to remove `blueman-tray.svg`.

**Comment by Foggalong** [comment]
As long as it's not causing any problems there's no reason to remove it :) It could well still be being used by  a legacy system.

**Comment by dirtydancing** [comment]
Sure thing! :) I was just thinking about cleaning up a bit.

**Comment by Foggalong** [comment]
Not a problem! The work you put in is much appreciated :)

After I've finished either Circle & Folders I'm  gonna come back to base and assess all these pull requests and issues more thoroughly.

**Comment by amithm7** [comment]
Can we reopen this issue? The numix base icon overrides the numix circle's bluetooth icon. I can no longer get bluetooth-active (green icon) when connected to my headphone.

**Comment by palob** [comment]
Can you show a screenshot? What's you DE?

**Comment by amithm7** [comment]
![screenshot from 2017-07-22 22-08-49](https://user-images.githubusercontent.com/7036770/28492953-72a1bdec-6f2a-11e7-9394-81d5086fb947.png)
![screenshot from 2017-07-22 22-07-36](https://user-images.githubusercontent.com/7036770/28492974-0846a196-6f2b-11e7-8900-f832a0e71572.png)
I am using GNOME 3 with Numix-circle, this icon is from the Numix base. I don't think it has anything to do with DE, i get the same icon on i3wm.
Numix-Circle's icon appears only when i remove the base theme.

**Comment by bil-elmoussaoui** [comment]
@amithm7 The Circle theme works only with the base theme.

**Comment by palob** [comment]
This is a spot where app icons aren't supposed to be displayed (and are blurry), so as long as there are distinct icons for active/inactive there isn't any issue for us to fix.

If you still want to see the Cirlce icon you can rename the respective files in your Numix base theme installation so they won't be picked up.

**Comment by amithm7** [comment]
@bil-elmoussaoui 
If when i remove the base theme, these are the icons i get:
![screenshot from 2017-07-22 22-23-46](https://user-images.githubusercontent.com/7036770/28493050-daf07ee0-6f2c-11e7-9b0e-dc893ccd380d.png)
![screenshot from 2017-07-22 22-24-00](https://user-images.githubusercontent.com/7036770/28493052-df399522-6f2c-11e7-8cd6-8b764bd93e3e.png)
![screenshot from 2017-07-22 22-24-21](https://user-images.githubusercontent.com/7036770/28493054-e1a48808-6f2c-11e7-8c2b-6af7dd3955b8.png)
Which is how it should be, but with base theme installed, it gets overridden by the icon from base pack, which doesn't have green icon for active state.

**Comment by bil-elmoussaoui** [comment]
Nop, those aren't the correct icons. Numix uses a monochrome icons for tray icons. We might use a slightly different color for connected state but not a colorful one like the ones in your latest screenshot

**Comment by amithm7** [comment]
@bil-elmoussaoui See this, this form Numix circle pack
https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48/apps/bluetooth-active.svg

**Comment by palob** [comment]
Maybe they even should be removed from Circle. Are there actually apps using them?

**Comment by wa4557** [comment]
@palob yes. The launcher changes the icon depending on the state of Bluetooth

**Comment by palob** [comment]
Which launcher was that again?

**Comment by wa4557** [comment]
The icons that show on the left side in Ubuntu. Also in the dash of Ubuntu I think.

**Comment by palob** [comment]
Blueman? Installed it and it doesn't for me.

**Comment by amithm7** [comment]
@palob 
You said i can rename them, but is so many in `16`, `22`... which ones should i rename?
Is there a way i can selectively choose not to inherit blueman's icon from base pack using config file of Numix-circle?
I just want icons for files and folder from Numix base pack. I am fine with just Numix-Circle otherwise.

**Comment by wa4557** [comment]
@palob at least the standard Ubuntu Bluetooth app does it

**Comment by wa4557** [comment]
@amithm7 this won't work. Numix uses monochrome icons for the tray. If you want colourful icons you should probably use a different theme

**Comment by palob** [comment]
It's interesting that in this case the base icons correctly override the Circle ones (instead of vice versa).

**Comment by wa4557** [comment]
Because of the symlinks in the panel folders

**Comment by palob** [comment]
Wait, so the tray picks up the base icon but the laucher picks up the app icons???

**Comment by wa4557** [comment]
Yes. Because the launcher asks for a 48px icon (which exists in circle) and the tray for a 22px icon (which also exists in circle because of symlinks)

**Comment by amithm7** [comment]
That's what i was wondering cause Numix base itself inherits from gnome and overrides it's icon but Numix-Circle which inherits from Numix can't override Numix icons!

**Comment by palob** [comment]
In GNOME this actually isn't a legacy tray icon, @amithm7 are you using blueman?
I don't know what's the actual icon shown there, sorry.

**Comment by amithm7** [comment]
@palob yes, i use blueman hence the tray icon. GNOME's bluetooth manager doesn't have any tray icon.

**Comment by palob** [comment]
@amithm7 Ideally there wouldn't be any overriding between Numix base and Numix Circle as both themes are complementary (both are incomplete on their own).

**Comment by amithm7** [comment]
Yeah, but i see what happens now.
With both base pack and Circle installed. For tray icon it looks for 22px/24px folder which symlink to Numix base theme's monochrome icons.
But when i remove the base theme, only 48px icons from Circle theme exist. Hence i get the coloured ones.

**Comment by palob** [comment]
Nice to see that in this case there is actually a sanity check in terms of icons size as supposed to action icons.

**Comment by amithm7** [comment]
So my problem is solved now that i have renamed `16`, `22` and `24` symlink folders in Numix-Circle.
