### ISSUE TITLE
Using HardcodeTray

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-icon-theme#445]
Hello everyone! 
I just released a stable version of HardcodeTray which fixes a lot of issues and support dark and light version, use symlinks insttead of copy and support different sizes. (22x22 in elementary OS and 24x24x other distributions)
https://github.com/bil-elmoussaoui/Hardcode-Tray

I did create a demo using Numix and the supported icons at the moment : 
- Touchpad indicator
- Grive-tools

First thing i created a folder in Numix named "extra" and created two folders for the two applications

![capture du 2015-04-09 14 13 44](https://cloud.githubusercontent.com/assets/7660997/7066405/b5c0d798-dec2-11e4-9fc9-f57bbf10ae12.png)
I add the two sizes
![capture du 2015-04-09 14 13 53](https://cloud.githubusercontent.com/assets/7660997/7066421/d021a752-dec2-11e4-9857-f317f7182315.png)
and then create a subfolder for dark and light version.
![capture du 2015-04-09 14 14 02](https://cloud.githubusercontent.com/assets/7660997/7066441/06a81270-dec3-11e4-8bc7-e9dd3fa5acd5.png)

I copied the icons from Numix base and Numix-light base to the extra folder, And then excute the script.py and everything works fine!
You can download the extra folder from here : https://www.dropbox.com/s/ykcf2g6umg169bt/extra.tar.gz?dl=0

My question is , Will Numix use this solutions to fix some hardcoded tray/indicators icons and support other applications? 

Thank you for reading!

**Comment by bil-elmoussaoui** [comment]
Well, we can forget about what i write here. After the last update! The script detect automagically if the icon exists in the theme and symlink it directly :smile:

**Comment by Foggalong** [comment]
Oh wait, so we don't need specific folders for it now and it'll just pick it up from the normal folders? That's awesome :D

**Comment by bil-elmoussaoui** [comment]
Yes! And auto-detect if the distro uses 22x22 sizes or 24x24 sizes for the status folder

**Comment by Foggalong** [comment]
Oh cool! How is it doing that?

**Comment by bil-elmoussaoui** [comment]
Well, with some help of @wa4557.In the database file, we put all the icon names in the hardcoded location. The script detect the default theme, and than look up if there's an icon with the same name and the right size (24x24 for elementary and xfce , 22x22 for other distro). If the original icon (the hardcoded one) is a png icon and the icon located in theme is a svg icon, the script convert the svg file to png and copy it to the hardcoded location. If not, the script creates only a symlink

**Comment by Foggalong** [comment]
That's really cool! I'm out of the house today, but when I'm back I'll have a play with it :)
