### ISSUE TITLE
Non-Numix outadated png icons [$5]

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-icon-theme#450]
Here's a list of some of icons in the numix icons that are png and not really looking like numix icons. 

 - [x] application-x-cue.png
 - [x] contact-editor.png
 - [x] folder-copy.png
 - [x] folder-move.png
 - [x] go-today.png
 - [x] im-aim.png
 - [x] im-icq.png
 - [x] im-jabber.png
 - [x] im-msn.png
 - [x] im-nov.png
 - [x] im-yahoo.png
 - [x] mail-copy.png
 - [x] mail-move.png
 - [x] offline.png
 - [x] online.png
 - [x] opera-extension.png
 - [x] preferences-autocompletion.png
 - [x] preferences-calendar-and-tasks.png
 - [x] preferences-certificates.png
 - [x] preferences-composer.png
 - [x] preferences-mail-accounts.png
 - [x] preferences-mail.png
 - [x] preferences-system-network-proxy.png
 - [x] query-free-busy.png
 - [x] stock_alarm.png
 - [x] stock_bell.png
 - [x] stock_check-filled.png
 - [x] stock_contact-list.png
 - [x] stock_insert-note.png
 - [x] stock_insert-rule.png
 - [x] stock_insert-table.png
 - [x] stock_mail-filters-apply.png
 - [x] stock_mail-flag-for-followup-done.png
 - [x] stock_mail-flag-for-followup.png
 - [x] stock_mail-open-multiple.png
 - [x] stock_mail-unread-multiple.png
 - [x] stock_new-24h-appointment.png
 - [x] stock_new-meeting.png
 - [x] stock_notes.png
 - [x] stock_people.png
 - [x] stock_score-high.png
 - [x] stock_score-higher.png
 - [x] stock_score-highest.png
 - [x] stock_score-low.png
 - [x] stock_score-lower.png
 - [x] stock_score-lowest.png
 - [x] stock_score-normal.png
 - [x] stock_select-column.png
 - [x] stock_select-row.png
 - [x] stock_shared-by-me.png
 - [x] stock_shared-to-me.png
 - [ ] stock_show-all.png
 - [x] stock_signature-bad.png
 - [x] stock_signature-ok.png
 - [x] stock_signature.png
 - [x] stock_task-assigned-to.png
 - [x] stock_task-assigned.png
 - [x] stock_task-recurring.png
 - [x] stock_task.png
 - [x] stock_text-monospaced.png
 - [x] stock_timezone.png
 - [x] stock_todo.png
 - [x] stock_video-conferencing.png
 - [x] stock_view-details.png
 - [x] text-xhtml+xml.png
 - [x] view-calendar-day.png
 - [x] view-calendar-list.png
 - [x] view-calendar-month.png
 - [x] view-calendar-week.png
 - [x] view-calendar-workweek.png
 - [x] wrapped.png

**Comment by bil-elmoussaoui** [comment]
I did this using this python script : 
```bash

**Comment by wa4557** [comment]
Oh my this are a lot of icons...
kazam is sorted out. 

What's going on with the mimetype icons? those are icons that are symlinked from svg icons. Does that make sense?

@bil-elmoussaoui You should really check out bash-programming, python is cool and all, but for this it makes this whole thing a LOT easier!

**Comment by bil-elmoussaoui** [comment]
I don't really know why a png icon is symlinked to an svg one? 
@wa4557 I will try it next time :+1:

**Comment by bil-elmoussaoui** [comment]
Just one question, why not moving the apps in 16x16,24x24,32x32,22x22,48x48 to Numix-Circle?

**Comment by Foggalong** [comment]
Because Numix Circle is for Circle app icons not just general icons. There are a few exceptions but we're slowly removing them rather than adding more :)

**Comment by wa4557** [comment]
@bil-elmoussaoui Plus I think that most of the icons in the apps directories in numix-base can be deleted without re-adding them. Most of them are pretty useless (e.g. im-yahoo etc... nobody needs them)

**Comment by bil-elmoussaoui** [comment]
I think they're used in some chat apps like pidgin or empathy?

**Comment by Foggalong** [comment]
Fixed all the mimetypes in this one 2f0418fd04db029ed937a07d21bfccb9f2d5bd72. For symlinks it doesn't actually matter what file extension you use (example below) but we use `.svg` as standard. The `application-x-cue.png` was a duplicated symlink too so wasn't actually needed to all.
![screenshot_2015-05-27_21-37-14](https://cloud.githubusercontent.com/assets/5920259/7846932/9698b1f8-04b8-11e5-9468-2843d4def4e2.png)

As for the rest of them, I'd sooner not remove them without adding something in their place (especially if we're going to look into dropping the inherits).

**Comment by wa4557** [comment]
So it's basically going through them and adding and designing new icons for them? Will this ever end? :P

**Comment by bil-elmoussaoui** [comment]
Doing this will make Numix a complete theme :D  and there's a lot of icons that can be used to fix too many issues like in #437 #61 #100 ...

**Comment by Foggalong** [comment]
@wa4557 @bil-elmoussaoui The work will literally never end. In theory with enough work it could get to a stable point where we were happy with it (like snwh is with Moka) but there'll always be things like GNOME messing around or Steam coming to Linux which make sure continuous maintained is needed.

**Comment by palob** [comment]
There are some non-Numix SVGs in ``devices``:
``device_mem.svg``
``gnome-dev-... .svg``
``media-flash-... svg``
``media-memory-... .svg``

For some sizes some do have a Numix design though.

**Comment by Foggalong** [comment]
That's a separate issue, but definitely needs solving down the line at some point. When we get to that I'll explain it in a bit more detail

**Comment by wa4557** [comment]
@palob @Foggalong Is this something we should open a new issue about? (The devices folders do have other problems as well)

**Comment by Foggalong** [comment]
You can if you want (just to remember or something), but I wouldn't just yet. As you say the devices icons in general need a proper look over like a did with mimetypes a while back because it has quite a few issues that need solving.

**Comment by wa4557** [comment]
So be it, say if you need with devices help or whatever, those png icons are extremely boring to do :P

**Comment by Foggalong** [comment]
@wa4557 @dirtydancing @palob Just as a thing on tackling the list issues - I'd like to get this one sorted first, and then tackle each of the theme lists one at a time. This way we can root out duplicates and by the time we get around to plasma it won't seem so daunting

**Comment by Foggalong** [comment]
I've got icons for stock_task* ready to push :)

**Comment by palob** [comment]
Alright, I'll just push what I've got ready.

**Comment by Foggalong** [comment]
This isn't to say people can't do icons for other lists, just saying what the "official" priority will be :+1:

**Comment by palob** [comment]
Wondering where for instance ``preferences-certificates.png`` comes from. Can't find it ``Adwaita``, ``gnome``, ``Oxygen``, ``Breeze``, ``elementary``.

**Comment by Foggalong** [comment]
If it's from #658 it's probably legacy/obscure :)

**Comment by Foggalong** [comment]
Only 12 to go \O/

**Comment by wa4557** [comment]
Yeah but those icons are super hard to do. Especially those *** mail icons...

**Comment by Foggalong** [comment]
Yeah, not nice ones to do :(

**Comment by wa4557** [comment]
What do you guys think about a ruler for `stock_insert-rule`? That's the best (although arguably not perfect) metaphor I could come up with...

**Comment by Foggalong** [comment]
Fine with me :)

**Comment by wa4557** [comment]
Cool,I guess I can do that (and probably some of the easier mail-icons) but for the other icons we might need a more creative mind than myself :P

**Comment by Foggalong** [comment]
Np :)

**Comment by wa4557** [comment]
I'm a bit lost on the last 4 icons, would be cool if someone else comes up with something :)

**Comment by palob** [comment]
For ``query-free-busy`` I'd just use a symlink to the magnifying glass icon but then again I don't have the faintest idea where it's used.
For ``stock_check-filled`` just the ``dialog-ok`` design or a monochrome redesign of how the original looks like.
For ``stock_show-all`` something like ``view-grid-symbolic``?

For ``stock_insert-rule`` something with a green check and a red cross?

**Comment by Foggalong** [comment]
Isn't the stock_insert-rule icon of a ruler?

**Comment by palob** [comment]
Yep, it's a yellowish line which probably is supposed to be one.

**Comment by wa4557** [comment]
I tried to design a ruler for `stock_insert_rule` but it just looked completely stupid, maybe someone could do a better job?

**Comment by dirtydancing** [comment]
Coming in from left field here, have not been following this one closely. I am happy to help out. @wa4557 could you post your design, so I know what we are talking about?

**Comment by wa4557** [comment]
It's in this branch: https://github.com/wa4557/numix-icon-theme/tree/ruler (but it is very bad imo)

**Comment by dirtydancing** [comment]
I can tell that this question has come up above, so just to be sure: Are you sure that this icon is supposed to be a ruler? That does not make any sense to me. "Insert a ruler?" Not "Insert a rule", like the icon name says? Inserting a rule, like a formula, makes sense to me. Inserting a "ruler" does not. :)

**Comment by wa4557** [comment]
I guess the original `png` icon is also meant to be a ruler. I'd say it kind of makes sense since it is a somehow valid metaphor (after all the word "ruler" is not without reason very close to "rule"). But if you have a better approach go for it :)

**Comment by dirtydancing** [comment]
Well, other "stock_insert" icons are `stock_insert-note` and `stock_insert-table`. And e.g. for `table`, you would not go for a dinner table or s.th. like that, and for `note` you would not go for a dollar bill, ok, kidding here :) I just fail to understand why/how s.o. could insert a "ruler", meaning a measurement tool?

**Comment by wa4557** [comment]
Lol, well you're not wrong :D As I'm already mentioned I'm not 100% happy either. What do you propose?

**Comment by dirtydancing** [comment]
Ah, I am beginning to understand: the ruler is supposed to be a metaphor for rule, not a symbol for a  ruler for measuring purposes? Well, in that case, I would think that a ruler is actually a misleading symbol, because I thought this was for measuring purposes :) I will have a look into this a little later.

**Comment by Foggalong** [comment]
@dirtydancing my guess is that it's for graphic design programs where you literally add a ruler for making measurements in the design. Inkscape, GIMP, and a few others have features like this

**Comment by palob** [comment]
Yeah, maybe like a horizontal/vertical line for alignment.

**Comment by dirtydancing** [comment]
Do we have an example of this icon name being used in an application? Could be for spreadsheet calculation programs (and mean formula or calculation) or could be for grahic design programs (and mean measurement or alignment). To me, the name `rule` and not `ruler` indicates formula/calculation.

**Comment by Foggalong** [comment]
@dirtydancing A quick search and it would seem that again it's Evolution (and something called GWrite?) that use this.

**Comment by palob** [comment]
So far I can't find ``stock_show-all`` and ``stock_insert-rule`` anywhere in Evolution. Maybe they got axed during the GTK3 porting.

**Comment by Foggalong** [comment]
@palob They're both in [this list](https://www.archlinux.org/packages/extra/i686/evolution/files/)

**Comment by palob** [comment]
@Foggalong What I meant was I can't find them exposed in the GUI.

**Comment by Foggalong** [comment]
Ah, I see :)

**Comment by palob** [comment]
Regarding the ``rule`` symbol: maybe the design from the glade mimetype could be used.

**Comment by Foggalong** [comment]
I'm starting to doubt what I've said about it being a ruler now - where would a ruler be used in Evolution? :/

**Comment by dirtydancing** [comment]
I cannot locate the `rule` symbol in Evolution, either. And I agree, in programs such as Evolution, arguably a "ruler" is not needed :)

**Comment by Foggalong** [comment]
If someone wants to do it (if not I will) just stick a yellow rectangle in similar to how the PNG is designed. Less likely to get the wrong metaphor if we just borrow the one from GNOME :)

**Comment by palob** [comment]
Still can't find it. I've found other missing icons however:
``appointment-soon``
``appointment-missed``
from the ``gnome``/``Adwaita`` theme. Both are already reported in the respective issue.

I think the rule thing was used for mail filtering rules.

**Comment by palob** [comment]
@Foggalong Or maybe just a symllink to a general ``+`` symbol picking up the ``insert`` aspect.

**Comment by Foggalong** [comment]
@palob sure, that works too!

**Comment by dirtydancing** [comment]
@Foggalong I will leave it up to you then :). For some reason, I could not locate `stock_insert-rule` in current GNOME or Adwaita icon themes. And I agree, a `+` symbol would be the most universal solution.

E.g., in Oxygen there is `insert-horizontal-rule` (whatever that one refers to), and it has a horizontal line with a `+`. So the `+` fits imo. Screenshot:

![insert-horizontal-rule](https://cloud.githubusercontent.com/assets/7164227/9699770/81d4bb4c-53ee-11e5-9746-7a74fb32d75d.png)

**Comment by wa4557** [comment]
Hmm or something like this? http://uxrepo.com/static/icon-sets/icomoon/svg/filter.svg That's more like a rule/filter

**Comment by dirtydancing** [comment]
English language question: could "rule" simply mean "line", i.e. this would be about adding a vertical line?

**Comment by Foggalong** [comment]
Yeah, a rule can just mean a line like this one

-----

Now you've mentioned horizontal I'm guessing that's what it's referring to. Going with just a yellow horizontal line (possibly with the `+` like in Ozygen) would be the best solution.

**Comment by dirtydancing** [comment]
Sounds good :+1:

**Comment by Foggalong** [comment]
@bil-elmoussaoui @wa4557 @dirtydancing @palob 

Just posting here because it's an issue you're all already participating in. I've had an accident on my bike and can't really use a keyboard or mouse right now because I've tore my hands to shreds. They should heal up within a week or so but until then the pull requests and things will be on hold (though feel free to make more, I'll deal with them all when I get back).

Thanks as ever guys for the brilliant contributions you make, and talk soon!

**Comment by wa4557** [comment]
Ouch, hope you'll get well soon! A whole week without computer, that's eventuell worse than the torn hands :)

**Comment by dirtydancing** [comment]
Nah, @Foggalong will survive this week without computer and return stronger, I am sure :). Get well soon!

**Comment by bil-elmoussaoui** [comment]
Get well soon! :)

**Comment by palob** [comment]
Ouch :grimacing: but good to hear you didn't come by any serious injury. Get well soon.
Guess in a week's time this issue is about to be closed finally.

**Comment by Foggalong** [comment]
Thanks for the well wishes guys :) my right hand has mostly healed so I can now use a mouse and type one handed. The left is still a mess so I won't be committing my own changes but I'll take a look over what's been going on so there's less of a backlog when I come back

**Comment by bil-elmoussaoui** [comment]
3 icons to finish this one :D Thank you guys for your hard work

**Comment by palob** [comment]
Yay! :dancer:

**Comment by bil-elmoussaoui** [comment]
Thanks you guys again for your hard work on this :dancer:

**Comment by ChuckDaniels87** [comment]
:+1:

**Comment by dirtydancing** [comment]
Well done, sweet to see this one closed! :+1:

**Comment by Foggalong** [comment]
You can test that we've actually done this by running `find . ! -name "*.svg" -type f `, and the only file you'll get is `index.theme` which is also non-binary. [Big thanks](https://plus.google.com/+NumixProjectOrg/posts/8tGUGz2XKK4) again to everyone who's work on this! Feels good to be PNG free :D

-----

As an afterthought, what do people want to do about the bounty since multiple people were responsible for the fix?

**Comment by wa4557** [comment]
I don't wann the bounty, so from my side either keep it or give it to someone else (@palob made really creative icons)

**Comment by palob** [comment]
I made only 2 or so for this one :) 
5 bucks is not that much but how about using it for the GTK theme redesign?

If we don't find an issue to put it on we could donate the money to a bountysource project of whoever's choice.

**Comment by Foggalong** [comment]
If noone objects could the money be diverted to #124? It's a fairly old bug at this point and not the most enjoyable to do either

**Comment by wa4557** [comment]
:+1: Not enjoyable, quite an euphemism :P
