### ISSUE TITLE
Icon nm-device-wired.svg is inconsistent in 22x22/devices

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-icon-theme#460]
In continuation of https://github.com/numixproject/numix-icon-theme/issues/458, because this is a separate issue: The icon `nm-device-wired.svg` in the **devices** directories (not in `status`) currently is a "golden" non-monochrome icon. But in `22x22/devices`, there is an inconsistency and the icon looks like this (apparently outdated panel design from before the fixed size status icons redesign):

![devices_nm-device-wired](https://cloud.githubusercontent.com/assets/7164227/7155311/0c0bc3b6-e35e-11e4-9492-917212fad45a.png)

**Comment by Foggalong** [comment]
@dirtydancing I think this icon might be a status design but located in devices because of Xubuntu

**Comment by dirtydancing** [comment]
Yeah, this one might have been used in Xubuntu, but it is not anymore. iirc I came across a very old screenshot of Xubuntu that displayed this one, but I have not seen it for a long time. Should be save to "remove", i.e. make consistent with the other fixed sizes.

**Comment by Foggalong** [comment]
Ah that's good to hear. If I merge [this pull request](https://github.com/numixproject/numix-icon-theme/pull/468) will it take care of this issue too then?

**Comment by dirtydancing** [comment]
Yes.

**Comment by Foggalong** [comment]
\O/
