### ISSUE TITLE
Icon enhancement for nm-device-wired.svg in devices

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-icon-theme#461]
In continuation of https://github.com/numixproject/numix-icon-theme/issues/458 and https://github.com/numixproject/numix-icon-theme/issues/460: the issue of an icon enhancement for `nm-device-wired.svg` in the **devices** directories (not in `status`) has come up. Currently, this icon looks somewhat inconsistent with the other Numix icons. Example screenshot from `48x48/devices`:

![48x48_devices](https://cloud.githubusercontent.com/assets/7164227/7155433/f490e724-e35e-11e4-9313-d3bfeb64a3f8.png)

Alternative designs (if an alternative design is chosen) could display the network cable plug like currently in `scalable/status` and in `48x48/notifications`, or the actual plug socket.

**Comment by dirtydancing** [comment]
Cross-referencing this possibly related issue: https://github.com/numixproject/numix-icon-theme-circle/issues/1963.

Ideally, a redesigned Numix icon for `nm-device-wired.svg` in `devices` would also be in harmony with the Numix Circle/Square Icons, in order to additionally address the Avahi icon issue in Arch (Avahi using the icon line `network-wired`, and `network-wired.svg` in Numix base could be symlinked to the target `nm-device-wired.svg`, cf. https://github.com/numixproject/numix-icon-theme/issues/458).

Exemplary screenshot of current Arch-based default Antergos:

![antergos](https://cloud.githubusercontent.com/assets/7164227/7188220/71682e20-e476-11e4-8f16-63121ae7331a.png)

**Comment by dirtydancing** [comment]
Cross-reference to https://github.com/numixproject/numix-icon-theme-circle/issues/1963#issuecomment-93991918. Screenshot:

![antergos_avahi](https://cloud.githubusercontent.com/assets/7164227/7203488/55ff3340-e51b-11e4-9a0b-4a9745cff418.png)

**Comment by dirtydancing** [comment]
This issue for `nm-device-wired.svg` in `devices` can be seen as continuing aspects of https://github.com/numixproject/numix-icon-theme/issues/114 and https://github.com/numixproject/numix-icon-theme/issues/186. Those other two issues can be closed now. I will comment there accordingly and refer to this issue.

As a side note: `nm-device-wired.svg` from `devices` is still used in Xubuntu 15.04 Beta 2 for the "notification" (NOT in the panel). So currently this is one more use case of the icon in question here.

In contrast to Ubuntu/Unity, cf. https://github.com/numixproject/numix-icon-theme/issues/253 and https://github.com/numixproject/numix-icon-theme/pull/283, this has not changed after the adding of `nm-device-wired.svg` to `48x48/notifications`. This means Xubuntu is still picking up this icon from `devices`.

(Just for completeness: For wired disconnected, also in Xubuntu 15.04 Beta 2 the notification icon `notification-network-ethernet-disconnected.svg` in `48x48/notifications` is picked up.)

Screenshots of current Xubuntu 15.04 Beta 2, `nm-device-wired.svg` from `devices` pointed to:

![xubuntu1504beta2_connected](https://cloud.githubusercontent.com/assets/7164227/7214848/a9ca0692-e5bd-11e4-8776-09d01259c5ef.png)

![xubuntu1504beta2_disconnected](https://cloud.githubusercontent.com/assets/7164227/7214846/89d8677a-e5bd-11e4-86e5-b94e41a0df70.png)

**Comment by wa4557** [comment]
What do you make out of this? I'm still not 100% convinced (frankly, I'm not the most best designer in the world) but with a little bit improvement this might turn into a decent icon
![wired](https://cloud.githubusercontent.com/assets/6475757/7216926/93b0faec-e611-11e4-8d8d-8b437bbba9b7.png)

**Comment by dirtydancing** [comment]
To me, this looks like it is off to a very good start! This design should scale very well, too.

1) I would probably go for a yellow light in the upper left instead of a red one, as for an ethernet port the regular colours seem to be green for link and yellow for activity (?).

2) The blue-grey contour colour to me could me a little more vivid. This is not a monochrome icon, so there should be some "colour flexibility".

3) At the same time, it might be worth a look if the colour inside for the contacts could be "metallic" (I guess some kind of "gold") instead of dark grey.

Comparative example from `48x48/devices`: `gnome-dev-memory.svg`:
![gnome-dev-memory](https://cloud.githubusercontent.com/assets/7164227/7217104/d64637da-e618-11e4-96b7-c09e16a0a374.png)

4) To be more consistent with other Numix icons in `devices`, I am wondering if there is a way to incorporate some kind of "reflective stripe" to make it less flat? Then again, not all icons are designed consistently, and this kind of "stripe" might not apply to the current draft design above.

5) I would recommend to keep this icon design the same also beyond size 48x48, that means not to turn it "monochrome" and "flat" from size 64x64 on. That change from sizes up from 64x64 happens with several icons in `devices`, but not for all of them. This is esp. considering the use case of this icon as a target for the symlink `network-wired.svg` which in Arch & Co. will be displayed also in larger sizes for the three Avahi icons (cf. screenshots above). Also currently, the "golden" design for `nm-device-wired.svg` in `devices` is designed consistently throughout all fixed sizes up to 256x256.

These are just a couple of aspects that came up for me. What do you make of this?

**Comment by wa4557** [comment]
Good calls here's another improvement:
![wired](https://cloud.githubusercontent.com/assets/6475757/7218857/da09e0c2-e683-11e4-89ed-208d1dfa23f7.png)

Still not good enough

**Comment by dirtydancing** [comment]
Some more feedback:

To me, something about the shape of the green/red "lights" looks off. Maybe this is also unnecessarily creating a face shape. For another shape composition, I modified the .png above to more align these two "lights" vertically with the other parts, just as a mock-up for demonstration purposes. Comparison:

current:
![93b0faec-e611-11e4-8d8d-8b437bbba9b7](https://cloud.githubusercontent.com/assets/7164227/7218843/f83c3456-e682-11e4-8c4d-6e01bdf0fc67.png)

alternative:
![93b0faec-e611-11e4-8d8d-8b437bbba9b7_2](https://cloud.githubusercontent.com/assets/7164227/7218844/fc6004e0-e682-11e4-8a33-3db0594a78c3.png)

**Comment by dirtydancing** [comment]
Ah, posting at the same time again :-)

**Comment by dirtydancing** [comment]
Initial feedback regarding the new version: this is getting better and better :)

1) I still think the vertically aligned shape of the green and yellow lights might be worth considering.

2) I would suggest that the two upper corners of the inner shape should not be rounded, but rectangular, to conform with all the other rectangular shapes in the upper part. The two bottom corners should stay rounded, though.

Screenshot:

![da09e0c2-e683-11e4-89ed-208d1dfa23f7](https://cloud.githubusercontent.com/assets/7164227/7218920/4f8f5f9a-e687-11e4-977a-a41c3bb2007f.png)

**Comment by dirtydancing** [comment]
Additionally, the grey colour might be somewhat dark, esp. for darker backgrounds (such as e.g. in the Antergos screenshot above), also considering that the icon currently is transparent in the centre. This icon should work on light as well as on dark backgrounds.

One additional possibility to address that could be to add a lighter colour outline on the inside of the center. Mock-up (possible probably also with e.g. a lighter grey colour):

![da09e0c2-e683-11e4-89ed-208d1dfa23f7_1](https://cloud.githubusercontent.com/assets/7164227/7219218/c5875f32-e695-11e4-86c6-64b92ed10633.png)

**Comment by wa4557** [comment]
Idk, for me this icon is far from being good enough to be merged, regardless of what I do it doesn't do it for me

**Comment by dirtydancing** [comment]
Well, the direction to me is a good one. With the latest changes and the "two steps" at the top, this would be the counterpart to the Numix wired network icon representing the cable plug for that socket.

At the same time, I agree that this is a tricky one to do, also given its varied use in various distributions.

Could you share your .svg file(s), so I could possibly have a more detailed look at this? Interesting icon :)

**Comment by wa4557** [comment]
https://github.com/wa4557/numix-icon-theme/tree/network feel free to change anything :)

**Comment by dirtydancing** [comment]
Thanks! :)

**Comment by dirtydancing** [comment]
How about this one?

![draft_1](https://cloud.githubusercontent.com/assets/7164227/7219512/9b6b4196-e6a4-11e4-9d22-60d79787e635.png)

**Comment by wa4557** [comment]
That's actually a really good one :+1:

**Comment by wa4557** [comment]
One thing though: It is also necessary to have a `network-wired-disconnected` as well. This might be possible by changing the LEDs to a grey colour?

**Comment by dirtydancing** [comment]
Yeah, that should be a good approach here. Proposal for disconnected. What do you think?

![draft_1_disconnected](https://cloud.githubusercontent.com/assets/7164227/7219609/f5e45560-e6a7-11e4-8314-23f0bf01fc19.png)

**Comment by wa4557** [comment]
Great! I really like these icons. Do you want help at creating additional sizes?

**Comment by dirtydancing** [comment]
Thanks! I am glad you like these :) Well, actually I am not really sure how to do the different sizes at all. This is created at 48x48. The size would have to be larger in relation to the canvas size for 16x16 and smaller for the larger sizes I guess. How about you take over again from here? I have adjusted everything to grid, but on this occasion possibly you could have a look at that as well? Here is the corresponding branch:

https://github.com/dirtydancing/numix-icon-theme/tree/wired

**Comment by dirtydancing** [comment]
Oh, and could you also check please about the layers? I added one for the central background, and I am not sure if these have to be merged again?
