### ISSUE TITLE
Bluetooth panel icon in elementary OS Freya is too big

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-icon-theme#464]
In this recent post on the Google+ Numix Community page, https://plus.google.com/115098474041469785754/posts/HYt6B4vwQTV, I noticed that the bluetooth panel icon is way too big:

![elementary_bluetooth](https://cloud.githubusercontent.com/assets/7164227/7208923/560c27b6-e544-11e4-98bc-ea12b088425b.png)

@bil-elmoussaoui Are you still using elementary OS Freya, and are you interested in checking this out?

Looking closer at this screenshot, I noticed that the bluetooth icon is white. This leads me to the conclusion that this must be a "symbolic"-named icon, and indeed: elementary icon theme uses `bluetooth-active-symbolic.svg` and also in gnome icon theme (Numix inherits from gnome), there is a `bluetooth-active-symbolic.svg` icon in `scalable/status`, which looks like this:

![gnome_bluetooth-active-symbolic](https://cloud.githubusercontent.com/assets/7164227/7209063/4f60612e-e545-11e4-9f8a-1e43ab7c3075.png)

This is a 16x16 icon, and if that gets scaled up to the panel canvas size of 24x24 in elementary OS Freya, this would explain why this icon is displayed so large.

@bil-elmoussaoui A possible way to fix this could be to add a symlink `bluetooth-active-symbolic.svg` with the target `bluetooth-active.svg` in Numix base and to check whether the size of the bluetooth panel icon changes to normal.

The colour will still be white, because with "symbolic"-named icons in elementary OS Freya, the GTK theme will influence the icon colour in the panel, so with Numix GTK theme the icon colour could be more consistent with the other Numix panel icons.

I am creating this report so that this issue can be tracked. First of all, this would need to be confirmed.

**Comment by dirtydancing** [comment]
Actually, this could be even simpler to explain: Numix contains `bluetooth-active-symbolic.svg` in `scalable/status` itself :), and this seems to be the icon that is displayed in the panel above:

![numix_bluetooth-active-symbolic](https://cloud.githubusercontent.com/assets/7164227/7209488/4265a192-e549-11e4-975d-6455f0cf7000.png)

The question would then be whether `bluetooth-active-symbolic.svg` can be added to the fixed size directories (16x16), 22x22 and 24x24 without breaking anything in GNOME shell.

Taking into account the experiences with the battery icon in this regard, that should actually be possible without breakage for the fixed size directories 22x22 and 24x24, and since 24x24 is the relevant size for elementary OS Freya, this could already fix it.

**Comment by Foggalong** [comment]
Icons with the name `*-symbolic.svg` shouldn't go in the fixed size directories. The only exception is the battery icons for obvious reasons.

**Comment by dirtydancing** [comment]
@Foggalong Agreed, for all intents and purposes they should not. Still, I have created a testing branch:

https://github.com/dirtydancing/numix-icon-theme/tree/bluetooth-elementary

Possibly this could become the second exception, after the battery icon? :)

Another approach to deal with this situation would be to file a bug report against elementary OS Freya, but I assume that there is a reason for the elementary devs to go for a "symbolic"-named bluetooth icon for the panel (possibly because these can be colour-themed by the GTK theme, and the elementary GTK theme colour-themes the panel icons white #ffffff).

**Comment by dirtydancing** [comment]
@Foggalong As I agree that `*-symbolic.svg` icons should not be used in the fixed size directories (exception: battery icon), and as this issue has not even been confirmed on elementary OS Freya yet (I am not sure how to activate bluetooth on a VirtualBox guest anyways), and even if this could be fixed for elementary OS Freya, this would require further "breakage"-testing with other distributions, and esp. for GNOME Shell, and as I figure that no one here is really interested in any kind of second battery status icon saga :) :

Should I close this issue report?

Just for the sake of completeness: there are a couple of "symbolic"-named icons other than the battery icons in the fixed size directories (not sure why): e.g. in `22x22/status`: `ac-adapter-symbolic.svg`, `printer-symbolic.svg`

Actually, I am closing this myself. Please feel free to re-open :)

**Comment by bil-elmoussaoui** [comment]
Sorry, but i cannot test this at the moment. I must prepare for the finals. Maybe in two months !

**Comment by dirtydancing** [comment]
@bil-elmoussaoui Thanks for dropping in :) This issue has been closed anyways. Good luck with your finals!
