### ISSUE TITLE
Request: Application Icon: Gnome Books

### ISSUE THREAD

**Issue by plumpudding** [numixproject/numix-icon-theme#466]
File name should be "gnome-books"

**Comment by bil-elmoussaoui** [comment]
This is a Numix circle issue! And have already been fixed. The ppa has not been updated for a while, you can try the github version(at your own risk). Or just copy the missed icon to numix-circle folder

**Comment by plumpudding** [comment]
Sorry, my mistake! Thanks for that amazing icon theme anyways!
