### ISSUE TITLE
Background of File icon is the same as background of dialog window

### ISSUE THREAD

**Issue by Corsseir** [numixproject/numix-icon-theme#470]
Hey, I have noticed that background color of File icons is the same as background color of the dialog window. Please add white border around File icons.

![screenshot from 2015-04-27 00 18 38](https://cloud.githubusercontent.com/assets/11137173/7339569/0801136a-ec74-11e4-917d-7ae949fe796c.png)

**Comment by Foggalong** [comment]
We definitely won't add a white border around icons but that's certainly an issue we can look at fixing somehow.

**Comment by Corsseir** [comment]
Thank you for your effort anyway :)

**Comment by dirtydancing** [comment]
Might also be approached from the GTK theme side, e.g. this problem does not exist with Ambiance GTK theme. Screenshot of Ubuntu 14.10 with default Ambiance GTK theme:

![ambiance](https://cloud.githubusercontent.com/assets/7164227/7347095/4090740c-ece5-11e4-98d9-e4f4ae5190cb.png)

**Comment by Foggalong** [comment]
Yeah, it's because of the colour we chose for the GTK theme so it's not gonna be there for any other theme.

**Comment by bil-elmoussaoui** [comment]
I think that changing the mimetypes icons or adding a border around will be such a hard thing to do..Changing the grey colour in  Numix gtk is the fastest to do :)

**Comment by Foggalong** [comment]
@bil-elmoussaoui @Corsseir the GTK theme is actually being rewritten as we speak so waiting to see if the new version still has this problem :)

**Comment by wa4557** [comment]
It doesn't (given that the colours don't change anymore)

**Comment by Foggalong** [comment]
@wa4557 colours don't change?

**Comment by wa4557** [comment]
What I mean is, that in the new sass written theme this bug is not present anymore. But I don't know if this is now the final version, so if the colours are going to change it might occur again...

**Comment by Corsseir** [comment]
@Foggalong Ye, I know it. Actually I have seen preview version of new Numix theme and I am very exciting :)

**Comment by satya164** [comment]
@wa4557 Colors are finalized as of now :)

**Comment by wa4557** [comment]
Well then this bug is fixed I suppose :)
![unbenannt](https://cloud.githubusercontent.com/assets/6475757/7947184/d2cd509e-097b-11e5-923b-81deef7eff24.png)

**Comment by Foggalong** [comment]
Awesome! We can close it then soon as the new version land :)

**Comment by wa4557** [comment]
@Foggalong Since the new gtk version is out yet, this one can be closed...
