### ISSUE TITLE
Enhance nm-device-wireless in devices

### ISSUE THREAD

**Issue by wa4557** [numixproject/numix-icon-theme#472]
In continuation of #463 and #461 I'd suggest to enhance `nm-device-wireless.svg` in `devices` since it is basically a status icon and not `devices` icon and doesn't fit the other icons. 
Suggestion: 
New icon:
![test](https://cloud.githubusercontent.com/assets/6475757/7390544/9728a4a2-ee79-11e4-8941-61958d4a316a.png)
Old icon:
![test2](https://cloud.githubusercontent.com/assets/6475757/7390548/9fdc3848-ee79-11e4-9797-c8fe8460b9ca.png)

**Comment by wa4557** [comment]
alternative:
![nm-device-wireless](https://cloud.githubusercontent.com/assets/6475757/7395312/685a9dea-ee99-11e4-946e-191513eb9336.png)

**Comment by dirtydancing** [comment]
Good call about this `device` icon! Am I correct in assuming that this icon will be size `48x48` only? Because that would allow for this kind of detail in the design. I like both variants :+1:

**Comment by wa4557** [comment]
No this needs to be for all sizes. Doesn't scale too bad. Comparable to `network-wired.svg`, which is also present in all sizes

**Comment by dirtydancing** [comment]
Do we have an example of when this icon is used in smaller sizes than 48x48?

**Comment by wa4557** [comment]
Nope. But for the sake of consistnency (`nm-device-wired`) it should be added for smaller sizes as well

**Comment by dirtydancing** [comment]
Yeah, makes sense to me.
