### ISSUE TITLE
Midori menu icon.

### ISSUE THREAD

**Issue by v3getarian** [numixproject/numix-icon-theme#494]
Every other icon displays fine except the menu icon.

![bug](https://cloud.githubusercontent.com/assets/6824845/7783221/257f3a4a-0108-11e5-92c7-44d40260b705.png)

Correct me if I'm wrong, but I can't imagine that is what's supposed to be there...

**Comment by wa4557** [comment]
That's actually a Numix-icon -> Numix can't do anything about it

**Comment by Foggalong** [comment]
Yeah, that's just Midori picking the wrong icon :/
