### ISSUE TITLE
Missing Indicator Icons: Clip-It and Redshift

### ISSUE THREAD

**Issue by Sadi58** [numixproject/numix-icon-theme#495]
The icons missing are :
```
"./status/xx/clipit-trayicon.svg"
"./status/xx/redshift-status-off.svg"
"./status/xx/redshift-status-on.svg"
```

**Comment by wa4557** [comment]
redshift is not missing, I suppose clipit is a clipboard manager?

**Comment by Sadi58** [comment]
1) It seems redshift used the color app icon instead of monochrome status icon here because it couldn't find one under the sub-folder for size 22 although there were 16px and 24 px icons.
2) Yes, ClipIt is a fork of Parcellite clipboard manager.

**Comment by bil-elmoussaoui** [comment]
The application uses a circular icon(if you use Numix circle) because of this #190. This is not fixed yet. And the redshift icons do exists in Numix/22x22/status/ , if not you can get them from the github repo

**Comment by Sadi58** [comment]
Wov, what a long reading to do ; -)
Actually I just came back to report this problem of missing redshift status icon in Numix Circle although it exists in Numix base icon theme ;-)
Probably we need to add some lines to index.theme file of Numix Circle then?

**Comment by Sadi58** [comment]
No, adding some lines wasn't enough. I had to symlink 22x22 and 24x24 sub-folders as well.

**Comment by Sadi58** [comment]
And as for ClipIt, all I had to do was to create a symlink:
ln -s "~/.icons/Numix-Circle-Light/22x22/status/clipman.svg" "~/.icons/Numix-Circle-Light/22x22/status/clipit-trayicon.svg"

**Comment by bil-elmoussaoui** [comment]
Well, Happy that this worked for you! @wa4557 have pushed a pull request to Numix base. This can be closed one his PR will be merged

**Comment by wa4557** [comment]
@Sadi58 We pretty much figured out what to do :) we're just waiting for the Numix devs to decide how to handle this bug; it's not that trivial

**Comment by Sadi58** [comment]
OK, at least I've got an "amateur" solution working for me now :-)
Thanks for all :-)

**Comment by Sadi58** [comment]
FYI: I've just started using Numix (gtk/icon) themes from Ubuntu PPA channel instead of git repository, and I no longer have this issue with Redshift On/Off status icon.

So I have only the ClipIt tray icon issue now.

**Comment by bil-elmoussaoui** [comment]
@Sadi58 the numix ppa was not updated as i said and the tray icons are still in circle. that's why everything is working fine for you, you can create a symlink to fix this for clipit or use the ppa version

**Comment by Sadi58** [comment]
I understand, OK, thanks...
