### ISSUE TITLE
Mimetype: application/x-sharedlib

### ISSUE THREAD

**Issue by hlechner** [numixproject/numix-icon-theme#557]
Name: **shared library**
Mimetype: **application/x-sharedlib**
Possible extensions: **.so**

Description: **Library file**

![image](https://cloud.githubusercontent.com/assets/11244067/8086188/75535e50-0f6a-11e5-907b-4f9c779ea550.png)

**Comment by hlechner** [comment]
Related Numix-Circle icons:
![image](https://cloud.githubusercontent.com/assets/11244067/10567270/a4aad744-75dd-11e5-9a3b-aff9300d23b6.png)

An idea is to use a book (or books) and the cover cold be gears (idea of system) or tux (idea of linux)

**Comment by Foggalong** [comment]
How so related to books? The description I've found is "shared object, dynamically linked library" :/

**Comment by hlechner** [comment]
The description that you find is also right.
the .so file is "shared object" or also known as "shared library".

I'll quote here the description of Linux Library Types from [yolinux.com](http://www.yolinux.com/TUTORIALS/LibraryArchives-StaticAndDynamic.html):
```
There are two Linux C/C++ library types which can be created:

 1.Static libraries (.a): Library of object code which is linked with, and becomes part of the application.
 2.Dynamically linked shared object libraries (.so): There is only one form of this library but it can be used in two ways.
 - 1. Dynamically linked at run time but statically aware. The libraries must be available during compile/link phase. The shared objects are not included into the executable component but are tied to the execution.
 - 2. Dynamically loaded/unloaded and linked during execution (i.e. browser plug-in) using the dynamic linking loader system functions.
```

some users compare also the .so as the windows DLL [here](http://unix.stackexchange.com/questions/13192/what-is-the-difference-between-a-and-so-file):
```
A .a file is a static library, while a .so file is a shared object (dynamic) library similar to a DLL on Windows. There's some detailed information about the differences between the two on this page.
```

More related references could be found on google by searching ``so files``

**Comment by hlechner** [comment]
The idea of ``library`` itself return me the idea of books, but use the way that you guys prefer, its just my opinion.

**Comment by Foggalong** [comment]
Yeah, I'd rather not associate it with books since that has the potential to confuse users with regard to eReader formats.

**Comment by hlechner** [comment]
I understand, just for reference what other systems are showing as library icon:

## Windows System (DLL files):
### Windows 95:
![image](https://cloud.githubusercontent.com/assets/11244067/10590695/df7a96b2-7690-11e5-962e-2ec006c9c7dd.png)
### Windows XP:
![image](https://cloud.githubusercontent.com/assets/11244067/10590718/fcffecbe-7690-11e5-8b3f-4145d4b12baa.png)
### Windows 7:
![image](https://cloud.githubusercontent.com/assets/11244067/10590734/1a58821c-7691-11e5-9e2d-51b694e31b45.png)

## Mac OS X (dylib files):
![image](https://cloud.githubusercontent.com/assets/11244067/10590890/0975af28-7692-11e5-845e-762d85976c9e.png)
* I don't have the mac osx to check it, it was what I found on google, it seems to be correct

--

## Oxygen Icon (application/x-sharedlib):
![image](https://cloud.githubusercontent.com/assets/11244067/10591152/75eb20f6-7693-11e5-8ecc-ed1ffdf35fce.png)
