### ISSUE TITLE
Mimetype: application/x-shared-library-la

### ISSUE THREAD

**Issue by hlechner** [numixproject/numix-icon-theme#559]
Name: **libtool shared library**
Mimetype: **application/x-shared-library-la**
Possible extensions: **.la**

Description: **Library file**. could use the same mimetype icon as #557 

![image](https://cloud.githubusercontent.com/assets/11244067/8086309/1f68792a-0f6b-11e5-9d3a-ebac47011d72.png)

**Comment by hlechner** [comment]
Just to complement with a possible design idea:
- Books - it should be appropriated for the library mimetypes.

Or anything else, it is just an idea.

**Comment by hlechner** [comment]
Merged

**Comment by hlechner** [comment]
I found a way to use the guideline on these mimes:
![image](https://cloud.githubusercontent.com/assets/11244067/11890399/2c84d05c-a53b-11e5-9192-4424fc569f51.png)![image](https://cloud.githubusercontent.com/assets/11244067/11890405/36e45e32-a53b-11e5-98a9-6774c7042534.png)![image](https://cloud.githubusercontent.com/assets/11244067/11890413/4065be56-a53b-11e5-8ecf-b484aad6adb5.png)![image](https://cloud.githubusercontent.com/assets/11244067/11890414/45762034-a53b-11e5-877f-3853895668bd.png)![image](https://cloud.githubusercontent.com/assets/11244067/11890417/4a91d798-a53b-11e5-87c0-cfd0e10adbd5.png)

@Foggalong Should I send a pull request of these?

**Comment by Foggalong** [comment]
:+1:
