### ISSUE TITLE
Unreadable icons in synaptics

### ISSUE THREAD

**Issue by freed00m** [numixproject/numix-icon-theme#562]
![selection_011](https://cloud.githubusercontent.com/assets/9461698/8095583/c08dade8-0fcf-11e5-9275-ae0110364616.png)
Happened with latest update, or maybe 2 updates back Synaptic icons became hardly readable.

I know it is purely looks and not a failure but I have an personal issue reading what I have installed and what I did not. 

I don't want to rant :) I am happy with all other icons.

Preview:

Mint 17.1 MATE

**Comment by bil-elmoussaoui** [comment]
I was going to report this too. 
Ps: you can attach images in Github

**Comment by palob** [comment]
So higher contrast or coloured package symbols?

**Comment by freed00m** [comment]
@palob "coloured package symbols" would be much more readable in my opinion :)

**Comment by Foggalong** [comment]
This is tricky because changing those colours would mean a massive redesign of the other colours we use too. Coloured packages isn't really in keeping with how the rest of the icons look either. I'll have to think on this one.

**Comment by wa4557** [comment]
We could make the icons bigger for smaller sizes (16 22 and 24)

**Comment by palob** [comment]
How about the something like the following colours for better contrast:

+ red
   ``e84444ff``
+ green (replacing orange)
  ``48d848ff``
+ yellow
  ``f5f357ff``
+ blue
   ``84a9c8ff``
![pkg-colours](https://cloud.githubusercontent.com/assets/7050624/8616404/5ba02ff8-26fb-11e5-81e0-8a08dc9e6a76.png)

**Comment by Foggalong** [comment]
I'm not entirely sure on this.The green in particular is a bit garish - @me4oslav any opinions on this?

**Comment by palob** [comment]
Better green tint (also used in *user-available*):
![green2](https://cloud.githubusercontent.com/assets/7050624/8630754/0ff9856c-276a-11e5-8bdd-5e409389380a.png)

**Comment by Foggalong** [comment]
I think it's because it's from a different colour scheme type rather than the colour itself. i.e. that shade of browm doesn't go with that shade of green

**Comment by palob** [comment]
![pkg-colours](https://cloud.githubusercontent.com/assets/7050624/8810795/d1055ada-2ff1-11e5-9551-1c0434cbd866.png)

Difficult to balance the contrast to the package symbol and to a white background while not ending up with too bright or garish a green.

**Comment by palob** [comment]
Another option might be to work on the semi-symbolic ``pamac-...`` icons in ``status``.

**Comment by wa4557** [comment]
Hmm. What about removing the package symbol altogether (for small sizes)  and only leave the arrows etc.?

**Comment by bil-elmoussaoui** [comment]
@wa4557 elementary do the same thing on a white background ! and i think it's a good idea ;)

**Comment by palob** [comment]
@wa4557 Might work but I think for bigger sizes the contrast needs to be improved anyway.

**Comment by bil-elmoussaoui** [comment]
@wa4557 why not using only the symbol, and remove the package icon in the background? that will make it easier to read!

**Comment by wa4557** [comment]
I can do that sure. I need some feedback though if this is something that should happen? (don't what to put work into somehting futile)

**Comment by Foggalong** [comment]
Are these package icons used (or symlinked) to anywhere else?

**Comment by bil-elmoussaoui** [comment]
Nop, they can be symlinked to aptdeamon icons too

**Comment by wa4557** [comment]
Ok so should I do that then? I'd suggest to go with it since this is the only place the icons are used...
