### ISSUE TITLE
Mimetype: text/x-gettext-translation

### ISSUE THREAD

**Issue by hlechner** [numixproject/numix-icon-theme#563]
Name: **translation file**
Mimetype: **text/x-gettext-translation**
Possible extensions: **.po**

![image](https://cloud.githubusercontent.com/assets/11244067/8094176/b45579f4-0f9b-11e5-9247-b0c70744586f.png)

**Comment by hlechner** [comment]
Additional Info: I found on Oxygen theme the following Mimetype:
- text/x-po

It seems to be the same think, so a symlink to this one could be useful too.

**Comment by palob** [comment]
Not easy to tackle, here are some raw drafts I'm not overly confident of:
![text-x-gettext-translation-48b](https://cloud.githubusercontent.com/assets/7050624/8267385/04750bc2-1760-11e5-836e-013222e0711e.png)
![text-x-gettext-translation-48c](https://cloud.githubusercontent.com/assets/7050624/8267386/04765cf2-1760-11e5-8cea-d9bd82da5ea9.png)
![text-x-gettext-translation-48d](https://cloud.githubusercontent.com/assets/7050624/8267387/047700bc-1760-11e5-94ea-3d060d2dfa00.png)

Any ideas?

**Comment by Foggalong** [comment]
The first and second are okay because they link back to their app icon counterparts, but as you say not 100% on either

**Comment by palob** [comment]
A new approach (nothing groundbreakingly new however):

``text-gettext-translation``/``text-x-po``
![16-64-po](https://cloud.githubusercontent.com/assets/7050624/10561129/2fbdfa06-751f-11e5-8e83-b92e8565ebdb.png)


``text-x-gettext-translation-template``
![16-64-pot](https://cloud.githubusercontent.com/assets/7050624/10561130/339e950e-751f-11e5-89cf-91822deb9fc3.png)

**Comment by Foggalong** [comment]
I like the colourful implementation but it sort of feels like the flag isn't aligned properly. Maybe try 1px to the left?

**Comment by wa4557** [comment]
I'd make the flag 1px narrower...

**Comment by palob** [comment]
How about the non-dog-ear shape for the colourful ``.pot`` mimetype to be in line with the other *template* mimetypes?

@wa4557 So 1px narrower and 1px to the right?

**Comment by Foggalong** [comment]
@palob I was forgetting about that, definitely do that

**Comment by palob** [comment]
With or without the *PO* *POT* text?

**Comment by wa4557** [comment]
I would keep the text

**Comment by Foggalong** [comment]
Yeah, same :)

**Comment by palob** [comment]
Last call: Above colour (the one from the patch mimetype) or this one (from the glade mimetype)?
![text-x-po1](https://cloud.githubusercontent.com/assets/7050624/10564696/2f482ea4-75bd-11e5-86bd-6dac22c8b323.png)

**Comment by bil-elmoussaoui** [comment]
Prefer the one from the patch mimetype

**Comment by Foggalong** [comment]
Yeah, perfer patch also :)

**Comment by palob** [comment]
Here's the latest iteration:
![16-64](https://cloud.githubusercontent.com/assets/7050624/10564971/34d6b468-75c6-11e5-9e55-8abe021a618a.png)

**Comment by wa4557** [comment]
:+1:
