### ISSUE TITLE
Mimetype: application/x-xpinstall

### ISSUE THREAD

**Issue by hlechner** [numixproject/numix-icon-theme#564]
Name: **XPInstall installer module**
Mimetype: **application/x-xpinstall**
Possible extensions: **.xpi**

Description: **technology created by Mozilla to install Add-ons/Extensions**, http://en.wikipedia.org/wiki/XPInstall

![image](https://cloud.githubusercontent.com/assets/11244067/8094293/884ee4fc-0f9c-11e5-9e63-ab1247e5c425.png)

**Comment by bil-elmoussaoui** [comment]
This can be symlinked to ```opera-extension```, what do you think? @hlechner

**Comment by hlechner** [comment]
@bil-elmoussaoui To me I think the opera-extension fit well on this one
