### ISSUE TITLE
Mimetype: text/x-matlab

### ISSUE THREAD

**Issue by wa4557** [numixproject/numix-icon-theme#567]
![unbenannt](https://cloud.githubusercontent.com/assets/6475757/8102334/9316aa9a-101f-11e5-80cf-47caec478c42.png)

Currently an octave mimetype is used, which is not very suitable

**Comment by palob** [comment]
Why isn't that suitable? Octave/Matlab are actually the same files.

**Comment by Foggalong** [comment]
For University I actually have to use MATLAB, and so use Octave and then convert to MATLAB when it needs sending to a professor so I could definitely see the usefulness in the distinction.

**Comment by palob** [comment]
What do you mean by "convert"?

Apparently regarding mimetype recognition there's no distinction between ``text-x-octave`` and ``text-x-matlab``.
Testing with my old scripts or the ones that come with Octave the file properties dialog always shows ``text-x-matlab``, gedit always says *Octave*.

**Comment by Foggalong** [comment]
I'm trying to find my old school work now to see. I could have sworn there was a conversion process between the two formats

**Comment by wa4557** [comment]
Is the mimetype really just recognized by the extension? I have a few `.m` files that have mimetype `text/x-matlab` others are `text/c-source` and others are `application/matlab`

**Comment by palob** [comment]
I have a few files recognised as Objective-C (those not beginning with a comment).

**Comment by wa4557** [comment]
@palob I think you're right there seems to be no difference between thos two files mimetype wise. And since octave is a foss program I'll close this here. Too bad they decided to use the same extension :(
