### ISSUE TITLE
Request: Dropbox folder icon

### ISSUE THREAD

**Issue by brittyazel** [numixproject/numix-icon-theme#569]
Many of us use Dropbox, and by default Dropbox puts a new folder labeled "Dropbox" in the user directory. While all of the default folders have customized icons, i.e. Documents, Music, Pictures, Downloads, etc, perhaps it might be nice to have a Dropbox specialized folder added to the set. Just a thought. Cheers.

**Comment by wa4557** [comment]
[There is one] (https://github.com/numixproject/numix-icon-theme/blob/master/Numix/48x48/places/default-folder-dropbox.svg)

**Comment by brittyazel** [comment]
Weird, the dropbox folder is not using it then. Is there a special way to enable it?

**Comment by wa4557** [comment]
Try this:
`gvfs-set-attribute /path/to/folder metadata::custom-icon-name folder-dropbox`

**Comment by brittyazel** [comment]
Hey wow that worked :-)

But now the issue is that Nautilus-Dropbox does not show the overlayed sync checkmark on the icon...hrm...

**Comment by brittyazel** [comment]
Hey wow that worked :-)

But now the issue is that Nautilus-Dropbox does not show the overlayed sync
checkmark on the icon...hrm...
