### ISSUE TITLE
Missing icons from Adwaita theme

### ISSUE THREAD

**Issue by andia89** [numixproject/numix-icon-theme#577]
Since there is the same issue report for Elementary freya #437 I figured I might as well file a bug report for all mising icons in the Adwaita theme (the new default icon theme for gtk 3+). There are actually not that much icons. 
- [x] network-wired-acquiring-symbolic
- [x] battery-symbolic
- [x] drive-harddisk-ieee1394-symbolic
- [x] drive-harddisk-system-symbolic
- [x] drive-harddisk-usb-symbolic
- [x] drive-harddisk-solidstate-symbolic
- [x] address-book-new-symbolic
- [x] airplane-mode-symbolic
- [x] alarm-symbolic
- [x] application-certificate-symbolic
- [x] application-exit-symbolic
- [x] application-rss+xml-symbolic
- [x] applications-engineering-symbolic
- [x] applications-games-symbolic
- [x] applications-graphics-symbolic
- [x] applications-multimedia-symbolic
- [x] applications-science-symbolic
- [x] applications-system-symbolic
- [x] applications-utilities-symbolic
- [x] application-x-addon
- [ ] application-x-appliance-symbolic
- [ ] application-x-executable-symbolic
- [x] application-x-firmware
- [x] appointment-missed
- [x] appointment-missed-symbolic
- [x] appointment-new-symbolic
- [x] appointment-soon
- [x] appointment-soon-symbolic
- [x] audio-card-symbolic
- [x] call-missed-symbolic
- [x] call-stop-symbolic
- [ ] camera-video
- [x] camera-video-symbolic
- [x] changes-allow
- [x] changes-allow-symbolic
- [x] changes-prevent
- [x] channel-insecure-symbolic
- [x] channel-secure-symbolic
- [x] checkbox-checked-symbolic
- [x] checkbox-mixed-symbolic
- [x] checkbox-symbolic
- [x] color-select-symbolic
- [ ] colorimeter-colorhug-symbolic
- [x] computer-apple-ipad-symbolic
- [ ] computer-fail
- [x] computer-fail-symbolic
- [x] computer-symbolic
- [x] display-projector-symbolic
- [x] document-print-preview-symbolic
- [x] document-print-symbolic
- [x] document-revert-rtl
- [x] document-revert-symbolic
- [x] document-revert-symbolic-rtl
- [ ] drive-multidisk
- [ ] drive-removable-media-symbolic
- [x] edit-clear-all
- [x] edit-clear-rtl
- [x] edit-clear-symbolic-rtl
- [x] edit-find-replace-symbolic
- [x] edit-redo-rtl
- [x] edit-redo-symbolic-rtl
- [x] edit-undo-rtl
- [x] edit-undo-symbolic-rtl
- [ ] emote-love
- [x] emote-love-symbolic
- [x] face-angel
- [ ] face-angel-symbolic
- [x] face-angry
- [ ] face-angry-symbolic
- [ ] face-confused-symbolic
- [x] face-cool
- [ ] face-cool-symbolic
- [x] face-crying
- [ ] face-crying-symbolic
- [x] face-devilish
- [ ] face-devilish-symbolic
- [x] face-embarrassed
- [ ] face-embarrassed-symbolic
- [x] face-glasses
- [ ] face-glasses-symbolic
- [x] face-kiss
- [ ] face-kiss-symbolic
- [x] face-laugh
- [ ] face-laugh-symbolic
- [x] face-monkey
- [ ] face-monkey-symbolic
- [x] face-plain
- [ ] face-plain-symbolic
- [x] face-raspberry
- [ ] face-raspberry-symbolic
- [x] face-sad
- [ ] face-sad-symbolic
- [ ] face-shutmouth-symbolic
- [x] face-sick
- [ ] face-sick-symbolic
- [x] face-smile
- [x] face-smile-big
- [ ] face-smile-big-symbolic
- [ ] face-smile-symbolic
- [x] face-smirk
- [ ] face-smirk-symbolic
- [x] face-surprise
- [ ] face-surprise-symbolic
- [x] face-tired
- [ ] face-tired-symbolic
- [x] face-uncertain
- [ ] face-uncertain-symbolic
- [x] face-wink
- [ ] face-wink-symbolic
- [x] face-worried
- [ ] face-worried-symbolic
- [ ] face-yawn-symbolic
- [x] focus-legacy-systray-symbolic
- [x] focus-top-bar-symbolic
- [x] focus-windows-symbolic
- [ ] folder-drag-accept-symbolic
- [ ] folder-new-symbolic
- [ ] folder-open-symbolic
- [ ] folder-publicshare-symbolic
- [ ] folder-remote-symbolic
- [ ] folder-saved-search-symbolic
- [ ] folder-visiting-symbolic
- [x] font-select-symbolic
- [x] font-x-generic-symbolic
- [x] format-indent-less-rtl
- [x] format-indent-less-symbolic-rtl
- [x] format-indent-more-rtl
- [x] format-indent-more-symbolic-rtl
- [x] go-first-rtl
- [x] go-first-symbolic-rtl
- [x] go-last-rtl
- [x] go-last-symbolic-rtl
- [x] go-next-rtl
- [x] go-next-symbolic-rtl
- [x] go-previous-rtl
- [x] go-previous-symbolic-rtl
- [x] help-about-symbolic
- [x] image-denoise-symbolic
- [x] image-filter-symbolic
- [x] image-loading-symbolic
- [x] image-sharpen-symbolic
- [x] image-x-generic-symbolic
- [ ] inode-directory-symbolic
- [ ] input-dialpad
- [x] input-dialpad-symbolic
- [x] input-gaming
- [x] input-tablet-symbolic
- [x] input-touchpad-symbolic
- [x] keyboard-brightness-symbolic
- [x] mail-attachment
- [x] mail-attachment-symbolic
- [x] mail-read-symbolic
- [x] mail-replied-symbolic
- [ ] mail-signed
- [ ] mail-signed-verified
- [x] mail-unread-symbolic
- [ ] mark-location
- [x] media-optical-bd-symbolic
- [x] media-optical-dvd-symbolic
- [x] media-playback-start-rtl
- [x] media-playback-start-symbolic-rtl
- [x] media-playlist-consecutive-rtl-symbolic
- [x] media-playlist-consecutive-symbolic
- [x] media-playlist-repeat-rtl-symbolic
- [x] media-playlist-repeat-song-rtl-symbolic
- [x] media-playlist-repeat-song-symbolic
- [x] media-playlist-repeat-symbolic
- [x] media-playlist-shuffle-rtl-symbolic
- [x] media-playlist-shuffle-symbolic
- [x] media-removable-symbolic
- [x] media-seek-backward-rtl
- [x] media-seek-backward-symbolic-rtl
- [x] media-seek-forward-rtl
- [x] media-seek-forward-symbolic-rtl
- [x] media-skip-backward-rtl
- [x] media-skip-backward-symbolic-rtl
- [x] media-skip-forward-rtl
- [x] media-skip-forward-symbolic-rtl
- [x] media-tape-symbolic
- [x] media-view-subtitles-symbolic
- [x] media-zip-symbolic
- [x] notification-microphone-sensitivity-high
- [x] microphone-sensitivity-high-symbolic
- [x] notification-microphone-sensitivity-low
- [x] microphone-sensitivity-low-symbolic
- [x] notification-microphone-sensitivity-medium
- [x] microphone-sensitivity-medium-symbolic
- [x] notification-microphone-sensitivity-muted
- [x] microphone-sensitivity-muted-symbolic
- [x] modem
- [ ] modem-symbolic
- [ ] network-cellular-3g-symbolic
- [ ] network-cellular-4g-symbolic
- [ ] network-cellular-acquiring-symbolic
- [ ] network-cellular-connected
- [ ] network-cellular-connected-symbolic
- [ ] network-cellular-edge-symbolic
- [ ] network-cellular-gprs-symbolic
- [ ] network-cellular-hspa-symbolic
- [ ] network-cellular-no-route-symbolic
- [ ] network-cellular-offline-symbolic
- [ ] network-cellular-signal-excellent-symbolic
- [x] network-cellular-signal-good-symbolic
- [x] network-cellular-signal-none-symbolic
- [x] network-cellular-signal-ok-symbolic
- [x] network-cellular-signal-weak-symbolic
- [x] network-error-symbolic
- [x] network-idle-symbolic
- [ ] network-no-route-symbolic
- [x] network-offline-symbolic
- [x] network-receive-symbolic
- [x] network-transmit-receive-symbolic
- [x] network-transmit-symbolic
- [ ] network-vpn-acquiring-symbolic
- [ ] network-vpn-symbolic
- [ ] network-wired-no-route-symbolic
- [ ] network-wireless-hotspot-symbolic
- [ ] network-wireless-no-route-symbolic
- [x] network-wireless-offline-symbolic
- [x] network-wireless-symbolic
- [x] non-starred
- [x] non-starred-symbolic
- [x] open-menu-symbolic
- [x] package-x-generic-symbolic
- [x] pan-down-symbolic
- [x] pan-end-symbolic
- [x] pan-end-symbolic-rtl
- [x] pan-start-symbolic
- [x] pan-start-symbolic-rtl
- [x] pan-up-symbolic
- [x] pda-symbolic
- [x] phone-apple-iphone-symbolic
- [x] printer-error-symbolic
- [x] printer-network
- [ ] printer-network-symbolic
- [x] printer-printing
- [x] printer-printing-symbolic
- [x] printer-warning-symbolic
- [x] process-working-symbolic
- [x] radio-checked-symbolic
- [x] radio-mixed-symbolic
- [x] radio-symbolic
- [x] rotation-allowed-symbolic
- [x] rotation-locked-symbolic
- [x] security-high
- [x] security-high-symbolic
- [x] security-low
- [x] security-low-symbolic
- [x] security-medium-symbolic
- [x] selection-end-symbolic
- [x] selection-end-symbolic-rtl
- [x] selection-start-symbolic
- [x] selection-start-symbolic-rtl
- [x] semi-starred
- [x] semi-starred-rtl
- [x] semi-starred-rtl-symbolic
- [x] semi-starred-symbolic
- [ ] software-update-available
- [x] software-update-available-symbolic
- [ ] software-update-urgent
- [x] software-update-urgent-symbolic
- [x] star-new-symbolic
- [x] starred
- [x] starred-symbolic
- [x] start-here-symbolic
- [x] system-help-symbolic
- [x] system-lock-screen-symbolic
- [x] system-search-symbolic
- [x] task-due
- [x] task-due-symbolic
- [x] task-past-due
- [x] task-past-due-symbolic
- [x] text-x-generic-symbolic
- [x] tools-check-spelling-symbolic
- [x] touchpad-disabled-symbolic
- [ ] trophy-bronze
- [ ] trophy-gold
- [ ] trophy-silver
- [x] tv-symbolic
- [ ] uninterruptible-power-supply
- [x] uninterruptible-power-supply-symbolic
- [x] user-bookmarks-symbolic
- [x] user-idle
- [x] user-status-pending-symbolic
- [x] view-more-horizontal-symbolic
- [x] view-sort-ascending-symbolic
- [x] view-sort-descending-symbolic
- [x] view-wrapped-symbolic
- [x] view-wrapped-symbolic-rtl
- [x] x-office-address-book-symbolic
- [x] x-office-calendar-symbolic
- [x] x-office-document-symbolic
- [x] x-office-drawing-symbolic
- [x] x-office-presentation-symbolic
- [x] x-office-spreadsheet-symbolic
- [ ] x-package-repository

**Comment by dirtydancing** [comment]
@wa4557 `network-wired-acquiring-symbolic.svg` has been added, cf. https://github.com/numixproject/numix-icon-theme/issues/570, https://github.com/numixproject/numix-icon-theme/pull/571.

**Comment by wa4557** [comment]
are all of those `-symolic` icons related to #485?

**Comment by dirtydancing** [comment]
No, not at all. I have not checked in detail, but https://github.com/numixproject/numix-icon-theme/issues/485 is mainly related to app icons with an added `-symbolic` name. Also, several of those icons over from https://github.com/numixproject/numix-icon-theme/issues/485 are located in `hicolor` and not in `gnome/Adwaita`, but apparently also this differs in detail depending on the respective distro.

**Comment by dirtydancing** [comment]
@wa4557 When looking into the harddisk icons, I have noted that e.g. `drive-harddisk-solidstate-symbolic` (in `scalable/devices`) is missing from the list.

What is the reference source for the list? An overview of the icons in current adwaita-icon-theme 3.16.2.1 can be found e.g. at https://www.archlinux.org/packages/extra/any/adwaita-icon-theme/ (file list link below "Package Contents").

**Comment by wa4557** [comment]
@dirtydancing I used the ubuntu package as reference, which seems to be outdated. I changed that accordingly

**Comment by dirtydancing** [comment]
Great! I have also noticed that e.g. `battery-symbolic` was not on the list before, and now it is :+1:

**Comment by dirtydancing** [comment]
For the time being, I would like to suggest to strike out the (36) icons in `scalable/apps`, as these appear to be among the ones that are being dealt with in https://github.com/numixproject/numix-icon-theme/issues/485. In the end, they might not be included at all:

usr/share/icons/Adwaita/scalable/apps/accessories-calculator-symbolic.svg
usr/share/icons/Adwaita/scalable/apps/accessories-character-map-symbolic.svg
usr/share/icons/Adwaita/scalable/apps/accessories-dictionary-symbolic.svg
usr/share/icons/Adwaita/scalable/apps/accessories-text-editor-symbolic.svg
usr/share/icons/Adwaita/scalable/apps/applets-screenshooter-symbolic.svg
usr/share/icons/Adwaita/scalable/apps/bluetooth-symbolic.svg
usr/share/icons/Adwaita/scalable/apps/gnome-power-manager-symbolic.svg
usr/share/icons/Adwaita/scalable/apps/goa-panel-symbolic.svg
usr/share/icons/Adwaita/scalable/apps/help-browser-symbolic.svg
usr/share/icons/Adwaita/scalable/apps/help-contents-symbolic.svg
usr/share/icons/Adwaita/scalable/apps/help-faq-symbolic.svg
usr/share/icons/Adwaita/scalable/apps/multimedia-volume-control-symbolic.svg
usr/share/icons/Adwaita/scalable/apps/preferences-color-symbolic.svg
usr/share/icons/Adwaita/scalable/apps/preferences-desktop-accessibility-symbolic.svg
usr/share/icons/Adwaita/scalable/apps/preferences-desktop-display-symbolic.svg
usr/share/icons/Adwaita/scalable/apps/preferences-desktop-font-symbolic.svg
usr/share/icons/Adwaita/scalable/apps/preferences-desktop-keyboard-shortcuts-symbolic.svg
usr/share/icons/Adwaita/scalable/apps/preferences-desktop-locale-symbolic.svg
usr/share/icons/Adwaita/scalable/apps/preferences-desktop-remote-desktop-symbolic.svg
usr/share/icons/Adwaita/scalable/apps/preferences-desktop-screensaver-symbolic.svg
usr/share/icons/Adwaita/scalable/apps/preferences-desktop-wallpaper-symbolic.svg
usr/share/icons/Adwaita/scalable/apps/preferences-system-network-proxy-symbolic.svg
usr/share/icons/Adwaita/scalable/apps/preferences-system-network-symbolic.svg
usr/share/icons/Adwaita/scalable/apps/preferences-system-notifications-symbolic.svg
usr/share/icons/Adwaita/scalable/apps/preferences-system-privacy-symbolic.svg
usr/share/icons/Adwaita/scalable/apps/preferences-system-search-symbolic.svg
usr/share/icons/Adwaita/scalable/apps/preferences-system-sharing-symbolic.svg
usr/share/icons/Adwaita/scalable/apps/preferences-system-time-symbolic.svg
usr/share/icons/Adwaita/scalable/apps/system-file-manager-symbolic.svg
usr/share/icons/Adwaita/scalable/apps/system-software-install-symbolic.svg
usr/share/icons/Adwaita/scalable/apps/system-users-symbolic.svg
usr/share/icons/Adwaita/scalable/apps/text-editor-symbolic.svg
usr/share/icons/Adwaita/scalable/apps/user-info-symbolic.svg
usr/share/icons/Adwaita/scalable/apps/utilities-system-monitor-symbolic.svg
usr/share/icons/Adwaita/scalable/apps/utilities-terminal-symbolic.svg
usr/share/icons/Adwaita/scalable/apps/web-browser-symbolic.svg

**Comment by wa4557** [comment]
Makes sense. I'll do it a little ater

**Comment by dirtydancing** [comment]
Ah, it looks like you removed the icons from `scalable/apps`. This is not what I meant. I would still suggest to leave them listed and to just strike them out, like e.g. the "GitHub folder" in this list over at numix-folders: https://github.com/numixproject/numix-folders/issues/78. This way, they will still be visible and can still be cross-checked e.g. with https://github.com/numixproject/numix-icon-theme/issues/485.

Moverover: would it be possible to bring back the couple of icons that were added since you created the list, just like before? That way, at least some of all these icons can be seen as added, looks more motivating :)

The icon names were:

`network-wired-acquiring-symbolic`, cf. https://github.com/numixproject/numix-icon-theme/issues/570
`battery-symbolic`, cf. https://github.com/numixproject/numix-icon-theme/issues/581
`drive-harddisk-ieee1394-symbolic`, `drive-harddisk-system-symbolic`, `drive-harddisk-usb-symbolic`, cf. https://github.com/numixproject/numix-icon-theme/issues/583
`drive-harddisk-solidstate-symbolic`, cf. https://github.com/numixproject/numix-icon-theme/issues/585

Cheers! I am hopeful that the list management will not turn into too much of an issue in and of itself :)

**Comment by wa4557** [comment]
I think the lists are long enough as is, so I think it's a better idea to remove the finished icons from time to time :)

**Comment by dirtydancing** [comment]
Fair enough :) And imo your call, as you are managing this list. No need to create unnecessary work.

**Comment by dirtydancing** [comment]
@wa4557 So, after the PSA from @Foggalong from over here, https://github.com/numixproject/numix-icon-theme/issues/437#issuecomment-113192513, are you going to re-include the icons I listed above with a check mark? :) That would indeed make it easier to track things.

**Comment by hlechner** [comment]
**application/x-firmware** reported also in #566

**Comment by wa4557** [comment]
For all those symbolic icons: Would it be ok to just use the icons from Adwaita and modify them slightly so that they fit the numix design (I guess that's what happened with all the scalable icons currently present in the theme)

**Comment by dirtydancing** [comment]
Well, I cannot confirm that all the Numix scalable symbolic icons, e.g. in `devices` and `status`, are slight modifications of Adwaita. Adwaita is very good in these imo, though, and so does not really crash with the Numix icons. Anyways, with my use of Arch/GNOME, I do not run into that many Adwaita icons at all.

**Comment by Foggalong** [comment]
Regarding the symbolic icons, no. afaik the Numix symbolic icons (mostly designed by @me4oslav) are of Numix design, not an Adwaita one.

**Comment by wa4557** [comment]
I politely disagree, but that's not true. Most of the icons in `scalable/devices` and `scalable/actions` are from the adwaita theme, the icons from `scalable/status` are original however, that's true

**Comment by dirtydancing** [comment]
To me, there seems to be an overlap but also differing icons/icon names in `scalable/actions`, but there seem to be distinguished Numix icons in `scalable/categories`, `scalable/devices`, `scalable/emblems`, `scalable/mimetypes`, `scalable/places` and `scalable/status`. I am not sure why there are still coloured non-symbolic named icons in `scalable/apps`.

**Comment by palob** [comment]
I think a few icons are older-revision Adwaita icons.

**Comment by bil-elmoussaoui** [comment]
@Foggalong @wa4557 a lot of symbolic icons were in added in the latest pull request! i think they should be ticked :+1:

**Comment by wa4557** [comment]
done, still more than 200 icons :)

**Comment by Foggalong** [comment]
:+1:

**Comment by bil-elmoussaoui** [comment]
@wa4557 ` network-wireless-offline-symbolic` already exists

**Comment by bil-elmoussaoui** [comment]
@wa4557 @Foggalong Those icons can be ticked from the list :p 
- view-wrapped-symbolic
- view-wrapped-symbolic-rtl
- network-wireless-offline-symbolic
- touchpad-disabled-symbolic
- tools-check-spelling-symbolic
- starred-symbolic
- phone-apple-iphone-symbolic
- network-wireless-symbolic
-  media-removable-symbolic
- media-playlist-shuffle-symbolic
- input-touchpad-symbolic
- input-tablet-symbolic
- go-previous-symbolic-rtl
-  edit-clear-all
- document-print-symbolic
- computer-apple-ipad-symbolic

**Comment by wa4557** [comment]
@bil-elmoussaoui Done

**Comment by bil-elmoussaoui** [comment]
@wa4557 Those ones too
-  tv-symbolic
-  media-playback-start-symbolic-rtl
-  media-optical-bd-symbolic
-  media-optical-dvd-symbolic
-  mail-replied-symbolic
-  computer-symbolic

**Comment by palob** [comment]
Closing this because GNOME apps don't use the non-symbolic icons anymore.
The few icons missing here for completion probably won't be used in any app anyway.
