### ISSUE TITLE
Icon for battery-symbolic.svg

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-icon-theme#581]
A Numix base icon is missing for `battery-symbolic.svg`.

I am not sure where this one is used, but it is present in th GNOME default icon theme Adwaita in `scalable/devices`. In Adwaita, this is the same icon as `battery-full-symbolic.svg` in `scalable/status`. So the way to go about this in Numix would be to add a symlink `battery-symbolic.svg` in `scalable/devices` with the target `battery-full-symbolic.svg` in`scalable/status`.

Icon screenshot:

![battery-symbolic](https://cloud.githubusercontent.com/assets/7164227/8206028/2403b46e-14f6-11e5-9516-66d34960b327.png)

**Comment by wa4557** [comment]
`scalable` icons are great, you only have to worry about one size :)

**Comment by dirtydancing** [comment]
Agreed, this is a good side of gnome/Adwaita making more and more use of "symbolic"-named icons :)
