### ISSUE TITLE
Icon for drive-removable-media-symbolic.svg

### ISSUE THREAD

**Issue by dirtydancing** [numixproject/numix-icon-theme#588]
A Numix base icon is missing for `drive-removable-media-symbolic.svg`. This icon is present in current GNOME default Adwaita icon theme. But in contrast to Numix base, Adwaita does not contain `drive-removable-media-usb-symbolic.svg`.

So the way to go about this would be to copy the current Numix base `drive-removable-media-usb-symbolic.svg` and rename the copy into `drive-removable-media-symbolic.svg`. I checked with Arch/GNOME: in the absence of `drive-removable-media-usb-symbolic.svg`, then `drive-removable-media-symbolic.svg` is picked up for USB sticks.

It should be fine to take this icon as the "general" one for "drive-removable":

![drive-removable-media-symbolic](https://cloud.githubusercontent.com/assets/7164227/8252995/8a9cd53e-168b-11e5-8929-527a451335d2.png)

At the same time, it then makes sense to rename the current "backup" icons in Numix base, naming in line with `drive-harddisk-symbolic-backup...`, cf. https://github.com/numixproject/numix-icon-theme/issues/578:
`drive-removable-media-usb-symbolic-1.svg` to `drive-removable-media-usb-symbolic-backup.svg`
`drive-removable-media-usb-symbolic-old.svg` to `drive-removable-media-usb-symbolic-backup2.svg`
`drive-removable-media-usb-symbolic.svg` to `drive-removable-media-usb-symbolic-backup3.svg`

**Comment by palob** [comment]
Closing this. Don't think we need our own symbolic icons. The Adwaita ones blend in well enough.
