### ISSUE TITLE
Mimetype: inode/socket (inode)

### ISSUE THREAD

**Issue by hlechner** [numixproject/numix-icon-theme#593]
Name: **socket**
Mimetype: **inode/socket**

Description: As you already known, devices in UNIX systems are interpreted as files. Then, it has the respective mimetypes, most of them begin with **inode/**

It's not exactly a device, but a socket. for example:
/dev/stderr
/dev/stdout
/run/systemd/journal/dev-log
/dev/fd/1
etc..

![image](https://cloud.githubusercontent.com/assets/11244067/8269443/a344c648-177e-11e5-8ec4-73601c4d150c.png)

**Comment by Foggalong** [comment]
@hlechner can we please get example of what these mimetypes usually look like - there's not too much to go on in a lot of these requests :/

**Comment by hlechner** [comment]
Before the design idea I just want to add here a simple description of Unix socket:

> A socket is a special file used for [inter-process communication](https://en.wikipedia.org/wiki/Inter-process_communication). These allow communication between two processes. In addition to sending data, processes can send [file descriptors](https://en.wikipedia.org/wiki/File_descriptor) across a Unix domain socket connection using the ``sendmsg()`` and ``recvmsg()`` system calls.
>
> Unlike named pipes sockets are fully duplex-capable.

So, Basically its communication point of two sides, the most icons that I've found refer to a outlet plug design.

Already existent Numix design of outlet plug:
![image](https://cloud.githubusercontent.com/assets/11244067/8443179/d2447108-1f5a-11e5-9e5a-78b9af770d94.png) ![image](https://cloud.githubusercontent.com/assets/11244067/8443187/ea3117c6-1f5a-11e5-906a-e4cdcc6e4d87.png) ![image](https://cloud.githubusercontent.com/assets/11244067/8443203/12149ce0-1f5b-11e5-8afc-2dd65602891d.png)


**Additional notes**:
Both **inode/socket** and **[inode/fifo](https://github.com/numixproject/numix-icon-theme/issues/592)** are used for [inter-process communication](https://en.wikipedia.org/wiki/Inter-process_communication), it's possible to use the same icon for both.
