### ISSUE TITLE
Mimetype: inode/symlink (inode)

### ISSUE THREAD

**Issue by hlechner** [numixproject/numix-icon-theme#594]
Name: **Link**
Mimetype: **inode/symlink**

Description: It's the mimetype for symlinks, it will only be displayed when the symlink is broken.

In Nautilus when exist this mimetype in theme, it'll show the icons of (link),(no permission) and (error ? ):
![image](https://cloud.githubusercontent.com/assets/11244067/8269725/836f3738-178b-11e5-8301-fa9d283f8235.png)

The example above I've just created a symlink of **application-x-rpm.svg** to **inode-symlink.svg** to exemplify. 

![image](https://cloud.githubusercontent.com/assets/11244067/8269712/f2c6b2ec-178a-11e5-9a2c-f686224a6433.png)

**Comment by Foggalong** [comment]
This doesn't interfere with symlinks in *any* other situation?

**Comment by hlechner** [comment]
I've tested and no problem found.

Also I check some oxygen-theme-related discussion about this mime, and people said that no reason found at that time to create this mime because it doesn't effect nothing, so it seem safe in KDE side too.

**Comment by hlechner** [comment]
Because the system will follow the symlink and use the destination mimetype, however if it's broken, the mimetype of inode/symlink should be used.

**Comment by hlechner** [comment]
Just for complement it:

Broken symlink:
```
$ gvfs-info --attributes=standard:: Air\ Supply\ -_Goodbye.mp3 
display name: Air Supply -_Goodbye.mp3
edit name: Air Supply -_Goodbye.mp3
name: Air Supply -_Goodbye.mp3
type: symlink
size:  27
attributes:
  standard::type: 3
  standard::is-symlink: TRUE
  standard::name: Air Supply -_Goodbye.mp3
  standard::display-name: Air Supply -_Goodbye.mp3
  standard::edit-name: Air Supply -_Goodbye.mp3
  standard::copy-name: Air Supply -_Goodbye.mp3
  standard::icon: inode-symlink, inode-x-generic
  standard::content-type: inode/symlink
  standard::fast-content-type: inode/symlink
  standard::size: 27
  standard::allocated-size: 0
  standard::symlink-target: ../Air_Supply_-_Goodbye.mp3
  standard::symbolic-icon: inode-symlink-symbolic, inode-x-generic-symbolic, inode-symlink, inode-x-generic
```
``` standard::icon: inode-symlink, inode-x-generic ```

Working symlink:
```
$ gvfs-info --attributes=standard:: Bryan\ Adams\ -\ Heaven.mp3 
display name: Bryan Adams - Heaven.mp3
edit name: Bryan Adams - Heaven.mp3
name: Bryan Adams - Heaven.mp3
type: regular
size:  4879308
attributes:
  standard::type: 1
  standard::is-symlink: TRUE
  standard::name: Bryan Adams - Heaven.mp3
  standard::display-name: Bryan Adams - Heaven.mp3
  standard::edit-name: Bryan Adams - Heaven.mp3
  standard::copy-name: Bryan Adams - Heaven.mp3
  standard::icon: audio-mpeg, audio-x-generic
  standard::content-type: audio/mpeg
  standard::fast-content-type: audio/mpeg
  standard::size: 4879308
  standard::allocated-size: 4882432
  standard::symlink-target: ../Bryan Adams - Heaven.mp3
  standard::symbolic-icon: audio-mpeg-symbolic, audio-x-generic-symbolic, audio-mpeg, audio-x-generic
```

```standard::icon: audio-mpeg, audio-x-generic```

So, it doesn't affect the icon, because this mimetype is not even in the icon list from a working symlink.

**Comment by hlechner** [comment]
Nice!
