### ISSUE TITLE
Implement Better HiDPI Support

### ISSUE THREAD

**Issue by Foggalong** [numixproject/numix-icon-theme#610]
The brilliant folks at elementary recently went to a summit to talk to the GNOME folks. They talked about various things including increased collaboration (yay!) but the thing important for Numix is that they discussed how to implement better HiDPI support in their icon themes. This is the [relevant commit](https://code.launchpad.net/~elementary-design/elementaryicons/hidpi-test/+merge/263317) on Launchpad for the elementary icon theme and we basically need to dig through this and find what we need to add to our themes. 

I'd really like to finish #190 first since adding support for both involves significant changes to the `index.theme` file. The equivalent issue for Circle is [found here](https://github.com/numixproject/numix-icon-theme-circle/issues/2377). The change for Circle will then be ported to Square and all our other supported icon themes.

**Comment by wa4557** [comment]
Boah, I bet that this will break something. The battery icons won't be happy with the fiddling in the `index.theme` (I still think we should do that; sitting in front of one of those fancy retina screens right now :)

**Comment by Foggalong** [comment]
Yeah, it's a hell of a big issue so will need dealing with very sensitively and in isolation.

**Comment by bil-elmoussaoui** [comment]
This might help http://blog.elementary.io/post/124193007916/whats-up-with-hidpi-icons

**Comment by Foggalong** [comment]
Yeah, just been reading this! Sounds simple enough so gonna deal with all the outstanding pull requests tomorrow and then get this one solved :D

**Comment by Foggalong** [comment]
Started working on this in the [HiDPI branch](https://github.com/numixproject/numix-icon-theme/tree/hidpi)

**Comment by wa4557** [comment]
I have implemented that in a branch of my fork. Works great (tried it already on a hidpi Screen), I'll open a new PR as soon as my current one is merged...

**Comment by bil-elmoussaoui** [comment]
@Foggalong fixed by @wa4557 in his latest commit :dancer:
