### ISSUE TITLE
Autokey indicator

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-icon-theme#611]
More info [Autokey](https://code.google.com/p/autokey/)
the missing icons are : 
- [ ]  autokey-status-dark.svg
- [ ]  autokey-status-error.svg
- [ ]  autokey-status.svg

default icons
![capture du 2015-07-03 18 52 01](https://cloud.githubusercontent.com/assets/7660997/8502711/97dee8d4-21b4-11e5-879d-d87f87362140.png)

**Comment by wa4557** [comment]
The question is now of course: where should I put them if I make them?

**Comment by bil-elmoussaoui** [comment]
when i use Numix Circle the application icon is used :/ it's seems to be a "toxic" icon.
![capture du 2015-07-03 18 47 09](https://cloud.githubusercontent.com/assets/7660997/8502741/03ee3c50-21b5-11e5-9877-44ab6f8946aa.png)

**Comment by Foggalong** [comment]
I probably won't accept any more status icon type merges until after #190 is done. After we've figured out that bit we can start debating where we move from there

**Comment by wa4557** [comment]
makes sense.
