### ISSUE TITLE
Qt apps indicator

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-icon-theme#613]
Hardcode-Tray now support Qt applications using the patched version of sni-qt. 
I added a support to Skype,Megasync and Google Music Manager
For Skype : 
- [x] skype-status-connected.svg
- [x] skype-status-connected-notification.svg
- [x] skype-status-disturb.svg (for do not disturb status)
- [x] skype-status-disturb-notification.svg
- [x] skype-status-offline.svg
- [x] skype-status-offline-notification.svg
- [x] skype-status-invisible.svg
- [x] skype-status-invisible-notification.svg
- [x] skype-status-away.svg
- [x] skype-status-away-notification.svg
- [x] skype-status-connecting-0.svg
- [x] skype-status-connecting-1.svg
- [x] skype-status-connecting-2.svg
- [x] skype-status-connecting-3.svg

For Megasync 
- [x] megasync-status-paused.svg
- [x] megasync-status-disconnected.svg
- [x] megasync-status-syncing.svg
- [x] megasync-status-ok.svg

For Google Music Manager : 
- [x] google-music-manager-panel.svg

For Google Chrome:  
- [x] google-chrome-notification
- [x] google-chrome-notification-disabled
- [x] google-chrome-no-notification
- [x] google-chrome-no-notification-disabled

Those indicators won't affect #190 and so they can be added without any problem

**Comment by wa4557** [comment]
You have a type in your list: distrub should read disturb (skype)

**Comment by wa4557** [comment]
I guess they belong then to `status`?

**Comment by bil-elmoussaoui** [comment]
@wa4557 Yeah

**Comment by wa4557** [comment]
I'm kinda excited that it is now possible to theme the skype icon, I kind of avoided to use it, because it always looked so ugly in the tray :)

**Comment by bil-elmoussaoui** [comment]
Numix everywhere :dancers:

**Comment by bil-elmoussaoui** [comment]
I added google chrome indicator icons since it's possible to fix them using HardcodeTray

**Comment by pgera** [comment]
Can you add some documentation about the hardcode script to the main README or to the README of the hardcode repo ? It is not very clear how the installation/removal is handled. Is it a one time call to the script ? How would one revert back to stock ? If this is a long term solution, would it make sense to create a separate package and add it to the ppa ?

**Comment by bil-elmoussaoui** [comment]
@pgera well, the script is used to fix the hardcoded tray icons. there's no way to revert back at the moment but i'm going to work on that as soon as possilbe. and you just run the script one time only if there's an update for an application and the way the icons are hardcoded have changed

**Comment by Foggalong** [comment]
@pgera That's something that needs to be added to the [hardcode-tray](https://github.com/bil-elmoussaoui/Hardcode-Tray) repo not here. The script is designed to work with any icon theme, not just Numix, so won't be added to our PPA either.
