### ISSUE TITLE
Syncthing AppIndicator/Panel Icons

### ISSUE THREAD

**Issue by allanbreyes** [numixproject/numix-icon-theme#634]
Posting here per @palob 's request in https://github.com/numixproject/numix-icon-theme-circle/issues/1369#issuecomment-120705904

Located in `/usr/share/icons/hicolor/32x32/apps`

si-idle.png
![si-idle](https://cloud.githubusercontent.com/assets/7947900/8637454/b0132416-2857-11e5-9ecd-a8fb352a47cd.png)

si-syncing-0.png
![si-syncing-0](https://cloud.githubusercontent.com/assets/7947900/8637450/b0100376-2857-11e5-957e-25dcf5b7cf84.png)

si-syncing-1.png
![si-syncing-1](https://cloud.githubusercontent.com/assets/7947900/8637452/b0117de6-2857-11e5-9083-185af6566ade.png)

si-syncing-2.png
![si-syncing-2](https://cloud.githubusercontent.com/assets/7947900/8637451/b010a40c-2857-11e5-9c32-71f54ad84b90.png)

si-syncing-3.png
![si-syncing-3](https://cloud.githubusercontent.com/assets/7947900/8637453/b0119c0e-2857-11e5-9955-8417974ce534.png)

si-syncing-4.png
![si-syncing-4](https://cloud.githubusercontent.com/assets/7947900/8637449/b00f875c-2857-11e5-99d2-c507e80fadc7.png)

si-syncing-5.png
![si-syncing-5](https://cloud.githubusercontent.com/assets/7947900/8637457/b01d2ad8-2857-11e5-9b51-090d617a6f88.png)

si-syncing-6.png
![si-syncing-6](https://cloud.githubusercontent.com/assets/7947900/8637458/b01d1cf0-2857-11e5-9120-9ac7d055055a.png)

si-syncing-7.png
![si-syncing-7](https://cloud.githubusercontent.com/assets/7947900/8637455/b01c5752-2857-11e5-8b69-b46f89911033.png)

si-syncing-8.png
![si-syncing-8](https://cloud.githubusercontent.com/assets/7947900/8637456/b01c7354-2857-11e5-8616-fa9289766bcd.png)

si-syncing-9.png
![si-syncing-9](https://cloud.githubusercontent.com/assets/7947900/8637459/b01e60ba-2857-11e5-8631-c4d95fe9aa22.png)

si-syncing-10.png
![si-syncing-10](https://cloud.githubusercontent.com/assets/7947900/8637460/b0209e5c-2857-11e5-9d03-16cb11503eee.png)

si-syncing-11.png
![si-syncing-11](https://cloud.githubusercontent.com/assets/7947900/8637463/b0289bb6-2857-11e5-93bd-05c39070dc51.png)

si-unknown.png
![si-unknown](https://cloud.githubusercontent.com/assets/7947900/8637462/b0283400-2857-11e5-9a06-dcba22d6592f.png)

syncthing-gtk.png
![syncthing-gtk](https://cloud.githubusercontent.com/assets/7947900/8637461/b0260ac2-2857-11e5-8965-3c0cf04440d2.png)

Numix needs to be EVERYWHERE!

**Comment by wa4557** [comment]
@palob @allanbreyes I guess the last icon is the app icon?

**Comment by allanbreyes** [comment]
Yep!  numix-icon-theme-circle has a fix just for that file at https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/syncthing-gtk.svg

**Comment by palob** [comment]
Yep, the last one's fixed.

**Comment by wa4557** [comment]
I don't get it: are this now emblems (as lad out in the issue in circle) or tray/panel icons?

**Comment by palob** [comment]
The elementaryPlus has the above in ``status/24``, and additionally the follwing in ``emblems/16``.
![syncthing](https://cloud.githubusercontent.com/assets/7050624/8637571/a0998264-2898-11e5-9d27-82511f8fd49d.png)

@allanbreyes Can you find those as well?

**Comment by wa4557** [comment]
@allanbreyes Another information that's necessary. If those icons are panel icon, what icon is showing up right now in the panel? Is it the Numix-circle icon or the icons you posted above (this information is necessary because it shows us where to put the icon)

@palob Emblems in `16x16`, seriously? I figure they are in bigger sizes as well oO

**Comment by palob** [comment]
@wa4557 They've got a different size definition:
```
[emblems/16]
Size=16
Context=Emblems
MinSize=8
MaxSize=512
Type=Scalable
```

**Comment by wa4557** [comment]
That's actually pretty smart

**Comment by allanbreyes** [comment]
Panel icons: It's definitely not the Numix ones.

![image](https://cloud.githubusercontent.com/assets/7947900/8637605/4a54f39a-285f-11e5-976e-c6784060b657.png)

Total noob at this, but I don't think the emblems on my system (Ubuntu 15.04) can be fixed from Numix's side.  They are stored/hardcoded for `/usr/local/pixmaps`, so I filed a request on syncthing-gtk via https://github.com/syncthing/syncthing-gtk/issues/177  Not sure how elementaryPlus gets it to work....
