### ISSUE TITLE
Corrupt zip file download

### ISSUE THREAD

**Issue by Enawa** [numixproject/numix-icon-theme#648]
Symbolic links are damaged
![captura de pantalla de 2015-07-20 11-15-45](https://cloud.githubusercontent.com/assets/6188052/8780766/bb91d434-2ed0-11e5-9024-4bf6d7356426.png)
![captura de pantalla de 2015-07-20 11-17-24](https://cloud.githubusercontent.com/assets/6188052/8780795/ee45afb8-2ed0-11e5-816a-d8de86f0b2b9.png)

**Comment by Foggalong** [comment]
Where have you downloaded this from?

**Comment by palob** [comment]
Those ``....-symbolic.svg`` named files aren't symbolic links btw.

**Comment by Foggalong** [comment]
I'm so not used to seeing file managers not using Numix or Flattr that this has really thrown me off :P

**Comment by Enawa** [comment]
It's an SVG, sorry. :(
GitHub zip download.

**Comment by Enawa** [comment]
![captura de pantalla de 2015-07-20 14-42-29](https://cloud.githubusercontent.com/assets/6188052/8785598/888f854a-2eee-11e5-9210-134189fd3b4a.png)

**Comment by palob** [comment]
Can't confirm. Extracted the ZIP and got 26152 objects @66.2 MB

**Comment by Enawa** [comment]
This bug not is from Numix. It's from GitHub or Zip, sorry.
Excuse the trouble.

**Comment by Foggalong** [comment]
No problem! :)
