### ISSUE TITLE
 mate-tweak fails to launch with Numix theme 

### ISSUE THREAD

**Issue by bedfojo** [numixproject/numix-icon-theme#659]
As reported at: https://bugs.launchpad.net/ubuntu/+source/mate-tweak/+bug/1477730

I try to launch mate-tweak when running the Numix theme, but nothing happens. If I change to another theme it launches.

Trying to launch in a terminal gives:

Traceback (most recent call last):
  File "/usr/bin/mate-tweak", line 740, in <module>
    MateTweak()
  File "/usr/bin/mate-tweak", line 584, in __init__
    img = theme.load_icon(sidePage.icon, 36, 0)
GLib.Error: gtk-icon-theme-error-quark: Icon 'preferences-system-windows' not present in theme (0)

Ubuntu MATE 15.04
mate-tweak version 3.5.0-1~vivid1
Numix GTK Theme version 2.3+341~201506190531~ubuntu15.04.1
Numix icon theme version 0.3+507~201507221917~ubuntu15.04.

The missing icon needs adding.

**Comment by bil-elmoussaoui** [comment]
Can you share an icon of the original icon? preferences-system-windows

**Comment by Foggalong** [comment]
The solution isn't for us to add that icon (though it is something that we'll do) it's for the MATE devs to add a fallback theme.

**Comment by bedfojo** [comment]
Here are the MATE and MATE-fazenda icons.
![preferences-system-windows](https://cloud.githubusercontent.com/assets/9306613/8993744/0392372c-3707-11e5-8e48-caebd7a17ef5.png)
![preferences-system-windows](https://cloud.githubusercontent.com/assets/9306613/8993756/243b6624-3707-11e5-88b9-154298256bab.png)
