### ISSUE TITLE
Tilda icon

### ISSUE THREAD

**Issue by lightonflux** [numixproject/numix-icon-theme#660]
Just installed the dropdown terminal Tilda and realised there is no numix icon for it. 

It is worth to mention that Ubuntu Mate is a popular distribution that uses ships with enabled tilda by default. 

A symlink to one of the generic terminal icons would be sufficient. 

Tilda's current logo: https://github.com/lanoxx/tilda/blob/master/tilda.png

Website: https://github.com/lanoxx/tilda

**Comment by Foggalong** [comment]
App requests [go here](https://github.com/numixproject/numix-icon-theme-circle) :)

**Comment by lightonflux** [comment]
Oh, sorry. Thanks for the fast reply and directions.
