### ISSUE TITLE
Default image for a missing icon

### ISSUE THREAD

**Issue by leoheck** [numixproject/numix-icon-theme#663]
There is a way to change the default icon for the missing icon?
It is possible to have a round icon when launcher can't find the icon?
Take a look in "ReceitaNet" application.
![icons](https://cloud.githubusercontent.com/assets/1277920/9156463/6c90ce3a-3eb1-11e5-8626-70129f9000cf.png)

**Comment by palob** [comment]
I've never used the Unity desktop but I think the default icons should show up in case there's no Numix icon.

**Comment by bil-elmoussaoui** [comment]
This is not the case in your screenshot, those icons are pointing to icons that does not exists (using a path) and not an icon name. That's why those icons are shown instead of the default icons

**Comment by leoheck** [comment]
I see, thanks
