### ISSUE TITLE
Inconsistency in device icons depending on Ubuntu icon size settings

### ISSUE THREAD

**Issue by keunes** [numixproject/numix-icon-theme#664]
Testing things for another bug with the launcher icons, I discovered that when I set the icon size 40 or higher, on my external monitor the icon for my windows partition is not the icon that I'm used to.

I reported a [bug](https://github.com/numixproject/numix-icon-theme-circle/issues/2476) for Numix Circle, but apparently it's an issue with the base theme. Would expect icons to remain consistent, regardless of size settings :)

Expected (38 & under) and unexpected (40 and up) icon:
![screenshot from 2015-08-12 22 14 37](https://cloud.githubusercontent.com/assets/11229646/9235595/eb420b14-413f-11e5-8022-8220e57455cf.png) ![screenshot from 2015-08-12 22 13 29](https://cloud.githubusercontent.com/assets/11229646/9235594/eb25c2ec-413f-11e5-9ee7-c6ff4c2924fa.png)

**Comment by Foggalong** [comment]
I'll fix this asap :)

**Comment by wa4557** [comment]
What's the way to fix this? Adding polychrome icons to larger sizes as well? (Probably just a scaled up version of the `32x32` icons)

**Comment by Foggalong** [comment]
Yeah, I need to ask someone why the devices icons above 48px are monochrome and check it is intact just a case of never being updated.

**Comment by wa4557** [comment]
Fortunately if we are going to add polychrome icons for larger sizes this might be a very easy task. Almost all the icons for lower sizes are nicely aligned to grid

**Comment by Foggalong** [comment]
Excellent :D

**Comment by wa4557** [comment]
Obviously larger icons just weren't added. Looking at [this] (https://github.com/numixproject/numix-icon-theme/commit/7f88cbeefe4dc47c0fb8f8e1ded0c6003a3ae041) commit only icons up to `48x48` were added

**Comment by wa4557** [comment]
https://github.com/holylobster/nuntius-linux#the-icon

**Comment by sljunkie** [comment]
Devices icons in /usr/share/icons/gnome (Unity, Cinnamon and Gnome-shell use them):

$ pwd
/usr/share/icons/gnome/256x256/devices
$ ls -l
total 1416
lrwxrwxrwx 1 root root    16 Apr 15 18:38 3floppy_unmount.png -> media-floppy.png
-rw-r--r-- 1 root root 35206 Apr 15 18:38 ac-adapter.png
-rw-r--r-- 1 root root 22485 Apr 15 18:38 audio-headphones.png
-rw-r--r-- 1 root root 24953 Apr 15 18:38 audio-headset.png
-rw-r--r-- 1 root root 35641 Apr 15 18:38 audio-input-microphone.png
-rw-r--r-- 1 root root 57495 Apr 15 18:38 audio-speakers.png
-rw-r--r-- 1 root root 11276 Apr 15 18:38 battery.png
-rw-r--r-- 1 root root 35484 Apr 15 18:38 camera-photo.png
lrwxrwxrwx 1 root root    16 Apr 15 18:38 camera.png -> camera-photo.png
lrwxrwxrwx 1 root root    16 Apr 15 18:38 camera_unmount.png -> camera-photo.png
-rw-r--r-- 1 root root 31489 Apr 15 18:38 camera-web.png
lrwxrwxrwx 1 root root    17 Apr 15 18:38 cdrom_unmount.png -> media-optical.png
lrwxrwxrwx 1 root root    17 Apr 15 18:38 cdwriter_unmount.png -> media-optical.png
lrwxrwxrwx 1 root root    17 Apr 15 18:38 chardevice.png -> video-display.png
-rw-r--r-- 1 root root 27128 Apr 15 18:39 colorimeter-colorhug.png
-rw-r--r-- 1 root root 42393 Apr 15 18:39 computer-apple-ipad.png
-rw-r--r-- 1 root root 37415 Apr 15 18:38 computer.png
lrwxrwxrwx 1 root root    17 Apr 15 18:38 display.png -> video-display.png
lrwxrwxrwx 1 root root    17 Apr 15 18:38 drive-cdrom.png -> drive-optical.png
-rw-r--r-- 1 root root 22057 Apr 15 18:39 drive-harddisk-ieee1394.png
-rw-r--r-- 1 root root 27782 Apr 15 18:38 drive-harddisk.png
-rw-r--r-- 1 root root 22543 Apr 15 18:39 drive-harddisk-solidstate.png
-rw-r--r-- 1 root root 32666 Apr 15 18:39 drive-harddisk-system.png
-rw-r--r-- 1 root root 25308 Apr 15 18:39 drive-harddisk-system-solidstate.png
-rw-r--r-- 1 root root 21574 Apr 15 18:39 drive-harddisk-usb.png
-rw-r--r-- 1 root root 33560 Apr 15 18:38 drive-multidisk.png
-rw-r--r-- 1 root root 23035 Apr 15 18:38 drive-optical.png
-rw-r--r-- 1 root root 12111 Apr 15 18:38 drive-removable-media.png
lrwxrwxrwx 1 root root    17 Apr 15 18:38 dvd_unmount.png -> media-optical.png
lrwxrwxrwx 1 root root    11 Apr 15 18:38 gnome-dev-battery.png -> battery.png
lrwxrwxrwx 1 root root    17 Apr 15 18:38 gnome-dev-cdrom-audio.png -> media-optical.png
lrwxrwxrwx 1 root root    17 Apr 15 18:38 gnome-dev-cdrom.png -> drive-optical.png
lrwxrwxrwx 1 root root    12 Apr 15 18:38 gnome-dev-computer.png -> computer.png
lrwxrwxrwx 1 root root    17 Apr 15 18:38 gnome-dev-disc-cdr.png -> media-optical.png
lrwxrwxrwx 1 root root    17 Apr 15 18:38 gnome-dev-disc-cdrw.png -> media-optical.png
lrwxrwxrwx 1 root root    17 Apr 15 18:38 gnome-dev-disc-dvdram.png -> media-optical.png
lrwxrwxrwx 1 root root    17 Apr 15 18:38 gnome-dev-disc-dvdrom.png -> media-optical.png
lrwxrwxrwx 1 root root    17 Apr 15 18:38 gnome-dev-disc-dvdr-plus.png -> media-optical.png
lrwxrwxrwx 1 root root    17 Apr 15 18:38 gnome-dev-disc-dvdr.png -> media-optical.png
lrwxrwxrwx 1 root root    17 Apr 15 18:38 gnome-dev-disc-dvdrw.png -> media-optical.png
lrwxrwxrwx 1 root root    17 Apr 15 18:38 gnome-dev-dvd.png -> drive-optical.png
lrwxrwxrwx 1 root root    16 Apr 15 18:38 gnome-dev-floppy.png -> media-floppy.png
lrwxrwxrwx 1 root root    18 Apr 15 18:38 gnome-dev-harddisk-1394.png -> drive-harddisk.png
lrwxrwxrwx 1 root root    18 Apr 15 18:38 gnome-dev-harddisk.png -> drive-harddisk.png
lrwxrwxrwx 1 root root    18 Apr 15 18:38 gnome-dev-harddisk-usb.png -> drive-harddisk.png
lrwxrwxrwx 1 root root    21 Apr 15 18:38 gnome-dev-ipod.png -> multimedia-player.png
lrwxrwxrwx 1 root root    18 Apr 15 18:38 gnome-dev-keyboard.png -> input-keyboard.png
lrwxrwxrwx 1 root root    15 Apr 15 18:38 gnome-dev-media-cf.png -> media-flash.png
lrwxrwxrwx 1 root root    15 Apr 15 18:38 gnome-dev-media-ms.png -> media-flash.png
lrwxrwxrwx 1 root root    15 Apr 15 18:38 gnome-dev-media-sdmmc.png -> media-flash.png
lrwxrwxrwx 1 root root    15 Apr 15 18:38 gnome-dev-media-sm.png -> media-flash.png
lrwxrwxrwx 1 root root    15 Apr 15 18:38 gnome-dev-mouse-ball.png -> input-mouse.png
lrwxrwxrwx 1 root root    15 Apr 15 18:38 gnome-dev-mouse-optical.png -> input-mouse.png
lrwxrwxrwx 1 root root    11 Apr 15 18:38 gnome-dev-printer.png -> printer.png
lrwxrwxrwx 1 root root    25 Apr 15 18:38 gnome-dev-removable-1394.png -> drive-removable-media.png
lrwxrwxrwx 1 root root    25 Apr 15 18:38 gnome-dev-removable.png -> drive-removable-media.png
lrwxrwxrwx 1 root root    25 Apr 15 18:38 gnome-dev-removable-usb.png -> drive-removable-media.png
lrwxrwxrwx 1 root root    12 Apr 15 18:38 gnome-fs-client.png -> computer.png
lrwxrwxrwx 1 root root    26 Apr 15 18:38 gnome-stock-mic.png -> audio-input-microphone.png
lrwxrwxrwx 1 root root    17 Apr 15 18:38 gtk-cdrom.png -> media-optical.png
lrwxrwxrwx 1 root root    16 Apr 15 18:38 gtk-floppy.png -> media-floppy.png
lrwxrwxrwx 1 root root    18 Apr 15 18:38 gtk-harddisk.png -> drive-harddisk.png
lrwxrwxrwx 1 root root    18 Apr 15 18:38 harddrive.png -> drive-harddisk.png
lrwxrwxrwx 1 root root    18 Apr 15 18:38 hdd_unmount.png -> drive-harddisk.png
-rw-r--r-- 1 root root 29939 Apr 15 18:38 input-dialpad.png
-rw-r--r-- 1 root root 15163 Apr 15 18:38 input-keyboard.png
-rw-r--r-- 1 root root 26452 Apr 15 18:38 input-mouse.png
-rw-r--r-- 1 root root 22599 Apr 15 18:38 input-tablet.png
lrwxrwxrwx 1 root root    21 Apr 15 18:38 ipod_mount.png -> multimedia-player.png
lrwxrwxrwx 1 root root    18 Apr 15 18:38 keyboard.png -> input-keyboard.png
lrwxrwxrwx 1 root root    11 Apr 15 18:38 kjobviewer.png -> printer.png
lrwxrwxrwx 1 root root    18 Apr 15 18:38 kxkb.png -> input-keyboard.png
lrwxrwxrwx 1 root root    17 Apr 15 18:38 media-cdrom.png -> media-optical.png
-rw-r--r-- 1 root root 53447 Apr 15 18:38 media-flash.png
-rw-r--r-- 1 root root 31878 Apr 15 18:38 media-floppy.png
-rw-r--r-- 1 root root 57689 Apr 15 18:39 media-optical-bd.png
-rw-r--r-- 1 root root 59313 Apr 15 18:39 media-optical-cd-audio.png
-rw-r--r-- 1 root root 57663 Apr 15 18:39 media-optical-dvd.png
-rw-r--r-- 1 root root 49992 Apr 15 18:38 media-optical.png
-rw-r--r-- 1 root root 39140 Apr 15 18:38 media-removable.png
lrwxrwxrwx 1 root root    15 Apr 15 18:38 mouse.png -> input-mouse.png
-rw-r--r-- 1 root root 33863 Apr 15 18:39 multimedia-player-apple-ipod-touch.png
-rw-r--r-- 1 root root 20673 Apr 15 18:38 multimedia-player.png
-rw-r--r-- 1 root root 32379 Apr 15 18:39 phone-apple-iphone.png
-rw-r--r-- 1 root root 34412 Apr 15 18:39 phone-google-nexus-one.png
-rw-r--r-- 1 root root 36169 Apr 15 18:39 phone-htc-g1-white.png
-rw-r--r-- 1 root root 33923 Apr 15 18:39 phone-palm-pre.png
-rw-r--r-- 1 root root 17682 Apr 15 18:38 phone.png
-rw-r--r-- 1 root root 27305 Apr 15 18:39 phone-samsung-galaxy-s.png
lrwxrwxrwx 1 root root    11 Apr 15 18:38 printer1.png -> printer.png
-rw-r--r-- 1 root root 19778 Apr 15 18:38 printer-network.png
-rw-r--r-- 1 root root 15592 Apr 15 18:38 printer.png
lrwxrwxrwx 1 root root    11 Apr 15 18:38 printer-remote.png -> printer.png
lrwxrwxrwx 1 root root    11 Apr 15 18:38 printmgr.png -> printer.png
-rw-r--r-- 1 root root 21170 Apr 15 18:38 scanner.png
lrwxrwxrwx 1 root root     9 Apr 15 18:38 stock_cell-phone.png -> phone.png
lrwxrwxrwx 1 root root    26 Apr 15 18:38 stock_mic.png -> audio-input-microphone.png
lrwxrwxrwx 1 root root    11 Apr 15 18:38 stock_printers.png -> printer.png
lrwxrwxrwx 1 root root    16 Apr 15 18:38 system-floppy.png -> media-floppy.png
lrwxrwxrwx 1 root root    12 Apr 15 18:38 system.png -> computer.png
-rw-r--r-- 1 root root 12469 Apr 15 18:38 uninterruptible-power-supply.png
lrwxrwxrwx 1 root root    25 Apr 15 18:38 usbpendrive_unmount.png -> drive-removable-media.png
-rw-r--r-- 1 root root 24457 Apr 15 18:38 video-display.png
lrwxrwxrwx 1 root root    17 Apr 15 18:38 xfce4-display.png -> video-display.png
lrwxrwxrwx 1 root root    18 Apr 15 18:38 xfce4-keyboard.png -> input-keyboard.png
lrwxrwxrwx 1 root root    15 Apr 15 18:38 xfce4-mouse.png -> input-mouse.png
lrwxrwxrwx 1 root root    11 Apr 15 18:38 xfce-printer.png -> printer.png
lrwxrwxrwx 1 root root    18 Apr 15 18:38 yast_HD.png -> drive-harddisk.png
lrwxrwxrwx 1 root root    18 Apr 15 18:38 yast_idetude.png -> drive-harddisk.png
lrwxrwxrwx 1 root root    15 Apr 15 18:38 yast_mouse.png -> input-mouse.png
lrwxrwxrwx 1 root root    11 Apr 15 18:38 yast_printer.png -> printer.png

**Comment by bil-elmoussaoui** [comment]
This issue should get a higher priority as the monochrome icons look really ugly on my desktop :p

**Comment by wa4557** [comment]
I have the icons ready for `64px`. As soon as the current PR is merged I can open a new one with the new icons :)
