### ISSUE TITLE
Missing weather indicator icons

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-icon-theme#668]
I symlinked some weather indicators for my-weather-indicator (Hardcode-Tray), but there's still some missing icons 

- [ ] weather-chance-of-rain-night
- [ ] weather-chance-of-rain
- [ ] weather-chance-of-snow-night
- [ ] weather-chance-of-snow
- [ ] weather-chance-of-thunderstorms-night
- [ ] weather-chance-of-thunderstorms
- [ ] weather-cloudy
- [ ] weather-flurries
- [ ] weather-fog-night
- [ ] weather-freezing-drizzle
- [ ] weather-icy
- [ ] weather-light-rain
- [ ] weather-light-snow
- [ ] weather-mostly-sunny-night
- [ ] weather-mostly-sunny
- [ ] weather-not-available
- [ ] weather-rain-new
- [ ] weather-rain
- [ ] weather-windy

**Comment by wa4557** [comment]
I didn't know something like "freezing-drizzle" exists :) I'll do some of them as soon as I'm finished with the categories icons

**Comment by Foggalong** [comment]
Possibly means hail? Could be a translation problem

**Comment by bil-elmoussaoui** [comment]
@wa4557 Those are the my-weather-indicator icons if you don't want to install the application [Icons](https://www.dropbox.com/s/33f5djwep6pux0f/my-weather-indicator.tar.gz?dl=0)

**Comment by wa4557** [comment]
It's obviusly a thing: https://en.wikipedia.org/wiki/Freezing_drizzle

**Comment by Foggalong** [comment]
That actually sounds pretty cool!

**Comment by wa4557** [comment]
@bil-elmoussaoui The icons don't necessarily have the name you gave them, do they? I'm asking because there are already a lot of weather icons in #580 that have slightly different names (but the same meaning). You should adapt the icon names here probably...

**Comment by bil-elmoussaoui** [comment]
I just copied the names from my-weather-indicator, you can add them as in #580 and i will change the symlinks in hardcode-tray

**Comment by wa4557** [comment]
:+1:

**Comment by bil-elmoussaoui** [comment]
@wa4557 Is this really finished?

**Comment by wa4557** [comment]
Ah you're probably right I guess `weather-windy` is still missing. Apart from that, it's just symlinking (on Hardcode trays side)

**Comment by wa4557** [comment]
Moreover: `weather-mostly-sunny-night` seriously?

**Comment by bil-elmoussaoui** [comment]
@wa4557 I just saw it LOL
