### ISSUE TITLE
Telegram missing in notification area

### ISSUE THREAD

**Issue by depizol** [numixproject/numix-icon-theme#669]
I'm using Ubuntu Mate 14.04 with Numix Circle and I guess that the mini indicator applet version is 1.8.0
![telegram-is-missing-detail](https://cloud.githubusercontent.com/assets/385564/9364977/52748c7c-4685-11e5-9fad-7ac09c9355fd.png)

**Comment by bil-elmoussaoui** [comment]
are you using hardcode-Tray to fix Telegram indicator?

**Comment by depizol** [comment]
Nope,  I just installed hardcode-tray but can't end my session right now to test it.
Thanks for the tip.

**Comment by bil-elmoussaoui** [comment]
Well, which telegram you're talking about? there's a lot of version out there. If you can just share the PPA or the tutorial you followed so we can know the icons name
And you don't need to end your session to see the modifications, just close the application and reopen it again

**Comment by bil-elmoussaoui** [comment]
@Foggalong I think this have nothing to do with Numix; as all telegram clients does not use standard icon location. And the desktop file uses hardcoded icons too. So if it's a hardcoded Tray icon, this should be reported [here](https://github.com/bil-elmoussaoui/Hardcode-Tray) or if it's an application, this should be reported [here](https://github.com/Foggalong/hardcode-fixer). So you can close this

**Comment by Foggalong** [comment]
That icon only usually shows up if it's an icon that can be themed but there's no icon available for it anywhere in the inherits tree (Numix Circle -> Numix -> GNOME -> hicolor). I'm not sure how we can fix this without more information though :/

**Comment by wa4557** [comment]
@depizol Still an issue (After using Hardcode-Tray)?

**Comment by wa4557** [comment]
@Foggalong This can be closed. Hardcode-Tray supports Telegram for ages now..
