### ISSUE TITLE
WARNING: icon cache generation failed for /usr/share/icons/Numix

### ISSUE THREAD

**Issue by pgera** [numixproject/numix-icon-theme#692]
Latest ppa update on 14.04 gives this warning. Manual sudo gtk-update-icon-cache /usr/share/icons/Numix gives the same error too.

**Comment by pgera** [comment]
Still seeing this with the new package. "gtk-update-icon-cache: Failed to open file /usr/share/icons/Numix/.icon-theme.cache : File exists"

**Comment by wa4557** [comment]
If there's already an icon cache you have to forcefully create a new one: 
`gtk-update-icon-cache -f /path/to/Numix`

**Comment by pgera** [comment]
Thanks. Works.
