### ISSUE TITLE
Missing network-manager icon

### ISSUE THREAD

**Issue by eka-putra** [numixproject/numix-icon-theme#743]
Hello, 

I use numix circle light icon in fluxbox. Network manager icon disappears when the internet is connected.

![1](https://cloud.githubusercontent.com/assets/8128165/9977710/0f2d1870-5f3b-11e5-9300-0c7c93a605d5.png)

![2](https://cloud.githubusercontent.com/assets/8128165/9977713/181f4552-5f3b-11e5-8130-e7b26f7f6249.png)

**Comment by bil-elmoussaoui** [comment]
Try using your default theme and look for this icon in /usr/share/icons/IconThemeName

**Comment by eka-putra** [comment]
@bil-elmoussaoui default theme? which is it? I am using Xubuntu.

When I use gnome icon.
![screenshot - 210915 - 14 42 30](https://cloud.githubusercontent.com/assets/8128165/9987170/0ed028d8-606f-11e5-85e6-e8d06a85878f.png)

**Comment by eka-putra** [comment]
I just find it , it's a bug of nm-applet https://bugs.launchpad.net/ubuntu/+source/network-manager-applet/+bug/946180

**Comment by Foggalong** [comment]
:+1:

**Comment by akhyarrh** [comment]
This is maybe Numix issue. I got same problem. When connected, nm icons from default Lubuntu icon theme:

- nm-mb-roam
- nm-tech-3g
- nm-tech-cdma-1x
- nm-tech-edge
- nm-tech-evdo
- nm-tech-gprs
- nm-tech-hspa
- nm-tech-lte
- nm-tech-umts
- nm-wwan-tower

However, on Numix, all icons related to mobile broadband are transparent.
![2015-09-27_22 19 28](https://cloud.githubusercontent.com/assets/10618799/10123197/1d60d0ea-6566-11e5-8dd1-d21fe0d89094.png)

`nm-mb-roam` and all `nm-tech-*` are linked to `nm-wwan-tower`.

**Comment by wa4557** [comment]
The problem is that all of these svgs are just completely empty, which means that they show up but are transparent. Can you open an issue about that (in numix-icon-theme)?

**Comment by Foggalong** [comment]
:+1:

**Comment by wa4557** [comment]
@Foggalong You shouldn't reopen this bug, because there is no bug concerning fluxbox, but the mobile-broadband icons are missing (not the ones used by fluxbox). A new issue is necessary here...

**Comment by akhyarrh** [comment]
Renaming would be okay

**Comment by wa4557** [comment]
@akhyarrh One question before I start trying to come up with sth: When using a different theme is there also some kind of signal strength indication for the mobile broadband connection, or is it just indicating that you are connected and not specified how well?

**Comment by akhyarrh** [comment]
No. Just indicating you're connected or not when using mobile broadband. Icons when connecting are okay. I've checked it. The only issue is missing nm icons when connected using mobile broadband

**Comment by wa4557** [comment]
Something like this?
![bildschirmfoto vom 2015-09-27 17 46 14](https://cloud.githubusercontent.com/assets/6475757/10123660/ae4fff4e-653f-11e5-870e-9ba3f5f03b11.png)
