### ISSUE TITLE
Battery Status Icon Xfce-Power-Manager 1.5.x

### ISSUE THREAD

**Issue by ragazenta** [numixproject/numix-icon-theme#755]
After installing new xfce-power-manager 1.5.2, battery icon in panel was changed.

![screenshot_2015-09-27_01-45-00](https://cloud.githubusercontent.com/assets/3535194/10119240/18b58196-64ba-11e5-82f3-877dc0a218d3.png)

I found that non -symbolic filename suffix is needed. Those files were deleted #236.

```
battery-caution-charging.svg
battery-caution.svg
battery-empty-charging.svg
battery-empty.svg
battery-full-charged.svg
battery-full-charging.svg
battery-full.svg
battery-good-charging.svg
battery-good.svg
battery-low-charging.svg
battery-low.svg 
```

I tried restoring files above in 24x24 directory, it works for me now.

**Comment by wa4557** [comment]
@dirtydancing Will this break a lot?

**Comment by Foggalong** [comment]
Is v1.5.2 the version in 15.10?

**Comment by dirtydancing** [comment]
Woah, this sounds like breakage to me! I am not sure what though, will have to think about this.

For starters, I would like to clarify that not all of these icons have not been deleted, only `battery-caution` and `battery-low`. The others were never part of the battery status icons. These have simply not been used in the panel by any distro/DE/shell so far. For a current overview of the battery status icons, cf. https://github.com/numixproject/numix-icon-theme/issues/107#issuecomment-98399311.

@ragazenta What do you mean with "restoring files"?

**Comment by ragazenta** [comment]
@Foggalong I dunno, I'm not using Ubuntu.

@dirtydancing Those files above I mentioned were missing in 24x24 directory. 
I followed battery-*-symbolic.svg link and created same link without -symbolic suffix.

xfce-power-manager (xpm) 1.5.x maybe not been used in panel by most distro so far, I am using Gentoo, dzen + trayer-srg as panel. I updated xpm few days ago. Before xpm 1.5.x, everything was fine. Just curious why battery icon was changed.

**Comment by dirtydancing** [comment]
Here is the thing: so far, for the panel there were either **percentage-named** battery icons (**non-symbolic**-named; basically for non-GNOME shell) or **status-named** battery icons (**symbolic**-named; basically for GNOME shell).

Now with this new xfce-power-manager development, for the panel we get **status-named** battery icons that are **non-symbolic**-named. These icons e.g. in Ubuntu are used not for the panel, but for other purposes (should be mentioned somewhere over at https://github.com/numixproject/numix-icon-theme/issues/107).

So adding them to the fixed size status directories (16,22,24 or only specifically to 24) could result in breakage (not necessarily in the panel, but elsewhere) in other distros such as Ubuntu. This would depend on whether e.g. Ubuntu uses these icons specifically in sizes 32 or 48, and not in e.g. 24.

Getting the panel battery status icons to work in all distros is about as complex as it gets, just cf. the infamous https://github.com/numixproject/numix-icon-theme/issues/107. So before making any changes here, we need to be sure what exactly is requiring a modification. So just like @Foggalong already asked, first of all we need to know whether this xfce-power-manager change is employed in a new stable distro release. Is this about Xubuntu 15.10? This would then be a beta version and not a stable one, right?

**Comment by Foggalong** [comment]
@ragazenta ah, what OS are you on? It'll help us for testing

**Comment by dirtydancing** [comment]
Not sure what is going on, I just posted a longer post parallel to you, and now it is gone?

**Comment by Foggalong** [comment]
I can see it!

**Comment by ragazenta** [comment]
Well, in Gentoo, xpm 1.5.2 marked as stable last month. But maybe in other distro still unstable.

**Comment by dirtydancing** [comment]
Anyways, I was writing that so far, for the panel battery status icons there have been either **percentage-named non-symbolic-named** icons or **status-named symbolic-named** icons (esp. for GNOME shell).

Now, apparently we have a new kid on the panel block: **status-named non-symbolic-named** icons. These kind of icons so far are used e.g. in Ubuntu for non-panel purposes. Currently they exist in sizes 32 and 48 in devices, so adding them to (16,22) 24 in status might cause non-panel breakage. In addition, adding them to (16,22) 24 in status might also cause panel breakage elsewhere.

**Comment by dirtydancing** [comment]
Currently, e.g. Arch has xcfe4-power-manager 1.4.4, cf. https://www.archlinux.org/packages/extra/x86_64/xfce4-power-manager/. The file list includes `xfpm-primary-*` icons that are percentage-named non-symbolic-named. This would confirm that things must have changed with version 1.5. AUR contains (-devel) version 1.5.2, cf. https://aur.archlinux.org/packages/xfce4-power-manager-devel/.

**Comment by dirtydancing** [comment]
Ubuntu 15.10 currently has version 1.4.4, cf. http://packages.ubuntu.com/wily/xfce4-power-manager.

**Comment by wa4557** [comment]
At least in Ubuntu there seems to be no problem when adding those icons. The devices icons are still used where they should be (power managment preferences)

**Comment by Foggalong** [comment]
(@dirtydancing I edited that comment to try and keep this clean as possible. I'm well aware that battery issues tend to get very long very fast so gonna try and keep this one as readable as possible)

**Comment by dirtydancing** [comment]
Is this the relevant icon overview? http://git.xfce.org/xfce/xfce4-power-manager/tree/data/icons/scalable

That one includes symbolic-named as well as non-symbolic-named icons, both in `scalable`. I have checked, and the symbolic-named icons are the GNOME/Adwaita status icons, and those should be displayed in the panel.

At the moment, I am not quite sure what to make of this. This could mean that xpm 1.5 is following the GNOME/Adwaita icons, but for some reason is looking at fixed size 24 specifically (and then also at 32 or 48) before looking into scalable (?).

@ragazenta Could you check if the panel battery status icons are fine when you delete the icons (same icon names that you listed) that are currently located in sizes 32 and 48 in devices?

**Comment by dirtydancing** [comment]
@ragazenta Could you also check which battery status icons are displayed in the panel with the default (Adwaita?) icon theme.

**Comment by dirtydancing** [comment]
@wa4557 Good to hear that adding those icons does not cause any damage in Ubuntu. Where did you add them (fixed size or scalable)?

Before adding these icons and waiting for any bug reports (given the complexity of getting these icons to work on all distros, that might make sense), we should make sure that this is not a bug somewhere else.

**Comment by ragazenta** [comment]
@dirtydancing Yes. I have xpm tarball source, same as that git.xfce link.

I deleted icons you mentioned

![screenshot_2015-09-27_03-58-53](https://cloud.githubusercontent.com/assets/3535194/10119811/3347e7b2-64cc-11e5-8e99-e1f9815e197c.png)


Battery icon is changed
![screenshot_2015-09-27_03-42-49](https://cloud.githubusercontent.com/assets/3535194/10119833/c384a45a-64cc-11e5-91bd-0e76b6538fdb.png)


If using Adwaita
![screenshot_2015-09-27_03-48-02](https://cloud.githubusercontent.com/assets/3535194/10119841/001bd0a0-64cd-11e5-9fd4-11190d8d5039.png)

**Comment by dirtydancing** [comment]
This is strange. To me, this looks like something is wrong with the icons in xfce4-power-manager 1.5. Apparently, there are symbolic-named icons in scalable, which should be used in the panel, but they are not. This is demonstrated by your second screenshot using Adwaita.

And the first screenshot demonstrates that even if Numix does not contain the non-symbolic named icons, not the proper symbolic-named icons in Numix are used, but rather the non-symbolic named icons in GNOME/Adwaita (inherited or fallback icon theme).

At the moment, I am not sure what to make of this. Any ideas?

**Comment by dirtydancing** [comment]
@ragazenta Judging from your first screenshot above and from the very first screenshot at the top, apparently your panel is not using icons from the `scalable` directory, but rather from the fixed size directories, and from the fixed size directories exclusively. The network icon is not from `scalable`, either. So this might be an issue with the panel, or more precisely an issue with the panel in combination with xpm 1.5. Just speculating here.

**Comment by wa4557** [comment]
I'd argue that we can add those icons. They are not used by any other distro in the panel (if that would be the case they would have been added sooner), and the reason why we added those icons to `devices` were the ubuntu power preferences, and adding those icons to 16/22/24 does not break anything there

**Comment by dirtydancing** [comment]
@wa4557 You are probably right, and adding those (symlinks) would probably not break any other distro in the panel. Still, something seems to be off with xpm 1.5: it does provide monochrome symbolic-named status icons (for the panel?), but for some reason xpm 1.5 (or the panel in this specific case?) insists on using non-monochrome non-symbolic-named icons in the panel, which xpm 1.5 provides in parallel.

**Comment by dirtydancing** [comment]
I came across this bit of info over at http://news.softpedia.com/news/Xfce-Power-Manager-1-5-0-Finally-Ported-to-GTK3-plus-482317.shtml "the panel plugin now uses UPower's icon names, **symbolic icons are now used for the panel plugin**, colored icons have been implemented for the systray icon".

@ragazenta Are you using the "panel plugin" (which should be using symbolic icons) for your panel?

**Comment by ragazenta** [comment]
@dirtydancing
I'm not using panel plugin. I'm using trayer-syg, which is systray.

**Comment by dirtydancing** [comment]
Well, in this case, I would argue that there is no issue here, as with xpm 1.5 "colored icons have been implemented for the systray icon". So actually the correct icon is showing with Numix.

I would argue that we should not make any changes to the battery status icons at this point. In any event, it is good to be aware of this situation in case of further future issue reports.

**Comment by Foggalong** [comment]
Wait, I'm confused. The normal xpm uses the monochrome status icons, but you're using a systray which changes the icons to the device icons?

**Comment by dirtydancing** [comment]
As far as I can tell (not using xpm 1.5), systray in xpm 1.5 is implemented with "colored" icons, which in this context means non-monochrome non-symbolic-named status-named battery icons. In Numix base, those are located in `devices`, and they are looked up (as intended by xpm 1.5) due to their icon name.

**Comment by ragazenta** [comment]
Well, I agree about xpm implementation is the issue here. Before 1.5, battery icon systray was disabled. I couldn't show battery icon without panel plugin, so I downgraded it. Now in version 1.5, it has a feature to show/hide systray, but like @dirtydancing said, it's using colored (non-symbolic-named) icons.

I'll keep using the 'restored' version above. Thanks for the great icons.

**Comment by Foggalong** [comment]
@ragazenta Do you know if this has been fixed in the latest git version?

**Comment by ragazenta** [comment]
Yes, thanks.

![screenshot_2017-04-06_11-05-12](https://cloud.githubusercontent.com/assets/3535194/24737475/3f5a7c6e-1ab9-11e7-938f-2173e0be8815.png)
