### ISSUE TITLE
e-mail attachment icon missing

### ISSUE THREAD

**Issue by sljunkie** [numixproject/numix-icon-theme#765]
There's one missing icon that indicates e-mail attachments. In Evolution for instance:
![screenshot from 2015-10-02 01-44-05](https://cloud.githubusercontent.com/assets/7532854/10239762/cd90e320-68a8-11e5-97ab-9665dba616cd.png)

That's the middle icon.

The same icon has several names/places:

$ pwd
/usr/share/icons
$ find Adwaita gnome -name *attach*
Adwaita/22x22/status/mail-attachment.png
Adwaita/32x32/status/mail-attachment.png
Adwaita/24x24/status/mail-attachment.png
Adwaita/scalable/status/mail-attachment-symbolic.svg
Adwaita/16x16/status/mail-attachment.png
Adwaita/48x48/status/mail-attachment.png
gnome/22x22/status/stock_attach.png
gnome/22x22/status/mail-attachment.png
gnome/32x32/status/stock_attach.png
gnome/32x32/status/mail-attachment.png
gnome/24x24/status/stock_attach.png
gnome/24x24/status/mail-attachment.png
gnome/scalable/status/mail-attachment-symbolic.svg
gnome/16x16/status/stock_attach.png
gnome/16x16/status/mail-attachment.png
gnome/48x48/status/stock_attach.png
gnome/48x48/status/mail-attachment.png

**Comment by palob** [comment]
Already reported in #577.

**Comment by Foggalong** [comment]
I'm fine if outside people make requests for icons already in the big lists, it adds a priority for it :)

**Comment by palob** [comment]
@sljunkie Is this the last non-Numix icon for Evolution?

**Comment by sljunkie** [comment]
@palob yes, *if* we don't count the ones the package evolution installs on /usr/share/evolution/icons/hicolor:

$ pwd
/usr/share/evolution/icons/hicolor
$ tree
.
├── 16x16
│   ├── actions
│   │   ├── folder-copy.png
│   │   ├── folder-move.png
│   │   ├── go-today.png
│   │   ├── mail-copy.png
│   │   ├── mail-move.png
│   │   ├── stock_bell.png
│   │   ├── stock_contact-list.png
│   │   ├── stock_insert-note.png
│   │   ├── stock_insert-rule.png
│   │   ├── stock_insert-table.png
│   │   ├── stock_mail-filters-apply.png
│   │   ├── stock_mail-flag-for-followup-done.png
│   │   ├── stock_mail-flag-for-followup.png
│   │   ├── stock_mail-open-multiple.png
│   │   ├── stock_mail-unread-multiple.png
│   │   ├── stock_new-24h-appointment.png
│   │   ├── stock_new-meeting.png
│   │   ├── stock_notes.png
│   │   ├── stock_people.png
│   │   ├── stock_select-column.png
│   │   ├── stock_select-row.png
│   │   ├── stock_shared-by-me.png
│   │   ├── stock_shared-to-me.png
│   │   ├── stock_show-all.png
│   │   ├── stock_task-assigned.png
│   │   ├── stock_task-assigned-to.png
│   │   ├── stock_task.png
│   │   ├── stock_task-recurring.png
│   │   ├── stock_text-monospaced.png
│   │   ├── stock_timezone.png
│   │   ├── stock_todo.png
│   │   ├── stock_video-conferencing.png
│   │   ├── stock_view-details.png
│   │   ├── view-calendar-day.png
│   │   ├── view-calendar-list.png
│   │   ├── view-calendar-month.png
│   │   ├── view-calendar-week.png
│   │   └── view-calendar-workweek.png
│   ├── apps
│   │   ├── contact-editor.png
│   │   ├── im-aim.png
│   │   ├── im-icq.png
│   │   ├── im-jabber.png
│   │   ├── im-msn.png
│   │   ├── im-nov.png
│   │   └── im-yahoo.png
│   ├── places
│   │   ├── mail-inbox.png
│   │   ├── mail-outbox.png
│   │   └── mail-sent.png
│   └── status
│       ├── stock_check-filled.png
│       ├── stock_score-higher.png
│       ├── stock_score-highest.png
│       ├── stock_score-high.png
│       ├── stock_score-lower.png
│       ├── stock_score-lowest.png
│       ├── stock_score-low.png
│       ├── stock_score-normal.png
│       ├── stock_signature-bad.png
│       ├── stock_signature-ok.png
│       ├── stock_signature.png
│       └── wrapped.png
├── 22x22
│   ├── actions
│   │   ├── go-today.png
│   │   ├── view-calendar-day.png
│   │   ├── view-calendar-list.png
│   │   ├── view-calendar-month.png
│   │   ├── view-calendar-week.png
│   │   └── view-calendar-workweek.png
│   ├── apps
│   │   ├── contact-editor.png
│   │   ├── im-aim.png
│   │   ├── im-icq.png
│   │   ├── im-jabber.png
│   │   ├── im-msn.png
│   │   ├── im-nov.png
│   │   └── im-yahoo.png
│   └── places
│       ├── mail-inbox.png
│       ├── mail-outbox.png
│       └── mail-sent.png
├── 24x24
│   ├── actions
│   │   ├── go-today.png
│   │   ├── query-free-busy.png
│   │   ├── stock_contact-list.png
│   │   ├── stock_insert-note.png
│   │   ├── stock_insert-rule.png
│   │   ├── stock_insert-table.png
│   │   ├── stock_mail-filters-apply.png
│   │   ├── stock_mail-open-multiple.png
│   │   ├── stock_mail-unread-multiple.png
│   │   ├── stock_new-24h-appointment.png
│   │   ├── stock_new-meeting.png
│   │   ├── stock_notes.png
│   │   ├── stock_people.png
│   │   ├── stock_select-column.png
│   │   ├── stock_select-row.png
│   │   ├── stock_shared-by-me.png
│   │   ├── stock_shared-to-me.png
│   │   ├── stock_show-all.png
│   │   ├── stock_task-assigned.png
│   │   ├── stock_task-assigned-to.png
│   │   ├── stock_task.png
│   │   ├── stock_task-recurring.png
│   │   ├── stock_text-monospaced.png
│   │   ├── stock_timezone.png
│   │   ├── stock_todo.png
│   │   ├── stock_video-conferencing.png
│   │   ├── view-calendar-day.png
│   │   ├── view-calendar-list.png
│   │   ├── view-calendar-month.png
│   │   ├── view-calendar-week.png
│   │   └── view-calendar-workweek.png
│   ├── apps
│   │   ├── contact-editor.png
│   │   ├── im-aim.png
│   │   ├── im-icq.png
│   │   ├── im-jabber.png
│   │   ├── im-msn.png
│   │   ├── im-nov.png
│   │   └── im-yahoo.png
│   ├── places
│   │   ├── mail-inbox.png
│   │   ├── mail-outbox.png
│   │   └── mail-sent.png
│   └── status
│       ├── stock_signature-bad.png
│       ├── stock_signature-ok.png
│       └── stock_signature.png
├── 32x32
│   ├── actions
│   │   ├── view-calendar-day.png
│   │   ├── view-calendar-list.png
│   │   ├── view-calendar-month.png
│   │   ├── view-calendar-week.png
│   │   └── view-calendar-workweek.png
│   ├── apps
│   │   └── contact-editor.png
│   └── status
│       ├── offline.png
│       └── online.png
├── 48x48
│   ├── actions
│   │   ├── stock_alarm.png
│   │   ├── stock_mail-flag-for-followup-done.png
│   │   ├── stock_mail-flag-for-followup.png
│   │   ├── stock_new-24h-appointment.png
│   │   ├── stock_new-meeting.png
│   │   ├── stock_notes.png
│   │   ├── stock_people.png
│   │   ├── stock_timezone.png
│   │   └── stock_todo.png
│   ├── apps
│   │   └── contact-editor.png
│   ├── categories
│   │   ├── preferences-autocompletion.png
│   │   ├── preferences-calendar-and-tasks.png
│   │   ├── preferences-certificates.png
│   │   ├── preferences-composer.png
│   │   ├── preferences-mail-accounts.png
│   │   ├── preferences-mail.png
│   │   └── preferences-system-network-proxy.png
│   └── status
│       ├── stock_signature-bad.png
│       ├── stock_signature-ok.png
│       └── stock_signature.png
└── scalable
    ├── actions
    │   ├── view-calendar-day.svg
    │   ├── view-calendar-list.svg
    │   ├── view-calendar-month.svg
    │   ├── view-calendar-week.svg
    │   └── view-calendar-workweek.svg
    └── apps
        ├── im-aim.svg
        ├── im-icq.svg
        ├── im-jabber.svg
        ├── im-msn.svg
        ├── im-nov.svg
        └── im-yahoo.svg

**Comment by wa4557** [comment]
Even if we count those icons, there no more icons that are not present in Numix :P

**Comment by Foggalong** [comment]
:dancer:
