### ISSUE TITLE
Clementine indicator icons

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-icon-theme#766]
Some of Clementine indicator icons are missing [Clementine Idle icon not visible](https://github.com/bil-elmoussaoui/Hardcode-Tray/issues/105#issuecomment-145329040)

The icons are 
 - [ ] clementine-100-playing
 - [ ] clementine-90-playing
 - [ ] clementine-80-playing
 - [ ] clementine-70-playing
 - [ ] clementine-60-playing
 - [ ] clementine-50-playing
 - [ ] clementine-40-playing
 - [ ] clementine-30-playing
 - [ ] clementine-25-playing
 - [ ] clementine-15-playing
 - [ ] clementine-10-playing
 - [ ] clementine-05-playing

**Comment by sagarpanchal** [comment]
Hey, clementine indicator icon doesn't animate that way.

**Comment by bil-elmoussaoui** [comment]
Can you provide the right animation icons? :)

**Comment by sagarpanchal** [comment]
You'll only need two files inside Numix/24/panel
![clementine-panel](https://cloud.githubusercontent.com/assets/6555461/16347505/b4c7b424-3a6a-11e6-95cd-d01a7fcfc638.png) Numix/24/panel/clementine-panel.png
![clementine-panel-grey](https://cloud.githubusercontent.com/assets/6555461/16347506/b4c86a86-3a6a-11e6-8f28-9670f38db045.png) Numix/24/panel/clementine-panel-grey.png

For Light Theme,
You'll only need two files inside Numix-Light/24/panel
![clementine-panel](https://cloud.githubusercontent.com/assets/6555461/16347562/fdc420ea-3a6a-11e6-8879-3b20a3704df8.png) Numix-Light/24/panel/clementine-panel.png
![clementine-panel-grey](https://cloud.githubusercontent.com/assets/6555461/16347561/fdc1147c-3a6a-11e6-8973-58936f9df829.png) Numix-Light/24/panel/clementine-panel-grey.png

**Comment by sagarpanchal** [comment]
Save them and it will work.

**Comment by bil-elmoussaoui** [comment]
@sagarpanchal Are you sure? Someone reported something else here https://github.com/bil-elmoussaoui/Hardcode-Tray/issues/105#issuecomment-145329040

**Comment by sagarpanchal** [comment]
I just gave you a [solution](https://github.com/numixproject/numix-icon-theme/issues/766#issuecomment-228430805)

**Comment by bil-elmoussaoui** [comment]
I saw that, but i'm not sure that you only need those two icons. Clementine maybe have a feature to show those icons as asked for here. And i don't use Clementine to test that;)

**Comment by sagarpanchal** [comment]
It just needs two icons for animation. One for background and another for foreground.

**Comment by sagarpanchal** [comment]
I looked at another icon themes for solution and I observed that most of them includes only two icons for clementine indicator. So, I tested it on Ubuntu 16.04 and it works.

**Comment by sagarpanchal** [comment]
@bil-elmoussaoui A good example for it is Ubuntu-mono-dark and Ubuntu-mono-light. You can look at the files and test them.

**Comment by sagarpanchal** [comment]
@bil-elmoussaoui See this file. https://github.com/clementine-player/Clementine/blob/3fc6208248a211c10b4e171b450c8b3d6b600259/src/ui/qtsystemtrayicon.cpp
