### ISSUE TITLE
Size 96x96 for base theme

### ISSUE THREAD

**Issue by wa4557** [numixproject/numix-icon-theme#767]
So I tried fiddling around with the `index.theme` file so that the theme uses scaled up versions of the `48x48` for `96px` sized icons, but unfortunately there seems to be no way to do this reliable :( 
However: I've found a neat little program that can resize svgs exactly like we want it https://github.com/vieron/svg-resizer, which means that we could use this to easily create `96px` icons from the `48px` ones. (This program is also great when creating a new icon btw, because it simplifies the process of creating bigger sizes as well)

Is this something we want to happen?

**Comment by Foggalong** [comment]
We used to use [this script](https://github.com/numixproject/numix-tools/blob/master/numix-tools/svgscale) for that kind of things but stopped using it when it started causing problems. Particularly with Qt things iirc.

**Comment by wa4557** [comment]
I know that one, but the one I have works pretty smoothly (compared to your script it really keeps the pixel perfect alignment, and resizes correctly). 

I have them already ready (because it's really easy :). Should I push them then?

**Comment by Foggalong** [comment]
That's awesome then! Push away :)

**Comment by palob** [comment]
@wa4557 Did you look into how other themes do this, especially ``elementary`` or [https://github.com/mank319/elementaryPlus/blob/master/elementaryPlus/index.theme](elementaryPlus)?

**Comment by wa4557** [comment]
Ah that's interesting didn't see that, that basically the HIDPI support @Foggalong was working on in the HIDPI branch, isn't it?

**Comment by Foggalong** [comment]
Yeah, I'd not thought that that might be usable. Is that what `Scale=2` in the index.theme file does then, just scale the icons by 2?

**Comment by wa4557** [comment]
Maybe have to try it out. Still I don't understand how the theme knows it should use the `48px` icon for `96` instead of something else...

**Comment by palob** [comment]
AFAIK [just this](http://standards.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#icon_lookup) is the official documentation.

**Comment by Foggalong** [comment]
Yeah, the documentation makes me sad.

**Comment by wa4557** [comment]
Ok, cool I'll try this out, if this works this would be way cooler. @Foggalong @palob are there any folders (except `places`) that needs distinct sizes for sizes larger than `64px` (`mimetypes` maybe)

**Comment by palob** [comment]
I don't know whether it's needed but I definitely did a few distinct designs for mimetypes and actions.

**Comment by wa4557** [comment]
I'd argue that the distinct `actions` could be removed, no idea about `mimetypes` though, only did very few of them...

**Comment by wa4557** [comment]
I figured it out, it's actually pretty straightforward, thanks for the suggestion @palob, and will additionaly enable HIDPI support :) I'll create a PR for that as well and @Foggalong can then decide what suits him better :)
