### ISSUE TITLE
Sflphone indicators

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-icon-theme#772]
Slfphone has 3 tray icons, those icons are hardcoded
- [ ] sflphone-indicator
- [ ] sflphone-notification
- [ ] sflphone-offline

default icons : 

![screenshot from 2015-10-06 00-20-23](https://cloud.githubusercontent.com/assets/7660997/10295301/1908648a-6bc0-11e5-9779-eb5144f17c67.png)

**Comment by wa4557** [comment]
Symlinks to viber-indicator icons?

**Comment by bil-elmoussaoui** [comment]
Good idea! You will just need to add a new one as there's only two icons for viber

**Comment by wa4557** [comment]
no problem :+1:
