### ISSUE TITLE
Gnome-shell program start throbber messed up

### ISSUE THREAD

**Issue by piratenpanda** [numixproject/numix-icon-theme#774]
With the latest shell version 3.18 on Antergos the start throbber is messed up when starting programs. Seems like the throbber is moving from the top to the bottom quite quickly.
![throbber](https://cloud.githubusercontent.com/assets/920721/10413499/70c92fc6-6fab-11e5-852b-f2142c5b5ee7.png)

**Comment by Foggalong** [comment]
I'm not sure what you mean by the throbber? I'm not a GNOME user. Does this problem happen with other icon themes too>

**Comment by piratenpanda** [comment]
Sorry if i should have posted this somewhere else. Seems GNOME changed something in 3.18 as the standard theme shows a nice spinning wheel whereas numix behaves like a spinning wheel combined with a movie. Seems the spinner moves through the active area from top to bottom and all ober again until the animation is done

**Comment by Foggalong** [comment]
I think this is probably in the right place. So everything worked fine before 3.18? What distro are you on?

**Comment by piratenpanda** [comment]
I'm using antergos and it was working fine in 3.16

**Comment by palob** [comment]
@dirtydancing Did you notice something like this?

**Comment by dirtydancing** [comment]
I am not sure either what the "throbber" is, but I have not noticed any difficulties with Arch/GNOME and the recent Arch update to GNOME/GNOME Shell 3.18. All working very smoothly over here.

Is this possibly related to the GTK theme or the GNOME Shell theme, not to the icon theme (I am using the default Adwaita GTK/Shell theme)? Or is there any special extension involved here?

**Comment by piratenpanda** [comment]
Sorry, spinner may be the better word for it. When you start an app in 3.18 it shows a nice spinning icon next to its name in the top bar. Yes it's related to the Numix-Frost shell theme. Is it this? https://github.com/shimmerproject/Numix

**Comment by dirtydancing** [comment]
Ah, I realise now what the "throbber" is :), and yes, it is working fine with Adwaita GNOME Shell theme and Numix icon theme, but not e.g. with Numix Frost GNOME Shell theme. It is working fine with Numix GTK theme, though, so apparently this is a GNOME Shell theme issue.

**Comment by dirtydancing** [comment]
@piratenpanda Cross-posted at the same time here :). You referred to the Numix GTK theme GitHub site. I am not sure if that includes a GNOME Shell theme. I believe Numix Frost Shell theme is specific to Antergos. Other GNOME Shell themes are having issues with this at well (e.g. Ozon, Paper, Arc), but default Adwaita GNOME Shell theme is working fine.

**Comment by Foggalong** [comment]
CC: @satya164

**Comment by dirtydancing** [comment]
Just checked again after updating, and the spinner is now working properly with Arc GNOME shell theme. Also, e.g. Evopop GNOME shell theme is working just fine. Maybe this is of help.

**Comment by Foggalong** [comment]
Closed this as it appears to be a shell theme issue
