### ISSUE TITLE
Numix-Frost theme has wrong padding for nautilus icons

### ISSUE THREAD

**Issue by piratenpanda** [numixproject/numix-icon-theme#775]
In Nautilus 3.18 the padding icon padding for the left sidebar is wrong or non-existent. This is running latest Antergos with Numix-Frost 1.9.4-1
![nautilus](https://cloud.githubusercontent.com/assets/920721/10416969/1ea82d06-702c-11e5-9f07-41f2809ffaab.png)

**Comment by palob** [comment]
I think that's an issue for the [GTK theme](https://github.com/shimmerproject/Numix).

**Comment by piratenpanda** [comment]
Ok sry about that. Can somebody move it?

**Comment by piratenpanda** [comment]
Already there:
https://github.com/shimmerproject/Numix/issues/256
