### ISSUE TITLE
Top bar icons

### ISSUE THREAD

**Issue by leoheck** [numixproject/numix-icon-theme#779]
Hi, the last update changed the bluetooth icon. This is right? Is it possible to make the white icon with no bacground icon back?

![topbar](https://cloud.githubusercontent.com/assets/1277920/10486368/04c1acc4-7265-11e5-8697-c28dcf188a6c.png)

**Comment by Foggalong** [comment]
Duplicate of numix-icon-theme-circle#2601

**Comment by keunes** [comment]
Also see discussion at https://github.com/numixproject/numix-icon-theme-circle/issues/2274
