### ISSUE TITLE
Error when running Numix Folders

### ISSUE THREAD

**Issue by Foggalong** [numixproject/numix-icon-theme#780]
The error appears when running Numix Folders but I'm guessing it's caused by here

``````
(gksudo:16903): Gtk-WARNING **: Theme directory 64/apps of theme Numix has no size field
``````

**Comment by wa4557** [comment]
You are most certainly not running the latest version, because there is a size field for `64/apps`

**Comment by Foggalong** [comment]
I'll dluble check, but Im fairly sure the error came up when I was testing with the latest version :(

**Comment by dirtydancing** [comment]
I cannot confirm this issue. On my end, everything with Numix-Folders is running completely smoothly, with the latest versions of Numix-Folders, Numix-Circle and Numix base.

**Comment by Foggalong** [comment]
Yeah, it seems to have gone on my end now too :P
