### ISSUE TITLE
New icon for network-offline

### ISSUE THREAD

**Issue by wa4557** [numixproject/numix-icon-theme#785]
I always thought that the `network-offline` icon shouldn't be a "wifi" icon because a disconnected internet connection also happens for computers that are connected via ethernet cable. So I thought about a new icon for `network-offline`. I think this is actually a more appropriate icon symbolizing that there's no up- or download. It's basically the `network-idle` icon with both arrows 40% opacity.
![bildschirmfoto vom 2015-10-16 21 32 16](https://cloud.githubusercontent.com/assets/6475757/10551503/8ade106a-744d-11e5-8130-20ef4ea8a3d3.png)
All the other "offline" icons in Numix are designed this way, I see no reason why the network icon should be different...

**Comment by wa4557** [comment]
This would mean going from this:
![bildschirmfoto vom 2015-10-17 09 38 28](https://cloud.githubusercontent.com/assets/6475757/10557582/2633ca68-74b3-11e5-9f92-c7f2fab3f1c9.png)

to this (which is so much better imo): 
![bildschirmfoto vom 2015-10-17 09 38 45](https://cloud.githubusercontent.com/assets/6475757/10557584/2f383cfc-74b3-11e5-8a2d-065a6e6cc80a.png)

**Comment by dirtydancing** [comment]
Actually, I recall discussing this aspect back in the day when I was running Ubuntu/Unity. In the end, I thought is was alright to have the current empty symbol for this, because the two arrows are used for ethernet connections and thus can be just as "misleading". iirc, the current empty symbol shows up no matter which internet connection was disconnected, be it wireless, ethernet or wwan (?).

Alternatively, maybe the current empty "wifi" icon could be used with 40% opacity?

**Comment by wa4557** [comment]
Yeah, but I'd argue that the n up- or downstream symbol is the most generic, and as already said all the other "offline" icons are icons with 40% opacity

**Comment by dirtydancing** [comment]
Agreed, what you say about the most generic icon makes sense to me :+1:

**Comment by Foggalong** [comment]
This icon has it's own unique problems - some network managers have an icon with solid-up/trans-down & trans-up/solid-down to denote when the connection is old sending/receiving. Thus this icon could be interpreted as when it's properly connected but just not sending/receiving at this particular moment

**Comment by dirtydancing** [comment]
Maybe a design that includes some kind of a cross-out? With the current wifi icon design, at least the current offline icon imo is sufficiently distinct from the wifi connected icons.

**Comment by wa4557** [comment]
What about this one?
![bildschirmfoto vom 2015-10-19 23 02 24](https://cloud.githubusercontent.com/assets/6475757/10591308/d60eebb2-76b5-11e5-9d68-b56b0149f68a.png)

**Comment by Foggalong** [comment]
Gets points because the `×` position follows the Numix convention, but still don't feel it looks quite right :(

**Comment by wa4557** [comment]
Still better than the current one...

**Comment by dirtydancing** [comment]
One difficulty with the latest proposed icon is that it might be confused as kind of blocking the download part, but still having the upload part. We should also keep in mind that for the fixed size status icons, there is also e.g. `network-error.svg`, which currently is the same icon in red.

![network-error](https://cloud.githubusercontent.com/assets/7164227/10592996/51b98e0c-76c0-11e5-883a-b15b9f6a3165.png)

**Comment by Foggalong** [comment]
ooo, I was forgetting that one.

**Comment by wa4557** [comment]
But that's easy. Just the offline Icon in numix warning red

**Comment by wa4557** [comment]
Ok this icon is really bugging me so let me try to convince you why the above suggestions are much better (my personal favourite is the one with the cross): 

1. The current icon is just a ripoff of the same (and arguably one of the worst) icons from ubuntu-mono-dark, a original numix icon is needed
2. The icon does not fit to the other status icons: All the "offline" status icons are 40% opacity, no icon is displaying the off status by using this kind of contour icon.
3. Why for the `network-offline` or `network-error` icon a wifi icon is used is totally not understandable. There are people out there (like me) not using a wireless connection all the time. The more generic upstream downstream icon would be better
4. all the other `network-*` icons in numix do have the upstream downstream arrow icons (why should this be different for `network-offline`?)
5. The icon is not good looking, just look at the first screenshot. It is (apart from the keboard icon maybe) the worst looking icon in the tray
6. If you think that the proposed icons are too close to the ethernet icons, I'd suggest to change the ethernet icons instead (there are very pretty ethernet icons in scalable) and use the up-down arrow only for the `network-*` icons

**Comment by dirtydancing** [comment]
As I have written above, I am totally fine with changing to the more generic icon. Personally, I prefer the first proposal with the two arrows at 40% opacity. As I have also written, the design proposal with the `x` might be more confusing than necessary, as the `x` might be understood to relate to download only.

Using the sweet ethernet icons from `scalable` is not all that easy, because in the fixed size directories, there are additional icons for transmit only and for receive only. These do not exist in `scalable`.

@Foggalong your call :)

**Comment by wa4557** [comment]
@dirtydancing I'm talking about `nm-device-wired` which is for example used in ubuntu

**Comment by dirtydancing** [comment]
I see. Yeah, it should be fine to make use of the design of `network-wired-symbolic.svg` from `scalable/status` for `nm-device-wired.svg` (and `nm-device-wired-autoip.svg`) in the fixed size `status` directories. Then there would also be `nm-device-wired-secure.svg` in the fixed size `status` directories, which would have to be adapted to that design as well I guess.

**Comment by wa4557** [comment]
Ok new proposal. All the roblems that were mentioned above should now be gone...
![unbenannt](https://cloud.githubusercontent.com/assets/6475757/10862804/dbb0d6f6-7fb7-11e5-94be-259d8c5e42a8.png)

**Comment by dirtydancing** [comment]
Looks good to me :+1: 

Question: Is this a slightly different design from `network-wired-symbolic.svg` from `scalable`?. Cf. https://github.com/numixproject/numix-icon-theme/pull/482

Screenshot of `network-wired-symbolic.svg`:

![network-wired-symbolic](https://cloud.githubusercontent.com/assets/7164227/10862821/f5585376-7fb8-11e5-9850-c1b92c14c7d9.png)

**Comment by wa4557** [comment]
Just resized and aligned to grid. (Icons above are 22px)

**Comment by dirtydancing** [comment]
I see. imo it would be a nice improvement to have a specific icon for `wired` for Ubuntu's panel as well, different from the generic `network` icons. :+1: Also fits with the Numix `notification` icons.

**Comment by wa4557** [comment]
@Foggalong Any opinion on this. I still want the ugly icon to go away, and I want to stop using a custom icon theme just for these icons. If we want to stay consistent throughout the theme , I'd argue that [this proposal[(https://github.com/numixproject/numix-icon-theme/issues/785#issuecomment-152717092 ) makes most sense

**Comment by Foggalong** [comment]
@wa4557 That proposal has [this problem](https://github.com/numixproject/numix-icon-theme/issues/785#issuecomment-149315791) :cry:

**Comment by wa4557** [comment]
Alright. So if I can think of a better icon for network-offline ( to be consistent it has to be Made using two arrows somehow), then ok?

**Comment by wa4557** [comment]
I know we had a similar proposal already, but can we use this one. This would be such a vast improvement
![1](https://cloud.githubusercontent.com/assets/6475757/18254473/70fe49ca-739e-11e6-8db0-0d2eea797f6b.png)

Just compare it to the current design, which is just plain ugly

![unbenannt](https://cloud.githubusercontent.com/assets/6475757/18254475/7338546a-739e-11e6-89f5-e32c71ea38f0.png)

**Comment by Foggalong** [comment]
I'm wrestling with this, trying to work out in my head own to have network-error and network-offline be consistent with each other. Sorry to mess you around on this but I think [your proposal](https://github.com/numixproject/numix-icon-theme/issues/785#issuecomment-152717092) is probably going to be the best way to do it. I can't think of any other way to keep them both consistent and recognisable. We'll give it a try and if any confusion crops up we can always make adjustments down the line.
