### ISSUE TITLE
Wired network icon

### ISSUE THREAD

**Issue by leoheck** [numixproject/numix-icon-theme#810]
The same problem as bluetooth icon had

![selection_029](https://cloud.githubusercontent.com/assets/1277920/10679568/568df852-78f8-11e5-9559-e57fb8009a60.png)

**Comment by wa4557** [comment]
Distro? (Version etc.)

**Comment by leoheck** [comment]
```
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty
```

Using unity 7.2.5

**Comment by wa4557** [comment]
Wut?? No idea why this happens, using unity as well and no problems here...

**Comment by leoheck** [comment]
Ok. I will try to reboot  :(  or reinstall to see what happens.

**Comment by Foggalong** [comment]
@leoheck any joy?

**Comment by leoheck** [comment]
No, I still have the wrong icon.

**Comment by wa4557** [comment]
What Network Manager do you use?

**Comment by leoheck** [comment]
I purged the package then reinstalled it then I rebooted. Now it is ok. I think my pc was not rebooting properlly. Thank you.
