### ISSUE TITLE
Tray icon request for Wiznote

### ISSUE THREAD

**Issue by alim0x** [numixproject/numix-icon-theme#841]
[Desktop Entry]
Name=WizNote
Name[zh_CN]=为知笔记
Name[zh_TW]=为知笔记
Comment=cloud based note-taking application
Comment[zh_CN]=开源云笔记
Comment[zh_TW]=开源云笔记
Exec=WizNote
Terminal=false
Type=Application
StartupNotify=true
Icon=wiznote
Categories=KDE;Qt;Utility;

![94ab7d68-6510-11e5-8722-d402cf66c960](https://cloud.githubusercontent.com/assets/4954007/10994955/71708b18-84b4-11e5-98a1-a24ea0f92ac7.png)

![64512a5c-84b2-11e5-8bb9-be3c583bbf62](https://cloud.githubusercontent.com/assets/4954007/10994961/79a39f28-84b4-11e5-8170-d29d5b65434d.png)

**Comment by bil-elmoussaoui** [comment]
The icon name should be wiznote-indicator, it's a hardcoded qt applications ;)
