### ISSUE TITLE
goa-account-* are not used

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-icon-theme#847]
Hello, 
the icons used in Gnome online account and ubuntu online accounts too are not used even if they do exists in Numix;
the icon used instead is `goa-account` in Circle 
I think that having a symlink between Circle and base the same way we fixed status icons will fix that ?

**Comment by wa4557** [comment]
What do you mean? Everything fine here...
![bildschirmfoto vom 2015-11-08 14-13-03](https://cloud.githubusercontent.com/assets/6475757/11020562/0a4f4242-8623-11e5-9f79-fe57b2548938.png)

**Comment by bil-elmoussaoui** [comment]
![screenshot from 2015-11-08 14-18-21](https://cloud.githubusercontent.com/assets/7660997/11020576/95a2f10e-8623-11e5-9740-5a66ac5c4894.png)

**Comment by wa4557** [comment]
Ok but that means that `gnome-online-accoounts` uses `goa-account` and not the individual `goa-account-google` etc. There's arguably nothing numix can do about that

**Comment by bil-elmoussaoui** [comment]
Everything works fine with the default theme..

**Comment by wa4557** [comment]
Ah ok. Yes you're right that's the same thing as with the status icons. Yeah symlinking the icons from `48/apps` in base to circle should be fine I guess...

**Comment by wa4557** [comment]
I remember that this icons used to be in `Numix-Circle/48x48/apps`, this bug might be the reason why. Should we symlink them back?

**Comment by bil-elmoussaoui** [comment]
We have moved them as they're not really "circle"

**Comment by bil-elmoussaoui** [comment]
I think that a symlink is fine! :+1:

**Comment by bil-elmoussaoui** [comment]
Fixed :+1:
