### ISSUE TITLE
user-bookmark does not have the same design

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-icon-theme#849]
Hello, i was trying to add some new symlinks and i find out that `user-bookmarks`does not have the same design in all sizes! 
![screenshot from 2015-11-08 16-29-29](https://cloud.githubusercontent.com/assets/7660997/11021057/e5e66026-8635-11e5-8e44-ce17aff6a20f.png)

**Comment by palob** [comment]
Inconsistent symlinks?

**Comment by bil-elmoussaoui** [comment]
I don't think so, `user-bookmarks` has the same design as `starred` in `status` the same for `user-bookmarks-missing`

**Comment by palob** [comment]
Ah, I've had a look, both are distinct icons. So what's the better design to go for?

**Comment by wa4557** [comment]
I'd say the flag

**Comment by palob** [comment]
And I take it it can be safely removed from ``96``?

**Comment by wa4557** [comment]
If it is in actions -> yes. If it is in places -> no

**Comment by palob** [comment]
OK, fixing it to the flag :)

**Comment by palob** [comment]
Interestingly enough, the ``96`` one was only 48x48.

**Comment by wa4557** [comment]
Yeah there are still some inconsistencies there...
