### ISSUE TITLE
Mimetype: application/x-gnucash

### ISSUE THREAD

**Issue by hlechner** [numixproject/numix-icon-theme#860]
**Name:** GnuCash financial data
**Mimetype:** application/x-gnucash
**Possible extensions:** .xac

**Description**: File used to save the user's financial data of GnuCash program.

![image](https://cloud.githubusercontent.com/assets/11244067/11079806/fdbeff8e-87f5-11e5-9eb4-cb744e159a92.png)

`` standard::icon: application-x-gnucash, x-office-spreadsheet ``

Related to ``gnucash-icon`` of Numix-Circle: [here](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/gnucash-icon.svg?short_path=73f7db8)

**Comment by hlechner** [comment]
First drafts:
![image](https://cloud.githubusercontent.com/assets/11244067/11669700/36b33ce2-9de5-11e5-8321-f994fd2ba681.png)![image](https://cloud.githubusercontent.com/assets/11244067/11669711/3a287054-9de5-11e5-8171-0e0e16331e9c.png)

**Description:** first try with the numix-circle icon

**Comment by hlechner** [comment]
@Foggalong it's possible to create a mime related to gnucash but without use the numix-circle icon? I'm having difficulty to adapt it to use on mime and be on guideline.

**Comment by Foggalong** [comment]
While I like the draft, yeah it's very not to the guidelines. Possibly a loacalised bordered graph as a symbol? Or something which interprets cash literally like our currency icons

**Comment by wa4557** [comment]
:+1: for a dollar sign icon

**Comment by hlechner** [comment]
Yea, I'll try the graphs, I just need to find one that fit better on the mimes.

And here the dollar sign icon:
![image](https://cloud.githubusercontent.com/assets/11244067/11754391/2e933590-a032-11e5-93d1-37780fbb8fe1.png)

(not aligned yet)

**Comment by hlechner** [comment]
![image](https://cloud.githubusercontent.com/assets/11244067/11756380/a1a1ef50-a040-11e5-920e-7772d39c1c43.png)

@Foggalong your idea was something like that? (the draft above is not finished)

**Comment by hlechner** [comment]
![image](https://cloud.githubusercontent.com/assets/11244067/11756978/d70a962a-a044-11e5-8ec0-5656db62538b.png)

**Comment by Foggalong** [comment]
Yeah, much more on the guildelines :)

**Comment by hlechner** [comment]
![image](https://cloud.githubusercontent.com/assets/11244067/11759857/242d80b2-a06c-11e5-9f43-a52da25e0876.png)![image](https://cloud.githubusercontent.com/assets/11244067/11759860/2b9fb108-a06c-11e5-88de-cde7cc018825.png)![image](https://cloud.githubusercontent.com/assets/11244067/11759863/34d29d08-a06c-11e5-9a41-406110e26bfd.png)![image](https://cloud.githubusercontent.com/assets/11244067/11759865/3b6276f2-a06c-11e5-8239-6590e183c680.png)![image](https://cloud.githubusercontent.com/assets/11244067/11759866/4101f722-a06c-11e5-850c-296039ce6ac5.png)

Suggestions?

**Comment by ChuckDaniels87** [comment]
I think that alternative icons are better fo 24px and 16px.

**Comment by Foggalong** [comment]
Yeah, definitely use the 16/22/24 alts.
