### ISSUE TITLE
Feedreader missing icons

### ISSUE THREAD

**Issue by bilelmoussaoui** [numixproject/numix-icon-theme#868]
Feedreader is one of the best feed readers out there!
Actions: 
- [ ] feed-add-symbolic
- [ ] feed-arrow-up-symbolic
- [ ] feed-refresh-symbolic
- [ ] feed-remove-symbolic
- [ ] feed-share-symbolic
- [ ] feed-sidebar-arrow-down-symbolic
- [ ] feed-sidebar-arrow-side-symbolic
- [ ] feed-tag-symbolic
- [ ] feed-mark-read-symbolic

Status
- [ ] feed-article-read
- [ ] feed-article-unread
- [ ] feed-backend-info
- [ ] feed-marked-symbolic
- [ ] feed-non-starred
- [ ] feed-read-symbolic
- [ ] feed-starred
- [ ] feed-unmarked-symbolic
- [ ] feed-unread-symbolic
- [ ] feed-status-ok
- [ ] feed-rss-symbolic

Screenshot : 
![capture du 2015-11-15 00-25-53](https://cloud.githubusercontent.com/assets/7660997/11166338/75206252-8b2f-11e5-8230-cf37ce29d906.png)

**Comment by palob** [comment]
Again, as for the symbolic icons I don't see how they could get significantly more Numixy.

**Comment by bil-elmoussaoui** [comment]
@palob I just did symlinked the two Numix symbolic icons, the others can be a won't fix at the moment as there's a lot of missing icons

**Comment by palob** [comment]
Are there any left whih need a distinct design?

**Comment by bil-elmoussaoui** [comment]
Yes, you can see in my PR. Sorry, i can't give you a list of the icons as im using my smartphone

**Comment by wa4557** [comment]
As I was doing a lot of `*-symbolic` icons the last time I agree with @palob It is really hard to make distinct icons for those. I tried to use already existing numix designs but for a few it's basically the same as in the Adwaita theme just a few minor changes aligned to grid and cleaned up. But I don't see how for example how the above `feed-marked-symbolic.svg` could be made different from the one above...

**Comment by bil-elmoussaoui** [comment]
I will mark the symbolic icons as a won't fix

**Comment by wa4557** [comment]
Wait, no. I think we still should do them since Adwaita is not in the Numix inheritence line, sorry for the confusion :) All I want to say is that they will not differ very much from the Adwaita ones

**Comment by wa4557** [comment]
@bil-elmoussaoui Can you tell me where the icons are located? (All action icons?)

**Comment by bil-elmoussaoui** [comment]
Actions and status , there's two lists :p

**Comment by wa4557** [comment]
oops didn't see that :P

**Comment by palob** [comment]
Uses 100& symbolic icons by now.
