### ISSUE TITLE
Octave missing icons

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-icon-theme#870]
There's a few missing icons in Octave
![capture du 2015-11-15 11-45-05](https://cloud.githubusercontent.com/assets/7660997/11168415/64713936-8b8e-11e5-8e9b-6fce392be5e1.png)
The icons names are from left to right
- [x] bp-toggle -> media-playback-record
- [x] bp-prev
- [x] bp-next
- [x] bp-rm-all
- [x] db-step
- [x] db-step-in
- [x] db-step-out
- [x] db-cont -> media-playback-start
- [x] db-stop -> media-playback-stop

**Comment by palob** [comment]
@bil-elmoussaoui Do you face blurry Numix icons in Octave?
![octave](https://cloud.githubusercontent.com/assets/7050624/11284326/6abecf00-8f09-11e5-9df0-21a5b23ce6f8.png)

**Comment by bil-elmoussaoui** [comment]
@palob only when  you i choose small icons size in settings

**Comment by palob** [comment]
Hmm, for me small icons result in the least blurry icons.

**Comment by palob** [comment]
It's probably the 16px icons scaled up to 24px and 32px instead of using the 24px and 32px ones.

**Comment by palob** [comment]
I'm working on those. 16px ``bp-*`` icons:
![bp-icons](https://cloud.githubusercontent.com/assets/7050624/11613847/23693260-9c30-11e5-8103-71baf73d2aee.png)

**Comment by bil-elmoussaoui** [comment]
Nice!! :D

**Comment by palob** [comment]
``db-*`` icons in 16px:
![db-icons](https://cloud.githubusercontent.com/assets/7050624/11614049/59218492-9c36-11e5-9a69-5437736766fb.png)

**Comment by wa4557** [comment]
Could we use the same design for the `distribute-*` icons (from #437, inkscape icons )

**Comment by palob** [comment]
Well, looking at the ``distribute-*`` icons in ``elementary`` and ``breeze`` I think a distinct design is justified.

**Comment by wa4557** [comment]
Sure but the general design idea could be similar :)

**Comment by bil-elmoussaoui** [comment]
Octave will look so Numixy! :D
