### ISSUE TITLE
Mimetype: application/pkcs10

### ISSUE THREAD

**Issue by hlechner** [numixproject/numix-icon-theme#872]
**Name:** PKCS#10 Certificate Request
**Mimetype:** application/pkcs10
**Possible extensions:** .csr
**Mimetype Information:** https://tools.ietf.org/html/rfc5967

**Description:** This is a request file for a certificate

```
What is a Certificate Signing Request (CSR)?

A Certificate Signing Request (CSR) is a PKCS10 request which is an unsigned copy of your certificate. Entrust Certificate Services will use the Certificate Signing Request (CSR) to generate your signed digital x509 V3 SSL server certificate. Your CSR contains the following:
- Information about your organization (organization name, country, etc…)
- Your Web Server’s public key
- A unique mathematical match to your server’s private key

Why do I need a Certificate Signing Request?

The Certificate Signing Request is required by Entrust Certificate Services to generate your digital certificate, and must be submitted to Entrust Certificate Services during the enrollment process. Entrust Certificate Services will issue a new certificate.
```

![image](https://cloud.githubusercontent.com/assets/11244067/11187915/8d638722-8c6f-11e5-8a57-b43ef6e66d44.png)
`standard::icon: application-pkcs10, text-x-generic`

I was checking if there was no icon already existent to symlink to it, then I found 3 related to certificate:
- **application-certificate.svg** - [[here]](https://github.com/numixproject/numix-icon-theme/blob/master/Numix/64/mimetypes/application-certificate.svg) - It's used to the certificate itself
- **encrypted-key.svg** - [[here]](https://github.com/numixproject/numix-icon-theme/blob/master/Numix/64/mimetypes/encrypted-key.svg) - It's used to keys/signature
- **encrypted.svg** - [[here]](https://github.com/numixproject/numix-icon-theme/blob/master/Numix/64/mimetypes/encrypted.svg) - It seems to be used to encrypted data of PGP or example (not sure about)

So, I didn't create a symlinks to any icons quoted above because I'm not sure if any of this is appropriated to this mimetype.

**Comment by hlechner** [comment]
First drafts:
![image](https://cloud.githubusercontent.com/assets/11244067/11760308/c5f0c98e-a07d-11e5-9fc4-c8d4cd7ced83.png)

**Description:** this draft is just awful, my idea is just to share the idea itself. This certificate request is basically your info and your keys, maybe the idea of "sending a key" or something related. what you guys think about?

**Comment by Foggalong** [comment]
Toying with the idea of recolouring all the security mimes mentioned here the orange from certificate. Thoughts?

**Comment by hlechner** [comment]
I don't know about all security mime but for the mime related to certificate will be very good :+1:
