### ISSUE TITLE
Mimetypes: ROM files (consoles)

### ISSUE THREAD

**Issue by hlechner** [numixproject/numix-icon-theme#879]
**Description:** There are some specific mimetypes for some ROM files of consoles that it's listed below:

![image](https://cloud.githubusercontent.com/assets/11244067/11255722/e15cd70a-8e2e-11e5-9c16-b702a9266b31.png)

Nintendo:
- [x] **[NES](https://en.wikipedia.org/wiki/Nintendo_Entertainment_System) ROM** (application/x-nes-rom) - [[nestopia.svg]](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/nestopia.svg) [<1>](http://www.clker.com/cliparts/6/c/8/5/11971195211198311825BHSPitMonkey_Old_School_Game_Controller.svg) [<2>](http://cdn.flaticon.com/svg/38/38453.svg)
- [x] **[Nintendo DS](https://en.wikipedia.org/wiki/Nintendo_DS) ROM** (application/x-nintendo-ds-rom) [<1>](http://www.pubzi.com/f/Handheld-3D-Game-System.svg)[<2>](https://upload.wikimedia.org/wikipedia/ru/4/4e/Nintendo_DS.svg)
- [x] **[Nintendo64](https://en.wikipedia.org/wiki/Nintendo_64) ROM** (application/x-n64-rom) [<1>](https://upload.wikimedia.org/wikipedia/en/0/04/Nintendo_64_Logo.svg)
- [x] **[Game Boy](https://en.wikipedia.org/wiki/Game_Boy) ROM** (application/x-gameboy-rom) [<1>](https://upload.wikimedia.org/wikipedia/commons/4/41/Gameboy.svg)
- [x] **[Game Boy Advance](https://en.wikipedia.org/wiki/Game_Boy_Advance) ROM** (application/x-gba-rom) - [[vbam.svg]](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/vbam.svg)  [[gba.svg]](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/gba.svg)

Sega:
- [x] **Sega [Master System](https://en.wikipedia.org/wiki/Master_System)/[Game Gear](https://en.wikipedia.org/wiki/Sega_Game_Gear) ROM** (application/x-sms-rom)
- [x] **[Genesis](https://en.wikipedia.org/wiki/Sega_Genesis) ROM** (application/x-genesis-rom) - [[gensgs.svg]](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48x48/apps/gensgs.svg)

**Comment by Foggalong** [comment]
I have a vague idea here. Rather than desperately trying to fit the shape of a whole console into a 16px icon, use a generic gaming symbol for all the mimetypes but then use the main colour of each console for the background (possibly coupled with the usual text?)

**Comment by hlechner** [comment]
I think it's great idea, because it will save a lot of time making these icons and also will be easier if we found new kind of ROMs in the future.

**Comment by bil-elmoussaoui** [comment]
@hlechner There's an icon for this mimetype `application-vnd.nintendo.snes.rom` in Numix. Maybe creating a symlink from this `application/x-nes-rom`in your PR to the other one? your new design look so far better :)

**Comment by hlechner** [comment]
@bil-elmoussaoui Yea, thanks, it's very interesting idea because it could standardize the consoles rom files by using the same design, but in that case I need to create a new icon with a proper text.

That decision should be made by the Numix member @Foggalong, if he approves I can add this

**Comment by bil-elmoussaoui** [comment]
@Foggalong What do you think about changing the design of `application-vnd.nintendo.snes.rom` and make it look the same as other ROM mimetypes?

**Comment by Foggalong** [comment]
I'm a-okay with doing that :+1:

**Comment by hlechner** [comment]
I'll make the snes mime them and send a pull request
