### ISSUE TITLE
Mimetype: application/x-amiga-disk-format (floppy image)

### ISSUE THREAD

**Issue by hlechner** [numixproject/numix-icon-theme#881]
**Name:** Amiga disk image
**Mimetype:** application/x-amiga-disk-format
**Possible extensions:** .adf
**Information:** https://en.wikipedia.org/wiki/Amiga_Disk_File

**Description:** This is a disk image like ISO but from floppy instead of CD/DVD of **Amiga** OS.
![image](https://cloud.githubusercontent.com/assets/11244067/11257861/cafef260-8e3b-11e5-8201-e25c957dcd71.png)
``standard::icon: application-x-amiga-disk-format, application-x-generic``

**My personal design idea:** could be a similar idea of ISO mimetype but with floppy and maybe (or not) use some logo/color from Amiga OS:
![image](https://cloud.githubusercontent.com/assets/11244067/11257980/9604d86c-8e3c-11e5-91bd-0cb063e1a5e5.png) ![image](https://cloud.githubusercontent.com/assets/11244067/11258010/d1e49ffc-8e3c-11e5-877d-3d51d053d5ac.png)
![image](https://cloud.githubusercontent.com/assets/11244067/11258048/1fda66ec-8e3d-11e5-9998-fa2115d2f461.png)

[[Logo in SVG here]](http://en.academic.ru/pictures/enwiki/65/Amiga_Logo_1985.svg)
**Related Numix Icons:**
[![image](https://cloud.githubusercontent.com/assets/11244067/11277686/b48c3d2e-8ece-11e5-9f42-9543e2f3a58a.png)](https://github.com/numixproject/numix-icon-theme/blob/master/Numix/64/mimetypes/application-blank.svg)[![image](https://cloud.githubusercontent.com/assets/11244067/11277773/0c5a52de-8ecf-11e5-8d69-adbb7c0d5db7.png)](https://github.com/numixproject/numix-icon-theme/blob/master/Numix/64/mimetypes/application-x-cd-image.svg)[![image](https://cloud.githubusercontent.com/assets/11244067/11277834/65e247b2-8ecf-11e5-9ee8-7793779cf531.png)](https://github.com/numixproject/numix-icon-theme/blob/master/Numix/64/devices/media-floppy.svg)

**Related non-Numix:**
![image](https://cloud.githubusercontent.com/assets/11244067/11278560/bf447886-8ed2-11e5-87da-fae76e21e841.png) (from [electrem software](http://sourceforge.net/projects/electrem/))
![image](https://cloud.githubusercontent.com/assets/11244067/11279252/8d24a8d6-8ed6-11e5-8735-bb9300dc048e.png) (from [this](https://www.facebook.com/AmigaHeaven/) facebook community)

**Comment by hlechner** [comment]
I've tried:
![image](https://cloud.githubusercontent.com/assets/11244067/11289333/e379a0c4-8f12-11e5-8e44-f2badb886d12.png)

But I'm not sure about it, I'm a terrible with design.

**Comment by Foggalong** [comment]
Yeah, that doesn't really fit in with the other mimetypes so would need a bit more work

**Comment by wa4557** [comment]
The mimetypes icon symbol is usually monochrome. If you try to simplify the symbol but keeping it recognizable it might even work...

**Comment by hlechner** [comment]
Based on disk photo I've first created this svg:
![image](https://cloud.githubusercontent.com/assets/11244067/11310300/fe1ee9be-8faf-11e5-8587-a5e2b25154d6.png)

And I some tests like this one:
![image](https://cloud.githubusercontent.com/assets/11244067/11310322/161028d0-8fb0-11e5-80a9-0d83deac2ddd.png)

But still far way to be good, I'll probably try more later if I have time

**Comment by hlechner** [comment]
I'm not working on it right now, but just to share the old try:
![image](https://cloud.githubusercontent.com/assets/11244067/11628657/3bcae79a-9cda-11e5-989f-180e1d599b3a.png)

I still trying to figure out what is the best result for this mime.

**Comment by hlechner** [comment]
New draft:
![image](https://cloud.githubusercontent.com/assets/11244067/11760824/ec1c81d4-a091-11e5-9807-a5528decf131.png)

**Comment by ChuckDaniels87** [comment]
Last one is nice.

**Comment by hlechner** [comment]
![image](https://cloud.githubusercontent.com/assets/11244067/11762328/00dcec5c-a0ca-11e5-8287-875d0b803a0d.png)![image](https://cloud.githubusercontent.com/assets/11244067/11762329/066ce6ae-a0ca-11e5-9646-bf00920f354c.png)![image](https://cloud.githubusercontent.com/assets/11244067/11762330/0be5da1e-a0ca-11e5-9886-f1313ebc0c27.png)![image](https://cloud.githubusercontent.com/assets/11244067/11762331/10c47d10-a0ca-11e5-99c8-47b90a18da26.png)![image](https://cloud.githubusercontent.com/assets/11244067/11762332/1617977a-a0ca-11e5-9260-0b08be068363.png)

**Comment by Foggalong** [comment]
Much much better :+1:
