### ISSUE TITLE
Missing icon for Museeq

### ISSUE THREAD

**Issue by pavethem** [numixproject/numix-icon-theme#888]
Icon Name: museeq

Notes: Soulseek client

Additional info: It also has a tray icon

![auswahl_001](https://cloud.githubusercontent.com/assets/847563/11298235/d85f0bb4-8f7d-11e5-9690-28ae688eba66.png)

**Comment by wa4557** [comment]
Is the name of the tray icon also museeq? If yes we cannot fix it :(

**Comment by bil-elmoussaoui** [comment]
@wa4557 Museeq is a Qt application..

**Comment by Foggalong** [comment]
I can see where this one is going to go :(

**Comment by wa4557** [comment]
so should I make a tray icon with name `museeq-panel` then?

**Comment by Foggalong** [comment]
Looking through the [source](https://github.com/eLvErDe/museek-plus) I can't find the panel icon anywhere, so I'm assuming it's hardcoded to the app icon (which I guess makes the original report corret). `museeq-panel` is a go!

**Comment by wa4557** [comment]
aye

**Comment by bil-elmoussaoui** [comment]
@wa4557 Are you still using Ubuntu? if so can you try to install the application and see if you can find the icon name in `/tmp`

**Comment by pavethem** [comment]
you can indeed find these icons in /tmp.
It uses different ones for when you are connected/disconnected. i could never really make sense of it.
![museeq_30211_2f0bfbefd5f436ee06255de74ae04b74](https://cloud.githubusercontent.com/assets/847563/11315550/fcaf5e44-8ff3-11e5-8f84-136728241d7d.png)
![museeq_30256_0008df6b8abb9fb96af23f526732e605](https://cloud.githubusercontent.com/assets/847563/11315553/fcb275ac-8ff3-11e5-9d37-3e983a6015d6.png)
![museeq_30256_21dff8ad54c6c56ada4c3e69610fcaf4](https://cloud.githubusercontent.com/assets/847563/11315551/fcb1d75a-8ff3-11e5-9da8-49b5cbf3b4cf.png)
![museeq_30256_bdf9b53b9cd16f3c032bf1eca0892643](https://cloud.githubusercontent.com/assets/847563/11315552/fcb1fb18-8ff3-11e5-8334-d17877180387.png)

**Comment by wa4557** [comment]
@pavethem Can you provide the names of the icons as well? Am I right that one icon would be sufficient for the first three + an additional disconnected icon?

**Comment by pavethem** [comment]
I think I know why I'm not seeing the icon yet. My original request was for a launcher icon for museeq, which was never made I think? I think I just worded the issue weirdly. Can somebody reopen?
