### ISSUE TITLE
Dropbox missing emblems

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-icon-theme#893]
Theres two missing emblems icon for Dropbox
The first one is used for application that have permission to sync files to your Dropbox account
- [ ] emblem-dropbox-app
- [ ] emblem-dropbox-selsync

![capture du 2015-11-21 00-05-06](https://cloud.githubusercontent.com/assets/7660997/11314176/8824ed06-8fe3-11e5-9c88-c5a5c0310819.png)

**Comment by wa4557** [comment]
And the second one? I think the name does not really work with the icon!?

**Comment by bil-elmoussaoui** [comment]
I really don't know where the second one is used
For the first one : 
![capture du 2015-11-21 10-57-28](https://cloud.githubusercontent.com/assets/7660997/11317900/ad8637f2-903e-11e5-9a1c-0a177d072bf2.png)

**Comment by wa4557** [comment]
Ok then it will be the same icon numixyfied :)
