### ISSUE TITLE
Mimetypes: Microsoft files

### ISSUE THREAD

**Issue by hlechner** [numixproject/numix-icon-theme#898]
# Microsoft common files:

Help Files:
- [x] **CHM document** (application/vnd.ms-htmlhelp) [[INFO]](http://fileformats.archiveteam.org/wiki/CHM)
- [x] **WinHelp help file** (application/winhlp) [[INFO]](http://fileformats.archiveteam.org/wiki/HLP_%28WinHelp%29)

Cursor Files:
- [x] **Windows cursor** (image/x-win-bitmap) [[INFO]](http://fileformats.archiveteam.org/wiki/CUR)
- [x] **Windows animated cursor** (application/x-navi-animation) [[INFO]](http://fileformats.archiveteam.org/wiki/Windows_Animated_Cursor)

Other:
- [x] **RIFF container** (application/x-riff) [[INFO]](http://fileformats.archiveteam.org/wiki/RIFF)
- [x] **Internet shortcut** (application/x-mswinurl) [[INFO]](http://fileformats.archiveteam.org/wiki/Internet_Shortcut) - also reported on #580

---
## Help Files:

**Description**:  **CHM** and **HLP** are used to show help information on Windows platform.
![image](https://cloud.githubusercontent.com/assets/11244067/11320197/a8a3dfe4-9077-11e5-9845-19c87c7ba699.png)
- **CHM**: `standard::icon: application-vnd.ms-htmlhelp, x-office-document`
- **HLP**: `standard::icon: application-winhlp, application-x-generic`

**Design Association**: Help, Information, Manpage
**Note**: Could be used this mimetype for  **Manpage manual document** file.
## Cursor Files:

**Description**: **CUR** file is a static cursor and **ANI** animated cursor for Windows systems. nautilus used to preview (thumbnail) the **CUR** as a normal image.
![image](https://cloud.githubusercontent.com/assets/11244067/11320227/0d7a7c9c-9079-11e5-914f-29d193fc0de4.png)
- **CUR**: `standard::icon: image-x-win-bitmap, image-x-generic`
- **ANI**: `standard::icon: application-x-navi-animation, application-x-generic`

**Design Association**: Cursor, pointer
**Note**: Could be used this mimetype for **X11 Cursor** file. The image BMP use the following mime: (image/bmp), the CUR uses  (image/x-win-bitmap) instead.
### RIFF

**Description**: It's a container format created by Microsoft common used to include audio and video format. I guess its not used at all to a user execute/use it directly, so I think will be ok link to windows binary mimetype.
![image](https://cloud.githubusercontent.com/assets/11244067/11320275/cfd88b84-907a-11e5-8211-88f6bdec2fc8.png)
- **RIFF**: `standard::icon: application-x-riff, application-x-generic`
### URL file

**Description**: used on Windows systems to create a file link to a Internet URL. also reported on #580 
![image](https://cloud.githubusercontent.com/assets/11244067/11320302/af405928-907b-11e5-8a35-9589439c8f93.png)
- **URL**: `standard::icon: application-x-mswinurl, application-x-generic`

**Design Association**: Globe, Internet, Link, Page

Fixes hlechner/hl-numix-mime#1

**Comment by hlechner** [comment]
I was thinking about so many mimetypes request that I'm doing lately here, and it's actually counterproductive.

So I've found a solution, that I think could fit. I want to continue helping with mimetypes but instead of creating a lot of issues here I've created a separated repo to report it. It will be better because its is not priority and also don't disturb this repo with the mime requests.

I've also created a "standard" for my requests and also I've recreated the most of my issue there with easier and clean information with better references of texts and icons and concatenate the similar issues.

On the new repo I also created drafts of 8 mimetypes if you can check there what you think of them.

And I want to close the issues here to continue there, the idea is basically the same as here but just for mime, you not even need to look to it often.

Repo link: https://github.com/hlechner/hl-numix-mime/issues

What you think @Foggalong ?

**Comment by Foggalong** [comment]
I'll be honest, I think it's a bad idea. While I appreciate the effort adding another repo just for issue tracking a specific component is overcomplicating things

**Comment by hlechner** [comment]
@Foggalong No problem, if its better this way, let me use just this way. Sorry about creating the repo I though that could be useful.

Before I deactivate the other repo could you just take a look into the issues there? I think some icons that I made could be merged, then I can make the pull request and close the issue, if its not ready I transfer it to this repo. I'll not raise more anything there.

I didn't create the all mime yet because I'm not used to use the inkscape and it take me a lot of time, so it's better know if you can approve it or I need to change something before.

Also @wa4557 is helping me a lot there.

**Comment by bil-elmoussaoui** [comment]
Love the VirtualBox mimetypes ! Nice design !

**Comment by hlechner** [comment]
Hey @Foggalong, what you think about the following icon (RIFF) it's ok for you?
#### RIFF:
First Drafts:
![image](https://cloud.githubusercontent.com/assets/11244067/11457570/8ee11ff0-9693-11e5-9160-039d283162e6.png)
