### ISSUE TITLE
Missing disk symlink from eXFCE

### ISSUE THREAD

**Issue by Foggalong** [numixproject/numix-icon-theme#901]
By pure chance I stumbled upon a missing icon from Thunars volume manager. I didn't have time to catch the icon name at the time so I'll leave it invalid as it should be for now. I'm guessing the icon is included in eXFCE since that's the base on Xubunutu
![screenshot_2015-11-25_02-52-49](https://cloud.githubusercontent.com/assets/5920259/11387143/b5a501d2-931f-11e5-85ab-ff5bfc062c08.png)

**Comment by wa4557** [comment]
Seems to be this icon `stock_xfburn-burn-cd`

**Comment by Foggalong** [comment]
OH damn, I'd forgot about this. Thanks for finding it!
