### ISSUE TITLE
monochrome clipboard request

### ISSUE THREAD

**Issue by sljunkie** [numixproject/numix-icon-theme#905]
The popular gnome-shell extension 'Clipboard Indicator' uses this icon. https://extensions.gnome.org/extension/779/clipboard-indicator/

![screenshot from 2015-11-20 19-43-24](https://cloud.githubusercontent.com/assets/7532854/11611439/f47633c0-9bb4-11e5-964f-774db632db57.png)

I think Numix could polish it a bit... here's the same icon in Elementary for example:

![screenshot from 2015-12-06 01-03-17](https://cloud.githubusercontent.com/assets/7532854/11611445/2fff30f4-9bb5-11e5-82f5-8b372d168dc1.png)

**Comment by bil-elmoussaoui** [comment]
The icon name is `edit-paste-symbolic`  [see here](https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/blob/master/extension.js#L66)
```
./Numix/scalable/actions/edit-paste-symbolic.svg
./Numix-Light/scalable/actions/edit-paste-symbolic.svg
```
Which already exists in Numix & Numix-Light. @Foggalong Maybe an enhancement instead of a request? :P

**Comment by sljunkie** [comment]
Yes, it looks exactly the same as the `edit-paste-symbolic.svg` icon from Adwaita.

**Comment by palob** [comment]
I use the extension as well. The icon looks the same with ``Adwaita``, so that's where the Numix icon originates from.
