### ISSUE TITLE
Mimetype : text/x-arduino (Arduino)

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-icon-theme#912]
There's a missing mimetype icon for Arduino files
Mimetype : ` text/x-arduino`

Arduino IDE does not provide a default mimetype icon.

**Comment by hlechner** [comment]
First drafts:
![image](https://cloud.githubusercontent.com/assets/11244067/11614722/dae94ec4-9c31-11e5-9c99-462ba07bd30f.png)

**Description:** Something like this? it is just a fast draft as you can see the "+" is blurry and I didn't try the smaller icons.

**Comment by bil-elmoussaoui** [comment]
Good one! :+1:

**Comment by bil-elmoussaoui** [comment]
@Foggalong What do you think?

**Comment by hlechner** [comment]
It's just a fast draft, I need to polish it before it could be considered to a pull request, @bil-elmoussaoui 

When I have time to finish it I'll post here the result.

If someone want to try, please go ahead.

**Comment by hlechner** [comment]
Hey Bill, just to keep you updated, the main issue for me now is the smaller size. the symbol didn't fit on 16px. Maybe the solution will be just the "+" and "-" sings but it remind me math operation.

So I'm work on it. But if you have any idea please share it here, if just the idea or if some draft.

**Comment by hlechner** [comment]
![image](https://cloud.githubusercontent.com/assets/11244067/11644275/c6ab9f9c-9d31-11e5-9995-bbeff07dbb36.png)![image](https://cloud.githubusercontent.com/assets/11244067/11644276/cadd29a0-9d31-11e5-9818-4eae077f7bc6.png)![image](https://cloud.githubusercontent.com/assets/11244067/11644283/d01bd89e-9d31-11e5-8ac7-b4d1887fe7e4.png)![image](https://cloud.githubusercontent.com/assets/11244067/11644284/d565c86e-9d31-11e5-8854-1faaf244effd.png)![image](https://cloud.githubusercontent.com/assets/11244067/11644288/d9ea0e40-9d31-11e5-9201-b7cea3c00304.png)![image](https://cloud.githubusercontent.com/assets/11244067/11644291/df6fa65e-9d31-11e5-824f-ccc4048caea1.png)

**Comment by hlechner** [comment]
New draft:
![image](https://cloud.githubusercontent.com/assets/11244067/11668587/14594f48-9ddf-11e5-9e91-4f103fa9d255.png)

.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
Yes... of course is a joke

**Comment by ChuckDaniels87** [comment]
LoL

**Comment by bil-elmoussaoui** [comment]
:laughing:
