### ISSUE TITLE
Musescore Mimetype

### ISSUE THREAD

**Issue by Foggalong** [numixproject/numix-icon-theme#923]
Mimetype used by sheetmusic software Musescore.
Name: application/x-musescore
Icon: ![screenshot_2015-12-08_14-30-29](https://cloud.githubusercontent.com/assets/5920259/11658024/552ce164-9db8-11e5-8081-97d796f0c147.png)

**Comment by palob** [comment]
A distinct one or a symlink to the lilypond mimetype?

**Comment by Foggalong** [comment]
symlink to lilypond is probably good :+1:
