### ISSUE TITLE
Wrong icon for home, trash and desktop with Numix Light icons

### ISSUE THREAD

**Issue by milos-rootsman** [numixproject/numix-icon-theme#972]
![screenshot-28-14 59 20](https://cloud.githubusercontent.com/assets/16455444/12019687/7dcb3216-ad6b-11e5-9e16-8128843557db.png)

They all use the avatar icon

**Comment by palob** [comment]
Which file manager is that?

**Comment by wa4557** [comment]
Everything fine when not using the light theme?

**Comment by milos-rootsman** [comment]
It's pcmanfm.
When using the dark theme it's fine.

**Comment by Foggalong** [comment]
@milos-rootsman Just so this doesn't get confusing

- the light theme (Numix Light) is the theme with black icons, which is to be used with light panels
- the normal theme (Numix) is the theme with white icons, which is to be used with dark panels

**Comment by wa4557** [comment]
Did it work before?

**Comment by dirtydancing** [comment]
I can confirm this issue in PCManFM 1.2.3 with Arch/GNOME.

Screenshots with Numix-Circle (fine) and Numix-Circle-Light:

![numix](https://cloud.githubusercontent.com/assets/7164227/12050542/3112972e-aef7-11e5-8915-c169acc2ce58.png)

![numix-light](https://cloud.githubusercontent.com/assets/7164227/12050544/36d5d8ba-aef7-11e5-90e8-94a78382b215.png)

**Comment by wa4557** [comment]
Can you try and find out which icon is the problematic one? (avatar-default maybe)

**Comment by dirtydancing** [comment]
Well, for the time being I am not sure what is going on here. `avatar-default.svg` is present in Numix as well as in Numix-Light. Still, after removing `avatar-default.svg` from Numix-Light, I end up with these question mark icons. Maybe some issue with the folder icons? Screenshot with Numix-Light:

![question-mark](https://cloud.githubusercontent.com/assets/7164227/12050872/4c216d52-aefb-11e5-94b4-5d7155e1b428.png)

**Comment by wa4557** [comment]
weird... `icon-cache` maybe?

**Comment by milos-rootsman** [comment]
@wa4557 it worked fine before, until i updated to the newest version

**Comment by dirtydancing** [comment]
Confirmed that this was an icon cache thing, and a strange one at that, as I had to create an icon cache for Numix Light where there was none before. Anyways, it works with Numix Light after removing `avatar-default.svg`. But this is still very strange: did `avatar-default.svg` change recently?

One more thing I can think of is the inheritance line: maybe s.th. related to Numix Light inheriting from Numix?

@milos-rootsman Do you mean an update to the newest version of pcmanfm or of Numix icon theme? Just trying to figure out if an issue with pcmanfm could be behind this.

**Comment by wa4557** [comment]
`avatar-default` has been there for a very long time, so no :( I was thinking about inheritance as well, that's the only thing that is different for `numix` and `Numix-Light`. Still weird though that only these three icons are showing up as `avatar-default`.

**Comment by wa4557** [comment]
@dirtydancing Maybe it is not `avatar-default` but one of the symlinks pointing to it. `user` might be the problem because this would mean that it is the same problem as #190 (Wow this issue really has some bad reputation now). So instead of `user-trash.svg` `user.svg` is used because it is in the base theme which is higher in the inheritence line...

**Comment by milos-rootsman** [comment]
@dirtydancing the update of the icons

**Comment by dirtydancing** [comment]
Confirmed that https://github.com/numixproject/numix-icon-theme/pull/977 fixes this issue.
