### ISSUE TITLE
Wrong icon for Battery low notification

### ISSUE THREAD

**Issue by Red-devilz** [numixproject/numix-icon-theme#973]
"The battery has 20 minutes remaining" Notification is displayed with the wrong icon as shown in the screenshot :
![image](https://cloud.githubusercontent.com/assets/15090318/12020235/1c4ca3dc-ada0-11e5-9ef7-d0c56ca96e88.png)

The same icon also appears when I press the touchpad disable/enable button on my keyboard as seen in :
![image](https://cloud.githubusercontent.com/assets/15090318/12020207/c415cb4e-ad9f-11e5-8d7e-1413d0078693.png)

This change has happened out of nowhere and I dont remember installing anything new. Can someone direct me as to how I should change it back to the default battery and touchpad icons? Thanks in advance.

Note: This problem occurs only when I select any Numix-icon theme(ex:numix icon circle), and not for any other icon theme(ex: Ambiance). . I run ubuntu 14.04 LTS.

**Comment by hg8** [comment]
I am affected by this issue as well on Ubuntu 15.10.

**Comment by wa4557** [comment]
The problem seems to be `notification-symbolic.svg` in `scalable/status` if you remove that the notifications work again. @Foggalong I think we should/could/have to remove the icon... No idea why this happens though

**Comment by jwadolowski** [comment]
I experienced kinda similar issue, but in my case it happens whenever I press Fn+F5 key combination, which disables/enables touchpad. Worked perfectly fine some time ago.

![numix_icon](https://cloud.githubusercontent.com/assets/6334715/12044879/87a0491e-ae99-11e5-8cc5-6365739d0193.png)

**Comment by Foggalong** [comment]
Any ideas @dirtydancing?

**Comment by wa4557** [comment]
See my comment above...

**Comment by dirtydancing** [comment]
On first sight, to me this looks like a clean-cut case of a bug in Ubuntu/Unity (I am not sure which exact package, though).

@wa4557 and I have done some work on the Ubuntu notification icons, cf. e.g. https://github.com/numixproject/numix-icon-theme/issues/255 and https://github.com/numixproject/numix-icon-theme/pull/283#issuecomment-81230253. In the meantime, I have moved from Ubuntu/Unity to Arch/GNOME, and things might have changed a little in Ubuntu. But already back then, there were several different icon names for low battery notifications in the Ubuntu notification bubbles (NotifyOSD):

`notification-battery-020.svg`
`notification-battery-low.svg` (symlink with target notification-battery-020.svg)
`notification-battery-000.svg`
`notification-battery-empty.svg` (symlink with target notification-battery-000.svg)
`battery-caution-symbolic.svg` (symlink with target notification-battery-000.svg)

Now, `notification-symbolic.svg` seems to have taken over. This does not make any sense at all, as this is a generic icon name, and there were specific battery-related icon names before. So this looks like a bug in Ubuntu/Unity.

**Is there a corresponding bug report against Ubuntu?**

The next question would be: which ones of the battery notifications have been taken over by `notification-symbolic.svg`. All five of the previous battery notification icons? Or even all the notification icons, as the touchpad notifications appear to be affected as well?

The problem with simply removing `notification-symbolic.svg` is that that icon might be used elsewhere (in Ubuntu or in other distros/DEs), so before removing this icon from Numix, I figure we would need to check whether/where it is (properly) used.

In Arch/GNOME, I have not come across `notification-symbolic.svg` so far, but to me this looks like an icon that is used somewhere, so I would advise against removing it prematurely. On the other hand, this icon name is not present at all in e.g. in Adwaita (GNOME's default icon theme).

In Numix, `notification-symbolic.svg` is a symlink with the target `notifications-symbolic.svg`. `notifications-symbolic.svg` (with an `s`) exists e.g. as well in Paper and Evopop icon themes.

**Comment by wa4557** [comment]
It is the `battery-caution-symbolic` icon that get's replaced by `notification-symbolic` (no idea why though the other ones look fine. 

You can test this by doing `notify-send test -i "battery-caution-symbolic"`

**Comment by wa4557** [comment]
Found out how to fix it without removing any icons. Renaming `battery-caution-symbolic.svg` to `notification-battery-caution-symbolic` does the trick. 

The same goes for `notification-input-touchpad-symbolic` and `notification-touchpad-disabled-symbolic`. That's actually good news because it means Ubuntu has fixed some bugs in their notification system

**Comment by dirtydancing** [comment]
Yeah, good news indeed, now Ubuntu seems to be more consistent with the notification icon names :+1: Of course, this name change would only apply to `battery-caution-symbolic.svg` in `48/notifications`.

**Comment by wa4557** [comment]
+ We have to add `notification-input-touchpad-symbolic` and `notification-touchpad-disabled-symbolic`

**Comment by wa4557** [comment]
Interestingly this seems to apply only to `-symbolic` named icons `nm-device-wired` for example is still showing up correctly

**Comment by wa4557** [comment]
@Red-devilz @hg8 @jwadolowski I've opened a PR with a proper way to fix it (you can try it out if you want). On my machine (Ubuntu 15.10) this works flawlessly. If you see other notification icons replaced by the generic one, please report it (I wasn't able to find one, though)

**Comment by jwadolowski** [comment]
Thanks @wa4557! Just tested your branch on my machine (Ubuntu 14.04) and indeed proper icons are displayed for both touchpad and battery notifications.

**Comment by hg8** [comment]
@wa4557 Works for me too thanks! When can we expect the fix in the official PPA ?

**Comment by wa4557** [comment]
As soon as the PR is merged...

**Comment by hg8** [comment]
Thanks very for your great work.

**Comment by Red-devilz** [comment]
Thanks a lot, it works for me too

**Comment by Red-devilz** [comment]
The suggested changes work well with *Numix*, and *Numix-light*  icon themes, however, the wrong Icon seems to appear for *Numix-circle* and *Numix-circle-Light*  Icon themes.

![image](https://cloud.githubusercontent.com/assets/15090318/12074320/ec232872-b171-11e5-9fd5-09d34983ecd4.png)

![image](https://cloud.githubusercontent.com/assets/15090318/12074327/7a7f2274-b172-11e5-8572-4d032ec74550.png)

Can anyone else confirm the same. I hope this is the right place to raise the issue(Since Numix base has the required icons but displayed icon is present in Numix-circle folder)


Note: this is after using the files [here](https://github.com/numixproject/numix-icon-theme/tree/18ac296662a77050608972b9360ee3564c6626a7)

**Comment by wa4557** [comment]
@Red-devilz Cannot confirm that. Even when using Numix-Circle on Ubuntu 15.10 the correct icon is displayed...
