### ISSUE TITLE
TeamViewer Icons

### ISSUE THREAD

**Issue by gustavodini** [numixproject/numix-icon-theme#975]
Hello. I would like to request the development of the teamviewer app icons. thank you

**Comment by bil-elmoussaoui** [comment]
@gustavodini Which icons you're talking about? the application or the indicator one?

**Comment by gustavodini** [comment]
@bil-elmoussaoui application icons, see the pictures:


![captura de tela de 2015-12-30 20 57 44](https://cloud.githubusercontent.com/assets/16492447/12058870/147c4d58-af38-11e5-8825-c3919c1841c7.png)
![captura de tela de 2015-12-30 20 58 11](https://cloud.githubusercontent.com/assets/16492447/12058871/148b86ec-af38-11e5-8f6a-86079097acc5.png)

**Comment by Foggalong** [comment]
This should have been an issue for [Numix Circle](https://github.com/numixproject/numix-icon-theme-circle) the app icon theme, but it's a hardcoded duplicate too. See the readme there for more information.

**Comment by gustavodini** [comment]
@Foggalong thanks for your reply, i run fix script and the icon change.....

**Comment by Foggalong** [comment]
@gustavodini Excellent \O/
