### ISSUE TITLE
window-manager icon

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-icon-theme#976]
I was trying to test the symlink way to fix #847 and i've found that there's a `window-manager` icon in `/Numix/xx/apps` I don't really know why..
The same icon do exists in Numix Circle; This icon is used somewhere? 
![screenshot from 2015-12-31 00-47-57](https://cloud.githubusercontent.com/assets/7660997/12059258/3216c5c6-af58-11e5-988f-6fdc95302841.png)

**Comment by bil-elmoussaoui** [comment]
@wa4557 You seem that you've added those icons in this PR #724 , do you know where they are used?

**Comment by wa4557** [comment]
As far as I remember the icon is used in LXDE somewhere. The icon is there for a long time. I've just cleaned it and added multiple sizes

**Comment by wa4557** [comment]
But we have to symlink the icons one by one anyways, so just don't symlink this one.

**Comment by bil-elmoussaoui** [comment]
Alright, i thought it wasn't used anywhere; i will close this :)
