### ISSUE TITLE
Blender Icon ?

### ISSUE THREAD

**Issue by SuicSoft** [numixproject/numix-icon-theme#983]
Where's the icon for blender. I installed blender and found that this icon theme doesn't have an icon for blender

**Comment by dirtydancing** [comment]
Blender is an application, so the blender icon is not located in numix-icon-theme (base theme), but rather in Numix-Circle, https://github.com/numixproject/numix-icon-theme-circle:

![blender_app](https://cloud.githubusercontent.com/assets/7164227/12074041/b4de8592-b13e-11e5-9e43-4ea89aabbbe4.png)

For issues with the application icon, please report over at Numix-Circle.

This Numix base theme does contain the blender filetype icon, though:

![blender_filetype](https://cloud.githubusercontent.com/assets/7164227/12074042/c4867de2-b13e-11e5-94c8-b8262a40a365.png)

**Comment by SuicSoft** [comment]
I installed blender from the Blender website which doesn't come with a .desktop file so it has to be launched from the command line. There is a Blender available from the Software Center but it's not up to date. So can anyone give me a .desktop file from the Software Center version so I can get the icon.

**Comment by dirtydancing** [comment]
Assuming you are using Ubuntu as you are mentioning the Software Center, then the Ubuntu community and the Ubuntu forums would be the proper place for this support request. I am sure you will find information and, if needed, support over there.

I checked `blender.desktop` in Arch/GNOME, and (without all the translations) the file reads like this:
```
[Desktop Entry]
Name=Blender
GenericName=3D modeler
Comment=3D modeling, animation, rendering and post-production
Keywords=3d;cg;modeling;animation;painting;sculpting;texturing;video editing;video tracking;rendering;render engine;cycles;game engine;python;
Exec=blender %f
Icon=blender
Terminal=false
Type=Application
Categories=Graphics;3DGraphics;
MimeType=application/x-blender;
```

**Comment by SuicSoft** [comment]
@dirtydancing Thanks for the .desktop file. Also I use Elementary OS (based on Ubuntu and has Software Center) with Numix-Circle. Now Blender appears in the applications menu and has the correct icon.

**Comment by dirtydancing** [comment]
Great! :+1:
