### ISSUE TITLE
nm-applet cellular icon is broken

### ISSUE THREAD

**Issue by Hypfer** [numixproject/numix-icon-theme#989]
![image](https://cloud.githubusercontent.com/assets/974410/12173198/bb01da80-b555-11e5-8a24-5104f0b0f5ce.png)

Reproduce:

1. Install Numix icon theme
2. Connect to 3g network with network manager nm-applet

**Comment by Foggalong** [comment]
Did this happen after a particular update or has this always been the case?

CC: @wa4557

**Comment by Hypfer** [comment]
This is the case since I've been using Numix.

**Comment by wa4557** [comment]
Looks like the icon is still using `text` instead of `path` elements. The thing is: it doesn't. Weird...

**Comment by wa4557** [comment]
@Hypfer Can you try out this branch https://github.com/wa4557/numix-icon-theme/tree/maintstatus and see if the problem persists?

**Comment by Hypfer** [comment]
@wa4557 Yes, the problem still persists

**Comment by wa4557** [comment]
oO When using the branch you might have to perform `sudo gtk-update-icon-cache -f /path/to/Numix`. Afterwards please change the icon-theme to something else and then back to Numix again.

**Comment by Hypfer** [comment]
Did that. Still the same

![image](https://cloud.githubusercontent.com/assets/974410/12173980/4b1a89e2-b55a-11e5-8ac1-0e08097868d4.png)

As you can see it seems like it layers 2 icons on top of each other.

**Comment by Foggalong** [comment]
I wonder what the other icon is?

**Comment by wa4557** [comment]
I guess this is a bug of the distro you are using, because the other icon seems to be the wifi icon. And there is definitely no wifi icon in the `nm-tech-3g` icon

**Comment by wa4557** [comment]
Ah that might be the reason why the icons are transparent in `ubuntu-mono-dark`!

**Comment by Foggalong** [comment]
It sounds silly, but could the situation be that they take the base icon as the network icon and then intend for the overlay icon just to be a small letter signifying the type of connection?

**Comment by wa4557** [comment]
I guess that's exactly what happens :( That's a pitty though, I kinda liked the new icon...

**Comment by Foggalong** [comment]
Yeah, me too

**Comment by wa4557** [comment]
@Hypfer how does it look like with any other theme? `ubuntu-mono-dark` `elementar` or something similar...

**Comment by Hypfer** [comment]
![image](https://cloud.githubusercontent.com/assets/974410/12189015/a5d2b25a-b5ba-11e5-843a-4ccbb64975c4.png)

As you can see it works fine with the oxygen icon theme. With numix it layers the 3g icon with the signal strength indicator of the wifi.
Interestingly enough, switching to oxygen icon theme didn't need a nm-applet restart. However switching back to numix did require one.

OS is Debian jessie and nm-applet Version: 0.9.10.0-2

**Comment by wa4557** [comment]
Can you try another theme? Oxygen doesn't have those icons, so appearantly fallback icons are used which I cannot find

**Comment by Hypfer** [comment]
Sure
![image](https://cloud.githubusercontent.com/assets/974410/12207007/8584c1ca-b644-11e5-91ad-26c7444d1906.png)

This is the elementary Icon Theme taken from here: https://launchpad.net/elementaryicons Version 3.2.2

**Comment by wa4557** [comment]
Ok thanks, yeah it seems that these icons are used as overlays for the wifi icons. I'll open a PR with a fix soon :)
