### ISSUE TITLE
Antergos implementation is breaking Nautilus desktop background (all grey)

### ISSUE THREAD

**Issue by axfelix** [numixproject/numix-icon-theme#991]
See: https://forum.antergos.com/topic/3294/desktop-wallpaper-goes-gray-but-it-configured-for-an-image/9

Desktop image is displayed during superkey launcher, just not any time it'd be behind Nautilus destop icons -- then it's flat grey. Switching back to Adwaita works OK for now. Rolling back a few versions of Numix doesn't fix the issue, so I'm assuming it's actually some update to Gtk that Numix isn't compliant with.

**Comment by palob** [comment]
That's an issue for the [GTK theme](https://github.com/shimmerproject/Numix).
Anyway, development for thr GTK dormant is somewhat dormant at the moment. Currently support for GTK 3.16/18 is shaky.

**Comment by axfelix** [comment]
Got it, thanks! That's good to know. Might actually best be handled by Antergos package managers in that case, but, well, that's the trouble with Arch -- no freezes when things are unmaintained (or near-unmaintained) and break :)

The good news is this is the first thing that's gone wrong after a year of running off of the newest bleeding edge 3.16/3.18. I'll open an issue on the Gtk theme and see if anyone has any ideas.

**Comment by palob** [comment]
I'd just recommend Antergos not to use Numix as their default theme. Now you boot into their iso and it looks broken everywhere.

**Comment by axfelix** [comment]
Like I said, this is the first breakage I've encountered in a year of running Antergos with weekly-ish updates, and Numix is a really nice theme, so even though it is a bit dangerous to run it as a default theme if the upstream support isn't there, I can appreciate trying to keep it working!
