### ISSUE TITLE
bug on input-touchpad-symbolic 

### ISSUE THREAD

**Issue by bil-elmoussaoui** [numixproject/numix-icon-theme#992]
See the screenshot : 
Using Numix 
![screenshot from 2016-01-15 15-55-52](https://cloud.githubusercontent.com/assets/7660997/12356009/9ca05dfe-bba0-11e5-92f2-e4533719a835.png)
Using Adwaita
![screenshot from 2016-01-15 15-57-30](https://cloud.githubusercontent.com/assets/7660997/12356038/c0d2ffce-bba0-11e5-81ef-0b3c4dc2b689.png)

**Comment by Foggalong** [comment]
This might be fixed in one of the maintenance branches. I'm waiting until I'm back at University with my Linux desktop (rather than just a Linux VM running on my Windows laptop) before I check them and merge them.

**Comment by bil-elmoussaoui** [comment]
I tried to copy the icon from #986, updated the icon cache and still the same issue :/

**Comment by wa4557** [comment]
I think it is because I used strokes on them again (same as in #987 ) Never knew GNOME has problems with strokes as well...
