### ISSUE TITLE
Tray icons for Linux Mint Update Manager

### ISSUE THREAD

**Issue by fwahh** [numixproject/numix-icon-theme#999]
Hi! There seem to be no indicator icons for Mint's update manager.

![update_manager](https://cloud.githubusercontent.com/assets/16854594/12541232/67a69a8e-c314-11e5-8e55-9627495e0e6c.png)

**Comment by wa4557** [comment]
Where are they shown? What are the icon names?

**Comment by bil-elmoussaoui** [comment]
@wa4557 They're hardcoded :p the same icons are used by Yum extender(in Fedora)

**Comment by bil-elmoussaoui** [comment]
Added to Hardcode-Tray , the icon names are 
- mintupdate-indicator-apply -> yum-indicator-updates
- mintupdate-indicator-error -> yum-indicator-error
- mintupdate-indicator-working -> yum-indicator-worknig
- mintupdate-indicator-info -> yum-indicator-info
- mintupdate-indicator  -> yum-indicator-no-updates

The symlinks are for Yum Extender(Dnf) as the icons are the same

**Comment by Foggalong** [comment]
Cool :+1:
